<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills624Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Estrategia de marketing para juguetes y juegos de mesa con IA',
                'description'      => 'Diseña campañas de marketing para la industria del juguete usando inteligencia artificial para personalizar mensajes, optimizar el gasto en publicidad y maximizar las ventas en temporada alta.',
                'prompt_content'   => <<<'EOT'
Actúa como un director de marketing con experiencia en la industria del juguete y los juegos de mesa, especializado en campañas de temporada, marketing digital para familias y en el uso de inteligencia artificial para optimizar el gasto publicitario y personalizar los mensajes a diferentes segmentos de compradores. Necesito diseñar la estrategia de marketing completa para el lanzamiento de una nueva línea de juegos de mesa para familias con niños de 6 a 12 años, con un presupuesto de marketing de 200.000 euros para el período septiembre-enero (temporada alta de juguetes).

contexto: El juego es una aventura de exploración cooperativa donde la familia trabaja junta para completar misiones, tiene una mecánica de rejugabilidad alta (más de 100 partidas diferentes gracias a cartas aleatorias) y un precio de venta al público de 39,95 euros. Compite directamente con juegos consolidados de marcas como Ravensburger, Asmodee y Hasbro. El principal canal de venta es Amazon España (40% de las ventas previstas), seguido de jugueterías independientes (30%), grandes superficies como El Corte Inglés y Carrefour (20%) y la tienda online propia (10%).

tarea: Desarrolla la estrategia de marketing completa con los siguientes apartados:

1. ANÁLISIS DE AUDIENCIAS Y SEGMENTACIÓN CON IA
Define los tres segmentos de comprador principales: (a) padres que buscan actividad offline para desconectar a sus hijos de las pantallas, (b) abuelos y familiares que compran regalos de Navidad y buscan recomendaciones de confianza y (c) aficionados a los juegos de mesa que coleccionan y prueban novedades. Para cada segmento, define: perfil demográfico y psicográfico, canales de información que usan para decidir la compra, mensajes que resuenan y barreras de compra. Explica cómo usar IA para analizar conversaciones en redes sociales, foros de juegos de mesa (BoardGameGeek, Reddit) y reseñas de Amazon para entender mejor a cada segmento.

2. POSICIONAMIENTO Y MENSAJES CLAVE
Desarrolla el posicionamiento del juego frente a la competencia: (a) los tres atributos diferenciadores del juego (cooperativo vs. competitivo, rejugabilidad, tiempo de partida de 45 minutos), (b) la propuesta de valor emocional (momentos de calidad en familia, desconexión digital, risas y recuerdos compartidos) y (c) los cinco mensajes clave adaptados a cada segmento de comprador. Redacta el tagline del juego en tres versiones: una emocional, una racional y una de urgencia para Black Friday y Navidad. Describe cómo usar IA para testear variantes de mensajes en anuncios A/B antes de comprometer el presupuesto.

3. PLAN DE MEDIOS POR CANAL
Diseña el plan de medios con distribución del presupuesto de 200.000 euros: (a) publicidad digital (Meta Ads e Instagram para el segmento de padres, YouTube para demos de partida, TikTok para contenido viral de unboxing y gameplay) — presupuesto sugerido: 90.000 euros, (b) marketing de contenidos e influencers (youtubers de juegos de mesa, instagramers de familia, tiktokers de juguetes) — presupuesto sugerido: 50.000 euros, (c) PR y relaciones con medios (revistas de familia, medios especializados en juegos de mesa, programas de radio matinales) — presupuesto sugerido: 25.000 euros y (d) activaciones en punto de venta, demos en jugueterías y eventos (ferias, centros comerciales) — presupuesto sugerido: 35.000 euros. Para cada canal, indica la métrica principal de optimización y cómo la IA puede automatizar la gestión de pujas y la selección de audiencias.

4. ESTRATEGIA DE INFLUENCER MARKETING
Diseña el programa de influencer marketing: (a) cómo identificar a los 20 creadores de contenido más relevantes para cada segmento usando herramientas de IA (análisis de audiencia, tasa de engagement, alineamiento con los valores de la marca), (b) qué tipos de contenido pedirles (unboxing, primera partida en familia, reseña honesta, reto de misión) y los briefings correspondientes, (c) modelo de compensación (fee fijo vs. porcentaje de ventas vs. producto + fee) según el tamaño del creador y (d) cómo medir el impacto real de cada colaboración (código de descuento propio, UTMs, correlación con picos de ventas). Proporciona el email tipo de contacto con un influencer de juegos de mesa.

5. ESTRATEGIA DE AMAZON Y MARKETPLACES
Diseña la estrategia de optimización en Amazon: (a) optimización de la ficha de producto (título con palabras clave, bullet points, descripción enriquecida, imágenes de estilo de vida, vídeo de gameplay), (b) estrategia de lanzamiento para conseguir las primeras 50 reseñas verificadas, (c) plan de Amazon Ads (Sponsored Products, Sponsored Brands, DSP para remarketing) con presupuesto y segmentación específica para temporada y (d) gestión del ranking orgánico (keywords, conversión, precio competitivo). Explica cómo usar IA para: monitorizar el posicionamiento de palabras clave, analizar reseñas de la competencia para identificar oportunidades de producto y generar variantes de copy optimizadas para Amazon.

6. CAMPAÑA DE NAVIDAD Y BLACK FRIDAY
Diseña la campaña específica de Black Friday y Navidad: (a) timeline de activaciones semana a semana desde el 1 de noviembre al 6 de enero, (b) ofertas y mecánicas de promoción (descuento directo vs. bundle con expansión vs. envío gratuito vs. regalo con compra), (c) estrategia de email marketing con segmentación y personalización por IA para la base de clientes propia y (d) creatividades específicas de temporada para cada canal. Proporciona el calendario de publicaciones y anuncios en formato tabla, con el mensaje principal de cada semana y el presupuesto asignado.

7. MÉTRICAS Y OPTIMIZACIÓN EN TIEMPO REAL
Define ocho KPIs de la campaña con objetivos específicos: ROAS (objetivo: 4x en Meta Ads, 5x en Amazon Ads), coste por conversión por canal, tasa de conversión de la ficha de Amazon, share of voice en búsquedas de "juegos de mesa familias", NPS de clientes que han jugado el juego, tasa de recomendación boca a boca (medida por encuesta post-compra) y número de reseñas verificadas en Amazon al 31 de diciembre. Describe cómo usar IA para monitorizar estas métricas en tiempo real y ajustar el presupuesto automáticamente entre canales según el rendimiento.

8. PRESUPUESTO DETALLADO Y ROI
Desglosa el presupuesto de 200.000 euros en partidas concretas (creación de contenido, fees de influencers, gasto en medios por plataforma, activaciones presenciales, herramientas de marketing) y proyecta el retorno esperado: si el ROAS promedio de la campaña es de 3,5x sobre el gasto en medios, ¿qué volumen de ventas genera? ¿Cuántas unidades necesitas vender para que la campaña sea rentable incluyendo el coste de fabricación y los márgenes del canal? Proporciona el modelo de P&L simplificado de la campaña de temporada.

Presenta la estrategia con un calendario de acciones semanal en formato tabla, ejemplos de creatividades (en texto) y una guía de implementación mes a mes. El tono debe combinar el rigor de un plan de marketing profesional con el entusiasmo y la creatividad que requiere el mundo del juguete.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 50,
                'use_case'         => 'Diseñar la estrategia de marketing completa para el lanzamiento de un juego de mesa en temporada alta con IA para optimizar el gasto publicitario.',
                'vote_score'       => 37,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de mecánicas de juego con inteligencia artificial generativa',
                'description'      => 'Usa herramientas de IA para diseñar, testear y equilibrar mecánicas de juego innovadoras para juguetes interactivos y juegos de mesa, acelerando el proceso de prototipado.',
                'prompt_content'   => <<<'EOT'
Actúa como un game designer con experiencia en diseño de juegos de mesa, juguetes interactivos y en la aplicación de inteligencia artificial generativa para acelerar el proceso de diseño y testeo de mecánicas de juego. Estoy desarrollando un nuevo juego de mesa para el mercado familiar (jugadores de 8 a 99 años) que quiere combinar el elemento clásico del juego analógico con una app complementaria que usa IA para personalizar la experiencia. Necesito apoyo en el diseño completo del sistema de juego.

contexto: El concepto base del juego es una aventura de misterio ambientada en una ciudad de los años 20, donde los jugadores son detectives que deben resolver un caso. La innovación principal es que la app con IA genera casos únicos cada vez que se juega (nunca el mismo misterio dos veces) adaptando la dificultad al perfil de los jugadores y añadiendo pistas de sonido y narración dinámica. El presupuesto de desarrollo del juego físico es de 80.000 euros y el de la app es de 60.000 euros.

tarea: Diseña el sistema de juego completo con los siguientes componentes:

1. DISEÑO DE MECÁNICAS CORE
Define las tres o cuatro mecánicas principales del juego que funcionan de forma analógica sin necesidad de la app: (a) mecánica de movimiento por la ciudad en tablero (tiles modulares que forman el mapa de forma aleatoria en cada partida), (b) mecánica de recopilación de pistas (cartas de pista con sistema de revelación gradual), (c) mecánica de dedución (tablero personal de notas, sistema de hipótesis y verificación) y (d) mecánica de tiempo y presión (pistas que se vuelven irrelevantes si tardas demasiado en actuar sobre ellas). Para cada mecánica, describe cómo funciona, cómo se ejecuta en el turno del jugador y cómo se relaciona con las otras mecánicas para crear un sistema coherente.

2. GENERACIÓN DE CONTENIDO CON IA
Diseña el sistema de generación procedural de casos de misterio con IA: (a) estructura narrativa de un caso (quién, qué, dónde, cuándo, móvil, alibi) y los parámetros que varía la IA en cada partida, (b) cómo usar un modelo de lenguaje para generar la narración del caso manteniendo consistencia interna (el asesino siempre tiene un alibi que puede romperse, siempre hay tres sospechosos con motivo), (c) sistema de adaptación de dificultad según el tiempo que tardan los jugadores en encontrar las pistas clave y (d) generación de audio narrativo con IA de texto a voz para ambientar la partida. Proporciona el esquema de datos JSON que define un caso de misterio y un ejemplo completo de caso generado por IA.

3. DISEÑO DEL SISTEMA DE EQUILIBRIO
Define el sistema de equilibrio del juego para garantizar que siempre sea justo y desafiante: (a) curva de dificultad — cómo progresar de partidas introductorias a casos experto, (b) sistema antifrustración — mecanismos para que los jugadores nunca se queden completamente bloqueados (pistas de emergencia, acciones de investigación alternativas), (c) equilibrio entre suerte y habilidad — qué parte del resultado depende de las cartas que salen y qué parte del razonamiento y la deducción del jugador y (d) tiempo de partida — diseño de casos para que una partida dure entre 60 y 90 minutos, con variante de 45 minutos para familias con niños. Describe cómo usar IA para simular miles de partidas y detectar desequilibrios (cartas que nunca se usan, rutas de solución que siempre son óptimas, cuellos de botella).

4. PROTOTIPADO RÁPIDO CON IA
Diseña el proceso de prototipado ágil con IA: (a) cómo usar IA generativa (Claude para texto de reglas y narración, MidJourney o DALL-E para arte conceptual de las cartas y el tablero) para crear un prototipo jugable en dos semanas, (b) proceso de playtest estructurado con grupos de cinco a ocho personas de diferentes perfiles (familias, gamers adultos, novatos) y plantilla de feedback estandarizado, (c) cómo procesar el feedback de playtest con IA para identificar los problemas más frecuentes y proponer soluciones y (d) ciclos de iteración — cuántos playtests son necesarios antes de considerar el diseño estable. Proporciona el protocolo de observación de un playtest y la plantilla de análisis post-sesión.

5. DISEÑO DEL REGLAMENTO
Escribe el borrador del reglamento completo del juego (entre 1.000 y 1.500 palabras) con los siguientes apartados: objetivo del juego, componentes, preparación de la partida, turno de juego paso a paso, uso de la app de IA, condiciones de victoria y derrota, variantes de dificultad y consejos para la primera partida. Usa un lenguaje claro y amigable, con ejemplos ilustrativos y una estructura lógica de aprendizaje progresivo. Explica cómo usar IA para testear la claridad del reglamento con usuarios reales y medir el tiempo que tardan en entender las reglas sin ayuda.

6. INTEGRACIÓN APP-JUEGO FÍSICO
Diseña la arquitectura de la app y su integración con el juego físico: (a) qué hace la app que no puede hacer el juego sin ella (generación del caso único, narración de sonido, pistas adaptativas, timer visible, gestión del historial de partidas), (b) qué hace el juego físico que enriquece la experiencia más allá de la app (el tacto de las cartas, el movimiento de las fichas, la escritura de notas en papel, la conversación cara a cara), (c) cómo se sincroniza la app con el estado del juego físico (QR en cartas que la app escanea para revelar información, gestos en el tablero detectados por cámara del teléfono) y (d) diseño de la UX de la app para que sea complementaria al juego, no dominante. Proporciona el wireframe en texto de las cinco pantallas principales de la app.

7. ANÁLISIS DE COMPETIDORES Y DIFERENCIACIÓN
Analiza los cinco juegos de mesa de misterio más vendidos del mercado (Cluedo, Sherlock Holmes Detective Asesor, Exit: El Juego, Chronicles of Crime y Unlock!) comparando: mecánicas de juego, perfil de jugador objetivo, precio, presencia de componente digital y puntuación media en BoardGameGeek. Define cómo se posiciona el nuevo juego frente a cada uno y cuál es la razón de compra diferencial para cada segmento de jugadores. Explica qué aprende el nuevo juego de las reseñas negativas de cada competidor (usando IA para analizar las críticas en BoardGameGeek y Amazon) y cómo aborda esos problemas en su diseño.

8. PLAN DE DESARROLLO Y LANZAMIENTO
Diseña el roadmap de desarrollo del juego en cuatro fases: (a) diseño y primer prototipo (semanas uno a ocho), (b) playtesting y ajuste de mecánicas (semanas nueve a veinte), (c) diseño gráfico final y producción del juego físico (semanas veintiuno a cuarenta) y (d) desarrollo de la app y pruebas de integración (paralelo a la fase de producción, semanas quince a cuarenta). Incluye los hitos clave, los recursos necesarios (game designer, ilustrador, desarrollador de app, editor de audio), los riesgos principales y el plan para la presentación en ferias del sector (Nuremberg Toy Fair, Essen Spiel, Madrid Games Festival).

Presenta el diseño con ejemplos concretos de mecánicas, un caso de misterio de ejemplo completo generado como si fuera la IA y un cronograma visual del desarrollo. El tono debe ser apasionado por el diseño de juegos, técnico donde sea necesario y creativo en los ejemplos.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Diseñar mecánicas de juego innovadoras para un juego de mesa con componente de IA generativa, desde el concepto hasta el prototipo jugable.',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de juguetes y packaging con IA: del concepto a la producción',
                'description'      => 'Aplica herramientas de inteligencia artificial generativa al proceso de diseño de juguetes y su packaging, desde la generación de conceptos hasta la preparación de archivos para producción.',
                'prompt_content'   => <<<'EOT'
Actúa como un diseñador industrial y de packaging con experiencia en la industria del juguete, en el uso de herramientas de inteligencia artificial generativa para acelerar el proceso de diseño y en los requerimientos técnicos de fabricación y certificación de juguetes para el mercado europeo. Trabajo en el departamento de diseño de una empresa de juguetes de tamaño mediano y necesito modernizar nuestro proceso de diseño integrando herramientas de IA para reducir el tiempo de desarrollo de nuevos productos de 18 a 10 meses.

contexto: La empresa desarrolla juguetes de plástico y cartón para niños de 3 a 10 años, con un catálogo de 40 referencias activas y el lanzamiento de ocho a diez nuevos productos al año. El proceso actual de diseño es lineal (brief, concepto, bocetos manuales, modelado 3D, prototipo físico, aprobación, producción) y los principales cuellos de botella son la generación de conceptos (normalmente cuatro a seis semanas) y las iteraciones del modelado 3D por cambios de última hora. Queremos integrar IA en las fases de concepto y prototipo visual sin perder la calidad y el control del proceso de diseño.

tarea: Diseña el proceso de diseño modernizado con IA con los siguientes componentes:

1. PROCESO DE GENERACIÓN DE CONCEPTOS CON IA
Redefine la fase de concepto con IA: (a) cómo usar herramientas de IA generativa de imagen (Midjourney, DALL-E, Adobe Firefly, Stable Diffusion) para generar rápidamente entre 20 y 30 variantes visuales de un concepto de juguete a partir del brief del producto, (b) cómo escribir instrucciones efectivas para la IA de imagen que incluyan las restricciones técnicas del juguete (tamaño, materiales, público objetivo, restricciones de seguridad, paleta de colores de marca) y (c) cómo usar estas imágenes generadas para presentar opciones al cliente interno o al departamento de marketing antes de comprometer recursos de modelado 3D. Proporciona tres ejemplos de instrucciones para generar conceptos de juguetes en distintos estilos (realista, ilustración, estilo 3D render).

2. DISEÑO DE PERSONAJES Y UNIVERSO VISUAL
Diseña el proceso de creación de personajes con IA para una nueva línea de juguetes: (a) cómo usar IA para generar variantes de un personaje manteniendo consistencia visual entre todas las piezas de la línea, (b) cómo iterar rápidamente sobre el diseño del personaje (proporción, expresión facial, paleta de colores, detalles de vestuario) con la IA como herramienta de bocetado acelerado, (c) cómo usar IA para expandir el universo visual del personaje a diferentes aplicaciones (packaging, materiales de marketing, ilustraciones del manual) garantizando coherencia de estilo y (d) qué workflows en Photoshop, Illustrator o Figma con plugins de IA pueden acelerar la vectorización y limpieza de los assets generados por IA. Proporciona el brief tipo que usarías para generar el diseño inicial de un personaje de juguete.

3. DISEÑO DE PACKAGING CON IA
Diseña el proceso de packaging con IA: (a) cómo usar IA para generar conceptos de packaging que cumplan con los requerimientos regulatorios europeos (marcado CE, advertencias de seguridad, información obligatoria) y de comunicación del producto (imagen del juguete, edad recomendada, características clave, branding de la empresa), (b) cómo usar IA para probar diferentes layouts de la caja, paletas de color y tipografías antes de pasar a diseño final en InDesign o Illustrator, (c) cómo adaptar el mismo packaging a diferentes formatos (caja, blíster, bolsa) manteniendo la coherencia visual y (d) cómo usar IA para generar los textos del packaging en múltiples idiomas (mínimo seis para el mercado europeo) de forma consistente y con la terminología correcta de seguridad de juguetes. Proporciona una estructura de packaging de caja estándar con todos los elementos obligatorios y opcionales.

4. MODELADO 3D ASISTIDO POR IA
Describe cómo la IA puede acelerar el proceso de modelado 3D en la industria del juguete: (a) herramientas de IA que generan modelos 3D a partir de imágenes de concepto (Luma AI, Meshy, Kaedim) y cómo usarlas como punto de partida para el modelado en Blender o ZBrush, (b) uso de IA para generar texturas y materiales realistas en los renders de presentación, (c) herramientas de IA que detectan automáticamente problemas de diseño para fabricación (geometrías imposibles, paredes demasiado delgadas, radios de curva insuficientes para moldeo por inyección) y (d) automatización con IA de la generación de vistas técnicas y listas de materiales a partir del modelo 3D. Incluye una evaluación de las principales herramientas de modelado 3D con IA disponibles en 2024 con sus ventajas y limitaciones para la industria del juguete.

5. PROCESO DE PROTOTIPADO E ITERACIÓN
Diseña el proceso de prototipado acelerado con IA: (a) cómo usar renders fotorrealistas generados con IA para validar el diseño visualmente antes de imprimir el prototipo físico (ahorrando el coste de prototipos rechazados), (b) cómo usar IA para generar simulaciones de cómo se verá el juguete en diferentes contextos de uso (niño jugando, en la estantería de la juguetería, en la caja del árbol de Navidad) para validar el atractivo del producto, (c) protocolo de presentación de prototipos digitales a los departamentos de marketing y ventas con herramientas de visualización 3D interactiva y (d) cuándo es imprescindible el prototipo físico y cuándo puede reemplazarse por digital, con criterios claros de decisión.

6. CUMPLIMIENTO NORMATIVO Y SEGURIDAD
Analiza los requerimientos normativos de seguridad de juguetes en Europa y cómo la IA puede ayudar a cumplirlos: (a) Directiva de seguridad de juguetes 2009/48/CE y sus requisitos de diseño (materiales aprobados, tamaños mínimos de piezas, resistencia, inflamabilidad), (b) marcado CE — proceso de evaluación de conformidad y documentación técnica requerida, (c) cómo usar IA para revisar el diseño frente a la normativa de seguridad durante el proceso de diseño (checklist de cumplimiento automático) y (d) cómo documentar el proceso de diseño para facilitar la auditoría de conformidad y reducir el tiempo de certificación. Proporciona un checklist de diseño seguro para juguetes de plástico para niños de 3 a 6 años.

7. GESTIÓN DE ACTIVOS DIGITALES Y ARCHIVO
Diseña el sistema de gestión de activos digitales para el departamento de diseño: (a) estructura de carpetas y nomenclatura de archivos para los activos generados con IA, (b) sistema de versiones y aprobaciones (cuándo se considera un concepto generado por IA listo para pasar a modelado 3D), (c) biblioteca de estilos y prompts de IA reutilizables para mantener la coherencia visual de la marca en todos los productos y (d) proceso de archivo de los activos de IA para cumplir con los requerimientos legales de propiedad intelectual (qué documentar, durante cuánto tiempo, cómo acreditar la autoría de los diseños generados con IA). Proporciona la plantilla de brief de diseño que el equipo completa antes de usar herramientas de IA.

8. FORMACIÓN DEL EQUIPO Y GESTIÓN DEL CAMBIO
Diseña el plan de formación del equipo de diseño para adoptar las nuevas herramientas de IA: (a) evaluación del nivel actual de cada diseñador con herramientas de IA (desde nulo hasta experto), (b) plan de formación de 12 semanas (dos horas semanales) que progrese de herramientas básicas a flujos de trabajo avanzados, (c) cómo manejar la resistencia de diseñadores que ven la IA como una amenaza para su trabajo (encuadrar la IA como herramienta, no como sustituto del criterio creativo del diseñador) y (d) sistema de incentivos para la adopción (compartir con el equipo el tiempo ahorrado gracias a la IA, reconocer a los diseñadores que desarrollan flujos de trabajo innovadores). Proporciona el calendario de las primeras cuatro semanas de formación con los ejercicios prácticos de cada sesión.

Presenta el proceso con ejemplos de instrucciones de IA listas para usar, ejemplos de outputs esperados por herramienta y un cronograma de implementación de 90 días. El tono debe ser técnico en la parte de herramientas y procesos, y creativo en los ejemplos de aplicación al diseño de juguetes.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Modernizar el proceso de diseño de juguetes y packaging integrando IA generativa para reducir el tiempo de desarrollo a la mitad.',
                'vote_score'       => 31,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Gestión de temporada alta y planificación de ventas de juguetes con IA',
                'description'      => 'Optimiza la planificación de ventas, la gestión de inventario y las estrategias de precio en la temporada alta de juguetes usando inteligencia artificial para anticipar la demanda y maximizar el margen.',
                'prompt_content'   => <<<'EOT'
Actúa como un director comercial con experiencia en la industria del juguete, especializado en la gestión de la temporada alta (septiembre a enero) y en el uso de inteligencia artificial para la planificación de ventas, la gestión de inventario y la optimización de precios. Dirijo el equipo comercial de un fabricante de juguetes de tamaño mediano con un catálogo de 60 referencias y ventas de 15 millones de euros anuales, de los cuales el 65% se concentran en el último trimestre del año.

contexto: El mayor problema histórico de la empresa es la gestión del inventario en temporada: dos de cada tres años tenemos desabastecimiento en las referencias más vendidas (perdiendo ventas), mientras que acumulamos exceso de stock de las referencias menos populares que hay que liquidar con descuento en enero y febrero. La previsión de demanda actual la hacen los comerciales a partir de su experiencia, sin modelos estadísticos ni datos estructurados. El objetivo es reducir las roturas de stock un 70% y el exceso de stock un 40% usando IA para mejorar la previsión de demanda.

tarea: Diseña el sistema de gestión de temporada con IA con los siguientes componentes:

1. MODELO DE PREVISIÓN DE DEMANDA
Diseña el modelo de previsión de demanda para la temporada alta: (a) qué variables históricas incluir en el modelo (ventas por referencia de los últimos tres años semana a semana, precio, promociones activas, presencia en lineales, temperatura, eventos del calendario), (b) qué señales externas añadir como predictores (búsquedas en Google Trends, menciones en redes sociales, datos de compras anticipadas de los grandes distribuidores), (c) cómo usar IA para construir el modelo de previsión y actualizarlo cada semana con los datos de ventas reales y (d) cómo presentar las previsiones al equipo comercial y de operaciones en un formato comprensible que incluya el intervalo de confianza de cada previsión. Proporciona el esquema de datos de entrada del modelo y el formato de salida esperado.

2. SEGMENTACIÓN DEL CATÁLOGO PARA TEMPORADA
Diseña el sistema de segmentación del catálogo de 60 referencias para la planificación de temporada: (a) clasificación ABC basada en el valor de ventas esperado (A: top 20% que generan el 80% del margen, B: 30% medio, C: 50% long tail), (b) análisis de ciclo de vida de cada referencia (estrella del año, clásico consolidado, novedad, en declive) y sus implicaciones para el plan de stock y (c) identificación de las referencias con mayor riesgo de rotura de stock basado en la velocidad de rotación histórica y la incertidumbre de la demanda. Explica cómo la IA puede identificar patrones de agotamiento temprano (señales de que una referencia se va a agotar antes de Navidad) para reaccionar con tiempo.

3. GESTIÓN DE RELACIONES CON GRANDES CUENTAS
Diseña la estrategia de gestión de los cinco grandes clientes que representan el 60% de las ventas: (a) proceso de negociación de pedidos en firme vs. pedidos en consignación (qué porcentaje del stock asumir en cada modalidad), (b) acuerdos de sell-through garantizado y sus implicaciones de logística inversa, (c) cómo usar datos de sell-out (ventas del distribuidor al consumidor final) para anticipar reposiciones urgentes y (d) sistema de alertas automáticas cuando un cliente grande está por debajo de su ritmo de ventas previsto, para actuar proactivamente con acciones de activación en punto de venta. Proporciona el template de reunión mensual de seguimiento de grandes cuentas con los cinco indicadores clave que hay que revisar.

4. ESTRATEGIA DE PRECIOS Y PROMOCIONES
Diseña la estrategia de precios y promociones para la temporada: (a) política de precios por canal (distribuidores nacionales, grandes superficies, jugueterías independientes, Amazon, tienda online propia) — qué márgenes garantizar a cada canal, cómo gestionar la paridad de precio y qué margen dejar para las promociones de temporada, (b) calendario de promociones — Black Friday (cuánto descuento, en qué referencias y canales), período navideño (evitar descuentos mientras la demanda es alta) y liquidación de enero (qué porcentaje del stock queda sin vender y cómo liquidarlo con el menor impacto en el precio de referencia) y (c) cómo usar IA para la optimización dinámica de precios en el canal online propio, ajustando automáticamente según el nivel de stock, la demanda en tiempo real y los precios de la competencia.

5. PLANIFICACIÓN DE LA PRODUCCIÓN Y EL APROVISIONAMIENTO
Describe cómo usar la previsión de demanda de IA para planificar la producción y el aprovisionamiento: (a) modelo de planificación de producción — cuándo fabricar, cuánto fabricar y cómo gestionar los tiempos de entrega de proveedores de componentes (normalmente 8 a 16 semanas), (b) estrategia de buffer de seguridad por referencia según su nivel de riesgo (A-críticas necesitan más buffer, C-long tail menos), (c) plan de contingencia para referencias que superan la previsión de ventas (qué opciones hay: fabricación urgente, sustitución por referencia similar, gestión de la espera del cliente) y (d) política de cancelación de pedidos a proveedores cuando la temporada va peor de lo esperado. Proporciona el calendario de decisiones de producción y aprovisionamiento de mayo a diciembre.

6. GESTIÓN DEL EQUIPO COMERCIAL EN TEMPORADA
Diseña el modelo de organización del equipo comercial durante la temporada alta: (a) estructura de objetivos — cómo balancear el objetivo de ventas con el objetivo de calidad de ventas (marginal, no solo volumen), (b) sistema de incentivos de temporada — cómo compensar al equipo comercial por referencias prioritarias y por la calidad del sell-through, (c) agenda tipo de un comercial en la semana punta (semana del 11 al 17 de diciembre) — qué visitas, qué acciones en punto de venta, qué reportes y (d) cómo usar IA para generar el reporte de ventas diario del equipo en cinco minutos, con los insights más relevantes y las acciones recomendadas para el día siguiente.

7. INTELIGENCIA COMPETITIVA EN TEMPORADA
Define el sistema de inteligencia competitiva para la temporada: (a) cómo monitorizar automáticamente los precios de la competencia en Amazon y webs de distribuidores usando herramientas de web scraping e IA, (b) cómo detectar los lanzamientos de la competencia que pueden afectar a las referencias propias (alertas de Google, análisis de menciones en redes sociales), (c) cómo usar IA para analizar las reseñas de los productos de la competencia en Amazon y detectar debilidades que podemos explotar en nuestra comunicación y (d) informe semanal de inteligencia competitiva — formato, frecuencia y destinatarios. Proporciona el template del informe de inteligencia competitiva semanal.

8. POST-TEMPORADA Y APRENDIZAJE
Diseña el proceso de análisis post-temporada con IA: (a) informe de temporada — qué analizar (previsión vs. real por referencia, análisis de las roturas de stock y su impacto en ventas perdidas, análisis del exceso de stock y su coste de liquidación, rentabilidad real por referencia y por canal), (b) cómo usar IA para identificar los patrones que explican las desviaciones más grandes entre previsión y realidad y (c) proceso de mejora continua del modelo de previsión — cómo incorporar los aprendizajes de la temporada para mejorar las previsiones del año siguiente. Proporciona la agenda de la reunión de post-temporada con el comité directivo.

Presenta el sistema con modelos de datos, plantillas de reportes y un calendario de acciones clave de mayo a enero. El tono debe ser comercial y orientado a resultados, con ejemplos concretos de la industria del juguete.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 55,
                'use_case'         => 'Implementar un sistema de previsión de demanda con IA para eliminar roturas de stock y excesos de inventario en la temporada alta de juguetes.',
                'vote_score'       => 40,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Product management de líneas de juguetes interactivos con IA',
                'description'      => 'Aplica metodologías de product management modernas para gestionar el ciclo de vida de líneas de juguetes que integran inteligencia artificial, desde el concepto hasta la descontinuación.',
                'prompt_content'   => <<<'EOT'
Actúa como un Product Manager con experiencia en la industria del juguete y en el desarrollo de productos de consumo que integran tecnología e inteligencia artificial. Gestiono la línea de productos de una empresa de juguetes que quiere lanzar su primera línea de juguetes interactivos con IA integrada (juguetes que aprenden del niño, adaptan sus respuestas y crecen con él a lo largo del tiempo). Necesito definir la estrategia de producto desde el concepto inicial hasta el plan de lanzamiento.

contexto: La empresa tiene experiencia en juguetes de plástico clásicos pero nunca ha desarrollado productos con componentes digitales o de IA. El mercado de juguetes interactivos está dominado por grandes marcas (Mattel con Barbie con IA, Hasbro con su línea de robots interactivos, LeapFrog en educación) y por startups tecnológicas. Tenemos un presupuesto de desarrollo de 2 millones de euros y un timeline de 24 meses hasta el lanzamiento en mercado. La línea objetivo son niños de 4 a 8 años con un precio de venta al público de entre 49 y 89 euros por juguete.

tarea: Desarrolla la estrategia de producto completa con los siguientes componentes:

1. DISCOVERY Y VALIDACIÓN DEL CONCEPTO
Diseña un proceso de discovery de cuatro meses para validar el concepto antes de comprometer el presupuesto de desarrollo completo: (a) investigación etnográfica con diez familias (qué observar: cómo juegan los niños, qué los aburre, cuándo piden la ayuda del adulto, cómo interactúan con juguetes que ya tienen componente digital), (b) entrevistas con padres (quince perguntas sobre motivaciones de compra, preocupaciones sobre pantallas y privacidad, disposición a pagar y criterios de éxito del juguete), (c) co-creación con niños de 4 a 8 años — talleres de diseño participativo donde los niños dibujan y describen el juguete de IA de sus sueños y (d) análisis de la competencia con IA para procesar reseñas, foros y redes sociales y detectar las frustraciones no resueltas de los compradores actuales de juguetes interactivos.

2. DEFINICIÓN DE LA PROPUESTA DE VALOR
Define la propuesta de valor del juguete interactivo con IA: (a) los tres problemas del niño que resuelve (aburrimiento de juguetes que siempre hacen lo mismo, necesidad de un compañero de juego siempre disponible, deseo de un juguete que le "entienda"), (b) los tres problemas del padre que resuelve (alternativa a pantallas pasivas, estimulación cognitiva y emocional, compañía segura cuando no puede jugar con el niño), (c) las capacidades de IA que diferencian el producto (personalización que aprende con el tiempo, reconocimiento del estado emocional del niño, generación de contenido nuevo que nunca se repite) y (d) por qué un juguete físico con IA es mejor que una app o un juego de pantalla (el tacto del objeto físico, la narrativa del personaje, la ausencia de pantalla adicional). Redacta la propuesta de valor en 150 palabras para la caja del producto.

3. REQUISITOS DE PRODUCTO Y PRIORIZACIÓN
Define los requisitos del producto en cuatro niveles de prioridad: (a) imprescindible para el lanzamiento — qué funcionalidades de IA son el núcleo del producto (reconocimiento de voz del niño, respuestas personalizadas, memoria de interacciones anteriores, personalidad adaptable del personaje), (b) importante pero no bloqueante — qué puede añadirse en actualizaciones (reconocimiento de emociones faciales, integración con contenido educativo, modo familiar para padres), (c) deseable a largo plazo — qué define la visión a tres años (un ecosistema de personajes que interactúan entre sí, contenido generado por la comunidad de padres, versión para distintas edades del mismo personaje) y (d) fuera del alcance — qué no hará el producto (no será una pantalla, no tendrá acceso a internet sin supervisión parental, no recopilará datos sin consentimiento explícito). Presenta en formato MoSCoW con justificación de cada decisión.

4. PRIVACIDAD Y ÉTICA EN JUGUETES CON IA PARA NIÑOS
Desarrolla el framework de privacidad y ética para el juguete: (a) requerimientos legales — RGPD para menores (artículo 8), COPPA si se vende en EE.UU., normativa específica de juguetes conectados y guías del Comité de los Derechos del Niño de la ONU sobre IA y menores, (b) decisiones de diseño de privacidad — qué datos se recogen (solo los necesarios para la funcionalidad de IA), dónde se procesan (on-device vs. cloud), cuánto tiempo se retienen y quién puede acceder, (c) controles parentales — qué control tienen los padres (ver el historial de interacciones, ajustar el nivel de contenido, limitar el tiempo de uso, borrar los datos del perfil del niño) y (d) comunicación transparente a los padres — cómo explicar de forma comprensible cómo funciona la IA del juguete y qué datos usa. Proporciona el borrador de la política de privacidad para padres en lenguaje accesible.

5. HOJA DE RUTA DEL PRODUCTO (24 MESES)
Diseña el roadmap de 24 meses organizado en cuatro etapas: (a) etapa de concepto y validación (meses uno a cuatro) — discovery, definición de requisitos, validación de la propuesta de valor con familias, (b) etapa de desarrollo (meses cinco a dieciséis) — desarrollo del hardware, entrenamiento de los modelos de IA del juguete, diseño de la experiencia de juego y pruebas de seguridad y certificación, (c) etapa de lanzamiento (meses diecisiete a veinte) — producción del primer lote, campaña de marketing, distribución y monitorización de los primeros usuarios y (d) etapa de evolución (meses veintiuno a veinticuatro) — primeras actualizaciones basadas en datos de uso, expansión de la línea con nuevos personajes, entrada en nuevos mercados. Para cada etapa, indica los hitos clave, las decisiones de inversión o parada y los criterios de éxito.

6. MÉTRICAS DE PRODUCTO Y EXPERIENCIA DE JUEGO
Define las métricas específicas para un juguete con IA: (a) métricas de adopción — porcentaje de compradores que activan el perfil de IA, número de sesiones por semana en los primeros 30, 60 y 90 días, (b) métricas de engagement — duración media de cada sesión de juego, porcentaje de niños que siguen usando el juguete a los seis meses (retención a largo plazo es el gran reto de los juguetes interactivos), (c) métricas de la IA — precisión del reconocimiento de voz en condiciones de juego real, tasa de respuestas del juguete que el niño percibe como "correctas" (medida por seguimiento de la sesión) y velocidad de personalización (cuántas interacciones necesita el juguete para que el niño sienta que "le conoce") y (d) métricas de negocio — NPS de padres, tasa de recomendación, tiempo de devolución en el primer mes y ratio de expansión de la línea (compra de accesorios o personajes adicionales). Proporciona los objetivos para cada métrica en el primer año post-lanzamiento.

7. GO-TO-MARKET PARA JUGUETES INTERACTIVOS CON IA
Diseña la estrategia de go-to-market específica para un juguete con IA: (a) cómo comunicar la tecnología de IA a padres que pueden ser escépticos o no entienden cómo funciona (lenguaje de beneficios, no de tecnología), (b) estrategia de distribución — por qué empezar con distribución selectiva (las mejores jugueterías y la tienda online propia) antes de entrar en grandes superficies, (c) pricing — cómo justificar un precio premium de 79 euros frente a juguetes sin IA de 30 a 40 euros y (d) plan de contenidos para redes sociales — qué contenido hace que los padres compartan el juguete de sus hijos (momentos mágicos de interacción entre el niño y el juguete que nadie esperaba, progresión visible del aprendizaje del personaje). Proporciona el plan de lanzamiento de las primeras ocho semanas.

8. GESTIÓN DE STAKEHOLDERS Y EQUIPOS MULTIDISCIPLINARES
Diseña el modelo de gestión del proyecto de 24 meses: (a) estructura del equipo necesario (qué perfiles son internos y cuáles son proveedores externos), (b) cómo gestionar la coordinación entre el equipo de diseño de producto, el equipo de ingeniería de hardware, el equipo de IA y los proveedores de manufactura en China, (c) proceso de toma de decisiones — quién decide qué (trade-offs entre funcionalidad, coste de fabricación y fecha de lanzamiento) y (d) gestión del riesgo del proyecto — los cinco riesgos principales (retrasos en certificación CE, problemas de precisión del reconocimiento de voz en niños, resistencia de los padres por privacidad, dificultad de fabricar el hardware con el margen objetivo, competidor que lanza primero) y los planes de mitigación. Proporciona la agenda de la revisión mensual del proyecto con el comité de dirección.

Presenta el plan de producto con una visión inspiradora del juguete y un plan de ejecución riguroso que equilibre la ambición de la IA con las realidades de la fabricación de juguetes. El tono debe combinar la visión creativa del mundo del juguete con la disciplina metodológica del product management.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Definir la estrategia de producto para la primera línea de juguetes con IA integrada, desde el discovery hasta el lanzamiento en 24 meses.',
                'vote_score'       => 35,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión de equipos en temporada alta de juguetes con IA para RRHH',
                'description'      => 'Diseña estrategias de gestión de personas para la industria del juguete durante la temporada alta, usando inteligencia artificial para optimizar la planificación de turnos, la formación y el bienestar del equipo.',
                'prompt_content'   => <<<'EOT'
Actúa como un responsable de recursos humanos con experiencia en la industria del juguete y la distribución estacional, especializado en la gestión de equipos de alto rendimiento durante los picos de trabajo de septiembre a enero. Dirijo el área de RRHH de una empresa fabricante y distribuidora de juguetes con 180 empleados fijos y la necesidad de incorporar entre 60 y 80 empleados temporales en la temporada alta. Quiero optimizar toda la gestión de personas de la temporada usando herramientas de inteligencia artificial.

contexto: La temporada alta es el período más estresante del año para todos los equipos: el almacén trabaja a tres turnos, el equipo comercial está en carretera constantemente, el equipo de atención al cliente gestiona un volumen de consultas cuatro veces superior al habitual y el equipo de producción trabaja con horas extra continuas. La rotación de empleados temporales es del 45% entre ediciones (solo la mitad repite), lo que obliga a formar a muchos empleados nuevos cada año. El absentismo en temporada sube un 30% respecto al promedio anual.

tarea: Diseña el sistema de gestión de RRHH para la temporada alta con los siguientes componentes:

1. PLANIFICACIÓN DE PLANTILLA PARA TEMPORADA
Diseña el proceso de planificación de plantilla para la temporada: (a) cuándo empezar a planificar (en junio para una temporada que arranca en septiembre), qué información recopilar para hacer la previsión (volumen de pedidos previsto, referencias del año anterior, plan de marketing que puede generar picos de demanda inesperados) y cómo traducir el plan de negocio en necesidades de personal por departamento y semana, (b) cómo usar IA para modelar diferentes escenarios de plantilla (si las ventas son un 20% superiores o inferiores a la previsión, cuántos temporales adicionales o menos necesitamos) y (c) proceso de aprobación del plan de plantilla y los presupuestos de nómina con la dirección financiera. Proporciona el calendario de decisiones de plantilla de junio a agosto.

2. RECLUTAMIENTO MASIVO DE TEMPORALES CON IA
Diseña el proceso de reclutamiento de 60 a 80 empleados temporales en ocho semanas: (a) canales de reclutamiento prioritarios para perfiles operativos (almacén, producción, atención al cliente) — portales de empleo, ETTs, asociaciones de desempleados de larga duración, programas de reintegración laboral, (b) proceso de selección express — qué competencias son imprescindibles (fiabilidad, trabajo en equipo, resistencia física en almacén o concentración en CS), qué se puede seleccionar en grupo (entrevistas colectivas, dinámicas de grupo de 20 minutos) y qué requiere evaluación individual, (c) cómo usar IA para: screening automatizado de CVs, programación de entrevistas en grupos, análisis de transcripciones de entrevistas para detectar señales de fiabilidad y compromiso y (d) proceso de incorporación express de 48 horas con formación esencial antes del primer día.

3. ONBOARDING DE TEMPORALES EN 48 HORAS
Diseña el proceso de onboarding acelerado para empleados temporales: (a) documentación obligatoria — contrato, prevención de riesgos, políticas esenciales — digitalizada y firmable en móvil antes del primer día, (b) formación de puesto — qué deben saber para ser productivos desde el primer turno, en formato visual y corto (máximo 90 minutos), cómo usar vídeos con IA y microlearning para que cada empleado lo haga en su teléfono y (c) buddy system — asignación de un empleado fijo como referente para las primeras dos semanas, con un guión de check-ins de cinco minutos diarios. Proporciona el checklist de onboarding de 48 horas por departamento (almacén, producción, CS).

4. PLANIFICACIÓN DE TURNOS Y HORARIOS CON IA
Diseña el sistema de planificación de turnos para la temporada: (a) cómo usar IA para generar los cuadrantes de turnos optimizando la cobertura de las necesidades del negocio, el cumplimiento de la normativa laboral (descansos, límite de horas extra, días libres), las preferencias de los empleados (donde sea posible) y la eficiencia del coste de mano de obra, (b) gestión de los picos inesperados — qué hacer cuando en una semana el pedido es un 50% superior al previsto (lista de voluntarios para horas extra, acuerdos previos con ETTs para disponibilidad inmediata, redistribución de tareas entre departamentos), (c) sistema de control de asistencia — cómo gestionar el absentismo en temporada sin destruir el clima laboral y (d) planificación del cierre de temporada — cómo gestionar la reducción gradual de empleados temporales con el mínimo impacto en el clima laboral y la reputación como empleador. Proporciona el ejemplo de cuadrante tipo para el departamento de almacén en la semana del 15 al 21 de diciembre.

5. BIENESTAR Y PREVENCIÓN DEL BURNOUT EN TEMPORADA
Diseña el programa de bienestar específico para la temporada alta: (a) señales de burnout en temporada — qué indicadores monitorizar (incremento del absentismo, errores repetidos, conflictos entre compañeros, quejas de clientes atribuibles a errores humanos) y cómo usar IA para detectarlos de forma temprana, (b) intervenciones preventivas — qué acciones tomar para evitar el agotamiento (descansos organizados, reconocimiento frecuente, comunicación constante del fin de la temporada y la fecha de regreso a la normalidad), (c) protocolo de apoyo a empleados en situaciones de dificultad personal durante la temporada (la familia de un empleado del almacén tiene un problema de salud: cómo gestionar el permiso sin dejar sin cobertura el turno) y (d) celebración del fin de temporada — cómo reconocer el esfuerzo del equipo de forma auténtica y económicamente sostenible. Proporciona el mensaje de comunicación interna que enviarías al equipo el primer día de octubre.

6. FORMACIÓN RÁPIDA CON IA
Diseña el sistema de formación en temporada con IA: (a) formación técnica de puesto — cómo usar microlearning y vídeos generados con IA para formar a los temporales en las tareas de almacén, producción o CS en menos de cuatro horas, (b) formación en seguridad — obligatoria para todos, con evaluación automatizada de comprensión y registro automático para cumplimiento legal, (c) formación en producto — el equipo de CS y ventas necesita conocer el catálogo de 60 referencias; diseña un sistema de formación de producto en formato quiz gamificado con IA que pueda completarse en el teléfono en los descansos y (d) formación de managers temporales — si asciendes a empleados fijos a roles de supervisión para la temporada, qué formación mínima necesitan en gestión de equipos. Proporciona el plan de formación de las dos primeras semanas para un empleado de atención al cliente temporal.

7. COMPENSACIÓN Y BENEFICIOS EN TEMPORADA
Diseña la política de compensación y beneficios para maximizar la atracción y retención de temporales: (a) política salarial — qué prima de temporada ofrecer sobre el convenio del sector para atraer al mejor talento temporal, cómo estructurar la prima de finalización de temporada (bonus por completar el contrato sin absentismo injustificado), (b) beneficios no salariales — qué ofrecer que no tenga coste o tenga coste mínimo pero genere percepción de valor (descuento en productos de la empresa, comida en el comedor de empresa durante el turno, regalo de Navidad para los hijos de los empleados con productos de la empresa), (c) política de conversión a fijo — qué porcentaje de temporales se convierten en fijos, con qué criterios y cómo comunicarlo desde el proceso de selección para generar motivación y (d) sistema de feedback al final de la temporada — cómo recoger el feedback de los temporales para mejorar el proceso del año siguiente.

8. MÉTRICAS DE RRHH EN TEMPORADA
Define ocho métricas de RRHH específicas de la temporada con objetivos: tiempo de cobertura de vacantes (objetivo: menos de cuatro semanas), tasa de finalización del contrato temporal (objetivo: 80%), tasa de absentismo en temporada (objetivo: no superar el 8% vs. 12% del año anterior), NPS de empleados temporales al final de la temporada (objetivo: superior a 30), coste de personal por unidad producida (comparativa con año anterior), tasa de accidentes laborales en temporada (objetivo: reducir un 20%), porcentaje de temporales que repiten la temporada siguiente (objetivo: 60%) y coste total del proceso de reclutamiento y formación de temporales. Diseña un dashboard mensual de RRHH en temporada con alertas automáticas para el director general cuando los indicadores críticos están en riesgo.

Presenta el sistema con plantillas listas para usar, calendarios de decisiones clave y ejemplos de comunicaciones internas para cada momento crítico de la temporada. El tono debe ser práctico y orientado a la realidad operativa de la industria del juguete en temporada.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Gestionar el ciclo completo de RRHH de la temporada alta en la industria del juguete usando IA para planificación, formación y bienestar del equipo.',
                'vote_score'       => 29,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Planificación financiera de la temporada de juguetes con IA',
                'description'      => 'Construye los modelos financieros para gestionar la alta concentración de ventas en el último trimestre de la industria del juguete, usando IA para optimizar el flujo de caja, la inversión en stock y el presupuesto de marketing.',
                'prompt_content'   => <<<'EOT'
Actúa como un director financiero con experiencia en la industria del juguete y los productos de consumo estacionales. Gestiono las finanzas de un fabricante y distribuidor de juguetes con 15 millones de euros de facturación anual, donde el 65% de las ventas se concentra en el último trimestre del año. La alta estacionalidad crea retos financieros significativos: necesitamos financiar el stock de temporada meses antes de cobrar las ventas, gestionar el cash flow negativo de los meses de baja temporada y justificar las inversiones de marketing ante una dirección que quiere rentabilidad trimestral.

contexto: Los principales problemas financieros actuales son: (a) necesidad de financiar 4 millones de euros de stock en agosto-septiembre que no se cobra hasta noviembre-enero, (b) márgenes muy variables por referencia (desde el 15% en juguetes básicos hasta el 45% en juguetes con tecnología propia), (c) exposición a devoluciones masivas en enero de los distribuidores que no vendieron en Navidad (históricamente el 12% del valor facturado en temporada) y (d) dificultad para medir el ROI real de las inversiones en marketing de temporada. La dirección quiere un sistema financiero más sofisticado que permita tomar mejores decisiones.

tarea: Desarrolla el sistema de planificación financiera completo con los siguientes módulos:

1. MODELO DE FLUJO DE CAJA ESTACIONAL
Construye el modelo de cash flow mensual del año completo: (a) proyección de cobros — cuándo se cobra cada canal (las grandes superficies pagan a 90-120 días, las jugueterías independientes a 30-60 días, Amazon y tienda online pagan en 7-15 días), cómo el mix de canal afecta al patrón de cobros y cómo modelar el cash flow esperado mes a mes, (b) proyección de pagos — cuándo se paga la producción (50% adelanto al proveedor en junio, 50% al embarque en agosto-septiembre), cuándo se incurre en los costes de marketing (agosto a diciembre) y cuándo se paga la mano de obra de temporada, (c) identificación del déficit máximo de caja — en qué mes del año el gap entre cobros acumulados y pagos acumulados es mayor y qué instrumento financiero conviene usar para cubrirlo (línea de crédito, factoring, descuento de pagarés, anticipo de facturas) y (d) escenario de estrés — si las ventas de temporada son un 25% inferiores a la previsión, ¿cuánto se deteriora el cash flow y qué medidas de contingencia hay que activar? Presenta el modelo en formato tabla mes a mes con saldos de caja.

2. ANÁLISIS DE RENTABILIDAD POR REFERENCIA Y CANAL
Construye el modelo de análisis de rentabilidad: (a) cuenta de resultados por referencia — precio de venta, coste de fabricación, coste de packaging, coste de logística, inversión en marketing atribuible, descuentos por canal, provisión para devoluciones y rentabilidad neta real, (b) análisis por canal — margen neto que queda después de los descuentos, plazos de cobro y coste financiero del crédito comercial para Amazon, grandes superficies, jugueterías y tienda online propia, (c) umbral de rentabilidad por referencia — cuántas unidades hay que vender de cada juguete para que sea rentable, incluyendo la amortización de los costes de desarrollo y moldes y (d) clasificación del catálogo por rentabilidad real (no solo por volumen de ventas) y sus implicaciones para la estrategia de producto. Proporciona el modelo en formato tabla con los campos de cálculo de cada referencia.

3. GESTIÓN DEL STOCK COMO INVERSIÓN
Diseña el modelo de gestión financiera del stock: (a) modelo de ROI del stock — para cada referencia, calcular la rentabilidad del capital inmovilizado en stock (margen neto dividido entre el coste del stock multiplicado por el período de inmovilización), comparar con el coste del capital y decidir qué referencias merecen financiación prioritaria, (b) modelo de optimización del stock — cuánto stock fabricar de cada referencia para maximizar las ventas sin asumir riesgo excesivo de liquidación (modelo de cantidad óptima de pedido adaptado a la temporalidad del juguete), (c) política de provisiones — cuándo provisionar el stock que puede no venderse (normalmente a partir de enero), con qué porcentaje y cómo impacta en el resultado del ejercicio y (d) política de liquidación — a qué precio mínimo liquidar el stock sobrante para recuperar el máximo posible del coste, considerando el efecto en el precio de referencia del mercado.

4. PRESUPUESTO DE MARKETING Y SU ROI
Diseña el modelo de planificación y seguimiento del presupuesto de marketing: (a) cómo asignar el presupuesto de marketing entre referencias (proporcional a las ventas esperadas, proporcional al margen o concentrado en las novedades de mayor potencial), (b) cómo calcular el ROI esperado de cada inversión de marketing (si invertiré 30.000 euros en Amazon Ads para esta referencia, ¿cuántas unidades adicionales debo vender para que el ROI sea positivo?), (c) sistema de seguimiento semanal del gasto real vs. presupuesto por canal y referencia, con alertas cuando el gasto supera el plan o cuando el ROAS real está por debajo del objetivo y (d) modelo de atribución de las ventas a las diferentes inversiones de marketing (cómo saber cuánto de las ventas de Navidad se debe a la campaña de YouTube, cuánto a Amazon Ads y cuánto al boca a boca). Proporciona el template de seguimiento semanal del presupuesto de marketing.

5. GESTIÓN DE RIESGOS FINANCIEROS
Identifica los cinco mayores riesgos financieros de la temporada y diseña los planes de mitigación: (a) riesgo de ventas por debajo de la previsión — cuándo activar el plan de contingencia (si a mitad de noviembre las ventas acumuladas están un 15% por debajo de la previsión), qué medidas tomar (reducir el gasto de marketing no comprometido, activar descuentos selectivos, acelerar el cobro de distribuidores con descuento por pronto pago), (b) riesgo de concentración de cliente — si el top 3 de clientes representan el 45% de las ventas, qué pasa si uno de ellos cancela un pedido grande a mediados de diciembre, (c) riesgo de tipo de cambio — la empresa fabrica en China y paga en dólares, ¿cómo afecta una variación del 10% del tipo de cambio EUR/USD al margen de los productos? y qué herramientas de cobertura (forwards, opciones) son apropiadas para una empresa de este tamaño, (d) riesgo de devoluciones masivas en enero — cómo provisionar adecuadamente sin destruir el resultado del ejercicio y (e) riesgo de impago de algún distribuidor — política de crédito comercial y seguros de crédito. Proporciona el mapa de riesgos en formato tabla con probabilidad, impacto y plan de mitigación.

6. REPORTING FINANCIERO DE TEMPORADA
Diseña el sistema de reporting financiero para la temporada: (a) informe semanal de ventas — formato, destinatarios (dirección general, equipo comercial, producción) y cómo usar IA para generar automáticamente el análisis narrativo a partir de los datos, (b) informe mensual de rentabilidad — cuenta de resultados real vs. presupuesto por línea de producto y canal, análisis de desviaciones y proyección actualizada del resultado del año, (c) informe de cash flow — posición de tesorería actual, proyección de los próximos 90 días y alerta temprana si se va a necesitar financiación adicional y (d) informe de cierre de temporada — P&L real de la temporada, análisis de por qué las referencias más vendidas no fueron las más rentables (si ese fuera el caso) y recomendaciones para la planificación del año siguiente.

7. USO DE IA EN LA GESTIÓN FINANCIERA
Describe cómo usar IA para transformar la gestión financiera de la empresa: (a) previsión de ventas con IA — cómo un modelo de ML puede mejorar la precisión de la previsión de ventas de temporada un 30% respecto a los métodos históricos, qué datos usar y cómo actualizar el modelo semanalmente con los datos de ventas reales, (b) detección de anomalías — cómo la IA puede alertar automáticamente cuando los datos de ventas, stock o cobros presentan valores atípicos que requieren investigación, (c) generación de reportes narrativos — cómo usar modelos de lenguaje para convertir los datos financieros en narrativas comprensibles para la dirección en cinco minutos y (d) simulación de escenarios — cómo usar IA para simular el impacto financiero de diferentes decisiones estratégicas (lanzar tres novedades en lugar de cinco, entrar en el canal online alemán, fabricar el 20% del stock en Europa en lugar de Asia). Proporciona un ejemplo de prompt que usarías para generar el análisis narrativo del informe semanal de ventas.

8. PLAN FINANCIERO A TRES AÑOS
Diseña el plan financiero a tres años de la empresa: (a) proyección de crecimiento — de 15 millones a 20 millones en año dos y 26 millones en año tres, con los supuestos de nuevas referencias lanzadas, nuevos mercados y mejora de márgenes, (b) plan de inversiones — desarrollo de referencias con tecnología propia (mayor margen, mayor inversión de desarrollo), expansión del equipo comercial, herramientas de IA para operaciones y finanzas, (c) estructura de financiación — qué parte del crecimiento se financia con deuda (línea de crédito estacional, factoring) y qué parte requiere recursos propios o inversores y (d) objetivos financieros a tres años — margen EBITDA objetivo (de 8% actual a 12%), rotación del stock (de 3,5 veces a 4,5 veces), días de pago de clientes y rentabilidad sobre el capital invertido.

Presenta todos los modelos con las fórmulas de cálculo, tablas numéricas con datos reales del caso y un sistema de alertas para las decisiones financieras más críticas de la temporada. El tono debe ser riguroso financieramente y orientado a la toma de decisiones en condiciones de incertidumbre propia del negocio estacional.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 65,
                'use_case'         => 'Construir el sistema de planificación financiera completo para la alta estacionalidad de la industria del juguete con IA para previsión y gestión de riesgos.',
                'vote_score'       => 32,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Normativa de seguridad de juguetes y compliance con IA en la UE',
                'description'      => 'Navega el complejo marco regulatorio de seguridad de juguetes en la Unión Europea usando inteligencia artificial para gestionar el compliance, la documentación técnica y la vigilancia del mercado.',
                'prompt_content'   => <<<'EOT'
Actúa como un abogado especializado en derecho de producto, seguridad de bienes de consumo y normativa de juguetes en la Unión Europea. Asesoro a un fabricante de juguetes de tamaño mediano que quiere lanzar tres nuevas líneas de producto en el mercado europeo: juguetes de plástico para niños de 3 a 6 años, un juego de mesa para familias y un juguete interactivo con componente de inteligencia artificial y conexión a internet para niños de 5 a 10 años. Necesito un análisis completo de las obligaciones de compliance y un sistema para gestionarlo de forma eficiente.

contexto: La empresa fabrica en China y vende directamente en España, Francia, Alemania e Italia, además de a través de Amazon en otros ocho países de la UE. Tiene un responsable de calidad a tiempo completo pero no tiene departamento legal interno. Actualmente el proceso de compliance es reactivo y basado en la experiencia del responsable de calidad, sin documentación sistemática ni seguimiento de cambios normativos. El objetivo es construir un sistema de compliance proactivo que garantice que todos los productos cumplen con la normativa antes del lanzamiento y que el equipo está siempre al día de los cambios regulatorios.

tarea: Desarrolla el sistema de compliance completo con los siguientes componentes:

1. MARCO NORMATIVO DE SEGURIDAD DE JUGUETES EN LA UE
Analiza el marco regulatorio completo aplicable a los tres tipos de juguete: (a) Directiva de seguridad de juguetes 2009/48/CE — ámbito de aplicación, requisitos esenciales de seguridad (seguridad química, mecánica, eléctrica, inflamabilidad, higiene), normas técnicas armonizadas que presumen conformidad (EN 71 partes 1 a 14, EN 62115 para juguetes eléctricos) y cómo ha cambiado la directiva con las revisiones de 2019 y 2022, (b) Reglamento general de seguridad de productos (RGSP 2023/988) y cómo complementa la directiva de juguetes para los riesgos no previstos en la directiva específica, (c) Reglamento de máquinas (2023/1230) si algún juguete interactivo pudiera clasificarse como máquina y (d) requisitos adicionales para juguetes conectados e inteligentes: Reglamento de ciberseguridad (Cyber Resilience Act), Reglamento de privacidad y comunicaciones electrónicas, Directiva NIS2 si el sistema de IA del juguete se considera infraestructura crítica y los requisitos del AI Act para sistemas de IA que interactúan con niños.

2. PROCESO DE EVALUACIÓN DE CONFORMIDAD
Diseña el proceso de evaluación de conformidad para cada tipo de producto: (a) juguetes de plástico y juego de mesa — procedimiento de auto-certificación (módulo A), qué ensayos son obligatorios (lista de ensayos de las normas EN 71 aplicables según el tipo de juguete) vs. cuáles son recomendables, cómo elegir el laboratorio notificado y qué esperar del proceso (plazos, costes, informes de ensayo), (b) juguete interactivo con IA y conectividad — cuándo es obligatoria la evaluación por un organismo notificado (módulo B+C o módulo H), qué ensayos adicionales se requieren para los componentes electrónicos y de software y cómo documentar los requisitos de ciberseguridad y privacidad para el marcado CE y (c) documentación técnica — qué debe incluir el expediente técnico de cada producto, cómo organizarlo y durante cuánto tiempo conservarlo (mínimo diez años). Proporciona el checklist de documentación técnica para un juguete electrónico.

3. GESTIÓN DE PROVEEDORES Y FABRICACIÓN EN CHINA
Analiza los riesgos de compliance en la cadena de suministro con fabricación en China: (a) cómo asegurar que el fabricante chino conoce y cumple con los estándares europeos de seguridad (cláusulas contractuales, auditorías previas, requisitos de ensayo en origen), (b) gestión de los certificados de materiales — cómo verificar que los plásticos y pinturas usados cumplen con los límites de sustancias peligrosas del Anexo II de la directiva (ftalatos, metales pesados, PAHs, nitrosaminas), (c) protocolo de cambios de material o proceso por parte del fabricante — cómo garantizar que cualquier cambio se notifica y se re-evalúa antes de exportar y (d) gestión de la trazabilidad del lote de producción — qué información debe estar en el marcado del juguete (lote, país de fabricación, nombre y dirección del importador UE) y cómo gestionar las retiradas de producto si se detecta un problema en un lote específico.

4. COMPLIANCE DEL JUGUETE CON IA Y CONECTIVIDAD
Desarrolla el análisis específico para el juguete interactivo con IA: (a) aplicación del AI Act — ¿está el juguete con IA interactiva para niños en la categoría de "alto riesgo" del AI Act? Analiza los criterios de clasificación y qué obligaciones adicionales implica si la respuesta es sí (evaluación de conformidad, sistema de gestión de riesgos, gobernanza de datos de entrenamiento, supervisión humana, transparencia), (b) Cyber Resilience Act — qué categoría de producto conectado es el juguete (producto con elementos digitales), qué requisitos de seguridad cibernética debe cumplir en el diseño (autenticación, cifrado, actualizaciones de seguridad durante el ciclo de vida) y qué obligaciones tiene el fabricante cuando se detecta una vulnerabilidad, (c) protección de datos de menores — RGPD para menores, cómo obtener el consentimiento de los padres de forma verificable, qué datos puede recibir el juguete del niño y cómo minimizarlos (privacy by design) y (d) comunicación de seguridad a los padres — qué información debe incluir el packaging y el manual del juguete sobre el procesamiento de datos y la seguridad del sistema de IA.

5. SISTEMA DE VIGILANCIA DEL MERCADO
Diseña el sistema de vigilancia del mercado post-comercialización: (a) obligaciones legales de seguimiento post-venta (Reglamento de vigilancia del mercado 2019/1020) — qué información debe recoger la empresa sobre incidentes y reclamaciones, con qué plazos y a qué autoridades hay que notificar los incidentes graves, (b) sistema interno de gestión de reclamaciones — proceso para registrar, investigar y resolver reclamaciones de seguridad, umbral para escalar a la dirección y al equipo legal, (c) cómo usar IA para monitorizar el mercado — análisis de reseñas en Amazon y otras plataformas para detectar patrones de incidentes, monitorización de las bases de datos de alertas de producto de la UE (RAPEX/Safety Gate) para detectar alertas de competidores con productos similares y (d) plan de retirada de producto — cuándo activarlo, cómo comunicarlo a distribuidores y consumidores, obligaciones de notificación a la autoridad competente y costes estimados de una retirada.

6. SISTEMA DE GESTIÓN DEL COMPLIANCE CON IA
Diseña cómo usar IA para gestionar el compliance de forma eficiente con un equipo pequeño: (a) monitorización de cambios normativos — cómo usar IA para seguir las actualizaciones de la directiva de juguetes, las normas EN 71, el AI Act y el Cyber Resilience Act y recibir alertas con el impacto en los productos actuales, (b) gestión documental — cómo usar IA para organizar, buscar y actualizar la documentación técnica de cada producto, generar checklists de compliance automáticos y detectar documentos que han expirado o que necesitan actualización por un cambio de norma, (c) revisión de diseño — cómo usar IA para revisar el diseño de un nuevo producto frente a los requisitos de la directiva y detectar posibles problemas antes de enviar a ensayo (ahorrando el coste de ensayos de productos no conformes) y (d) formación continua — cómo usar IA para formar al equipo de diseño, producción y comercial en las obligaciones de compliance sin necesitar formaciones presenciales costosas. Proporciona el prompt que usarías para que la IA genere un resumen del impacto del Cyber Resilience Act en el nuevo juguete interactivo.

7. GESTIÓN DE CRISIS Y RETIRADAS DE PRODUCTO
Diseña el protocolo de gestión de crisis de producto: (a) sistema de clasificación de incidentes — categorías (incidente sin lesión, incidente con lesión menor, incidente con lesión grave, incidente fatal) y los protocolos de respuesta para cada categoría, (b) árbol de decisión para retirada de producto — cuándo es una retirada voluntaria, cuándo es obligatoria por orden de la autoridad, cómo valorar el coste-beneficio de una retirada preventiva, (c) proceso de comunicación en crisis — quién habla (portavoz designado), qué canales usar (comunicado de prensa, web, redes sociales, contacto directo a distribuidores), qué decir y qué no decir para evitar responsabilidad adicional y (d) recuperación de la reputación — cómo gestionar la comunicación post-crisis para restaurar la confianza de distribuidores, consumidores y autoridades. Proporciona el borrador de comunicación de retirada de producto para un juguete con riesgo de asfixia por piezas pequeñas desprendibles.

8. PROGRAMA DE COMPLIANCE ANUAL
Diseña el programa de compliance anual con el calendario de actividades: (a) ciclo de revisión de productos existentes — cuándo y cómo revisar si los productos actuales siguen cumpliendo (cambios de normas, cambios en la cadena de suministro, incidentes detectados en el mercado), (b) proceso de aprobación de nuevos productos — en qué fase del desarrollo se integra la revisión de compliance, qué documentación debe estar lista antes de aprobar el lanzamiento, (c) auditorías de proveedores — frecuencia, metodología y criterios de aprobación de los proveedores clave de China y (d) formación del equipo — qué áreas de la empresa necesitan formación en compliance (diseño, producción, ventas, atención al cliente) y el plan de formación anual. Proporciona el calendario anual de compliance en formato tabla con los hitos clave de cada trimestre.

Presenta el análisis con referencias normativas específicas, checklists listos para usar y un sistema de priorización de las acciones de compliance según el riesgo. El tono debe ser riguroso jurídicamente pero orientado a la gestión práctica por un equipo sin experiencia legal especializada.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 65,
                'use_case'         => 'Construir un sistema de compliance proactivo para fabricantes de juguetes en la UE, incluyendo los nuevos requerimientos para juguetes con IA y conectividad.',
                'vote_score'       => 25,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención al cliente en temporada de juguetes con IA: guía completa',
                'description'      => 'Diseña un sistema de atención al cliente para la industria del juguete que gestione el cuádruple de volumen en temporada alta usando inteligencia artificial para mantener la calidad de servicio.',
                'prompt_content'   => <<<'EOT'
Actúa como un director de atención al cliente con experiencia en la industria del juguete y en la implementación de sistemas de IA para gestionar picos de demanda estacionales sin sacrificar la calidad del servicio. Dirijo el equipo de CS de un fabricante de juguetes que opera tanto B2B (servicio a distribuidores y jugueterías) como B2C (consumidores finales a través de la tienda online). En temporada alta (octubre a enero) el volumen de contactos se multiplica por cuatro: pasamos de 200 contactos diarios a 800, con los temas concentrados en: disponibilidad y plazos de entrega, montaje e instrucciones de juguetes, problemas técnicos de juguetes electrónicos y gestión de devoluciones y garantías navideñas.

contexto: El equipo actual es de seis agentes a tiempo completo, y cada temporada contratamos cuatro agentes temporales que necesitan formación intensiva. La tecnología actual es básica: un gestor de tickets por email y un número de teléfono. La tasa de resolución en primer contacto es del 68% fuera de temporada y cae al 52% en temporada por la presión del volumen. El objetivo es mantener la resolución en primer contacto por encima del 70% en temporada usando IA, sin aumentar el presupuesto de personal más de un 20%.

tarea: Diseña el sistema de CS con IA para la temporada alta con los siguientes componentes:

1. ANÁLISIS DE VOLUMEN Y TIPOLOGÍA DE CONTACTOS
Diseña el sistema de análisis de contactos de temporada: (a) cómo usar IA para analizar el histórico de tickets de las últimas tres temporadas y clasificarlos automáticamente por tipo (disponibilidad de stock, instrucciones de montaje, problema técnico del juguete, devolución o cambio, queja por regalo equivocado, daño en el transporte), (b) distribución horaria y semanal de los contactos en temporada — cuándo llegan los picos (24 y 25 de diciembre con juguetes sin instrucciones claras, primera semana de enero con devoluciones), (c) qué porcentaje de cada tipo de contacto puede resolverse de forma completamente automatizada con IA, cuál requiere asistencia de la IA al agente humano y cuál es puramente humano y (d) impacto financiero de los problemas más frecuentes — cuánto cuesta en tiempo de agente cada tipo de contacto y cuánto se podría ahorrar con la automatización. Proporciona la matriz de tipología de contactos con el nivel de automatización recomendado para cada uno.

2. CHATBOT PARA TEMPORADA CON IA
Diseña el chatbot de IA específico para la temporada de juguetes: (a) capacidades del chatbot — qué consultas resuelve de forma autónoma (estado del pedido en tiempo real conectado al sistema logístico, instrucciones de montaje de cualquier referencia del catálogo en formato paso a paso e ilustrado, política de devoluciones y cómo iniciar el proceso, disponibilidad de una referencia específica en tiendas cercanas o en la web) y qué escala al humano, (b) flujos de conversación específicos de temporada — árbol de conversación para el 24 de diciembre a las 22h cuando un padre no puede montar el juguete de su hijo, para el 26 de diciembre cuando quieren devolver un regalo repetido y para el 2 de enero cuando el juguete electrónico no enciende, (c) integración con sistemas — cómo conectar el chatbot con el ERP para información de pedidos, con la base de datos de instrucciones de montaje (PDFs e ilustraciones por referencia) y con el sistema logístico para tracking en tiempo real y (d) diseño de la personalidad del chatbot — tono empático y festivo en Navidad, eficiente pero cálido, con nombre propio que conecte con la marca. Proporciona el flujo de conversación completo para el caso del juguete que no se puede montar la noche del 24 de diciembre.

3. SISTEMA DE ASISTENCIA AL AGENTE CON IA
Diseña las herramientas de asistencia IA para los agentes humanos: (a) sugerencias de respuesta en tiempo real — la IA sugiere al agente la respuesta más adecuada basándose en el tipo de consulta, el historial del cliente y las políticas actuales, con opciones para editar y personalizar antes de enviar, (b) búsqueda inteligente en la base de conocimiento — el agente escribe el problema del cliente en lenguaje natural y la IA recupera los artículos de ayuda más relevantes, incluyendo instrucciones de montaje, soluciones a problemas técnicos conocidos y políticas de garantía, (c) resumen automático de conversaciones largas — cuando una consulta lleva varios intercambios, la IA genera un resumen del contexto para que el agente se ponga al día en 30 segundos y (d) detección de sentimiento y priorización — la IA analiza el tono del cliente (frustrado, urgente, potencialmente viral en redes sociales) y prioriza las escaladas al supervisor. Proporciona el diseño de la interfaz del agente con IA en formato descripción detallada.

4. GESTIÓN DE INSTRUCCIONES DE MONTAJE CON IA
Diseña el sistema de soporte de montaje de juguetes con IA — uno de los motivos más frecuentes de contacto en temporada: (a) base de datos de instrucciones — cómo estructurar las instrucciones de todas las referencias del catálogo en un formato que la IA pueda consultar y presentar de forma interactiva (paso a paso, con imágenes del paso correspondiente, con posibilidad de repetir un paso o pedir más detalle), (b) asistente de montaje conversacional — un flujo de conversación donde el cliente describe el problema que tiene en el montaje y la IA lo guía hasta resolverlo, preguntando por el nombre del juguete, el paso donde está atascado y qué ha intentado ya, (c) vídeos de montaje generados con IA — para las referencias con mayor volumen de consultas, cómo crear micro-vídeos de montaje paso a paso con narración de IA y (d) sistema de mejora continua — cómo usar las transcripciones de las conversaciones de soporte de montaje para identificar qué pasos de las instrucciones son más confusos y mejorar el diseño de instrucciones de futuros productos. Proporciona el ejemplo de conversación de asistencia de montaje para un juguete de construcción con 80 piezas.

5. GESTIÓN DE DEVOLUCIONES Y GARANTÍAS EN TEMPORADA
Diseña el proceso de gestión de devoluciones y garantías con IA: (a) política de devoluciones de temporada — cuánto tiempo para devolver un regalo de Navidad (mínimo 30 días por ley, pero qué política propia aplica la empresa), en qué condiciones y por qué canales, (b) automatización del proceso de devolución — cómo permite el chatbot iniciar una devolución sin intervención humana (verificar la compra, generar la etiqueta de devolución, informar del tiempo de reembolso), (c) gestión de defectos y garantía — proceso de verificación del defecto (qué fotos o vídeo pedir al cliente), cuándo ofrecer reparación vs. sustitución vs. reembolso y en qué plazo, y cómo documentar los defectos para informar al equipo de calidad y (d) análisis de devoluciones con IA — cómo categorizar automáticamente las razones de devolución para detectar si hay un problema de calidad sistémico en un lote de producción o si las devoluciones son por razones de preferencia del consumidor. Proporciona el árbol de decisión de gestión de una devolución post-Navidad.

6. FORMACIÓN DE AGENTES TEMPORALES CON IA
Diseña el programa de formación de los cuatro agentes temporales usando IA: (a) formación de producto — cómo usar IA para generar fichas de producto de cada referencia del catálogo en formato conversacional, listas para que el agente las consulte durante la atención, (b) simulación de escenarios — biblioteca de los 20 casos más frecuentes de temporada, con el agente temporal practicando la respuesta y recibiendo feedback de la IA sobre la calidad y completitud de su respuesta, (c) proceso de certificación — cuándo un agente temporal está listo para atender clientes de forma autónoma (mínimo de casos de práctica, puntuación mínima en la evaluación de la IA) y (d) soporte continuo durante la temporada — cómo la IA actúa como "buddy" del agente temporal, disponible para responder dudas durante la atención en tiempo real sin que el cliente lo note. Proporciona el plan de formación de las primeras 48 horas del agente temporal.

7. MÉTRICAS DE CS EN TEMPORADA CON OBJETIVOS
Define diez métricas de atención al cliente para la temporada alta con objetivos específicos: tasa de resolución en primer contacto (objetivo: mantener 70% en temporada vs. 68% fuera de temporada), tasa de resolución del chatbot sin escalada (objetivo: 55% de contactos resueltos de forma autónoma), tiempo de respuesta en canal digital (objetivo: menos de cuatro horas en email, menos de dos minutos en chat), tiempo de respuesta en teléfono (objetivo: menos de tres minutos de espera en el 80% de las llamadas), CSAT por canal y por tipo de consulta, tasa de devoluciones gestionadas en menos de 48 horas, NPS de temporada, tasa de contactos repetidos por el mismo problema (indicador de calidad de la resolución), coste de atención por contacto y tasa de escalada de chatbot a agente humano. Diseña el dashboard diario de temporada con las alertas automáticas más críticas.

8. PLAN DE MEJORA POST-TEMPORADA
Diseña el proceso de análisis y mejora post-temporada: (a) informe de temporada — qué analizar (volumen y tipología de contactos real vs. plan, eficiencia por canal, CSAT por tipo de consulta, problemas de producto más frecuentes reportados por CS), (b) mejora del chatbot — cómo usar las transcripciones de conversaciones donde el chatbot falló para mejorar los flujos y entrenar mejor el modelo para la siguiente temporada, (c) mejora de instrucciones de producto — comunicación formal al equipo de diseño y producción de los juguetes con más consultas de montaje y los pasos específicos que generaron más confusión y (d) planificación de la siguiente temporada — cuándo empezar a preparar el sistema de CS para la próxima temporada (en marzo, ocho meses antes) y qué decisiones de infraestructura tecnológica tomar con tiempo suficiente.

Presenta el sistema con flujos de conversación del chatbot, templates de comunicación con clientes y un plan de implementación para los próximos 90 días. El tono debe ser empático con el cliente y orientado a la resolución eficiente de problemas, especialmente en los momentos más estresantes de la temporada navideña.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Diseñar un sistema de atención al cliente con IA para cuadriplicar la capacidad en temporada de juguetes sin aumentar proporcionalmente el equipo.',
                'vote_score'       => 46,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Diseño freelance de juguetes y juegos de mesa: kit de herramientas IA',
                'description'      => 'Domina las herramientas de inteligencia artificial que te permiten ofrecer servicios de diseño de juguetes y juegos de mesa como freelancer con mayor velocidad, calidad y precio competitivo.',
                'prompt_content'   => <<<'EOT'
Actúa como un diseñador freelance especializado en juguetes y juegos de mesa con experiencia en la aplicación de herramientas de inteligencia artificial para acelerar el proceso de diseño, mejorar la calidad de las propuestas y gestionar el negocio de consultoría creativa de forma más eficiente. Quiero reinventarme como diseñador freelance de juguetes y juegos de mesa después de siete años en el departamento de diseño de una empresa del sector, diferenciándome por el uso intensivo de IA en todo el proceso de diseño.

contexto: Tengo experiencia en diseño industrial de juguetes de plástico, diseño gráfico de packaging y diseño de mecánicas de juego para juegos de mesa. Mi red de contactos incluye tres fabricantes de juguetes con los que he trabajado y varios estudios de diseño que subcontratan proyectos. Mi objetivo es facturar 60.000 euros en el primer año como freelancer, ofreciendo servicios de mayor valor añadido que los diseñadores tradicionales gracias a la IA, y escalar a 100.000 euros en el segundo año con servicios productizados.

tarea: Diseña el kit de herramientas y el modelo de negocio con los siguientes componentes:

1. STACK DE HERRAMIENTAS DE IA POR TIPO DE PROYECTO
Define el stack de herramientas de IA para cada tipo de servicio que ofreces: (a) diseño conceptual de juguetes — qué herramientas de IA generativa de imagen usas para la exploración de conceptos (Midjourney para estilo artístico, Adobe Firefly integrado en Creative Suite para coherencia con flujos de trabajo existentes, Canva con IA para mockups rápidos), qué instrucciones tipo usas para cada fase y cómo combinas las herramientas, (b) diseño de packaging — cómo usas IA para generar composiciones de packaging, texto de producto en varios idiomas y mockups de tienda para presentación al cliente, (c) diseño de juegos de mesa — qué herramientas usas para diseñar cartas, tableros, fichas y reglas (IA para el arte, Claude para el texto de las reglas y la narrativa del juego, herramientas de layout como Affinity Publisher) y (d) prototipado virtual — cómo usas renders con IA para presentar el producto terminado antes de fabricar el prototipo físico. Para cada herramienta, indica el coste mensual, el caso de uso principal y el nivel de habilidad necesario para usarla bien.

2. PROCESO DE DISEÑO AUMENTADO CON IA
Describe tu proceso de diseño freelance con IA integrada en cada fase: (a) brief y discovery — cómo usas IA para analizar el brief del cliente, identificar ejemplos de referencia en el mercado (búsqueda y análisis de competidores con IA) y generar las preguntas clave que debes hacer al cliente antes de empezar, (b) fase de concepto (días uno a tres) — cómo generas entre 30 y 50 variantes conceptuales con IA en dos horas, las filtras a los diez mejores y los presentas al cliente para selección, (c) fase de desarrollo (días cuatro a diez) — cómo usas la selección del cliente para profundizar el concepto elegido, iterar sobre los detalles y preparar los archivos técnicos para producción con IA como asistente y (d) fase de entrega — cómo usas IA para generar el dossier de diseño, los archivos para diferentes medios y la presentación final al cliente. Calcula el tiempo total de cada fase con y sin IA y el impacto en tu rentabilidad.

3. CATÁLOGO DE SERVICIOS Y PROPUESTA DE VALOR
Diseña el catálogo de servicios con cuatro líneas de producto: (a) sprint de concepto — 50 variantes visuales de concepto de juguete o juego en 48 horas, con cinco variantes refinadas y un dossier de presentación, precio sugerido entre 800 y 1.500 euros según la complejidad, (b) diseño completo de juguete — del concepto al archivo técnico para producción, incluyendo tres rondas de revisión, precio entre 3.000 y 8.000 euros según el tipo de juguete, (c) diseño integral de juego de mesa — concepto, arte de todas las cartas y componentes, reglas y packaging, precio entre 5.000 y 15.000 euros según el número de componentes y (d) pack startup de juguete — para inventores y startups que tienen una idea y necesitan ayuda para llevarla a prototipo presentable a inversores o fabricantes, precio entre 2.500 y 5.000 euros. Para cada servicio, define los entregables exactos, el tiempo de ejecución y las condiciones de pago.

4. POSICIONAMIENTO Y COMUNICACIÓN COMO FREELANCER
Define tu posicionamiento como diseñador freelance con IA: (a) qué aporta la IA a tus clientes (más opciones en menos tiempo, menor coste de iteración, posibilidad de ver el producto terminado virtualmente antes de invertir en moldes o producción), (b) cómo comunicar el uso de IA a clientes que pueden ser escépticos sobre la autoría y originalidad del diseño (la IA como herramienta, la visión y el criterio como propios, el proceso de curation como parte del valor), (c) cómo diferenciarte de diseñadores freelance sin IA (velocidad de propuesta, amplitud de opciones, precio competitivo en la fase de exploración) y de diseñadores que usan IA sin experiencia sectorial (conocimiento de normativa de juguetes, comprensión de los requerimientos de fabricación, red de contactos del sector) y (d) tres mensajes de posicionamiento para LinkedIn y tres para el portfolio online. Redacta el titular de tu perfil de LinkedIn y el primer párrafo de tu bio de portfolio.

5. GENERACIÓN DE PORTFOLIO CON IA
Diseña el proceso de construcción de portfolio con IA: (a) cómo usar IA para crear casos de estudio de proyectos reales de tu etapa corporativa sin revelar información confidencial (anonimizar la marca, cambiar el contexto suficiente para no identificar el cliente, resaltar tu contribución específica), (b) cómo crear proyectos de portfolio propios con IA — elige tres conceptos de juguete o juego que nunca has podido desarrollar en tu etapa corporativa y úsalos como proyectos de showcase personal, con el proceso completo de concepto a prototipo virtual, (c) formato del dossier de cada proyecto de portfolio — qué incluir (brief ficticio o real anonimizado, proceso de exploración con IA, selección y justificación del concepto final, renders del producto terminado, reflexión sobre qué aprendiste) y (d) publicación del portfolio — plataforma (Behance, web propia con Webflow, Notion público) y cómo usar IA para escribir los textos de cada proyecto.

6. ADQUISICIÓN DE CLIENTES EN LOS PRIMEROS 60 DÍAS
Diseña el plan de lanzamiento del negocio freelance: (a) activación de la red existente — mensaje personalizado a los tres fabricantes con los que has trabajado ofreciendo el nuevo servicio de sprint de concepto con IA, mensaje a los estudios de diseño de tu red para posicionarte como subcontratista especializado y mensaje a ex-colegas que ahora están en empresas de juguetes, (b) generación de contenido en LinkedIn — plan de contenido de ocho semanas (dos publicaciones semanales) con los temas más atractivos para directores de producto y marketing de juguetes (cómo la IA está cambiando el diseño de juguetes, comparativa de conceptos generados con y sin IA, proceso detrás de un diseño de juego de mesa), (c) participación en comunidades — dónde están los potenciales clientes online (LinkedIn grupos de juguetes, Discord de diseño de juegos, ferias virtuales) y cómo aportar valor antes de intentar vender y (d) oferta de lanzamiento — una oferta especial de sprint de concepto a precio reducido para los primeros tres clientes a cambio de un testimonio y permiso para publicar el trabajo. Proporciona el mensaje de presentación que enviarías al director de producto de uno de los fabricantes de tu red.

7. GESTIÓN DEL NEGOCIO FREELANCE CON IA
Explica cómo usar IA para gestionar el negocio freelance de diseño: (a) propuestas comerciales — cómo generar en 30 minutos una propuesta personalizada para cada cliente a partir de una plantilla base, incluyendo la descripción del servicio, el proceso, los entregables, el plazo y el precio, (b) contratos — cómo usar IA para generar el contrato de diseño adaptado a cada proyecto (incluyendo cláusulas de propiedad intelectual, derechos de IA, confidencialidad y revisiones incluidas), (c) gestión de clientes — qué CRM o herramienta de gestión de proyectos usar (Notion, Trello, ClickUp) y cómo automatizar los recordatorios de facturación y el seguimiento de proyectos y (d) facturación y contabilidad — stack de herramientas para la parte administrativa del freelancing (Holded o Quipu para facturación, gestoría online para la fiscalidad). Proporciona el template de propuesta comercial de una página que usarías para el servicio de sprint de concepto.

8. ESCALABILIDAD Y AÑO DOS
Diseña la estrategia de escalabilidad hacia los 100.000 euros en el segundo año: (a) productización del sprint de concepto — convertirlo en un producto completamente estandarizado con precio fijo, entregable en 48 horas y proceso casi completamente automatizado con IA para poder vender varios en paralelo, (b) curso online o taller de diseño de juguetes con IA — dirigido a otros diseñadores del sector que quieren aprender a usar IA en su trabajo (precio entre 200 y 500 euros por participante, ediciones mensuales de 20 personas), (c) licenciamiento de prompts e instrucciones de IA — crear un pack de instrucciones de IA especializadas en diseño de juguetes para vender a otros diseñadores del sector y (d) asociación con un estudio de desarrollo de juegos — unirte a un estudio más grande como freelancer especializado en IA para proyectos de mayor presupuesto. Para cada palanca de crecimiento, estima el tiempo de inversión para desarrollarla y el potencial de ingresos adicionales.

Presenta el kit de herramientas con instrucciones específicas de IA listas para usar, el catálogo de servicios con todos los detalles y un plan de implementación semanal para los primeros 60 días de actividad freelance. El tono debe ser creativo y emprendedor, orientado al freelancer que quiere construir un negocio diferencial en el mundo del diseño de juguetes.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 50,
                'use_case'         => 'Construir el kit de herramientas de IA y el modelo de negocio para un freelancer especializado en diseño de juguetes y juegos de mesa.',
                'vote_score'       => 49,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
