<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills570Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Marketing local y atracción de clientes a tiendas físicas con IA',
                'description'      => 'Diseña estrategias de marketing hiperlocal para tiendas físicas usando IA para atraer tráfico, fidelizar clientes del entorno y competir con el ecommerce desde la ventaja de la proximidad y la experiencia presencial.',
                'prompt_content'   => <<<'EOT'
Eres un director de marketing especializado en el sector minorista y el comercio de proximidad. Tienes experiencia desarrollando estrategias de marketing local para cadenas de tiendas físicas, comerciantes independientes y franquicias que compiten con el ecommerce y con los grandes distribuidores. Sabes que el marketing de tienda física tiene particularidades propias: el radio de captación es local, la experiencia presencial es el principal diferenciador y los recursos suelen ser más limitados que en el comercio online.

Contexto de la empresa:
- Cadena de 12 tiendas de ferretería y bricolaje en ciudades medianas de España
- Cada tienda tiene una zona de influencia de aproximadamente 5 km
- Competencia principal: Leroy Merlin y Bricomart (grandes superficies) y Amazon para los productos más estándar
- Situación: las ventas han caído un 15% en los últimos 2 años por la competencia del ecommerce y de las grandes superficies
- Presupuesto de marketing: 3.000 euros mensuales por tienda para campañas locales
- Ventajas competitivas identificadas: asesoramiento experto del personal, posibilidad de cortar materiales a medida, entrega rápida en la misma ciudad, devoluciones sin burocracia

Desarrolla la estrategia completa de marketing local con IA:

1. Estrategia de marketing hiperlocal por radio de influencia: El marketing de tienda física debe ser hiperlocal. Diseña el sistema. Incluye: segmentación del radio de influencia de cada tienda (zona de captación primaria a menos de 2 km, zona secundaria de 2 a 5 km, zona de oportunidad más allá de 5 km para clientes muy específicos), perfil del cliente local de la ferretería (propietarios de vivienda en obras de mejora, fontaneros y electricistas del entorno que necesitan reponer materiales urgentes, jardineros aficionados, comunidades de vecinos que necesitan reparaciones) y su comportamiento de compra diferenciado, estrategia de medios locales para cada zona (publicidad en el periódico digital local, colaboración con las asociaciones de vecinos del barrio, presencia en los grupos de WhatsApp y Facebook de vecinos del barrio), uso de Google Ads para campañas de búsqueda local con radio geográfico (captando las búsquedas de "ferretería cerca" o "materiales de construcción [nombre del barrio]") y estrategia de SEO local para aparecer primero en las búsquedas de Google Maps.

2. Google My Business y presencia digital local: La presencia en Google Maps es el primer punto de contacto de la mayoría de los clientes locales. Diseña el sistema. Incluye: optimización completa del perfil de Google My Business de cada tienda (nombre, dirección, horario actualizado, categorías correctas, fotos de la tienda, el equipo y los productos más buscados, respuestas a todas las preguntas de los clientes), estrategia de gestión de las reseñas de Google (proceso para pedir reseñas a los clientes satisfechos, protocolo de respuesta a las reseñas positivas y negativas, uso de IA para generar respuestas personalizadas a las reseñas), uso de los Posts de Google My Business para publicar ofertas semanales, novedades de producto y consejos de bricolaje (cada post es una mini-campaña gratuita que aparece en Google Maps), sistema de seguimiento de las métricas de Google My Business (número de búsquedas que muestran la ficha, número de clics en "Cómo llegar", número de llamadas desde la ficha) y integración de las búsquedas de Google Maps con las campañas de Google Ads Local.

3. Fidelización del cliente local: Los clientes fieles son el activo más valioso de la tienda física. Diseña el programa. Incluye: diseño del programa de fidelización de la cadena de ferreterías (puntos por compra, ventajas exclusivas para socios: descuentos en días específicos, acceso prioritario a talleres de bricolaje, asesoramiento personalizado gratuito), digitalización del programa de fidelización (app de la cadena o tarjeta de fidelización con código QR en el móvil que el cliente presenta en caja), uso de los datos de compra del cliente fidelizado para personalizar las comunicaciones (el cliente que siempre compra materiales de jardinería recibe las ofertas de jardinería antes que el resto), sistema de notificaciones push personalizadas para los clientes de la app (aviso cuando llega un producto que el cliente ha buscado antes, oferta flash de 24 horas exclusiva para socios, recordatorio de que el proyecto que empezó hace 3 meses lo puede continuar con un descuento esta semana) y análisis del valor del cliente fidelizado vs. el cliente ocasional.

4. Marketing de contenidos local y posicionamiento como experto: La tienda física puede competir con Amazon siendo el experto local de referencia. Diseña el sistema. Incluye: estrategia de contenidos de bricolaje y hogar para el blog y el canal de YouTube de la cadena (tutoriales de instalación de los productos más vendidos, guías de mantenimiento del hogar por temporada, consejos de los expertos de la tienda para proyectos de bricolaje), canal de WhatsApp de la tienda para los clientes más activos (donde se comparten los consejos semanales del experto y las ofertas exclusivas de la semana), presencia en Instagram con contenido visual de proyectos de bricolaje terminados por clientes de la tienda (el antes y el después, con mención a los productos de la tienda que se han usado), talleres presenciales gratuitos en la tienda (cómo instalar un grifo, cómo pintar una habitación, cómo poner un suelo de madera: atraen potenciales clientes a la tienda y posicionan a los empleados como expertos) y uso de IA para generar el contenido de los distintos canales de forma eficiente.

5. Campañas de publicidad local con presupuesto limitado: 3.000 euros al mes por tienda requieren maximizar el impacto. Diseña el plan. Incluye: distribución óptima del presupuesto mensual de 3.000 euros por tienda entre los canales (Google Ads Local con extensión de ubicación: 1.200 euros; Meta Ads con segmentación geográfica de 3 km: 800 euros; publicidad digital en medios locales: 400 euros; producción de contenido e IA: 300 euros; otras acciones locales: 300 euros), estrategia de campañas de Meta Ads hiperlocales (radio de 3 km alrededor de cada tienda, segmentación por intereses de bricolaje y hogar, creatividades con el nombre del barrio o la ciudad para aumentar la relevancia), uso de IA para optimizar el gasto publicitario local (análisis semanal del coste por visita a la tienda por canal y redistribución del presupuesto hacia los canales más eficientes), campañas estacionales de alto impacto (primavera: jardinería y exterior; verano: piscinas y reforma de vacaciones; otoño: calefacción y aislamiento; navidades: herramientas y regalos de bricolaje) y colaboración con otros comercios locales complementarios para campañas conjuntas.

6. Experiencia del cliente en tienda como palanca de marketing: La experiencia en tienda es el principal diferenciador frente al ecommerce. Diseña el sistema. Incluye: diseño de la experiencia en tienda que hace que el cliente vuelva (disposición del producto que favorece el descubrimiento, zona de asesoramiento técnico donde los expertos resuelven dudas, servicio de corte de materiales a medida que Amazon no puede ofrecer), formación del equipo de tienda en técnicas de venta y asesoramiento que crean fidelidad (cómo preguntar qué proyecto tiene el cliente para sugerirle todo lo que necesita, no solo lo que viene a comprar), sistema de feedback post-visita (encuesta por SMS o email al día siguiente de la compra con la pregunta de NPS: ¿nos recomendarías a un amigo? y qué podemos mejorar) y proceso de gestión de las quejas en tienda para convertir una mala experiencia en una oportunidad de fidelización.

7. Análisis del rendimiento del marketing local con IA: Medir el impacto del marketing local es más difícil que en el digital. Diseña el sistema. Incluye: métricas de negocio de la tienda física que el marketing debe mover (tráfico de clientes a la tienda, ticket medio por visita, frecuencia de visita de los clientes fidelizados, tasa de conversión de visitas a compras), sistema de atribución de visitas a la tienda a los canales de marketing (Google Ads Store Visits, Meta Ads Offline Conversions con los datos de las compras en tienda, encuesta de "¿cómo nos has conocido?" en el momento del alta en el programa de fidelización), dashboard mensual de marketing local por tienda (KPIs de cada canal: impresiones, clics, visitas atribuidas, coste por visita; KPIs del negocio: facturación, clientes nuevos, clientes fidelizados activos) y proceso de revisión mensual del rendimiento de cada tienda con el encargado local para adaptar la estrategia a las particularidades del entorno de cada una.

Incluye plantilla de plan de marketing local mensual por tienda, sistema de métricas de Google My Business y calendario de campañas estacionales para ferreterías. Todo orientado a cadenas de tiendas físicas con presupuestos limitados compitiendo con el ecommerce.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Recuperación de ventas en cadena de 12 ferreterías ante la competencia del ecommerce y las grandes superficies mediante marketing hiperlocal',
                'vote_score'       => 39,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de sistemas de gestión de tienda y punto de venta con IA',
                'description'      => 'Diseña y construye sistemas POS, plataformas de gestión de inventario y herramientas de analítica de retail usando IA para optimizar el flujo de caja, predecir la demanda y mejorar la eficiencia operativa de tiendas físicas.',
                'prompt_content'   => <<<'EOT'
Eres un arquitecto de software especializado en el desarrollo de sistemas de información para el sector del comercio minorista. Tienes experiencia construyendo sistemas de punto de venta (POS), plataformas de gestión de inventario, sistemas de fidelización de clientes, herramientas de análisis de ventas y soluciones de integración entre el canal físico y el canal online (omnicanal). Conoces las particularidades técnicas del retail: los sistemas POS deben funcionar sin conexión a internet, el inventario en tiempo real es crítico para evitar roturas de stock, y la integración entre tiendas físicas y ecommerce es un reto de sincronización de datos complejo.

Contexto del proyecto:
- Cadena de 25 tiendas de moda y complementos en España
- Sistema actual: POS legacy de 2011 en cada tienda, sin comunicación entre tiendas ni con el ecommerce lanzado en 2020
- Problemas: el inventario no está sincronizado entre tiendas y ecommerce (se producen ventas de productos sin stock disponible), no hay visibilidad del stock en tiempo real entre tiendas (un cliente en Madrid no puede saber si el producto está en la tienda de Barcelona), la gestión del inventario es manual con Excel, y los datos de ventas no se pueden analizar de forma centralizada
- Objetivo: desarrollar un sistema integrado que unifique el POS de las 25 tiendas, el ecommerce y la gestión del inventario en tiempo real

Desarrolla la arquitectura completa del sistema de gestión minorista:

1. Arquitectura del sistema de POS moderno: El POS es el corazón de la tienda física. Diseña la arquitectura. Incluye: componentes del POS moderno basado en la nube (frontend: aplicación en tablet o terminal de tienda que funciona offline con sincronización posterior cuando vuelve la conexión; backend: API central que gestiona el inventario, las ventas, los clientes y los pagos; base de datos: diseño del modelo de datos para productos, SKUs, variantes, precios, clientes, transacciones), flujo técnico de una venta en el POS (el cajero escanea el código de barras → el sistema comprueba el stock → el cliente paga (efectivo, tarjeta, móvil) → la venta se registra → el inventario se actualiza en tiempo real en todas las tiendas y en el ecommerce), diseño del modo offline del POS (cómo funciona la tienda cuando no hay conexión a internet: qué datos se cachean localmente, cómo se sincronizan las transacciones cuando vuelve la conexión, cómo se gestionan los conflictos de inventario), integración con los principales terminales de pago (Ingenico, Verifone: protocolo de comunicación, manejo de errores, gestión de las devoluciones y los pagos parciales) y sistema de impresión de tickets y de gestión de devoluciones.

2. Sistema de gestión de inventario en tiempo real: El inventario en tiempo real es el diferenciador del retail moderno. Diseña el sistema. Incluye: modelo de datos del inventario (producto → variantes (color, talla) → SKU → ubicación: tienda física X, almacén central, stock en tránsito, reservado por pedido online en tienda), sistema de actualización del inventario en tiempo real cuando se produce una venta en cualquier canal (tienda física o ecommerce) o una recepción de mercancía, sistema de alertas de stock (umbral de reorden: cuando el stock de un SKU en una tienda baja del umbral, se genera automáticamente una solicitud de traspaso desde la tienda con más stock o desde el almacén central), gestión de los traspasos de mercancía entre tiendas (solicitud de traspaso, confirmación, seguimiento del envío, recepción y actualización del inventario), sistema de inventario cíclico asistido por IA (qué zona de la tienda inventariar cada día para tener el inventario completo actualizado sin hacer el inventario general cerrado) y gestión de las mermas, las roturas y los productos defectuosos.

3. Motor de predicción de la demanda con IA: Predecir qué va a vender cada tienda permite optimizar el inventario. Diseña el sistema de ML. Incluye: datos disponibles para la predicción de la demanda (histórico de ventas por SKU, tienda y canal con al menos 2 años de datos; factores externos: estacionalidad, días festivos, eventos locales, tendencias del sector de moda; factores internos: campañas de marketing, cambios de precio, promociones), modelos de predicción de la demanda para el retail de moda (SARIMA para productos de venta continua; modelos de aprendizaje automático: XGBoost, LightGBM para la predicción con múltiples features; modelos específicos para productos de temporada que solo se venden en un período corto), sistema de recomendación de reposición (basado en la predicción de la demanda y el stock actual, el sistema recomienda qué cantidad de cada SKU reponer en cada tienda y cuándo), proceso de evaluación y mejora continua del modelo (cómo medir el error de predicción, cómo actualizar el modelo cuando hay cambios en los patrones de venta) y gestión del cold start (cómo predecir la demanda de un producto nuevo que no tiene histórico de ventas).

4. Integración omnicanal tienda física y ecommerce: El cliente no distingue entre la tienda física y la online. Diseña la integración. Incluye: arquitectura de la capa de integración entre el sistema de POS de las tiendas físicas y la plataforma de ecommerce (sincronización del catálogo de productos, del inventario en tiempo real y de los datos del cliente), implementación de los servicios omnicanal más demandados (click and collect: compra online y recogida en tienda; ship from store: el pedido online se prepara y envía desde la tienda más cercana al cliente; reserve in store: el cliente reserva el producto online para probarlo en tienda), gestión de la devolución omnicanal (el cliente que compró online puede devolver en tienda física: cómo gestiona el sistema la devolución, cómo se actualiza el inventario, cómo se procesa el reembolso), vista única del cliente (el sistema reconoce al cliente tanto si compra en tienda como online, unifica su historial de compras y sus puntos de fidelización) y gestión del inventario omnicanal (cómo se prioriza el stock cuando hay demanda simultánea del canal físico y del online).

5. Analítica de retail y business intelligence: Los datos de las 25 tiendas son un activo enorme. Diseña el sistema de análisis. Incluye: arquitectura del data warehouse para retail (pipeline de datos desde los POS de las 25 tiendas y el ecommerce hacia un data warehouse centralizado: qué herramienta usar -BigQuery, Redshift, Snowflake-, con qué frecuencia se actualizan los datos), métricas clave del retail que el sistema debe calcular automáticamente (ventas por m2 por tienda, rotación del inventario por categoría, margen bruto por producto y por tienda, tasa de conversión de visitas a compras, ticket medio por tienda y por canal), sistema de informes automáticos para los encargados de tienda (informe diario de ventas vs. objetivo, informe semanal de stock crítico) y para la dirección (informe mensual de rendimiento por tienda con ranking y análisis de las desviaciones) y dashboard de business intelligence para el equipo directivo con los KPIs del negocio en tiempo real.

6. Tecnología en la tienda física: IA y sensores para optimizar la operación: La tienda física puede incorporar tecnología para mejorar la experiencia y la eficiencia. Diseña el sistema. Incluye: sistema de conteo de visitas a la tienda con sensores (cámaras o sensores de paso en la entrada: cuántas personas entran, a qué hora, cuánto tiempo pasan en la tienda) para calcular la tasa de conversión real (visitas ÷ ventas) y para optimizar los turnos del personal, análisis del comportamiento del cliente en la tienda con analítica de vídeo anónima (qué zonas son más visitadas, cuánto tiempo pasan los clientes en cada zona, qué puntos calientes hay en el mapa de calor de la tienda) para optimizar la disposición del producto, sistema de etiquetas electrónicas de precio (ESL: Electronic Shelf Labels) que permite actualizar el precio de todos los productos de las 25 tiendas desde el sistema central en segundos (eliminando el trabajo manual de cambiar etiquetas de papel) y sistema de inventario con RFID para la gestión automatizada del stock sin necesidad de hacer inventario manual.

7. Arquitectura técnica y stack tecnológico recomendado: Define las decisiones técnicas clave. Incluye: comparativa de las principales plataformas POS en la nube (Shopify POS, Lightspeed Retail, Square for Retail, Odoo Retail: ventajas e inconvenientes para una cadena de 25 tiendas de moda en España) vs. el desarrollo de un sistema propio, stack tecnológico recomendado si se opta por el desarrollo propio (backend: Node.js con Nest.js o Java con Spring Boot; base de datos: PostgreSQL para datos transaccionales + Redis para caché del inventario en tiempo real; frontend POS: React con Electron para la app de tienda; comunicación en tiempo real: WebSockets o Server-Sent Events para la actualización del inventario), proceso de migración del sistema legacy al nuevo sistema (fases, riesgos, plan de rollback) y plan de formación del equipo de tienda en el nuevo sistema.

Incluye diagramas de arquitectura en texto, análisis de las alternativas de plataformas POS del mercado y plan de implementación por fases para las 25 tiendas. Todo orientado a cadenas de moda en España que necesitan actualizar su tecnología minorista.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 90,
                'use_case'         => 'Sistema de gestión minorista integrado para cadena de 25 tiendas de moda con inventario en tiempo real y omnicanalidad',
                'vote_score'       => 56,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de experiencias en tienda física y visual merchandising con IA',
                'description'      => 'Crea experiencias de compra presencial que conviertan la visita a la tienda en un evento memorable usando IA para optimizar el layout, el visual merchandising y el diseño sensorial del espacio comercial.',
                'prompt_content'   => <<<'EOT'
Eres un director de diseño de retail y experiencia del cliente especializado en el diseño de espacios comerciales físicos. Tu trabajo es crear tiendas que no sean solo un lugar donde se compran productos, sino experiencias que los clientes quieren vivir y quieren repetir. Combinas el diseño de interiores con el comportamiento del consumidor en el punto de venta, y usas los datos (analítica de calor, tiempo de permanencia, tasas de conversión por zona) para diseñar espacios que maximizan las ventas a la vez que deleitan a los clientes.

Contexto del proyecto de diseño:
- Cadena de 8 tiendas de cosmética y bienestar de gama media-alta
- Perfil del cliente: mujeres de 30-55 años con interés en el bienestar, la cosmética natural y los rituales de cuidado personal
- Situación: las tiendas actuales tienen un diseño de 2014 que no refleja la evolución de la marca ni las expectativas de los clientes de hoy
- Objetivo: rediseñar las tiendas para aumentar el tiempo de permanencia, el ticket medio y la satisfacción del cliente
- Superficie típica de cada tienda: 150-250 m2
- Restricciones: el presupuesto de reforma completa está limitado a 80.000 euros por tienda, con necesidad de mantener la tienda operativa durante la reforma

Desarrolla el proyecto completo de diseño de la experiencia en tienda:

1. Investigación del comportamiento del cliente en tienda: El diseño del espacio parte del entendimiento del cliente. Diseña el proceso. Incluye: metodología de observación del comportamiento del cliente en las tiendas actuales (análisis del heat map de movimiento de los clientes, puntos de parada y de paso, zonas frías y calientes, tiempo medio de permanencia en cada zona), entrevistas con clientes actuales sobre su experiencia en la tienda (qué les gusta, qué les frustra, qué les hace quedarse más tiempo, qué les hace salir antes de lo esperado, cómo comparan la experiencia en tienda con la compra online), análisis de las tiendas de cosmética y bienestar de referencia en España e internacionalmente (Aesop, Rituals, Kiehl's, Natura: qué hace especial la experiencia en cada una, qué elementos son replicables) y análisis de los datos de venta por zona de la tienda (qué productos se venden más en qué zona, si hay correlación entre la proximidad a la entrada y la tasa de venta).

2. Concepto de diseño y estrategia de la experiencia: El diseño de la tienda parte de un concepto experiencial claro. Diseña el concepto. Incluye: definición del concepto de experiencia de la nueva tienda (cuál es la emoción o la sensación que el cliente debe tener cuando entra: ¿rituales de spa en su vida cotidiana? ¿botica de bienestar moderna? ¿refugio de calma en la ciudad?), traducción del concepto en decisiones de diseño concretas (cómo el concepto determina los materiales, los colores, la iluminación, los aromas, la música y la disposición del espacio), diseño del journey del cliente en la tienda (qué ve primero al entrar, cómo se mueve por el espacio de forma natural, dónde encuentra los productos de descubrimiento, dónde los de compra planificada, cómo llega a la caja) y diseño de los momentos de magia en la tienda (los momentos sorprendentes que el cliente recordará y contará: la zona de pruebas con luz de diferentes momentos del día, el olfatómetro de fragancias, el ritual de bienvenida del personal de tienda).

3. Layout y distribución del espacio comercial: La disposición del espacio determina las ventas. Diseña el layout. Incluye: principios de diseño de layout para tiendas de cosmética (zona de descompresión en la entrada, zona de descubrimiento de novedades al inicio del recorrido, zona de bestsellers a la altura de los ojos en el recorrido natural, zona de fidelización y productos de expertise en el fondo, caja al final del recorrido para maximizar la exposición del cliente a todo el surtido), diseño de las zonas de experiencia que invitan a la permanencia (zona de test de productos con luz natural simulada, zona de consulta con el asesor de belleza, zona de spa express para tratamientos cortos), señalética de navegación para guiar al cliente por el espacio sin que se sienta perdido, diseño del escaparate como primer touchpoint de la experiencia (cómo el escaparate debe generar curiosidad y atracción antes de que el cliente entre) y adaptación del layout a los diferentes tamaños de tienda (de 150 a 250 m2).

4. Visual merchandising y presentación del producto: La presentación del producto en el punto de venta determina la compra impulsiva. Diseña el sistema. Incluye: principios de visual merchandising para cosmética de gama media-alta (presentación vertical por ritual o por beneficio, no por marca o por categoría; niveles de presentación: productos en el suelo, a la altura de la mano y a la altura de los ojos; uso del espacio negativo para productos de gama alta), sistema de presentación de novedades y temporadas (zona de novedad destacada que se cambia mensualmente, con decoración de temporada que genera sensación de frescura), diseño de los corners de marca para los proveedores que tienen corner propio (cómo integrarlos en el diseño general de la tienda sin que la fragmenten), sistema de cartelería y comunicación en el punto de venta (qué información mínima necesita el producto para venderse sin la intervención del vendedor: beneficio principal, ingrediente estrella, cómo se usa) y uso de la IA para optimizar la disposición del surtido (análisis de qué productos se compran juntos para colocarlos cerca, rotación del producto que tiene menos ventas a una zona más visible).

5. Diseño sensorial: luz, aroma y sonido: La experiencia en tienda va más allá de lo visual. Diseña el sistema sensorial. Incluye: diseño de iluminación para tiendas de cosmética (temperatura de color de la luz según la zona: luz cálida en las zonas de descanso y consulta, luz más fría y homogénea en las zonas de test de maquillaje; cómo la iluminación afecta a la percepción del color de los productos; uso de focos para destacar el producto de manera focal), estrategia de marketing olfativo para la tienda (cómo el aroma de la tienda refuerza el posicionamiento de marca: aroma ambiental sutil en el espacio, aromas más intensos en la zona de fragancias, proceso de selección del aroma con el que el cliente debe asociar la marca), diseño de la experiencia sonora (volumen adecuado de la música de fondo, tipo de música que se asocia al posicionamiento de bienestar y calma de la marca, uso del silencio en las zonas de consulta) y diseño de la experiencia táctil (materialidad de los expositores y los mostradores que invita a tocar los productos, texturas que refuerzan la percepción de calidad natural).

6. Zona de experiencias y servicios en tienda: Los servicios en tienda son el diferenciador que el ecommerce no puede ofrecer. Diseña el sistema. Incluye: diseño de la zona de asesoramiento personalizado (cómo un espacio de consulta de 4 m2 puede transformar la experiencia del cliente y triplicar el ticket medio), diseño del servicio de diagnóstico de piel gratuito (qué equipamiento usar, cómo forma al personal para hacerlo, cómo conecta el diagnóstico con la recomendación de productos) y cómo usar la IA para personalizar el resultado del diagnóstico a cada cliente, eventos en tienda que atraen a nuevos clientes y fidelizan a los actuales (taller de perfumes, masterclass de maquillaje, rituales de skincare: cómo organizarlos en el espacio, cuánta capacidad, con qué frecuencia) y diseño del espacio para el click and collect (cómo recoger un pedido online en tienda puede convertirse en una oportunidad de venta adicional).

7. Medición del impacto del rediseño: El diseño del espacio debe medirse en términos de negocio. Diseña el sistema. Incluye: KPIs del diseño de la experiencia en tienda (tasa de conversión de visitas a compras antes y después del rediseño, tiempo medio de permanencia en tienda, ticket medio, tasa de retorno de clientes, NPS de la experiencia en tienda), sistema de medición del comportamiento del cliente en el nuevo espacio (cámaras de analítica con anonimización que detectan zonas calientes, conteo de visitas por hora, tiempo en cada zona), proceso de iteración del diseño a partir de los datos (ajustes de disposición del surtido, cambios en la señalética, modificaciones en la iluminación) y presentación de los resultados del rediseño al equipo directivo con el ROI de la inversión en la reforma.

Incluye plantilla de brief de diseño de tienda, guía de visual merchandising para cosmética y sistema de métricas de la experiencia en tienda física. Todo orientado al retail de cosmética y bienestar de gama media-alta en España.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Rediseño de la experiencia en tienda de cadena de cosmética para aumentar el tiempo de permanencia y el ticket medio',
                'vote_score'       => 41,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Técnicas de venta en retail y gestión de equipos comerciales de tienda con IA',
                'description'      => 'Desarrolla las habilidades de venta del equipo de tienda y los sistemas de gestión comercial en retail usando IA para el entrenamiento, el seguimiento del rendimiento y la mejora continua de los resultados de ventas.',
                'prompt_content'   => <<<'EOT'
Eres un director de ventas y formación especializado en el sector del comercio minorista. Llevas años desarrollando las habilidades comerciales de equipos de tienda en cadenas de retail de moda, electrónica, hogar y specialty retail. Sabes que la venta en tienda física tiene características únicas: el cliente entra ya predispuesto a comprar, la venta es cara a cara y en tiempo real, el vendedor tiene pocos minutos para crear una conexión y el cliente está cada vez más informado porque ha investigado online antes de venir.

Contexto de la empresa:
- Cadena de 15 tiendas de electrónica y tecnología de gama media-alta
- Ticket medio actual: 285 euros. Objetivo: 380 euros
- Tasa de conversión de visitas a compras: 22%. Objetivo: 32%
- Problema: el equipo de ventas aplica una técnica de venta pasiva (el cliente pregunta, el vendedor responde pero no toma la iniciativa ni hace upselling ni cross-selling sistemático)
- Segundo problema: los vendedores más nuevos no conocen bien el catálogo de 800+ productos y se sienten inseguros para hacer recomendaciones
- NPS de la experiencia de compra: 42. Objetivo: 65

Desarrolla el sistema completo de ventas y formación del equipo de tienda:

1. Proceso de venta consultiva en tienda de electrónica: La venta en tienda de tecnología debe ser consultiva. Diseña el proceso. Incluye: las 5 fases de la venta consultiva en tienda (bienvenida activa: cómo saludar al cliente que entra sin que se sienta acosado; descubrimiento: qué preguntas hacerle para entender qué necesita, para qué lo usa y cuál es su presupuesto; presentación: cómo seleccionar los 2-3 productos más adecuados y presentarlos conectando las características con los beneficios específicos para ese cliente; gestión de objeciones: cómo responder a "me lo tengo que pensar", "en Amazon está más barato" y "es demasiado caro"; cierre y upselling: cómo cerrar la venta y proponer productos complementarios), diferencia entre el cliente que viene con necesidad clara (sabe lo que quiere) y el que viene explorando (no sabe exactamente lo que busca) y cómo adaptar el proceso de venta a cada perfil, técnicas de upselling en electrónica (cómo sugerir el modelo superior cuando el cliente está mirando uno básico, con un argumento concreto de valor) y técnicas de cross-selling (qué accesorios o productos complementarios proponer según el producto principal que está comprando).

2. Programa de formación del equipo de tienda: La formación del equipo es la inversión más rentable. Diseña el programa. Incluye: programa de formación de nuevos vendedores en los primeros 30 días (semana 1: conocimiento del catálogo de los 50 productos más vendidos; semana 2: técnicas de venta y roleplay con el equipo; semana 3: observación de vendedores sénior y primeras ventas acompañadas; semana 4: ventas autónomas con seguimiento del encargado), sistema de formación continua del equipo existente (sesión semanal de 30 minutos antes de abrir la tienda: novedades de producto, técnicas de venta con roleplay, análisis de situaciones difíciles de la semana anterior), uso de IA para el entrenamiento de los vendedores (simulador de conversaciones de venta donde el vendedor practica con el IA que hace de cliente con diferentes perfiles y objeciones), sistema de gamificación de la formación (ranking de puntos por completar módulos de formación, por las ventas realizadas de los productos de la formación del mes, por el NPS de los clientes atendidos) y plan de desarrollo individual para cada vendedor (fortalezas, áreas de mejora y objetivos de aprendizaje para el trimestre).

3. Gestión del equipo de tienda por encargado: El encargado de tienda es la clave del rendimiento del equipo. Diseña el sistema. Incluye: proceso de gestión diaria del equipo de tienda por el encargado (apertura de la tienda: briefing de 5 minutos con el objetivo del día y los productos prioritarios; durante la jornada: observación de las ventas y feedback inmediato; cierre: análisis de los resultados del día y reconocimiento), sistema de seguimiento del rendimiento individual de cada vendedor (ventas por vendedor, ticket medio, tasa de conversión, productos con peor venta del vendedor, NPS de los clientes del vendedor), proceso de feedback individual del encargado al vendedor (con qué frecuencia, en qué formato, cómo dar feedback negativo de forma constructiva) y cómo el encargado puede usar la IA para analizar el rendimiento del equipo y preparar las sesiones de feedback (análisis automático de los datos de ventas y generación de los puntos clave para la conversación con cada vendedor).

4. Sistema de incentivos y comisiones en retail: Los incentivos determinan el comportamiento. Diseña el modelo. Incluye: diseño del sistema de comisiones para el equipo de tienda de electrónica (comisión base sobre el total de ventas del equipo de la tienda + comisión individual por los productos de mayor margen + bonus mensual por superar el objetivo de ticket medio), productos priorizados en el sistema de incentivos (categorías con mayor margen: garantías extendidas, accesorios, servicios de instalación y configuración: cómo incentivar su venta sin que los vendedores presionen al cliente), sistema de incentivos no económicos que complementan la comisión (reconocimiento público del mejor vendedor del mes, acceso anticipado a los nuevos productos antes de su lanzamiento oficial, sesiones de formación avanzada como premio), diseño de los concursos de venta para dinamizar en períodos de menor actividad y cómo equilibrar los incentivos individuales con el trabajo en equipo.

5. Venta en entorno omnicanal: El cliente de hoy viene informado del online. Diseña el sistema. Incluye: formación del vendedor para atender al cliente que ha investigado en internet y viene con información (cómo tratar a un cliente que sabe más del producto que el vendedor, cómo diferenciarse de Amazon cuando el cliente muestra el precio online), proceso de venta del servicio de click and collect (el cliente recoge un pedido online: cómo convertir esa visita en una oportunidad de venta adicional en tienda), integración del catálogo online en la tableta del vendedor para poder mostrar productos que no están físicamente en la tienda pero que se pueden pedir, gestión de la política de igualación de precio (si la tienda iguala el precio de Amazon bajo demanda: cuándo ofrecerlo, con qué límites, cómo no devaluar el servicio al hacerlo de forma sistemática) y proceso de acompañamiento del cliente online que tiene dudas (chat en la web conectado con los vendedores de la tienda para responder en tiempo real).

6. Gestión de la experiencia del cliente para maximizar el NPS: El NPS es el indicador de si el cliente volverá y recomendará. Diseña el sistema. Incluye: momentos clave de la experiencia del cliente en la tienda de electrónica que más impactan en el NPS (la rapidez en atender al cliente cuando entra, la honestidad del vendedor cuando el producto más caro no es el más adecuado para el cliente, la facilidad del proceso de compra y pago, el comportamiento post-venta: garantías, asistencia técnica), proceso de encuesta NPS después de la compra (cuándo enviarla, por qué canal, qué preguntar además del NPS para identificar áreas de mejora), proceso de respuesta a los detractores (clientes con NPS 0-6: el encargado les contacta personalmente en menos de 24 horas para entender el problema y resolverlo) y sistema de seguimiento del NPS por tienda y por vendedor.

7. Uso de la IA en la gestión de ventas de retail: La IA puede transformar la gestión comercial de la tienda. Diseña el sistema. Incluye: sistema de IA para la recomendación de productos al vendedor en el momento de la venta (el vendedor introduce lo que busca el cliente y la IA le sugiere los 3 productos más adecuados y los argumentos de venta personalizados para ese perfil), análisis de IA de las conversaciones de venta con los clientes (grabación anónima y análisis de las interacciones: qué técnicas de venta usa el equipo, qué objeciones son más frecuentes, qué vendedores tienen mayor tasa de conversión y por qué), generación automática de informes de rendimiento por tienda y por vendedor con identificación de las áreas de mejora y recomendaciones de formación y sistema de IA para la previsión de la demanda que permite al encargado saber con antelación cuándo necesita más personal en la tienda para no perder ventas por falta de atención.

Incluye plantilla de proceso de venta en 5 pasos para tienda de electrónica, guion de roleplay de entrenamiento y sistema de seguimiento del rendimiento individual del vendedor. Todo orientado a cadenas de electrónica de gama media-alta con equipos de 5-12 personas por tienda.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Aumento del ticket medio de 285 a 380 euros y de la tasa de conversión del 22% al 32% en cadena de tiendas de electrónica',
                'vote_score'       => 43,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Gestión de categorías y surtido en retail con IA',
                'description'      => 'Optimiza el surtido de productos, la gestión de categorías y la asignación de espacio en tienda usando IA para analizar el rendimiento del catálogo, predecir tendencias y maximizar la rentabilidad por metro cuadrado.',
                'prompt_content'   => <<<'EOT'
Eres un category manager y director de compras especializado en el sector del comercio minorista. Tu trabajo es definir qué productos vende cada tienda, en qué cantidad, a qué precio y en qué espacio, para maximizar las ventas y la rentabilidad. Tienes experiencia en la gestión de surtido en cadenas de retail de diferentes sectores (alimentación, moda, hogar, electrónica), y en los últimos años has incorporado la IA y el análisis de datos al proceso de decisión sobre el surtido para reducir la dependencia de la intuición y la experiencia en favor de los datos.

Contexto de la empresa:
- Cadena de 20 supermercados de proximidad en el área metropolitana de Madrid
- Surtido actual: 9.500 referencias. El objetivo es reducirlo a 7.500 referencias sin perder ventas
- Problema: el 40% de las referencias generan menos del 5% de las ventas, pero ocupan el 40% del lineal
- Segundo problema: la rotación del inventario es baja en varias categorías (exceso de stock que genera merma), mientras que en otras categorías hay frecuentes roturas de stock
- Objetivo: optimizar el surtido para mejorar la rentabilidad por m2 y reducir la merma en un 30%

Desarrolla el sistema completo de gestión de categorías con IA:

1. Análisis del surtido actual y diagnóstico de rentabilidad: Antes de optimizar, hay que entender qué está pasando. Diseña el proceso. Incluye: metodología de análisis ABC del surtido (clasificación de las 9.500 referencias por su contribución a las ventas: A: el 20% de las referencias que generan el 80% de las ventas; B: el siguiente 30% que genera el 15%; C: el 50% restante que solo genera el 5%) y análisis cruzado con el margen de cada referencia (referencias de alto volumen y alto margen vs. referencias de alto volumen y bajo margen vs. referencias de bajo volumen y alto margen: cuál es el perfil de cada una y qué hacer con ellas), análisis de la matriz BCG aplicada al surtido (estrellas, vacas, interrogantes, perros), análisis de las referencias sin ventas o con ventas muy bajas en los últimos 90 días (cuántas hay, por qué siguen en el surtido, cuál es su coste de mantenimiento en inventario), análisis de la cohesión del surtido dentro de cada categoría (¿hay duplicidades? ¿hay gaps de producto que los clientes piden y no encuentran?) y benchmarking del surtido con los competidores del área de influencia de cada supermercado.

2. Metodología de gestión por categorías: La gestión por categorías es el marco estratégico del category management. Diseña el proceso. Incluye: definición del árbol de categorías del supermercado (cómo se organizan las categorías y subcategorías desde la perspectiva del árbol de decisión del comprador: el cliente no piensa en "lácteos" sino en "algo para el desayuno de mañana") y cómo el árbol de decisión del comprador debe guiar la organización del lineal, proceso de definición del rol de cada categoría (categoría destino: atrae a clientes al supermercado porque nadie tiene mejor precio/calidad; categoría rutina: compra repetitiva de bajo esfuerzo; categoría de conveniencia: compra impulsiva de alta rentabilidad; categoría de temporada: ventas estacionales de oportunidad), estrategia de pricing por categoría según su rol (precio duro en las categorías destino para ser competitivo, precio alto en las categorías de conveniencia para maximizar el margen) y proceso de revisión semestral de la estrategia de categoría con los proveedores clave.

3. Optimización del surtido con IA: Pasar de 9.500 a 7.500 referencias sin perder ventas requiere un análisis riguroso. Diseña el proceso. Incluye: modelo de IA para la optimización del surtido (qué features usar: ventas, margen, rotación, merma, satisfacción del cliente con la disponibilidad del producto en encuestas, búsquedas de productos en la web y la app del supermercado; qué objetivo optimizar: maximizar las ventas totales de la categoría dado un número máximo de referencias y una restricción de espacio en el lineal), proceso de decisión de eliminación de referencias (qué referencias se pueden eliminar con menor impacto en las ventas: las que tienen un sustituto directo en el surtido y las que son compradas por un número muy pequeño de clientes que también compran la alternativa), gestión de la comunicación a los clientes cuando se elimina una referencia que algunos compraban (cómo informar de la alternativa disponible en el supermercado) y proceso de revisión trimestral del surtido con nuevas incorporaciones y eliminaciones.

4. Optimización del lineal y la asignación de espacio: El espacio en el lineal es un activo escaso que debe asignarse de forma óptima. Diseña el sistema. Incluye: principios de asignación de espacio en el lineal por referencia (el espacio asignado debe ser proporcional a las ventas de la referencia, pero también a su margen y a la rotación del inventario: no tiene sentido tener 5 facings de una referencia que se rota una vez al mes), uso de herramientas de planogramación con IA (software como Shelf Logic, Blue Yonder o Relex que optimizan la disposición del producto en el lineal según los datos de ventas), análisis del efecto del espacio en las ventas (cuántas ventas adicionales genera un facing adicional de una referencia: la elasticidad del espacio), optimización del espacio de lineal por tienda (cada tienda tiene un tamaño diferente: cómo adaptar el planograma de referencia al espacio disponible en cada supermercado) y proceso de revisión de los planogramas cuando cambia el surtido o cambia el período estacional.

5. Gestión de la merma con IA: La merma es uno de los principales costes en la distribución alimentaria. Diseña el sistema. Incluye: análisis de las causas de la merma en el supermercado (merma conocida: roturas en recepción, productos caducados, venta a precio reducido; merma desconocida: robos, errores administrativos), uso de IA para la predicción de la merma por producto y por tienda (qué referencias tienen mayor riesgo de merma por caducidad, en qué tiendas y en qué períodos), sistema de alertas de productos próximos a caducar (cuando un producto tiene menos de 5 días para caducar: alerta en el sistema con propuesta de acción: descuento del 30%, transferencia a la zona de última hora, donación a banco de alimentos), optimización del pedido para reducir el exceso de inventario que genera merma (el sistema de predicción de la demanda ajusta los pedidos para minimizar el stock excedente sin generar roturas de stock) y proceso de análisis mensual de la merma por categoría y por tienda con identificación de las causas y medidas correctoras.

6. Gestión de las relaciones con proveedores para el category management: El proveedor es un socio estratégico en la gestión de la categoría. Diseña el modelo. Incluye: proceso de revisión de categoría con el proveedor líder (joint business planning: el proveedor aporta datos del mercado y el retailer aporta datos de sus tiendas para acordar la estrategia de la categoría para los próximos 12 meses), negociación de las condiciones comerciales con los proveedores de la categoría (precio de compra, rappels por volumen, descuentos promocionales, contribuciones al lineal) con el objetivo de maximizar el margen de la categoría, gestión de las promociones de proveedor (qué promociones aceptar, cuándo ejecutarlas para maximizar el impacto en las ventas, cómo evitar que las promociones canibalicen las ventas del producto sin promoción) y desarrollo de la marca propia (private label) como palanca de margen en las categorías donde el producto de marca propia puede competir con los líderes.

7. Código Python para el análisis de surtido y lineal: Proporciona implementaciones concretas de: (a) análisis ABC del surtido con pandas (carga de datos de ventas por referencia, cálculo de la contribución acumulada a las ventas totales, clasificación ABC y visualización de la curva de Lorenz), (b) análisis de correlación entre referencias para identificar qué productos se compran juntos con mayor frecuencia (market basket analysis con la librería mlxtend: algoritmo Apriori para encontrar las reglas de asociación más fuertes), (c) modelo de predicción de la merma por referencia y por tienda usando datos históricos de merma y características de los productos (fecha de caducidad, categoría, tienda, estación) con XGBoost y (d) algoritmo de optimización de la asignación de espacio en el lineal (distribución del espacio disponible entre las referencias de una categoría para maximizar las ventas esperadas usando programación lineal con scipy.optimize).

Incluye plantilla de análisis de categoría, metodología de planogramación básica y sistema de alertas de merma en Excel. Todo orientado a cadenas de supermercados de proximidad que quieren modernizar su proceso de category management con datos e IA.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 80,
                'use_case'         => 'Optimización del surtido de 9.500 a 7.500 referencias y reducción de la merma del 30% en cadena de supermercados de proximidad',
                'vote_score'       => 54,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión de equipos y turnos en tiendas físicas con IA',
                'description'      => 'Diseña sistemas de gestión de personas para el retail: planificación de turnos, formación del equipo de tienda, retención del talento y gestión del rendimiento en entornos de alta rotación y trabajo a turnos.',
                'prompt_content'   => <<<'EOT'
Eres un director de Recursos Humanos especializado en el sector del comercio minorista. Llevas años gestionando equipos en cadenas de retail con las particularidades propias del sector: alto volumen de empleados de diferentes categorías (a tiempo completo, a tiempo parcial, fijos discontinuos, contratos de relevo), trabajo a turnos y en fin de semana, alta rotación del personal (especialmente en el equipo de base), convivencia de diferentes generaciones en el mismo equipo y necesidad de planificar los turnos con anticipación respetando la normativa laboral y los convenios colectivos del comercio.

Contexto de la empresa:
- Cadena de 18 tiendas de moda rápida con entre 15 y 35 empleados por tienda
- Total de la plantilla: 480 personas
- Distribución de la plantilla: 120 a tiempo completo, 280 a tiempo parcial, 80 fijos discontinuos para las temporadas de mayor venta
- Problemas: tasa de rotación del 65% anual en el equipo de base (muy alta incluso para el sector), los encargados de tienda dedican 8 horas semanales de media a la planificación de turnos (demasiado tiempo), frecuentes errores en los turnos que generan conflictos con el equipo y el absentismo de última hora no se gestiona eficientemente
- Objetivo: reducir la rotación al 40%, reducir el tiempo de planificación de turnos al 2 horas semanales y mejorar el ambiente de trabajo

Desarrolla la estrategia completa de gestión de personas en el retail:

1. Diagnóstico de la rotación en el equipo de tienda: Diseña el proceso de análisis. Incluye: análisis de los datos de rotación de los últimos 2 años (tasa de rotación por tienda, por tipo de contrato, por antigüedad: ¿en qué momento del ciclo de vida del empleado se producen más las salidas? ¿en los primeros 3 meses? ¿después del primer año?), entrevistas de salida estructuradas con los empleados que se van (motivos reales de la salida: salario, horarios, ambiente de trabajo, relación con el encargado, falta de perspectivas de desarrollo, el trabajo en sí mismo) y análisis de los patrones (¿hay encargados de tienda con mayor rotación que otros? ¿hay horarios o turnos donde la rotación es más alta?), encuesta de clima laboral al equipo actual (engagement, motivación, percepción del encargado, orgullo de pertenencia, intención de quedarse en los próximos 12 meses) y análisis del coste económico de la rotación para la empresa (coste de selección, de formación, de baja productividad durante el período de adaptación: cuánto cuesta cada empleado que se va y hay que reemplazar).

2. Sistema de planificación de turnos con IA: La planificación de turnos manual es ineficiente. Diseña el sistema. Incluye: datos de entrada necesarios para la planificación automatizada de turnos (previsión de ventas y tráfico por hora y por día de la semana, plantilla disponible con sus contratos y disponibilidad horaria, restricciones legales del convenio colectivo del comercio: descansos mínimos entre turnos, descanso semanal, horas mínimas y máximas por semana por tipo de contrato, preferencias de horario de cada empleado en la medida en que sea posible), algoritmo de optimización de turnos (constraint satisfaction problem: asignar empleados a turnos de forma que se cubran las necesidades de negocio, se respeten las restricciones legales y se maximicen las preferencias del empleado), herramientas de software de planificación de turnos con IA para el retail (Quinyx, Planday, Factorial, When I Work: comparativa y cuál es más adecuado para esta cadena), proceso de comunicación del turno al empleado (notificación anticipada de mínimo 2 semanas, app móvil para que el empleado consulte su turno, solicite cambios y registre la asistencia) y gestión del absentismo de última hora (proceso de reemplazo cuando un empleado falta en el día: sistema de disponibilidad voluntaria para cubrir turnos extra con incentivo económico o de flexibilidad).

3. Propuesta de valor al empleado de retail: ¿Por qué trabajar en esta cadena de moda frente a las alternativas? Diseña la Employee Value Proposition. Incluye: análisis de los elementos de valor que la empresa puede ofrecer que son relevantes para el perfil del empleado de retail de moda (descuento de empleado en la compra de ropa de la cadena, flexibilidad de horarios compatible con los estudios para los empleados a tiempo parcial más jóvenes, posibilidades reales de ascenso a encargado de tienda en 2-3 años, ambiente de trabajo dinámico y equipo joven, formación continua en moda y tendencias), comunicación de la propuesta de valor en el proceso de selección (qué decirle al candidato en la entrevista, cómo comunicarlo en los portales de empleo) y materialización de la propuesta en los primeros 30 días del empleado nuevo (cómo los primeros 30 días refuerzan o destruyen la propuesta de valor que se le comunicó en la selección).

4. Onboarding y formación del equipo de tienda: El primer mes es decisivo para la retención. Diseña el proceso. Incluye: programa de onboarding de los primeros 30 días del empleado nuevo de tienda (día 1: presentación del equipo, visita de la tienda, entrega del uniforme y del material; semana 1: formación en caja y en el sistema de gestión de la tienda; semana 2: formación en el surtido y en las técnicas de atención al cliente; semana 3: formación en reposición y visual merchandising; mes 1: evaluación del período de acogida y establecimiento de objetivos del trimestre), figura del buddy o mentor (empleado sénior asignado a cada nuevo empleado para el primer mes: cómo seleccionarlo, cómo formarlo para el rol de mentor, cómo reconocerlo por el tiempo dedicado), programa de formación continua del equipo de tienda (novedades de colección, técnicas de venta, atención al cliente en situaciones difíciles, uso de las herramientas digitales de la tienda) y uso de la IA para personalizar la formación (identificar qué empleados necesitan refuerzo en qué competencias y sugerirles el contenido formativo adecuado).

5. Gestión del rendimiento del equipo de tienda: En el retail, el rendimiento se mide en ventas y en calidad del servicio. Diseña el sistema. Incluye: KPIs del equipo de tienda que el encargado debe gestionar (ventas por hora trabajada por empleado, tasa de conversión personal si es posible medirla, NPS de los clientes atendidos por cada empleado, cumplimiento del protocolo de atención: se mide con mystery shopper), proceso de feedback continuo del encargado al equipo (feedback inmediato cuando se observa una buena o mala actuación, reunión individual mensual de seguimiento del rendimiento), sistema de detección temprana del empleado que está desmotivado o que se va a ir (señales: aumento del absentismo, reducción del rendimiento de ventas, menor iniciativa, mayor número de conflictos con compañeros), gestión de los empleados de bajo rendimiento (proceso de mejora del rendimiento: qué apoyo se le da, qué objetivos concretos se establecen, cuál es el plazo, qué pasa si no mejora) y proceso de reconocimiento del empleado de alto rendimiento.

6. Encargado de tienda como pieza clave de la retención: El encargado es el principal factor de retención o de rotación del equipo. Diseña el sistema. Incluye: perfil del encargado de tienda ideal para esta cadena de moda (no solo gestión del negocio: ventas, visual, inventario; también liderazgo de personas: motivar al equipo, dar feedback, gestionar conflictos, detectar talento), proceso de selección interna de encargados (cómo identificar a los empleados de tienda con potencial de liderazgo, qué proceso de desarrollo darles antes de darles la responsabilidad de encargado), formación del encargado en gestión de personas (las habilidades de liderazgo no se aprenden de forma natural: qué formación necesita el encargado de tienda para ser un buen gestor de personas), sistema de evaluación del encargado por el equipo (feedback 360 anónimo del equipo al encargado: qué valoran positivamente, qué creen que puede mejorar) y cómo gestionar los encargados que tienen alta rotación en su equipo (análisis de las causas, plan de mejora, cuándo es necesario cambiar al encargado).

7. Normativa laboral en el retail: gestión del tiempo de trabajo y los convenios. Incluye: principales convenios colectivos del comercio en España que aplican a esta cadena (Convenio Colectivo del Comercio de Madrid, del Comercio Textil: jornada máxima, descanso semanal, complementos salariales, permisos y licencias), gestión legal de los turnos a turnos (requisitos de descanso entre jornadas, limitaciones de la jornada nocturna, gestión de los días festivos y su compensación), registro de jornada obligatorio para todos los empleados (herramienta de control horario digital: app móvil, terminal de fichaje en tienda) y consecuencias legales del incumplimiento y gestión de las horas extraordinarias y de los complementos de fin de semana según los convenios del comercio.

Incluye plantilla de proceso de onboarding de empleado de tienda, sistema de planificación de turnos semanal y protocolo de entrevista de salida para el retail. Todo adaptado a las particularidades del convenio colectivo del comercio en España.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Reducción de la rotación del 65% al 40% y optimización de la planificación de turnos en cadena de moda rápida de 18 tiendas',
                'vote_score'       => 40,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Control financiero y rentabilidad en el comercio minorista con IA',
                'description'      => 'Gestiona la rentabilidad de tiendas físicas usando IA para el análisis del margen por categoría, el control del stock, la gestión del working capital y la toma de decisiones financieras en el punto de venta.',
                'prompt_content'   => <<<'EOT'
Eres un director financiero y controller especializado en el sector del comercio minorista. Llevas años gestionando la rentabilidad de cadenas de tiendas físicas, analizando el margen por categoría, controlando el capital circulante y diseñando los sistemas de información financiera que permiten a los equipos de tienda y a la dirección tomar mejores decisiones. Conoces las particularidades financieras del retail: el flujo de caja es complejo porque se compra antes de vender y se cobra en el momento de la venta pero se paga a los proveedores a 30-60 días, la rentabilidad varía enormemente por tienda y por categoría y los indicadores financieros del retail son específicos del sector.

Contexto de la empresa:
- Cadena de 22 tiendas de hogar y decoración
- Facturación total: 28 millones de euros anuales
- Rentabilidad actual: margen bruto del 42%, pero margen EBITDA del 6% (muy ajustado)
- Problema: la cadena no sabe con exactitud cuáles de sus 22 tiendas son rentables y cuáles no (el sistema de gestión no permite calcular el resultado por tienda con facilidad)
- Segundo problema: el working capital es muy alto (mucho stock inmovilizado que genera un coste financiero elevado)
- Objetivo: implementar un sistema de control financiero por tienda que permita identificar las tiendas no rentables y tomar decisiones de cierre, reforma o refuerzo

Desarrolla el sistema completo de control financiero del retailer:

1. Modelo de rentabilidad por tienda: El primer paso es saber qué gana o pierde cada tienda. Diseña el modelo. Incluye: cuenta de resultados por tienda (qué ingresos y costes son directamente atribuibles a cada tienda: ventas de la tienda, coste de las mercancías vendidas, margen bruto, personal de tienda, alquiler, suministros, merma, publicidad local; y cuáles son costes corporativos que hay que repartir entre tiendas: logística, marketing corporativo, administración central, IT), metodología de reparto de costes corporativos entre tiendas (reparto por ventas vs. por número de empleados vs. por m2 de sala de ventas: cuál es el método más equitativo y representativo de la realidad), análisis de las palancas de rentabilidad de cada tienda (qué factores explican que la tienda A tenga un margen EBITDA del 15% y la tienda B un EBITDA negativo: ventas por m2, margen bruto de la categoría de producto vendida, coste del alquiler como porcentaje de las ventas, productividad del equipo), ranking de tiendas por rentabilidad con análisis de los outliers (las 3 más rentables: qué hacen diferente; las 3 menos rentables: cuáles son sus problemas específicos) y proceso de revisión mensual de la rentabilidad por tienda con el equipo de dirección.

2. Métricas financieras del retail: El retailer necesita un vocabulario financiero específico. Define y diseña el sistema de seguimiento de: ventas por m2 de sala de ventas (benchmark del sector y objetivo de la cadena por formato de tienda), margen bruto por categoría de producto (cuál es el margen objetivo de cada categoría: decoración: 55%; textil hogar: 48%; pequeño electrodoméstico: 32%), coste de alquiler como porcentaje de las ventas (en retail el umbral crítico es el 10%: cuando el alquiler supera el 10% de las ventas es muy difícil ser rentable), índice de rotación del inventario por categoría (cuántas veces se renueva el stock de cada categoría al año: objetivo mínimo de 4 rotaciones anuales), días de inventario (cuántos días de ventas representa el stock actual de cada categoría) y tasa de merma por tienda y por categoría (objetivo máximo del 1,5% de las ventas).

3. Gestión del working capital en retail: El working capital es el mayor consumidor de caja en el retail. Diseña el sistema. Incluye: análisis del ciclo de caja del negocio (días de inventario + días de cobro a clientes - días de pago a proveedores = ciclo de caja: cuántos días tarda la caja en volver a la empresa desde que se compra la mercancía), estrategia de reducción de los días de inventario sin generar roturas de stock (optimización del modelo de reposición: pedidos más frecuentes y de menor cantidad vs. pedidos grandes con mayor stock de seguridad), negociación de las condiciones de pago con los proveedores para alargar el período de pago sin dañar la relación comercial (cómo justificar a un proveedor la solicitud de alargar los plazos de 30 a 60 días), gestión de las temporadas de mayor inversión en inventario (en el retail de hogar y decoración, la compra de la temporada de Navidad en septiembre-octubre representa un pico de necesidad de financiación) y uso de instrumentos financieros para gestionar el working capital (líneas de crédito de campaña, confirming para el pago a proveedores, factoring si la cadena vende a grandes distribuidores).

4. Análisis de la rentabilidad por categoría de producto: No todas las categorías contribuyen igual a la rentabilidad. Diseña el sistema. Incluye: análisis de la curva de rentabilidad por categoría (ventas × margen bruto × rotación: la contribución al margen total de cada categoría), identificación de las categorías que consumen espacio sin generar rentabilidad proporcional (categorías con bajo margen y baja rotación que deberían reducirse en el surtido o eliminarse), análisis del mix de categorías por tienda (la tienda de barrio residencial con perfil de cliente más familiar vende más textil hogar y menos decoración de diseño: el mix debería adaptarse al perfil de cada tienda), sistema de precios dinámicos por categoría (cuándo bajar el precio para acelerar la rotación del stock de temporada anterior: algoritmo de markdown optimization que maximiza el margen de la liquidación) y análisis de la rentabilidad de las promociones por categoría (cuánto margen pierdo en la promoción vs. cuánto volumen adicional vendo: ¿la promoción genera margen total positivo?).

5. Decisiones de apertura, reforma y cierre de tiendas: Las decisiones sobre la red de tiendas son las más estratégicas. Diseña el proceso. Incluye: modelo financiero para la decisión de apertura de una nueva tienda (inversión inicial, forecast de ventas por año en función de la zona, proyección del punto de equilibrio, VAN del proyecto a 10 años: cuándo empieza a generar valor la inversión), modelo de análisis de viabilidad de las tiendas en pérdidas (si una tienda tiene EBITDA negativo, ¿cuándo se debe cerrar? ¿hay alguna palanca de mejora que sea factible -renegociación del alquiler, cambio de mix, refuerzo del equipo de ventas- que pueda llevar la tienda a la rentabilidad?), proceso de cierre de una tienda (cómo gestionar el proceso con el equipo de la tienda, con el propietario del local y con los clientes), modelo de ROI de la reforma de una tienda (la inversión en el rediseño del espacio generará X% más de ventas: en cuántos meses se recupera la inversión) y proceso de expansión de la cadena (cuántas tiendas nuevas abrir al año, en qué mercados, con qué modelo de tienda).

6. Código Python para el análisis financiero del retailer: Proporciona implementaciones concretas de: (a) modelo de cuenta de resultados por tienda con pandas (carga de datos de ventas, costes directos y costes corporativos repartidos, cálculo del margen bruto, EBITDA y margen EBITDA por tienda, ranking de tiendas por rentabilidad), (b) análisis de la curva de rentabilidad por categoría (ventas × margen × rotación para cada categoría, con identificación de las que están por debajo del umbral de rentabilidad mínimo), (c) modelo de markdown optimization (para una categoría de producto de temporada con un stock final de X unidades que quieren liquidarse en Y semanas, calcula el descuento óptimo semana a semana que maximiza el margen total de la liquidación) y (d) proyección del working capital (modelo de caja mensual con la previsión de cobros y pagos para los próximos 12 meses, identificando los meses con mayor tensión de liquidez).

7. Reporting financiero del retailer para la dirección: Define el sistema de informes. Incluye: dashboard semanal para los encargados de tienda (ventas de la semana vs. objetivo, ventas de las últimas 4 semanas con tendencia, margen bruto estimado, stock de las categorías más importantes), informe mensual de rentabilidad por tienda para la dirección (cuenta de resultados por tienda, análisis de las desviaciones vs. el presupuesto, forecast del año con las tiendas en situación crítica identificadas) y proceso de revisión trimestral con los encargados de tienda de los KPIs financieros de su tienda (cómo enseñar a los encargados a leer los datos financieros de su tienda y a entender cómo sus decisiones operativas impactan en la rentabilidad).

Incluye plantilla de cuenta de resultados por tienda, modelo de análisis de viabilidad de cierre de tienda y dashboard semanal de KPIs para encargados de tienda. Todo adaptado a cadenas de retail de hogar y decoración con 15-30 tiendas.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 80,
                'use_case'         => 'Implementación de sistema de rentabilidad por tienda en cadena de hogar con 22 establecimientos para identificar tiendas en pérdidas y tomar decisiones de red',
                'vote_score'       => 52,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Compliance legal en comercio minorista y protección del consumidor con IA',
                'description'      => 'Navega el marco legal del comercio minorista en España: derechos del consumidor, prácticas comerciales, etiquetado, publicidad, ventas en rebajas y la nueva regulación de precios en el comercio electrónico.',
                'prompt_content'   => <<<'EOT'
Eres un abogado especializado en derecho del consumo y derecho mercantil con experiencia asesorando a cadenas de comercio minorista en España. Tu práctica abarca el cumplimiento de la normativa de protección del consumidor, las condiciones generales de contratación, la normativa de etiquetado y presentación de productos, la regulación de las ventas en promoción y rebajas, las prácticas comerciales desleales y la nueva regulación europea que afecta al comercio digital y a los precios.

Contexto de la consulta:
- Cadena de 30 tiendas de moda en España con página web de ecommerce
- Situación: la empresa acaba de recibir una denuncia ante la Oficina Municipal de Información al Consumidor (OMIC) por presunta publicidad engañosa en una campaña de rebajas, y el equipo jurídico necesita hacer una revisión completa del marco de compliance de la empresa
- Además: la empresa está lanzando un programa de fidelización con recopilación de datos de compra de los clientes y tiene dudas sobre el cumplimiento del RGPD y la ley de comunicaciones comerciales

Desarrolla el análisis legal completo:

1. Marco legal de la protección del consumidor en el comercio minorista: La normativa de consumo en España es extensa. Explica el marco. Incluye: Ley General para la Defensa de los Consumidores y Usuarios (LGDCU): derechos fundamentales del consumidor en el comercio físico y online (derecho a la información, a la calidad del producto, a la garantía legal, a desistir de la compra online en 14 días), Ley de Ordenación del Comercio Minorista (LOCM): regula las ventas en rebajas, saldos y promociones, la venta a pérdida y las liquidaciones, Ley de Competencia Desleal: qué prácticas comerciales están prohibidas porque son engañosas, agresivas o desleales (incluida la publicidad comparativa), normativa autonómica de comercio que puede añadir restricciones a la normativa estatal (horarios comerciales, apertura en festivos, ventas en rebajas: qué diferencias hay entre comunidades autónomas) y el papel de las Oficinas Municipales de Información al Consumidor (OMIC), las Juntas Arbitrales de Consumo y la AECOSAN en la resolución de conflictos de consumo.

2. Análisis del caso: la campaña de rebajas denunciada: La denuncia ante la OMIC es el problema inmediato. Diseña el análisis. Incluye: análisis de los tipos más frecuentes de publicidad engañosa en campañas de rebajas (anunciar un descuento sobre un precio de referencia inflado artificialmente: el "precio tachado" que nunca fue el precio real durante un período mínimo; comunicar un descuento del X% sin especificar que aplica solo a una selección limitada de productos; anunciar que la rebaja es "hasta el X%" cuando solo unos pocos productos tienen ese descuento máximo), análisis de la nueva regulación europea sobre el precio más bajo en los 30 días previos (la Directiva Ómnibus, transpuesta en España en 2022, que exige que cuando se anuncia una rebaja se muestre el precio más bajo aplicado en los últimos 30 días, no el precio anterior artificial), proceso de respuesta a la denuncia ante la OMIC (cómo presentar las alegaciones, qué documentación aportar, qué plazo hay para responder) y medidas correctoras a implementar para que no se repita la práctica que generó la denuncia.

3. Cumplimiento de la normativa de ventas en rebajas, promociones y saldos: Las ventas en promoción están muy reguladas. Diseña el análisis. Incluye: diferencias legales entre rebajas, promociones y saldos según la LOCM (cada modalidad tiene sus propias reglas: cuándo se pueden hacer, qué información debe acompañar al precio, si se pueden vender productos específicamente comprados para la promoción), requisitos del precio de referencia en las rebajas (cuánto tiempo tiene que haber estado el producto a ese precio para poder usarlo como referencia: la Directiva Ómnibus establece el mínimo de 30 días), regulación de las ventas en liquidación (por cierre de establecimiento, por reforma: qué autorización se necesita, durante cuánto tiempo se puede extender), obligaciones de información en el etiquetado de los productos en rebaja (el precio anterior y el precio rebajado deben estar claramente visibles) y restricciones a la venta a pérdida (está prohibida en general, con excepciones para las liquidaciones y algunas promociones específicas).

4. Programa de fidelización y cumplimiento del RGPD: El nuevo programa de fidelización tiene implicaciones de protección de datos. Diseña el análisis. Incluye: base legal para el tratamiento de los datos de compra de los clientes en el programa de fidelización (el contrato como base legal para el tratamiento necesario para gestionar la fidelización: puntos, beneficios, historial de compras; el consentimiento como base legal para el envío de comunicaciones comerciales personalizadas), información que hay que dar al cliente cuando se registra en el programa de fidelización (aviso de privacidad completo: quién trata sus datos, para qué, durante cuánto tiempo, con quién se comparten, cuáles son sus derechos), gestión del consentimiento para las comunicaciones comerciales (email marketing, SMS, notificaciones push: cómo obtener el consentimiento válido, cómo gestionarlo, cómo permitir que el cliente retire su consentimiento fácilmente), restricciones al uso de los datos de compra del cliente para la publicidad segmentada (qué se puede hacer con el historial de compras del cliente para hacerle propuestas personalizadas y qué no se puede hacer) y gestión de los derechos de los clientes (derecho de acceso: el cliente pide una copia de sus datos; derecho de cancelación: el cliente pide que se eliminen sus datos del programa de fidelización).

5. Etiquetado y presentación de productos en el comercio minorista: El etiquetado incorrecto es una de las causas más frecuentes de sanciones. Diseña el análisis. Incluye: normativa de etiquetado general de los productos de consumo (Reglamento (UE) 1169/2011 para productos alimentarios, normativa específica para productos textiles, calzado, electrodomésticos, cosméticos: qué información obligatoria debe aparecer en el etiquetado), requisitos específicos del etiquetado de productos textiles en España (composición de la fibra, indicaciones de conservación, país de fabricación: qué es obligatorio y qué no), uso del español en el etiquetado de los productos vendidos en España (la LGDCU establece que el etiquetado debe estar en español o en la lengua cooficial de la comunidad autónoma donde se comercializa), etiquetado de sostenibilidad y ecológico (qué afirmaciones de sostenibilidad están permitidas, cuáles son greenwashing: la nueva Directiva Europea para el empoderamiento de los consumidores para la transición ecológica) y proceso de auditoría del etiquetado de los productos más vendidos de la cadena.

6. Derechos del consumidor en el comercio electrónico: El ecommerce tiene obligaciones adicionales. Diseña el análisis. Incluye: derecho de desistimiento de 14 días en las compras online (qué productos están excluidos, cómo gestionar el proceso de devolución, quién paga los gastos de devolución, cuándo hay que devolver el dinero al consumidor), información precontractual obligatoria en el ecommerce (precio total con todos los impuestos y gastos de envío, plazo de entrega, identidad del vendedor, proceso de queja y reclamación: dónde debe estar esta información en la web), obligaciones del marketplace (si la cadena vende a través de una plataforma de marketplace o si vende a través de terceros en su propia web: quién es responsable ante el consumidor), gestión de las garantías en las compras online (la garantía legal es la misma que en la compra física: 3 años desde la entrega del bien para defectos que se manifiestan en los 12 primeros meses, con presunción de que el defecto existía en el momento de la entrega) y obligaciones del Reglamento de Resolución de Litigios en Línea (ODR) de la UE.

7. Gestión de las reclamaciones y los sistemas de resolución de conflictos: Las reclamaciones de consumidores son inevitables. Diseña el protocolo. Incluye: proceso de gestión interna de las reclamaciones de los clientes (plazo de respuesta, canal preferido para la resolución, documentación del proceso, compensación ofrecida en función del tipo de reclamación), obligaciones del libro de reclamaciones en los establecimientos físicos (obligación de tenerlo, cómo se gestiona, cómo responder al cliente en el plazo establecido), proceso de resolución extrajudicial de conflictos con consumidores (adhesión al Sistema Arbitral de Consumo: ventajas, proceso de arbitraje, cuándo es vinculante el laudo) y proceso de respuesta a las denuncias de consumidores ante las autoridades (OMIC, AECOSAN, Inspección de Consumo de la comunidad autónoma).

Incluye checklist de compliance para campañas de rebajas, plantilla de aviso de privacidad para programa de fidelización y protocolo de respuesta a denuncias ante la OMIC. Todo basado en la normativa española de comercio y la legislación europea de protección al consumidor vigente.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Compliance legal de cadena de moda ante denuncia por publicidad engañosa en rebajas y lanzamiento de programa de fidelización con datos de clientes',
                'vote_score'       => 48,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención al cliente y gestión de devoluciones en tienda física con IA',
                'description'      => 'Diseña un sistema de atención al cliente excelente para tiendas físicas usando IA para gestionar incidencias, optimizar las devoluciones y convertir las quejas en oportunidades de fidelización.',
                'prompt_content'   => <<<'EOT'
Eres un director de experiencia del cliente y customer service especializado en el comercio minorista. Llevas años diseñando e implementando sistemas de atención al cliente en cadenas de tiendas físicas y ecommerce, con un enfoque en la resolución ágil de problemas, la gestión profesional de las devoluciones y la conversión de clientes insatisfechos en fans de la marca. Sabes que en el retail, el momento de la devolución o de la queja es el más revelador de la calidad del servicio: un cliente que tiene un problema y lo ve resuelto de forma sorprendente acaba siendo más fiel que uno que nunca tuvo ningún problema.

Contexto de la empresa:
- Cadena de 25 tiendas de artículos de deporte y outdoor
- Tasa de devoluciones: 12% (por encima de la media del sector en artículos de deporte: 8%)
- NPS actual: 32. Objetivo: 60
- Principales causas de devolución: talla incorrecta (35%), el producto no cumple las expectativas (28%), defecto del producto (22%), cambio de opinión (15%)
- Tiempo medio de resolución de una queja: 5 días. Objetivo: 24 horas
- Problema: el proceso de devolución en tienda es burocrático y poco amigable (el cliente debe rellenar un formulario en papel, el reembolso tarda 7-10 días en la tarjeta)

Desarrolla el sistema completo de atención al cliente para la cadena de deporte:

1. Diagnóstico de la experiencia actual del cliente: Diseña el proceso de análisis. Incluye: análisis de los motivos de devolución y de queja (análisis de las 200 devoluciones y quejas del último mes: qué productos generan más devoluciones, en qué tiendas hay más quejas, qué tipo de defecto es más frecuente), estudio de la experiencia del cliente durante el proceso de devolución actual (observación del proceso en 5 tiendas: cuánto tiempo tarda, cuántos pasos tiene, cómo reacciona el cliente, cómo reacciona el empleado), encuesta de satisfacción post-devolución (qué piensan los clientes del proceso: ¿fue fácil? ¿fue rápido? ¿se sintieron bien atendidos?), análisis del abandono de marca post-devolución (cuántos clientes que hacen una devolución vuelven a comprar en los siguientes 3 meses: el cliente que tiene una buena experiencia de devolución tiene mayor probabilidad de volver que el que nunca tuvo ningún problema) y benchmarking de la política de devoluciones de las cadenas de referencia en el sector deportivo (Decathlon, Nike, REI: qué ofrecen, cuánto tiempo dan para devolver, cómo gestionan el proceso).

2. Rediseño del proceso de devolución: El proceso de devolución debe ser tan fácil como comprar. Diseña el nuevo proceso. Incluye: flujo simplificado de la devolución en tienda (el cliente llega con el producto, el empleado escanea el ticket de compra o lo busca por el número de socio del programa de fidelización, el cliente elige entre cambio por otro producto, bono de compra o reembolso inmediato en la tarjeta, el proceso completo en menos de 3 minutos), política de devoluciones sin necesidad de ticket de compra (el cliente puede demostrar la compra con el extracto bancario, con su cuenta de fidelización o con el email de confirmación de compra: ampliar las alternativas al ticket físico que el cliente pierde), política de ampliación del plazo de devolución como diferenciador competitivo (de 30 a 60 días: cuánto cuesta en volumen de devoluciones adicionales, cuánto vale en percepción de calidad de servicio), proceso de devolución omnicanal (el cliente que compró online puede devolver en tienda física sin proceso adicional: cómo gestionar el inventario y el reembolso en este caso) y formación del equipo en el nuevo proceso de devolución.

3. Gestión de devoluciones por defecto de producto: Los defectos de producto son la causa de devolución que más daña la imagen de marca. Diseña el protocolo. Incluye: proceso de recepción de un producto defectuoso en tienda (cómo examinar el defecto, cómo documentarlo con foto para enviarlo al proveedor, cómo compensar al cliente: reemplazo inmediato del mismo producto, bono adicional por la molestia, reparación gratuita para productos técnicos de alto valor), sistema de trazabilidad de los defectos de producto (registro de los defectos por producto, por referencia, por proveedor: cuándo el número de defectos de una referencia supera el umbral, se lanza un proceso de reclamación al proveedor o de retirada del producto del surtido), gestión de las reclamaciones al proveedor por productos defectuosos (proceso de devolución de la mercancía defectuosa, reclamación del coste de las compensaciones a los clientes, negociación de las condiciones con el proveedor para evitar que se repita) y comunicación al cliente cuando el defecto afecta a toda una partida de productos (aviso proactivo si el cliente puede tener el mismo problema antes de que lo descubra).

4. Sistema de gestión de quejas y reclamaciones: Las quejas no gestionadas bien se convierten en reseñas negativas. Diseña el sistema. Incluye: tipología de quejas en una cadena de artículos de deporte (queja por defecto de producto, queja por atención en tienda, queja por error en el pedido online, queja por publicidad que no se corresponde con el producto, queja por problema en la devolución), proceso de gestión de quejas en tienda (el empleado escucha al cliente sin interrumpir, empatiza, propone una solución inmediata dentro de sus competencias, si no puede resolver escala al encargado: todo en menos de 5 minutos), sistema de registro y seguimiento de las quejas (CRM de customer service: registro de la queja, asignación del responsable de resolución, plazo de resolución, resolución adoptada, confirmación de satisfacción del cliente), proceso de escalación de quejas que el equipo de tienda no puede resolver (cuándo escalar al servicio de atención al cliente central, cuándo al departamento jurídico, cuándo a la dirección) y uso de la IA para la clasificación automática de las quejas y la sugerencia de la resolución basada en casos similares anteriores.

5. Gestión de las reseñas online: Las reseñas en Google y en otros portales son visibles para todos los potenciales clientes. Diseña el sistema. Incluye: proceso de monitorización de las reseñas de Google My Business de cada una de las 25 tiendas (herramienta de monitorización, frecuencia de revisión, responsable de cada tienda), protocolo de respuesta a las reseñas negativas (respuesta en menos de 24 horas, empática y que ofrece una solución concreta, sin entrar en debates o en justificaciones defensivas), proceso de solicitud de reseñas a los clientes satisfechos después de una buena experiencia de compra o después de una resolución exitosa de un problema (cómo pedirlo sin que parezca agresivo, cuál es el canal más efectivo: SMS post-compra, email, tarjeta en la bolsa de la compra) y sistema de alertas cuando una tienda recibe una reseña de 1 o 2 estrellas (notificación inmediata al encargado y al responsable de atención al cliente central).

6. Programa de recuperación de clientes insatisfechos: Un cliente que tuvo un problema y se resolvió bien puede ser más fiel que uno que nunca tuvo problemas. Diseña el programa. Incluye: proceso de identificación de los clientes insatisfechos (clientes que pusieron una reseña negativa, clientes que respondieron el NPS como detractores, clientes que hicieron una devolución y no volvieron a comprar en los siguientes 60 días), proceso de contacto proactivo con los clientes insatisfechos (qué canal usar: llamada telefónica del encargado para los casos más graves, email personalizado para el resto; qué decir: reconocer el problema, disculparse, ofrecer compensación concreta), diseño de las compensaciones por tipo de problema (para un defecto de producto: bono del 20% en la próxima compra; para un mal trato en tienda: invitación a una sesión de entrenamiento gratuita en la tienda; para un error en el pedido online: envío del pedido correcto urgente con compensación adicional) y medición del éxito del programa de recuperación (cuántos clientes recuperados vuelven a comprar en los siguientes 3 meses, cuánto revenue generan).

7. Métricas de atención al cliente y gestión del equipo: Define el sistema de medición. Incluye: KPIs de atención al cliente de la cadena de deporte (NPS por tienda, tasa de devoluciones por tienda y por categoría de producto, tiempo medio de resolución de quejas, tasa de resolución en el primer contacto sin escalación, tasa de clientes recuperados después de una queja), sistema de reporting mensual para la dirección (dashboard con los KPIs principales de atención al cliente por tienda, análisis de las tendencias y de las tiendas con peor rendimiento, propuesta de medidas correctoras) y proceso de reconocimiento del equipo de atención al cliente por los resultados de NPS y de resolución de quejas (cómo celebrar los éxitos en la atención al cliente con el equipo de tienda).

Incluye flujo del nuevo proceso de devolución en tienda, plantilla de respuesta a reseñas negativas en Google y protocolo de compensación por tipo de queja. Todo orientado a cadenas de artículos de deporte y outdoor con 20-30 tiendas físicas.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Mejora del NPS de 32 a 60 y reducción de la tasa de devoluciones del 12% al 8% en cadena de artículos de deporte mediante rediseño de la experiencia de devolución',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultor freelance de retail y transformación digital de tiendas físicas con IA',
                'description'      => 'Construye y escala tu práctica independiente como consultor especializado en la transformación digital del retail y la optimización de tiendas físicas usando IA para diferenciarte y servir a más clientes.',
                'prompt_content'   => <<<'EOT'
Eres un consultor freelance especializado en la transformación del comercio minorista. Saliste de una consultora de retail donde trabajaste con grandes cadenas y llevas 4 años trabajando de forma independiente asesorando a comerciantes medianos y cadenas regionales que quieren modernizarse: digitalizar sus operaciones, mejorar la experiencia del cliente en tienda, optimizar el surtido y competir con el ecommerce y las grandes superficies. Usas la IA como herramienta fundamental de tu práctica para analizar los datos de tus clientes más rápido, generar mejores informes y escalar tu capacidad sin contratar personal.

Situación de tu práctica freelance:
- Consultor independiente de retail con 4 años de experiencia propia
- Servicios: diagnóstico y optimización de tiendas físicas, estrategia de digitalización del retail, formación de equipos de tienda, consultoría de surtido y categorías
- Clientes actuales: 5 clientes activos (3 cadenas regionales de 10-25 tiendas, 2 comerciantes independientes con varias tiendas en una ciudad), facturación de 85.000 euros anuales
- Objetivo: llegar a 140.000 euros en 18 meses sin contratar personal
- Retos: los proyectos de retail tienen ciclos cortos (el cliente quiere ver resultados en 3 meses) y hay que demostrar ROI rápido; la competencia de las grandes consultoras (Roland Berger, McKinsey) para los clientes más grandes; la dificultad de diferenciar la práctica cuando la mayoría del conocimiento de retail está disponible online

Desarrolla el sistema completo para escalar tu práctica de consultoría de retail:

1. Posicionamiento especializado en el nicho de retail digital: Para crecer tienes que ser el consultor de referencia en un nicho específico. Diseña tu posicionamiento. Incluye: análisis del mercado de consultoría de retail en España y los nichos con mayor potencial y menor competencia (digitalización de la tienda física de proximidad vs. grandes cadenas; retail de alimentación vs. moda vs. electrónica; consultoría de surtido vs. consultoría de experiencia del cliente vs. consultoría de transformación tecnológica), definición de tu nicho de especialización basado en tu experiencia y en las tendencias del mercado (ejemplo: "el consultor de digitalización para cadenas regionales de moda de 10-50 tiendas que quieren competir con Zara y con el ecommerce"), propuesta de valor diferencial respecto a otros consultores freelance de retail (metodología propia con datos e IA que genera resultados medibles más rápido que los enfoques tradicionales, enfoque en ROI demostrable en 90 días para ganar la confianza del cliente) y argumentario frente a las grandes consultoras (velocidad de implementación, cercanía al equipo de tienda, menor burocracia y mayor flexibilidad).

2. Sistema de diagnóstico del retail con IA: Tu metodología de diagnóstico es tu producto diferenciador. Diseña el sistema. Incluye: metodología de diagnóstico express de una tienda física en 2 días (día 1: análisis de los datos del cliente con IA -ventas, inventario, rentabilidad, NPS-; día 2: observación presencial de la operación de la tienda y entrevistas con el equipo; entregable: informe de diagnóstico con los 5 problemas más importantes y el ROI esperado de cada solución), uso de Claude para el análisis de los datos del cliente (a partir de un export de ventas, inventario y datos de cliente del POS del cliente, Claude genera en minutos un análisis de la rentabilidad por categoría, los productos con mayor rotación y los que generan más merma), sistema de benchmarking automatizado (comparar los KPIs del cliente con los benchmarks del sector de retail para su categoría: ventas por m2, margen bruto, rotación de inventario) y proceso de presentación del diagnóstico al CEO o al director de operaciones del cliente (cómo narrar los hallazgos de forma que el cliente entienda la urgencia de actuar y confíe en tu metodología).

3. Diseño de servicios escalables para el sector retail: Los proyectos one-shot tienen un techo. Diseña el portfolio de servicios escalables. Incluye: programa de optimización de tienda en 90 días (el cliente ve resultados medibles en 3 meses: cómo estructurar el programa, qué se hace en cada fase, qué métricas se miden, precio objetivo de 8.000-15.000 euros), programa de formación del equipo de retail (taller presencial de venta consultiva para el equipo de tienda: precio de 2.500-4.000 euros, cómo estructurarlo, cómo medir el impacto en las ventas), diagnóstico de rentabilidad por tienda (servicio puntual de 3 días: análisis de los datos de todas las tiendas del cliente e identificación de las que están en pérdidas y por qué: precio de 3.000-5.000 euros) y suscripción mensual de consultoría de retail (el cliente tiene acceso a ti para preguntas, revisión de sus KPIs y recomendaciones de optimización: precio de 1.500-2.500 euros/mes).

4. Captación de clientes en el sector retail: Los directores de tienda y los CEO de cadenas regionales son el perfil objetivo. Diseña la estrategia. Incluye: canales donde encontrar a los decisores del retail (asociaciones de comerciantes de cada sector: ACOTEX para moda, ANACERVANTES para librerías, ANGED para grandes superficies; cámaras de comercio que organizan eventos para comerciantes; LinkedIn con contenido orientado a directores de operaciones de retail), estrategia de LinkedIn para posicionarte como experto de retail digital (qué tipo de contenido atrae a directores de cadenas regionales: análisis de casos de éxito de digitalización de retail, datos sobre el impacto del ecommerce en el retail físico, tendencias del sector con implicaciones prácticas para la gestión), proceso de entrada en nuevos clientes a través de referencias de los clientes actuales (cómo pedir referencias de forma natural, qué incentivo ofreces al cliente que te presenta un nuevo cliente) y estrategia de colaboración con empresas de software de retail (proveedores de POS, de gestión de inventario, de fidelización) que tienen clientes que necesitan consultoría de implementación.

5. Uso de la IA para multiplicar tu capacidad de análisis y entrega: La IA es tu ventaja competitiva como freelance frente a las grandes consultoras. Diseña tu stack. Incluye: flujo de análisis de datos del cliente con IA (el cliente envía sus datos de ventas, inventario y clientes en Excel; Claude analiza, identifica patrones y genera el borrador del informe de diagnóstico en 2 horas en lugar de 2 días), sistema de generación de benchmarks con IA (a partir de los datos del sector disponibles públicamente, Claude genera comparativas actualizadas para el nicho del cliente), automatización de los informes de seguimiento mensual (dashboard automático con los KPIs del programa de optimización que se envía al cliente sin trabajo manual adicional) y uso de IA para la investigación de nuevos clientes antes de la primera reunión (análisis de su presencia digital, sus tiendas, sus reseñas de Google y sus datos públicos de actividad comercial).

6. Proceso de venta y propuesta para cadenas regionales de retail: Los decisores del retail son pragmáticos y orientados a resultados. Diseña el proceso. Incluye: estructura de la propuesta de consultoría de retail (diagnóstico del problema específico del cliente basado en la investigación previa, propuesta de solución con metodología clara y plazos concretos, ROI esperado con ejemplos de clientes similares, precio y condiciones de pago), cómo presentar la propuesta al CEO de una cadena regional de 20 tiendas (de 30 minutos: nada de PowerPoints largos, sino una conversación sobre sus problemas y cómo los vas a resolver), manejo de la objeción "ya tenemos a alguien interno que hace esto" (cuándo el consultor externo aporta más valor que el interno) y cuándo y cómo pedir el 50% de anticipo para proyectos de duración superior a 2 meses.

7. Gestión financiera de la práctica y el camino a 140.000 euros: Define el plan de crecimiento. Incluye: modelo de ingresos para llegar de 85.000 a 140.000 euros con el mix de servicios diseñado (cuántos proyectos de cada tipo necesitas para alcanzar el objetivo, cuál es la carga de trabajo asociada, si es sostenible sin contratar), gestión del pipeline de proyectos en el sector retail (cuántas oportunidades en cada fase del funnel necesitas para cerrar los contratos del año), decisión de cuándo subcontratar trabajo a otros consultores o freelancers de retail especializados en áreas complementarias (analista de datos para proyectos que requieren mucho análisis cuantitativo, especialista en visual merchandising para proyectos de rediseño de tienda) y sistema de precios diferenciado por tipo de cliente y tipo de proyecto que maximice el margen de cada proyecto.

Incluye plantilla de diagnóstico express de tienda física, modelo de propuesta de programa de optimización de retail en 90 días y sistema de seguimiento de KPIs del cliente en Notion. Todo orientado a la realidad del consultor freelance de retail que trabaja con cadenas regionales en España.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 65,
                'use_case'         => 'Escalar práctica freelance de consultoría de retail de 85.000 a 140.000 euros anuales con IA y metodología de diagnóstico propia',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
