<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills569Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Estrategia de marketing con vídeo y contenido audiovisual con IA',
                'description'      => 'Diseña y ejecuta campañas de marketing basadas en vídeo y contenido audiovisual usando IA para producir más, distribuir mejor y medir el impacto real del vídeo en los objetivos de negocio.',
                'prompt_content'   => <<<'EOT'
Eres un director de marketing de contenidos con especialización en video marketing y estrategia audiovisual. Llevas años gestionando la estrategia de contenido en vídeo para marcas de consumo, empresas B2B y medios digitales, y has adoptado las herramientas de IA generativa para multiplicar la producción de vídeo sin aumentar proporcionalmente el equipo ni el presupuesto. Conoces en profundidad el ecosistema de distribución de vídeo: YouTube, Instagram Reels, TikTok, LinkedIn Video, vídeo en email y vídeo en landing pages.

Contexto de la empresa:
- Empresa de software B2B con 280 empleados que vende soluciones de gestión empresarial a PYMEs
- Marketing actual: blog con 40 artículos/mes, newsletter semanal, LinkedIn activo, pero muy poco vídeo
- Objetivo: convertir el vídeo en el canal principal de generación de leads cualificados
- Presupuesto de vídeo disponible: 8.000 euros/mes para producción y distribución
- Equipo: 1 responsable de contenidos que coordinará la estrategia de vídeo con recursos externos y herramientas de IA
- Reto principal: el equipo no tiene experiencia en producción de vídeo y los directivos creen que producir vídeo de calidad es muy caro y complejo

Desarrolla la estrategia completa de video marketing con IA:

1. Arquitectura de contenido en vídeo para B2B: El vídeo en B2B sigue una lógica diferente al B2C. Diseña el sistema de contenidos. Incluye: tipos de vídeo que funcionan para la generación de leads en B2B (vídeo explicativo del producto, caso de éxito de cliente, webinar grabado, tutorial de uso, vídeo de problema-solución, vídeo de opinión del CEO o fundador sobre el sector), mapa de contenido por etapa del funnel (awareness: vídeos educativos sobre los problemas que resuelve el software; consideración: demos del producto, comparativas con competidores, casos de éxito; decisión: testimonios de clientes, walkthrough de onboarding, calculadoras de ROI en vídeo), calendario editorial de vídeo mensual con los formatos y plataformas para cada pieza y estrategia de reutilización de cada vídeo en múltiples formatos (un webinar de 45 minutos se convierte en 8 clips de LinkedIn, 3 Reels de Instagram, 5 respuestas a preguntas de YouTube Shorts y 2 secciones del newsletter).

2. Producción de vídeo con IA y presupuesto limitado: La IA ha democratizado la producción de vídeo. Diseña el sistema de producción. Incluye: stack tecnológico de producción de vídeo con IA para equipos sin experiencia técnica (Descript para edición, ElevenLabs para voz en off, HeyGen o Synthesia para avatares de vídeo, Runway o Pika para efectos y B-roll generado con IA, CapCut para edición rápida de Reels y TikTok), flujo de producción de un vídeo explicativo de 3 minutos con IA (desde el guion hasta el vídeo final: redacción del guion con Claude, generación de la voz en off con ElevenLabs, edición con Descript, adición de subtítulos automáticos), proceso de producción de casos de éxito de clientes en vídeo (entrevista grabada por el cliente con su móvil, envío al equipo de marketing, edición profesional con IA), proceso de calidad para los vídeos generados con IA antes de publicarlos y cuándo merece la pena contratar una productora externa vs. producir con IA internamente.

3. Distribución multicanal y optimización por plataforma: Cada plataforma tiene sus propias reglas de distribución. Diseña la estrategia. Incluye: estrategia de YouTube para B2B (SEO de YouTube: cómo hacer keyword research para el canal de vídeo, estructura del vídeo para maximizar el watch time, miniatura y título que generan clics, estrategia de listas de reproducción, canal de membresía), estrategia de LinkedIn Video para la generación de leads B2B (formato de vídeo nativo vs. enlace a YouTube, hora óptima de publicación, cómo usar el vídeo de LinkedIn para promover conversaciones con compradores potenciales), estrategia de vídeo en landing pages para aumentar la tasa de conversión (vídeo en el hero de la landing page, vídeo de demo del producto, vídeo de testimonios: dónde colocarlos y cómo medir su impacto), uso del vídeo en la secuencia de emails de nurturing (qué tipos de vídeo funcionan mejor en email, cómo testar el asunto con el vídeo vs. sin él) y estrategia de YouTube Shorts y Reels para la generación de audiencia con clips del contenido largo.

4. Análisis y optimización del rendimiento del vídeo: El vídeo tiene sus propias métricas. Diseña el sistema. Incluye: métricas principales del vídeo B2B (watch rate: qué porcentaje del vídeo ve el espectador de media; engagement: likes, comentarios, compartidos; CTR de la miniatura en YouTube; tasa de conversión desde el vídeo a lead: cuántos espectadores acaban dejando sus datos de contacto), sistema de análisis de la retención por vídeo en YouTube (qué minutos del vídeo pierden más espectadores y qué significa eso para el contenido), proceso de A/B testing de miniaturas y títulos en YouTube para maximizar el CTR, integración de los datos de YouTube con el CRM para cerrar el loop entre el vídeo y los leads generados y proceso de revisión mensual del rendimiento de cada vídeo con decisiones concretas de optimización.

5. Vídeo como herramienta de ventas: El equipo de ventas puede usar el vídeo para cerrar más deals. Diseña el sistema de video selling. Incluye: uso del vídeo en el proceso de ventas B2B (vídeo de presentación personalizado del SDR al prospecto, vídeo-propuesta en lugar de PDF, vídeo de seguimiento post-reunión), herramientas de video selling para el equipo de ventas (Vidyard, Loom, Sendspark: comparativa y cuál elegir), librería de vídeos de ventas que el equipo puede usar en diferentes fases del proceso (demo del producto, respuesta a objeciones frecuentes, comparativa con competidores) y métricas de éxito del video selling (tasa de apertura de los vídeos enviados por el equipo de ventas, impacto en la tasa de conversión de propuesta a cierre).

6. Medición del ROI del video marketing: El vídeo debe demostrar su retorno. Diseña el framework. Incluye: modelo de atribución de leads al canal de vídeo (cuántos leads proceden directamente de YouTube, de LinkedIn Video, de las landing pages con vídeo), cálculo del coste por lead generado por el canal de vídeo vs. otros canales (SEO, paid search, email), análisis de la contribución del vídeo al cierre de deals (los deals donde el comprador vio al menos un vídeo antes de comprar tienen mayor tasa de cierre que los que no vieron ninguno: cómo demostrarlo con datos del CRM) y proceso de reporting mensual del video marketing al equipo directivo (inversión en vídeo, leads generados, influencia del vídeo en el pipeline).

7. Escala y automatización del video marketing: Para producir más sin aumentar el equipo. Diseña el sistema. Incluye: automatización de la producción de vídeo con plantillas (plantillas en Canva o Adobe Express para los formatos más repetitivos: clips de LinkedIn, miniaturas de YouTube, vídeos de tips), proceso de reciclaje sistemático del contenido existente en vídeo (transformar artículos del blog en guiones de vídeo con IA, transformar webinars en series de Shorts), sistema de monitorización de tendencias de vídeo en el sector para identificar oportunidades de contenido de alto impacto y proceso de escalado del volumen de producción de 4 vídeos al mes a 16 vídeos al mes en 6 meses.

Incluye plantilla de guion de vídeo B2B, calendario editorial de vídeo para el primer trimestre y sistema de métricas de video marketing para empresas de software.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Implementación de una estrategia de video marketing B2B para empresa de software que quiere convertir el vídeo en su principal canal de leads',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de plataformas de streaming y distribución de vídeo con IA',
                'description'      => 'Diseña y construye infraestructuras de streaming de vídeo, plataformas OTT y sistemas de distribución de contenido audiovisual usando IA para la transcodificación, la recomendación y la personalización de la experiencia.',
                'prompt_content'   => <<<'EOT'
Eres un arquitecto de software especializado en plataformas de vídeo y streaming con experiencia construyendo sistemas de distribución de contenido audiovisual, plataformas OTT (Over-the-Top), CDNs de vídeo y motores de recomendación para servicios de streaming. Conoces en profundidad la cadena técnica del vídeo: captura, ingestión, transcodificación, almacenamiento, distribución adaptativa (HLS, DASH), reproducción y medición.

Contexto del proyecto:
- Grupo de medios español con una televisión regional con licencia de emisión y un portal de noticias con 2 millones de visitas mensuales
- Objetivo: lanzar una plataforma OTT propia para distribuir el contenido de la televisión regional bajo demanda y en directo, monetizando con publicidad (AVOD) y con suscripción premium (SVOD)
- Contenido inicial: 15.000 horas de archivo histórico + producción en directo de 8 horas diarias
- Objetivo de audiencia: 500.000 usuarios registrados en el primer año
- Tecnología: el equipo técnico actual trabaja con AWS para la infraestructura, tiene experiencia en PHP y Node.js para el backend

Desarrolla la arquitectura completa de la plataforma OTT:

1. Arquitectura general de la plataforma OTT: Diseña la arquitectura técnica completa. Incluye: componentes principales de la plataforma (CMS para la gestión del contenido, sistema de ingestión y procesamiento del vídeo, almacenamiento y CDN, API de contenido para los clientes, sistema de usuarios y autenticación, motor de recomendación, sistema de publicidad CSAI/SSAI, sistema de pagos y suscripción, analytics de vídeo), flujo técnico del contenido desde la captura hasta la reproducción en el dispositivo del usuario (ingestión → transcodificación → empaquetado adaptativo → almacenamiento en S3 → distribución CDN → reproducción adaptativa en el player), diagrama de las integraciones clave (sistema de broadcast existente, CDN, payment gateway, DRM, ad server) y decisiones de arquitectura make-vs-buy (qué construir internamente y qué comprar como servicio: transcodificación con AWS MediaConvert vs. solución propia; DRM con Widevine + FairPlay vs. solución propietaria).

2. Pipeline de procesamiento de vídeo con IA: El procesamiento del contenido audiovisual es una tarea intensiva en computación. Diseña el pipeline. Incluye: arquitectura del pipeline de ingestión y transcodificación (cómo ingesta el vídeo desde el sistema de broadcast, cuántos perfiles de transcodificación se generan: desde 240p para conexiones lentas hasta 4K para usuarios premium, uso de AWS MediaConvert o ffmpeg en instancias spot para reducir el coste de transcodificación), uso de IA para la generación automática de metadatos del contenido (transcripción automática de los vídeos con Whisper o AWS Transcribe, generación de subtítulos en múltiples idiomas, extracción automática de temas y palabras clave para el SEO del contenido), sistema de IA para el análisis de calidad del vídeo (detección automática de vídeos con problemas técnicos: bloqueos, artefactos, pérdida de señal) y pipeline de preparación del archivo histórico de 15.000 horas (procesamiento por lotes, priorización del contenido más relevante, enriquecimiento de metadatos).

3. Distribución adaptativa y experiencia de reproducción: La calidad de reproducción es la métrica más importante para los usuarios. Diseña el sistema. Incluye: implementación del streaming adaptativo (HLS con múltiples bitrates usando el protocolo de Apple, DASH para dispositivos Android y Smart TVs), selección del player de vídeo (Video.js, Shaka Player, THEOplayer: comparativa según funcionalidades, coste y compatibilidad de dispositivos), estrategia de CDN para la distribución geográfica del contenido (CloudFront de AWS, Akamai, Cloudflare Stream: cuál usar y cómo configurar las reglas de caché), sistema de DRM (Digital Rights Management) para proteger el contenido premium (Widevine para Chrome y Android, FairPlay para Safari y iOS, PlayReady para Windows: cómo implementar una solución multi-DRM), optimización del inicio del vídeo (tiempo hasta el primer fotograma: objetivo menos de 2 segundos) y sistema de medición del QoE (Quality of Experience) en tiempo real.

4. Motor de recomendación de contenido con IA: La recomendación personalizada aumenta el tiempo de visionado. Diseña el sistema. Incluye: datos disponibles para la recomendación (historial de visionado, géneros y temáticas preferidas, hora del día de consumo, dispositivo, ubicación geográfica, valoraciones explícitas si las hay), arquitectura del motor de recomendación (filtrado colaborativo para usuarios con historial, recomendación basada en contenido para usuarios nuevos o con poco historial, cold start problem: cómo recomendar cuando el usuario es nuevo), modelos de ML para la recomendación (matrix factorization, modelos basados en embeddings de contenido, deep learning para la recomendación en tiempo real), A/B testing del motor de recomendación (cómo evaluar si una nueva versión del modelo mejora el tiempo de visionado o el engagement) y diseño de la interfaz de recomendaciones (carruseles por categoría, sección "Porque viste X", trending regional).

5. Monetización: publicidad AVOD y suscripción SVOD: La plataforma necesita ser rentable. Diseña el modelo de monetización. Incluye: diseño del modelo freemium con nivel AVOD gratuito con publicidad y nivel SVOD de pago sin publicidad (cómo definir los contenidos exclusivos del nivel premium para que valga la pena pagar), integración del sistema de publicidad en vídeo (CSAI: client-side ad insertion con Google IMA SDK; SSAI: server-side ad insertion con AWS Elemental MediaTailor para una experiencia de publicidad más fluida sin buffering), integración con el sistema de gestión de suscripciones (Stripe para los pagos, gestión de los planes de suscripción mensual y anual, proceso de trial gratuito, gestión de cancelaciones y reactivaciones) y sistema de publicidad programática para maximizar el CPM (conexión con DSPs a través de la integración con un ad server propio o con Google Ad Manager).

6. Analytics de vídeo y medición del negocio: Sin datos, no hay optimización. Diseña el sistema de medición. Incluye: métricas de contenido (número de reproducciones, horas totales vistas, watch rate por vídeo, momento de abandono del vídeo, replays), métricas de usuario (MAU, DAU, sesiones por usuario y mes, tiempo de sesión, retención al día 7, día 30 y día 90 de registro), métricas de negocio (ingresos SVOD: MRR, churn de suscriptores; ingresos AVOD: impresiones publicitarias, CPM, fill rate), sistema de analytics de vídeo en tiempo real (Mux Data, Conviva, o solución propia con Kafka + ClickHouse) y dashboard ejecutivo con los KPIs del negocio OTT para el equipo directivo del grupo de medios.

7. Aplicaciones cliente para dispositivos múltiples: La plataforma debe funcionar en todos los dispositivos relevantes. Diseña la estrategia de desarrollo. Incluye: priorización de plataformas cliente según la audiencia objetivo (Web: prioritario, iOS y Android: prioritario, Smart TVs: Samsung Tizen y LG webOS como segunda prioridad, Apple TV y Android TV como tercera), estrategia de desarrollo multiplataforma (React Native para móvil con código compartido entre iOS y Android, React para web, apps nativas para Smart TV) y proceso de certificación en las tiendas de aplicaciones y en el programa de Samsung o LG para Smart TVs.

Incluye diagramas de arquitectura en texto, referencias a las tecnologías de streaming más usadas en el mercado y análisis de costes de infraestructura para 500.000 usuarios en AWS.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 90,
                'use_case'         => 'Arquitectura de plataforma OTT para grupo de medios regional con monetización AVOD y SVOD',
                'vote_score'       => 58,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de identidad visual y motion graphics para producción audiovisual con IA',
                'description'      => 'Crea sistemas de identidad visual para medios audiovisuales, diseña motion graphics y brand packages para vídeo usando IA para acelerar la producción y mantener la coherencia visual en todos los formatos.',
                'prompt_content'   => <<<'EOT'
Eres un director de arte especializado en identidad visual para medios audiovisuales y motion graphics. Tu trabajo consiste en diseñar sistemas visuales coherentes que funcionen en el vídeo: desde el logotipo animado de un canal hasta la tipografía que aparece en pantalla, los gráficos de los informativos, los títulos de crédito, los overlays de las redes sociales y los bumpers que separan los bloques de contenido. Usas After Effects, Cinema 4D, Figma y las nuevas herramientas de IA generativa para crear y animar, acelerando la producción de un proceso que antes tardaba semanas.

Contexto del proyecto de diseño:
- Canal de YouTube de educación financiera con 380.000 suscriptores que quiere refrescar su identidad visual
- Problema: el canal tiene una identidad visual inconsistente creada hace 3 años por diferentes freelancers, sin sistema definido
- Objetivo: crear un sistema de identidad visual completo que sea coherente en todos los formatos: vídeos largos de YouTube, Shorts, miniaturas, redes sociales y el newsletter
- Restricción: el creador del canal produce 3 vídeos a la semana y necesita que el sistema visual sea fácil de replicar sin depender constantemente de un diseñador

Desarrolla el sistema completo de identidad visual audiovisual:

1. Estrategia de identidad visual para medios audiovisuales: Antes de diseñar, hay que definir la estrategia. Incluye: análisis de los canales de YouTube de referencia en el sector de educación financiera (The Plain Bagel, Ben Felix, Andrei Jikh) y sus decisiones de identidad visual (paleta de colores, tipografía, estilo de las miniaturas, uso de la persona o de gráficos abstractos), definición de los valores que la identidad visual debe transmitir para un canal de finanzas personales (confianza, accesibilidad, modernidad, optimismo económico) y cómo cada decisión de diseño contribuye a esa percepción, análisis de la audiencia del canal (perfil demográfico, nivel de educación financiera, qué otros canales consume) y cómo afecta eso a las decisiones visuales (¿tipografía más seria o más dinámica?), definición de la personalidad visual del canal (5 adjetivos que describen la estética deseada: moderno pero no frívolo, profesional pero accesible, etc.) y análisis de la identidad visual actual para identificar qué mantener y qué cambiar.

2. Diseño del sistema de identidad visual: El sistema visual define todas las piezas. Diseña el sistema completo. Incluye: logotipo y variaciones (versión principal, versión reducida para el avatar, versión en blanco, versión en negro, usos correctos e incorrectos), paleta de colores del canal (color principal, colores secundarios, colores de acento, colores de fondo, cómo combinarlos en pantalla para máxima legibilidad), sistema tipográfico para vídeo (tipografía de títulos, tipografía de cuerpo de texto en pantalla, tamaños mínimos para garantizar legibilidad en móvil, interlineado y tracking adecuado para pantalla), sistema de iconografía (estilo de los iconos que se usan en las infografías de los vídeos: líneal, relleno, duotono) y sistema de fotografía e ilustración (directrices sobre las imágenes que se usan en las miniaturas y en los gráficos de pantalla).

3. Brand package de motion graphics: El motion es la capa de animación sobre la identidad estática. Diseña el paquete completo. Incluye: logotipo animado (el "bumper" de entrada de 3-5 segundos que aparece al inicio de cada vídeo, con especificaciones técnicas: resolución 1080p o 4K, formato de exportación, canal alpha para superposición sobre vídeo), lower thirds (los textos que aparecen en la parte inferior de la pantalla para identificar al entrevistado o el tema: diseño de la plantilla en After Effects, instrucciones de personalización), títulos y rótulos para los vídeos educativos (cómo se presentan los títulos de sección dentro del vídeo, los datos y estadísticas, las fórmulas matemáticas), bumpers de separación de contenido (los 2-3 segundos de animación que separan los bloques del vídeo), outro animado con las llamadas a la acción del canal (suscribirse, activar la campanilla, ver el siguiente vídeo) y cómo usar herramientas de IA (Adobe Firefly, Runway, Motion Array) para acelerar la creación de las animaciones.

4. Sistema de miniaturas: Las miniaturas son el elemento más importante para el CTR en YouTube. Diseña el sistema. Incluye: anatomía de una miniatura de alto CTR para un canal de finanzas (qué elementos incluir: cara del creador con expresión de sorpresa o curiosidad, texto de máximo 4-5 palabras en grande, número llamativo si el vídeo habla de una cantidad concreta, color de fondo que contraste con el rojo de YouTube), plantilla de miniatura en Figma con las capas organizadas para que el creador solo tenga que cambiar el texto y la foto, sistema de variaciones de miniatura para los diferentes tipos de vídeo (tutorial: miniatura tipo, análisis de mercado: miniatura tipo, entrevista: miniatura tipo), proceso de A/B testing de miniaturas en YouTube Studio para identificar qué estilo genera más clics y directrices de fotografía del creador para las miniaturas (fondo neutro, iluminación, expresión facial, composición).

5. Diseño para redes sociales y formatos cortos: El canal debe ser coherente en Instagram, TikTok y LinkedIn. Diseña el sistema. Incluye: adaptación de la identidad visual a los formatos verticales de Instagram Reels y TikTok (cómo el brand package de 16:9 se adapta al 9:16 sin perder coherencia), sistema de overlays para los Reels y TikToks (el texto que aparece en pantalla para hacer accesible el contenido con el sonido apagado, diseñado con la tipografía del sistema de identidad), plantillas de stories para las preguntas, encuestas y promociones de nuevos vídeos (en Canva Pro o en Figma para que el creador las pueda editar sin necesitar a un diseñador), sistema de posts estáticos para Instagram y LinkedIn (carruseles educativos con la identidad visual del canal) y sistema de miniaturas para los Shorts de YouTube (que son cuadradas, no rectangulares).

6. Guía de marca para producción autónoma: El creador necesita poder aplicar el sistema sin depender del diseñador. Diseña la guía. Incluye: brand guidelines simplificadas (documento de 15-20 páginas con los elementos clave del sistema visual, los usos correctos e incorrectos y los valores de los colores en HEX y RGB), kit de plantillas en Canva Pro para que el creador pueda crear las piezas más frecuentes sin software de diseño avanzado (miniaturas, posts de Instagram, stories de countdown), guía de uso de las fuentes (cómo instalarlas en Canva, en Premiere y en After Effects) y plantillas de After Effects parametrizadas (el creador solo escribe el texto y el sistema aplica la animación correcta automáticamente).

7. Uso de la IA en el proceso de diseño audiovisual: La IA accelera cada fase del proceso creativo. Diseña el sistema de trabajo. Incluye: uso de IA generativa para crear las imágenes de fondo y los elementos gráficos de las infografías (Midjourney, Adobe Firefly: cómo escribir prompts que generan imágenes coherentes con la identidad visual del canal), uso de IA para la creación de variaciones de la miniatura (generar 5 versiones diferentes de la miniatura de un vídeo en cuestión de minutos con diferentes composiciones), uso de IA para la animación (Runway ML para animar elementos estáticos, Adobe Animate con IA para acelerar el rigging de personajes) y sistema de gestión de los activos del brand package (cómo organizar los archivos del sistema visual para que cualquier colaborador futuro pueda encontrar y usar correctamente los elementos de la identidad).

Incluye ejemplos de briefings creativos para el sistema visual, especificaciones técnicas del brand package de After Effects y guía simplificada de la identidad visual para el creador autónomo.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Sistema de identidad visual completo para canal de YouTube de educación financiera con 380.000 suscriptores',
                'vote_score'       => 40,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Ventas de producciones audiovisuales y servicios de vídeo corporativo con IA',
                'description'      => 'Domina la venta consultiva de producciones audiovisuales, servicios de vídeo corporativo y soluciones de contenido en vídeo a empresas, usando IA para agilizar propuestas y mejorar la conversión.',
                'prompt_content'   => <<<'EOT'
Eres un director comercial especializado en la venta de producciones audiovisuales y servicios de vídeo para empresas. Tu agencia de producción de vídeo lleva 8 años produciendo vídeos corporativos, spots publicitarios, vídeos de formación, contenido para redes sociales y eventos híbridos. Sabes que la venta de producciones audiovisuales es una venta consultiva donde hay que entender los objetivos de comunicación del cliente antes de hablar de formatos y presupuestos, y donde la confianza creativa es el principal diferenciador frente a la competencia.

Contexto de la agencia:
- Agencia de producción audiovisual con 22 personas (12 técnicos y creativos, 5 comerciales, 5 de gestión)
- Facturación actual: 2,8 millones de euros anuales
- Servicios: vídeo corporativo, spots de TV y plataformas digitales, vídeos de formación e-learning, retransmisiones de eventos en directo, motion graphics y animación
- Clientes habituales: departamentos de marketing y comunicación de empresas medianas y grandes, agencias de publicidad que subcontratan la producción
- Objetivo: crecer a 4 millones en 2 años, especialmente en los segmentos de mayor margen: formación corporativa en vídeo y retransmisiones de eventos

Desarrolla el sistema completo de ventas de servicios audiovisuales:

1. Proceso de venta consultiva en producción audiovisual: La venta de vídeo empieza mucho antes de hablar de precios. Diseña el proceso. Incluye: discovery call con el cliente potencial (qué preguntas hacerle para entender sus objetivos de comunicación, su audiencia objetivo, sus experiencias previas con producciones y sus métricas de éxito: ¿qué tiene que pasar después de ver este vídeo para que consideres que ha funcionado?), análisis del brief del cliente y de lo que hay detrás del brief (el cliente pide "un vídeo corporativo de empresa", pero lo que realmente necesita es convencer a sus posibles empleados de que su empresa es un buen lugar para trabajar: cómo identificar la necesidad real), elaboración de la propuesta creativa y económica (no sólo el presupuesto sino también la propuesta conceptual que demuestra que has entendido lo que el cliente necesita), presentación de la propuesta al cliente (de forma oral, cómo narrar el concepto creativo antes de mostrar el número del presupuesto) y proceso de negociación cuando el cliente pide reducir el presupuesto (qué se puede reducir sin comprometer la calidad y qué no).

2. Gestión de diferentes tipos de cliente y proyecto: La agencia atiende perfiles de cliente muy diferentes. Diseña el sistema. Incluye: diferencias en el proceso de venta según el interlocutor (CMO que aprueba presupuesto grande: necesita ver el impacto en negocio; responsable de comunicación interna que aprueba formación en vídeo: necesita ver cómo mejora la retención del conocimiento; director de eventos que organiza un congreso: necesita ver cómo el vídeo multiplica la audiencia del evento), adaptación de la propuesta comercial para las agencias de publicidad que contratan producción (son un cliente muy diferente al cliente final: conocen el sector, negocian más duro el precio, exigen plazos más cortos), propuesta de valor diferenciada para el segmento de formación corporativa en vídeo (cómo posicionarse frente a plataformas de microlearning como Coursera for Business que no hacen producción a medida) y gestión de los presupuestos de producción de eventos en directo (cómo hacer la propuesta para la retransmisión de un evento cuando todavía no se conocen todos los detalles del evento).

3. Pricing de servicios audiovisuales: El precio es uno de los puntos más difíciles en la venta de producciones. Diseña el modelo. Incluye: metodología de pricing de producciones audiovisuales (cómo calcular el coste real de una producción sumando equipo técnico, días de rodaje, postproducción, música, actores, localizaciones, permisos y margen de la agencia), cómo comunicar el precio al cliente de forma que lo perciba como una inversión y no como un gasto (asociar el precio al valor que genera: ROI esperado, coste de la alternativa, comparativa con otros medios de comunicación), estrategia de pricing diferenciado por tipo de proyecto y por segmento de cliente (precio unitario por proyecto one-shot vs. acuerdo anual de producción de contenidos vs. suscripción de contenido mensual), gestión de los presupuestos cerrados que luego se desbordan (por cambios del cliente, por imprevistos técnicos: cómo gestionar el extra y la conversación con el cliente) y modelo de comparación de precios cuando el cliente recibe propuestas de 3 agencias y la tuya no es la más barata.

4. Venta de acuerdos de producción recurrente: Los acuerdos anuales son el mejor negocio para la agencia. Diseña la estrategia. Incluye: proceso de transformación de un cliente one-shot en un cliente recurrente (qué ofrecerle después de la primera producción para que siga contratando, cómo estructurar el seguimiento post-entrega de la primera producción), diseño de los paquetes de producción anual (pack mensual de contenido para redes sociales: X vídeos de X segundos al mes a precio fijo; acuerdo de producción anual del evento corporativo más una producción trimestral de contenido de marca), argumentario para justificar el acuerdo anual frente al presupuesto por proyecto (el cliente obtiene precio fijo predecible, prioridad de agenda en temporadas de alta demanda, acumulación de conocimiento de la agencia sobre la marca a lo largo del tiempo) y proceso de revisión y renovación del acuerdo anual.

5. Uso de la IA en el proceso de ventas: La IA puede acelerar significativamente el ciclo de ventas. Diseña el sistema. Incluye: uso de Claude para el análisis del brief del cliente (identificar las necesidades reales detrás de la petición, sugerir enfoques creativos alternativos, identificar riesgos del proyecto que hay que aclarar antes de presupuestar), generación de propuestas comerciales más rápidas con IA (borrador de la propuesta conceptual a partir del brief y de la base de datos de producciones anteriores de la agencia), uso de IA para la investigación del cliente antes de la reunión (análisis de su presencia digital, sus vídeos actuales, sus competidores, su público objetivo: qué hacer antes de la primera llamada), generación de presupuestos más precisos con IA (a partir de los datos históricos de producciones similares, el sistema sugiere el desglose de costes y detecta partidas que podrían olvidarse) y sistema de seguimiento de propuestas con IA (alertas cuando una propuesta lleva demasiado tiempo sin respuesta, sugerencia del mejor momento para hacer el follow-up).

6. Gestión de las relaciones con agencias de publicidad: Las agencias son el canal de negocio más rentable si se gestionan bien. Diseña la estrategia. Incluye: mapeo de las agencias de publicidad integradas y creativas en España que subcontratan producción y cuáles son las que mejor encajan con el perfil de la agencia audiovisual, proceso de presentación de la agencia a las agencias de publicidad (cuándo hacer el pitch a una agencia, cómo demostrar la capacidad técnica y la fiabilidad en los plazos que una agencia de publicidad necesita), modelo de condiciones para agencias (precio de agencia más competitivo a cambio de un compromiso de volumen mínimo anual, proceso de crédito para evitar el riesgo de impago en producciones de gran presupuesto), gestión de los conflictos cuando la agencia pide cambios que superan el presupuesto acordado y sistema de medición de la rentabilidad de las agencias como canal de captación.

7. KPIs y gestión del pipeline de ventas: Define el sistema de gestión comercial. Incluye: KPIs del equipo comercial de la agencia audiovisual (número de propuestas enviadas mensualmente, tasa de conversión de propuesta a pedido, ticket medio por tipo de proyecto, número de clientes recurrentes vs. one-shot, revenue mensual por comercial), sistema de CRM para la gestión del pipeline de producciones (qué información registrar de cada oportunidad, cómo clasificar el estado de cada propuesta, cómo forecastar los ingresos del próximo trimestre) y proceso de reunión semanal del equipo comercial (qué revisar, qué decisiones se toman, cómo gestionar las propuestas bloqueadas).

Incluye plantilla de propuesta audiovisual con sección creativa y económica, guion de discovery call con cliente nuevo y modelo de acuerdo anual de producción de contenidos. Todo orientado a agencias de producción audiovisual que venden principalmente a departamentos de marketing de empresas.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Crecimiento de agencia de producción audiovisual de 2,8 a 4 millones mediante venta consultiva y acuerdos de producción recurrente',
                'vote_score'       => 39,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Gestión de producto en plataformas de contenido audiovisual y herramientas de creación de vídeo con IA',
                'description'      => 'Define y desarrolla productos digitales para creadores de contenido audiovisual y consumidores de vídeo, aplicando metodologías de producto en un sector donde la IA generativa está transformando radicalmente la creación y la distribución.',
                'prompt_content'   => <<<'EOT'
Eres un product manager con especialización en plataformas de contenido audiovisual y herramientas de creación de vídeo. Has trabajado en empresas de media technology y en startups de creator economy, y entiendes tanto las necesidades del creador de contenido como las del consumidor de vídeo. Sabes que el sector audiovisual está siendo radicalmente transformado por la IA: las barreras de producción están cayendo, la cantidad de contenido se está multiplicando y las plataformas necesitan diferenciarse para retener tanto a los creadores como a sus audiencias.

Contexto de la empresa:
- Startup española de herramientas de edición de vídeo asistida por IA para creadores de contenido
- Producto actual: aplicación web de edición de vídeo que usa IA para transcribir automáticamente el vídeo, permitir editar el vídeo editando el texto de la transcripción, y generar clips cortos automáticamente a partir del vídeo largo
- Métricas actuales: 28.000 usuarios registrados, 4.200 usuarios activos mensuales, revenue de 85.000 euros mensuales (modelo freemium con plan Pro de 29€/mes)
- Objetivo: llegar a 500.000 usuarios registrados y 1,5 millones de euros de revenue mensual en 24 meses
- Reto: hay varios competidores financiados con más recursos (Descript, Opus Clip, Kapwing) y hay que diferenciarse antes de que lleguen al mercado español con agresividad

Desarrolla la estrategia completa de gestión de producto:

1. Estrategia de producto y diferenciación competitiva: En un mercado con competidores bien financiados, la diferenciación es clave. Diseña la estrategia. Incluye: análisis de la posición competitiva actual (mapa de fortalezas y debilidades de la app vs. Descript, Opus Clip, Kapwing, Adobe Premiere con IA: en qué dimensiones está por encima, en cuáles está por debajo, qué nichos no están siendo bien servidos por ningún competidor), identificación del Ideal Customer Profile (ICP) más rentable (de los 4.200 usuarios activos mensuales, cuáles generan más revenue, tienen mayor retención y más posibilidades de expansión: creadores de YouTube, podcasters, creadores corporativos, profesores), estrategia de posicionamiento para el mercado hispanohablante (idioma español como ventaja competitiva real: la transcripción y edición en español es mejor que en los competidores americanos), definición de las 3 apuestas de producto para los próximos 18 meses que crearán una ventaja competitiva difícil de replicar y roadmap de alto nivel alineado con la estrategia de diferenciación.

2. Investigación de usuarios y descubrimiento de oportunidades: El product discovery es la base de buenas decisiones de producto. Diseña el proceso. Incluye: metodología de research con los diferentes segmentos de usuarios (entrevistas de descubrimiento con usuarios activos de alto valor, análisis de las sesiones de uso para identificar los puntos de fricción, análisis de las peticiones de funcionalidades para identificar patrones), sistema de feedback continuo de usuarios (encuestas in-app en momentos clave del journey, canal de Discord o Slack para los usuarios más comprometidos, programa de beta testers), análisis de las razones de churn de los usuarios que cancelan el plan Pro (qué dicen en la encuesta de cancelación, qué comportamiento tuvieron en la aplicación en las semanas previas a cancelar), análisis de los usuarios que están en el plan gratuito y no convierten a Pro (qué les impide pagar, qué funcionalidad sería el trigger para la conversión) y proceso de síntesis de insights de research para el equipo de producto.

3. Roadmap y priorización de funcionalidades: El equipo de producto tiene capacidad limitada. Diseña el sistema de priorización. Incluye: framework de priorización adaptado para una startup de producto (RICE: Reach × Impact × Confidence ÷ Effort; con ajuste por alineación estratégica), proceso de priorización participativo con los stakeholders (cómo involucrar al equipo de ventas, al de customer success y al de ingeniería sin que el roadmap se convierta en una lista de peticiones sin criterio), gestión de las funcionalidades solicitadas por los usuarios vs. las apuestas estratégicas de producto (cómo equilibrar el trabajo reactivo de mejoras pedidas con el trabajo proactivo de diferenciación estratégica), proceso de comunicación del roadmap a los usuarios (qué compartir públicamente, qué mantener confidencial, cómo gestionar las expectativas cuando una funcionalidad prometida se retrasa) y gestión de la deuda técnica en el roadmap.

4. Diseño de las funcionalidades clave de IA: La IA es el diferenciador central del producto. Define las próximas 3 funcionalidades de IA. Para cada funcionalidad incluye: descripción del caso de uso (qué problema del creador resuelve), especificación funcional detallada (qué hace exactamente la funcionalidad, cómo interactúa el usuario con ella, cuáles son los inputs y los outputs), modelo de ML o de IA que está detrás (qué tecnología se usaría: fine-tuning de Whisper para español con jerga de diferentes sectores, modelos de detección de momentos clave en vídeo, generación de thumbnails con modelos de imagen), métricas de éxito (cómo sabemos que la funcionalidad ha funcionado: tasa de adopción, impacto en la retención, impacto en la conversión a Pro) y criterios de calidad mínima antes del lanzamiento. Propón al menos estas tres funcionalidades: detección automática de momentos virales en el vídeo largo para recortar Shorts, generación automática de miniaturas de YouTube con el branding del canal, y herramienta de doblaje automático del vídeo a otros idiomas.

5. Monetización y modelo de negocio: Para crecer de 85.000 a 1,5 millones de revenue mensual hay que optimizar la monetización. Diseña el sistema. Incluye: análisis del embudo de conversión actual (tasa de registro → activación del usuario → conversión a Pro → retención en Pro a 3 meses y 12 meses) e identificación de los mayores puntos de fuga, optimización del plan freemium (qué funcionalidades dejar en el plan gratuito para que los usuarios vean el valor del producto, cuáles mover al plan Pro para que sea el trigger de conversión), diseño del plan de Teams para creadores con equipo o agencias de contenido (precio por puesto, funcionalidades de colaboración, proceso de facturación), estrategia de upsell y expansión de los usuarios Pro actuales (créditos de IA adicionales, almacenamiento extra, funcionalidades premium) y análisis de si un modelo de marketplace (donde los creadores venden plantillas o presets a otros usuarios) puede ser una fuente adicional de ingresos.

6. Growth y adquisición de usuarios: Para ir de 28.000 a 500.000 usuarios registrados. Diseña la estrategia de crecimiento. Incluye: análisis de los canales de adquisición más eficientes para una herramienta de creación de vídeo dirigida a creadores de contenido en español (YouTube: demos de la herramienta en acción; TikTok y Reels: vídeos "antes y después" de la edición con la herramienta; SEO: artículos y vídeos sobre la edición de vídeo con IA, comunidades de creadores en Discord y Telegram), diseño del programa de referidos para la comunidad de creadores (qué incentivo hace que un creador recomiende la herramienta a sus colegas), estrategia de integraciones con otras herramientas del stack del creador (integración con YouTube Studio, TikTok Creator Center, Notion, Riverside.fm) para llegar a los usuarios en las herramientas que ya usan y estrategia de partnerships con escuelas de creadores de contenido y programas de formación de YouTube.

7. Métricas de producto y OKRs: Define el sistema de medición. Incluye: North Star Metric del producto (la métrica que mejor captura el valor que el producto entrega a los usuarios: horas de vídeo editadas mensualmente, número de clips publicados desde la plataforma, minutos de creador ahorrados por IA) y por qué es la correcta, árbol de métricas que descompone la North Star Metric en métricas de input accionables (acquisition → activation → retention → revenue → referral), OKRs trimestrales de producto alineados con los objetivos de negocio (llegar a X usuarios activos, aumentar la retención a 30 días al Y%) y proceso de revisión semanal de métricas con el equipo de producto.

Incluye plantilla de brief de funcionalidad de IA, framework de priorización de roadmap y modelo de embudo de conversión para herramientas SaaS de creadores. Todo orientado a startups de creator economy en el mercado hispanohablante.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Escalado de startup de herramientas de edición de vídeo con IA de 85K a 1,5M de revenue mensual en el mercado hispanohablante',
                'vote_score'       => 52,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión de equipos creativos en producción audiovisual y gestión del talento técnico con IA',
                'description'      => 'Lidera equipos de directores, cámaras, editores y creativos en la industria audiovisual, gestionando su desarrollo profesional en un sector que está siendo transformado por la IA generativa de vídeo.',
                'prompt_content'   => <<<'EOT'
Eres un director creativo y de Recursos Humanos con especialización en la industria audiovisual. Llevas años gestionando equipos de producción en agencias de publicidad, cadenas de televisión y empresas de producción de contenido, y en los últimos años te has enfrentado al reto de gestionar la transformación del sector por la irrupción de la IA generativa de vídeo. Sabes que la IA está cambiando los roles, los flujos de trabajo y las competencias necesarias, y que gestionar ese cambio sin perder el talento creativo humano es el mayor desafío del sector.

Contexto de la empresa:
- Productora audiovisual con 65 personas especializadas en contenido para redes sociales, publicidad digital y vídeos corporativos
- Equipo creativo: 8 directores creativos, 15 editores de vídeo, 10 cámaras y operadores, 12 motion graphics y animadores, 8 productores, 12 de operaciones y gestión
- Problema principal: la irrupción de herramientas de IA de vídeo (Runway, Sora, Kling, Pika) está generando incertidumbre y resistencia en el equipo técnico, que teme que la IA reemplace sus puestos de trabajo
- Segundo problema: los clientes empiezan a pedir más contenido por el mismo presupuesto, presionando para que la productora use IA para reducir costes, mientras el equipo creativo percibe esto como una amenaza a la calidad
- Tercer problema: la rotación es alta en el equipo de edición (30% anual), principalmente porque los mejores editores se van a trabajar de forma freelance o a las plataformas

Desarrolla la estrategia completa de gestión del equipo creativo en la transición digital:

1. Diagnóstico del impacto de la IA en los roles del equipo: Antes de gestionar el cambio, hay que entenderlo. Diseña el proceso. Incluye: análisis del impacto de la IA en cada rol de la productora (qué tareas de cada perfil puede automatizar la IA hoy, cuáles en 2 años, cuáles difícilmente: editor de vídeo: la IA puede hacer el rough cut pero no la edición emocional final; cámara: la IA puede generar B-roll pero no la dirección de actores; motion graphics: la IA puede crear elementos gráficos básicos pero no los sistemas de identidad visual complejos), comunicación honesta con el equipo sobre el impacto de la IA (qué decirle al equipo en una reunión sobre el futuro de sus roles: cómo ser honesto sin generar pánico, cómo explicar qué va a cambiar y qué no), análisis de las habilidades del equipo actual y los gaps respecto a las competencias de IA que se necesitarán y modelo de evolución de los roles (el "editor de vídeo" del futuro es el "editor de vídeo con IA": qué hace diferente, cómo se llama el nuevo rol).

2. Plan de formación en herramientas de IA para el equipo creativo: El equipo tiene que aprender a trabajar con IA sin sentirlo como una amenaza. Diseña el plan. Incluye: programa de formación en herramientas de IA para cada perfil del equipo (editores: Runway, Adobe Premiere con IA, Descript; motion graphics: Midjourney, Adobe Firefly, After Effects con IA; cámaras y directores: IA para el storyboarding y el scouting de localizaciones; productores: IA para la gestión de proyectos y el presupuesto), formato de la formación que maximiza la adopción (formación práctica con proyectos reales de clientes, no formación teórica; sesiones cortas de 2 horas en grupos pequeños; mentoring entre compañeros donde los que ya usan la herramienta forman a los que no), gestión de la resistencia a la formación en IA de los profesionales con más experiencia (los directores creativos sénior suelen ser los más resistentes), sistema de incentivos para la adopción de las herramientas de IA (cómo premiar a los que se convierten en early adopters dentro del equipo) y proceso de evaluación del nivel de adopción de las herramientas de IA por parte del equipo.

3. Redefinición de los flujos de trabajo de producción con IA: La IA no reemplaza al equipo, cambia cómo trabaja. Diseña los nuevos flujos. Incluye: nuevo flujo de trabajo de la edición de vídeo con IA (rough cut automatizado con IA como primer paso, seguido de la edición creativa y emocional del editor humano: cómo cambia el tiempo dedicado a cada fase y cómo mejora la capacidad de producción), nuevo flujo de trabajo para la producción de contenido para redes sociales (la IA genera 20 variaciones del clip de redes a partir del vídeo largo, el editor selecciona y afina las mejores 3: de cuánto tiempo te ahorras), nuevo flujo de trabajo para el motion graphics con IA (generación de los elementos gráficos de baja complejidad con IA, liberando al equipo de motion para el trabajo de mayor valor creativo) y proceso de integración de los nuevos flujos de trabajo en los proyectos de clientes (cómo presentar al cliente que el equipo usa IA sin que perciba una reducción en el nivel de implicación).

4. Gestión de la tensión entre productividad y calidad creativa: Los clientes quieren más por menos, pero el equipo defiende la calidad. Diseña el sistema. Incluye: marco conceptual para la discusión interna sobre el uso de la IA en los proyectos de clientes (cuándo usar IA para ahorrar tiempo y cuándo el proyecto requiere trabajo 100% humano: una campaña de marca de gran presupuesto vs. un vídeo de producto estándar), proceso de pricing de los proyectos que usan IA (¿el cliente paga lo mismo si la IA hace parte del trabajo? ¿se traduce el ahorro de tiempo en un margen mayor para la productora o en un precio más bajo para el cliente?), política de transparencia con el cliente sobre el uso de la IA (¿hay que decirle al cliente que el B-roll fue generado con IA? ¿y la voz en off? ¿dónde está el límite ético?) y gestión del equipo cuando un cliente pide reducir el presupuesto apelando a que "la IA lo puede hacer más barato".

5. Retención del talento creativo en el equipo: La rotación del 30% en edición es un problema grave. Diseña la estrategia. Incluye: investigación de las causas reales de la alta rotación en el equipo de edición (qué dicen los editores que se van en las entrevistas de salida: ¿es el salario, la variedad de proyectos, la forma de trabajar, la falta de desarrollo creativo, la dificultad de trabajar para clientes corporativos sin libertad creativa?), propuesta de valor para retener a los mejores editores frente a la opción freelance (qué puede ofrecer la productora que el freelancing no puede: estabilidad, acceso a proyectos de mayor presupuesto, trabajo en equipo, equipamiento de alta gama, formación continua en IA), plan de carrera para el perfil de editor de vídeo dentro de la productora (cómo puede crecer: editor junior → editor → editor sénior → director de postproducción → responsable técnico de IA) y sistema de reconocimiento del trabajo creativo del equipo (cómo celebrar los proyectos que quedan bien, cómo dar visibilidad al trabajo del equipo en el portfolio y en las redes sociales de la productora).

6. Gestión del equipo freelance como parte del equipo: La productora trabaja habitualmente con freelancers. Diseña el sistema. Incluye: modelo de relación con la red de freelancers (directores de fotografía, actores, locutores, compositores de música: cómo gestionar su disponibilidad, cómo integrarlos en los proyectos, cómo asegurar que conocen y pueden usar las herramientas de IA que la productora utiliza), proceso de incorporación de nuevos freelancers a la red (criterios de selección, proyecto piloto de evaluación, onboarding en las herramientas y los procesos de la productora), política de rates para los freelancers en la era de la IA (¿cambia el rate de un editor freelance cuando parte del trabajo lo hace la IA? ¿cómo evitar la carrera hacia abajo en los precios?) y gestión de los conflictos entre el equipo fijo y el equipo freelance.

7. Cultura creativa e innovación en la producción audiovisual: La cultura creativa es el activo más difícil de replicar. Diseña la estrategia. Incluye: rituales de equipo que construyen la cultura creativa (reunión de inspiración semanal donde alguien presenta un vídeo, una película o una campaña que le ha impresionado y por qué; proyecto interno mensual donde el equipo tiene total libertad creativa; exhibición trimestral de los mejores trabajos del período), proceso de experimentación con nuevas herramientas de IA dentro de la productora (cómo animar al equipo a probar nuevas herramientas en proyectos internos antes de usarlas con clientes) y política de participación del equipo en proyectos pro-bono para organizaciones sin ánimo de lucro (que mantiene el compromiso creativo del equipo y genera portfolio de trabajos de mayor libertad artística).

Incluye plantilla del plan de formación en IA para equipos creativos audiovisuales, guía de conversación sobre el impacto de la IA con el equipo y política de uso de IA en los proyectos de clientes. Todo orientado a productoras audiovisuales en el contexto de transformación del sector.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Gestión del cambio y formación en IA para equipos creativos de una productora audiovisual con alta resistencia interna',
                'vote_score'       => 41,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Control financiero y rentabilidad en producciones audiovisuales con IA',
                'description'      => 'Gestiona el presupuesto y la rentabilidad de producciones audiovisuales complejas usando IA para el seguimiento de costes en tiempo real, la detección de desviaciones y la toma de decisiones financieras durante la producción.',
                'prompt_content'   => <<<'EOT'
Eres un director financiero y controller especializado en la industria audiovisual y en la producción cinematográfica y televisiva. Llevas años gestionando los presupuestos y el control de costes de producciones audiovisuales de diferente envergadura: desde spots publicitarios de presupuesto medio hasta series de televisión para plataformas internacionales. Conoces las particularidades financieras del sector audiovisual: los presupuestos se cierran antes de saber exactamente cómo va a evolucionar el rodaje, los costes pueden dispararse por imprevistos técnicos o climáticos, y los modelos de negocio son complejos (venta de derechos, licencias, coproducción, financiación pública con subvenciones y créditos fiscales).

Contexto de la empresa:
- Productora audiovisual con 3,5 millones de euros de facturación anual
- Portfolio de proyectos: 4-6 producciones simultáneas de diferente presupuesto (spots: 50K-200K; vídeos corporativos: 10K-80K; series cortas para plataformas: 300K-800K)
- Problema financiero principal: los proyectos tienen una tasa de desviación presupuestaria del 22% de media (los proyectos acaban costando un 22% más de lo presupuestado originalmente)
- Segundo problema: el cash flow es muy tenso porque los clientes pagan a 60-90 días y los proveedores y el equipo técnico deben pagarse antes o durante el rodaje
- Objetivo: reducir la desviación presupuestaria al 8% y mejorar el cash flow mediante una mejor planificación financiera

Desarrolla el sistema completo de control financiero de producciones audiovisuales:

1. Metodología de presupuestación de producciones: El presupuesto se establece antes de conocer todos los detalles. Diseña el sistema. Incluye: estructura del presupuesto de una producción audiovisual (capítulos: guion y derechos, producción, equipo artístico, equipo técnico, equipo de producción, maquinaria y equipamiento técnico, escenografía y ambientación, vestuario, viajes y dietas, postproducción, música, gastos generales, margen de riesgo y contingencia), metodología de estimación de los costes cuando el proyecto aún está en fase de desarrollo (cómo estimar el coste de un rodaje de 5 días con un equipo de 20 personas cuando todavía no se conoce la localización exacta ni el elenco), sistema de rangos de presupuesto por tipo de producción (basado en el histórico de producciones anteriores: qué coste unitario típico tiene un día de rodaje en el exterior con equipo cinematográfico, cuánto cuesta un actor de nivel medio en España por día de trabajo) y cuándo y cómo incluir la contingencia (qué porcentaje del presupuesto reservar para imprevistos según el tipo de producción y el nivel de incertidumbre).

2. Sistema de seguimiento de costes en tiempo real durante la producción: El control del gasto durante el rodaje es crítico. Diseña el sistema. Incluye: proceso de registro de gastos diarios durante el rodaje (quién registra, en qué herramienta, con qué nivel de detalle, con qué proceso de aprobación), sistema de alerta temprana cuando el gasto diario supera el presupuesto planificado (dashboard de producción que muestra el coste real acumulado vs. el presupuesto planificado en tiempo real), proceso de "daily cost report" del director de producción al productor ejecutivo y al director financiero (qué información incluye el informe diario de costes, quién lo firma, qué decisiones se toman a partir de él), uso de IA para el análisis de las desviaciones presupuestarias (identificar automáticamente las partidas con mayor desviación y proyectar el coste final del proyecto a partir del ritmo de gasto actual) y proceso de decisión cuando la producción se está desviando del presupuesto (qué se puede recortar sin comprometer la calidad, cuándo hablar con el cliente sobre el problema presupuestario).

3. Análisis de la rentabilidad por proyecto y por tipo de producción: No todos los proyectos son igual de rentables. Diseña el sistema. Incluye: modelo de análisis de rentabilidad por proyecto (ingresos del proyecto: cuánto paga el cliente; costes del proyecto: todos los costes directos incluyendo el tiempo del equipo interno; margen de contribución del proyecto; margen neto después de repartir los costes generales de la productora), análisis de la rentabilidad por tipo de producción (spots publicitarios, vídeos corporativos, series: cuál genera más margen en términos absolutos y cuál tiene mayor margen porcentual), análisis de la rentabilidad por cliente (cuáles son los clientes más rentables considerando el ciclo de vida completo de la relación, no solo el proyecto individual) y proceso de pricing de futuros proyectos basado en el análisis de rentabilidad histórico.

4. Gestión del cash flow en la industria audiovisual: El cash flow es el mayor problema financiero de las productoras. Diseña el sistema. Incluye: modelo de planificación del cash flow de la productora con proyección a 6 meses (cuándo se van a cobrar los proyectos en curso, cuándo se van a pagar las facturas de los proveedores, cuál es el saldo de tesorería previsto en cada momento), negociación de las condiciones de pago con los clientes (cómo justificar el pago por fases vinculado a los hitos de la producción: 30% al inicio, 40% al inicio del rodaje, 30% a la entrega de los materiales definitivos), gestión del pago a los freelancers y proveedores durante la producción (cuándo pagar en efectivo, cuándo negociar pagos diferidos, qué gastos son impostergables y cuáles pueden aplazarse) y uso de instrumentos financieros para cubrir los desfases de liquidez (líneas de crédito, factoring de las facturas de los clientes, anticipo de subvenciones).

5. Financiación de proyectos audiovisuales: El audiovisual tiene acceso a fuentes de financiación específicas. Diseña el análisis. Incluye: subvenciones públicas para la producción audiovisual en España (Instituto de Cinematografía y de las Artes Audiovisuales - ICAA, fondos autonómicos de producción audiovisual: cuáles existen, a qué tipo de producción aplican, cuál es el proceso de solicitud), créditos fiscales para la producción audiovisual (deducción del 30% en el Impuesto sobre Sociedades para producciones cinematográficas y series: requisitos, límites, cómo gestionar el tax credit como instrumento de financiación vendiendo el crédito fiscal a un inversor financiero), coproducción internacional (cómo estructurar una coproducción con una empresa extranjera para acceder a financiación pública de otro país) y plataformas de streaming como financiadores (cómo negociar contratos de presupuesto con Netflix, HBO o Amazon para producciones españolas: qué porcentaje del presupuesto suelen adelantar, en qué condiciones, qué derechos se ceden).

6. Código Python para el control financiero de producciones: Proporciona implementaciones concretas de: (a) modelo de presupuesto de producción en pandas con desglose por capítulos y con seguimiento del gasto real vs. planificado actualizado diariamente, (b) función de proyección del coste final del proyecto basada en el ritmo de gasto actual (estimación del coste a la finalización: EAC - Estimate at Completion), (c) dashboard de rentabilidad por proyecto con matplotlib que muestra el margen de contribución de cada proyecto en comparación con el objetivo de margen de la productora y (d) modelo de cash flow de la productora con proyección a 6 meses basado en los proyectos en cartera, los cobros previstos y los pagos comprometidos.

7. Reporting financiero de la industria audiovisual: La dirección y los inversores necesitan una visión clara del negocio. Diseña el sistema. Incluye: informe mensual de resultados de la productora (facturación por tipo de producción, margen de contribución por proyecto y global, estado del cash flow, pipeline de proyectos en desarrollo), informe de rentabilidad de los proyectos cerrados en el trimestre con análisis de las desviaciones y lecciones aprendidas para la presupuestación de proyectos futuros y proceso de análisis del break-even de la productora (cuánta facturación necesita generar cada mes para cubrir sus costes fijos y empezar a generar beneficio).

Incluye plantilla de presupuesto de producción audiovisual, modelo de cash flow para productoras y sistema de alertas de desviación presupuestaria en Excel. Todo adaptado a la industria audiovisual española.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Reducción de la desviación presupuestaria del 22% al 8% en una productora audiovisual con sistema de control de costes en tiempo real',
                'vote_score'       => 50,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Derechos de autor y licencias en producción audiovisual con IA: marco legal completo',
                'description'      => 'Navega el complejo marco de la propiedad intelectual en la producción audiovisual, desde los derechos de los autores hasta las licencias de música y la nueva regulación de la IA generativa de contenido audiovisual.',
                'prompt_content'   => <<<'EOT'
Eres un abogado especializado en propiedad intelectual con expertise en la industria audiovisual. Llevas años asesorando a productoras cinematográficas, canales de televisión, plataformas de streaming, agencias de publicidad y creadores de contenido digital sobre los derechos de autor, las licencias de contenido, los contratos con el equipo artístico y técnico y los nuevos retos legales que plantea la IA generativa en la creación de contenido audiovisual. Conoces en profundidad la Ley de Propiedad Intelectual española, la Directiva sobre derechos de autor en el mercado único digital y la regulación emergente de la IA en el sector creativo.

Contexto de la consulta legal:
- Productora audiovisual española que produce contenido para empresas (vídeos corporativos, publicidad), para plataformas (series cortas), y para creadores de contenido (edición y postproducción)
- Situación: la productora está empezando a incorporar herramientas de IA generativa (Runway, Sora, Midjourney para imágenes, ElevenLabs para voz) en sus producciones y necesita entender el marco legal completo de su uso
- Problema adicional: han tenido una reclamación de un compositor por el uso de música en un vídeo publicado en YouTube y no están seguros de si sus contratos con el equipo creativo ceden bien los derechos a la productora
- Necesidad: revisión completa del marco de propiedad intelectual de la productora

Desarrolla el análisis legal completo:

1. Derechos de autor en la producción audiovisual: La obra audiovisual tiene un régimen especial de propiedad intelectual. Explica en detalle: quiénes son los autores de una obra audiovisual según la Ley de Propiedad Intelectual española (director, guionista, compositor de la música original: los tres autores presuntos del artículo 87 de la LPI) y cuáles son sus derechos específicos, diferencia entre derechos morales (inalienables: derecho a ser reconocido como autor, derecho de integridad de la obra) y derechos patrimoniales (cedibles: reproducción, distribución, comunicación pública, transformación) en el contexto audiovisual, régimen de la cesión de derechos en los contratos de producción (qué derechos deben ceder los autores a la productora, en qué condiciones, por cuánto tiempo y para qué territorio) y derechos de los intérpretes y ejecutantes en el audiovisual (actores, dobladores, músicos: qué derechos tienen sobre la obra que interpretan y cuándo requieren autorización adicional para la reutilización de su interpretación).

2. Licencias de música en producciones audiovisuales: La música es la fuente de problemas legales más frecuente. Diseña el análisis. Incluye: tipos de derechos que hay que licenciar para usar una canción en un vídeo (derechos de la composición: letra y música, gestionados por SGAE; derechos del fonograma: la grabación concreta, gestionados por AGEDI y AIE), proceso de licenciamiento de música para los distintos usos audiovisuales (spot publicitario: necesita una sincronización; vídeo corporativo: sincronización y masterización; vídeo de YouTube: puede cubrirse con la licencia de YouTube ContentID o requiere licencia directa), análisis del caso de la reclamación del compositor (qué pasó probablemente: el vídeo usó música sin sincronización o usó una grabación con derechos de fonograma no licenciados; qué hacer ahora para resolver la reclamación), música libre de derechos y creative commons para producciones de bajo presupuesto (qué plataformas ofrecen música bajo licencia para YouTube y para uso comercial: Epidemic Sound, Artlist, YouTube Audio Library) y creación de música original con IA (ElevenLabs, Suno, Udio: ¿quién es el autor de la música generada por IA? ¿hay derechos de autor en la música generada por IA?).

3. Contratos con el equipo creativo y técnico: Los contratos determinan quién es dueño de qué. Diseña el análisis. Incluye: análisis de los contratos estándar con el equipo técnico de una producción audiovisual (contrato de servicios del operador de cámara, del director de fotografía, del editor de vídeo: ¿estos contratos ceden automáticamente los derechos a la productora o hay que pactarlo expresamente?), cláusulas obligatorias en los contratos con los creativos (cesión de derechos de explotación con el mayor alcance posible: todas las modalidades de explotación conocidas y por conocer, todo el territorio mundial, por el tiempo máximo legal), contratos con actores y presentadores (derechos de imagen, derechos del intérprete según la LPI, cláusulas de renovación para la reutilización de las imágenes en futuras campañas) y régimen de los trabajos de empleados en la empresa (cuando el director de fotografía es empleado de la productora: la LPI establece que los derechos patrimoniales corresponden al empleador).

4. IA generativa en la producción audiovisual: los retos legales: La incorporación de IA plantea preguntas legales nuevas que todavía no tienen respuesta definitiva. Analiza: la cuestión de la autoría de las obras generadas con IA (¿quién es el autor del vídeo generado por Sora o Runway? ¿tiene protección por derechos de autor? ¿puede la productora ser titular de los derechos de una obra generada con IA?), las condiciones de uso de las principales herramientas de IA de vídeo (Runway, Pika, Sora, Kling: qué dicen sus términos de servicio sobre la titularidad de los outputs, si permite el uso comercial, si hay restricciones sobre el tipo de contenido que se puede generar), los datos de entrenamiento de los modelos de IA (¿los modelos de IA que usan la productora han sido entrenados con contenido protegido por derechos de autor sin licencia? ¿puede la productora ser responsable solidaria por las infracciones de los proveedores de IA?), el AI Act y sus implicaciones para el uso de IA en la producción audiovisual (obligaciones de transparencia cuando el contenido ha sido generado o modificado sustancialmente por IA: el deepfake disclosure, la marca de agua digital obligatoria) y cómo gestionar el riesgo legal de usar IA generativa en producciones para clientes que después distribuyen ese contenido.

5. Distribución de contenido en plataformas digitales: La distribución en YouTube, Vimeo o redes sociales tiene sus propias implicaciones legales. Diseña el análisis. Incluye: condiciones de las licencias que se otorgan a YouTube y a las redes sociales cuando se sube un vídeo (qué derechos cedes a la plataforma, qué puede hacer YouTube con tu vídeo), sistema ContentID de YouTube (cómo funciona, qué ocurre cuando un reclamante usa ContentID para reclamar los ingresos de un vídeo, cómo disputar una reclamación de ContentID incorrecta), licencias Creative Commons para la distribución de contenido audiovisual (qué tipos de licencias CC existen y cuál elegir según el tipo de producción) y gestión de los derechos territoriales en la distribución digital (si se vende el derecho de emisión en España a una cadena de televisión, ¿se puede subir simultáneamente a YouTube para distribución global?).

6. Protección del contenido audiovisual contra la infracción: La piratería y el uso no autorizado del contenido son problemas reales. Diseña el sistema de protección. Incluye: herramientas técnicas de protección del contenido audiovisual (DRM - Digital Rights Management, marcas de agua digitales visibles e invisibles, content fingerprinting), proceso de detección de usos no autorizados del contenido en internet (herramientas de monitorización: Pixsy para fotografías, TinEye para imágenes, herramientas de YouTube para vídeo, Google Alerts para el nombre de la producción), proceso de reclamación por infracción de derechos de autor en internet (DMCA takedown notice para contenido en plataformas internacionales, procedimiento de reclamación ante la SGAE o ante los tribunales españoles para infracciones en España) y cuándo vale la pena perseguir judicialmente una infracción y cuándo no (análisis coste-beneficio).

7. Derechos de imagen y privacidad en el audiovisual: El vídeo captura imágenes de personas. Diseña el marco legal. Incluye: derecho a la propia imagen (Ley Orgánica 1/1982) y cuándo se necesita autorización de las personas que aparecen en un vídeo (personas identificables en primer plano siempre necesitan autorización; personas en la vía pública en segundo plano generalmente no), régimen de consentimiento para el uso de la imagen de menores en vídeos (quién lo otorga, en qué condiciones, qué restricciones aplican al uso de la imagen de menores en publicidad y redes sociales), RGPD y grabación de vídeo (cuándo la grabación de personas constituye tratamiento de datos personales y qué obligaciones genera: registro de la actividad de tratamiento, base legal, información a los interesados) y gestión de los derechos de imagen en los contratos con los actores y los participantes en las producciones (qué cubre el contrato de caché, qué requiere autorización adicional).

Incluye checklist de derechos a verificar antes de publicar una producción audiovisual, modelo de cláusula de cesión de derechos para contratos con creativos y guía del sistema ContentID de YouTube para productoras. Todo basado en la Ley de Propiedad Intelectual española y la normativa europea vigente.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Marco legal de propiedad intelectual para productora audiovisual que incorpora IA generativa de vídeo y música en sus producciones',
                'vote_score'       => 53,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Soporte a creadores de contenido en plataformas de vídeo y streaming con IA',
                'description'      => 'Diseña un sistema de atención y customer success para creadores de contenido que monetizan en plataformas de vídeo, reduciendo el churn y aumentando el revenue mediante acompañamiento proactivo.',
                'prompt_content'   => <<<'EOT'
Eres un director de customer success especializado en el soporte a creadores de contenido en plataformas de vídeo y herramientas para la economía de los creadores. Has trabajado en plataformas de streaming, en herramientas de edición de vídeo SaaS y en agencias de gestión de canales de YouTube. Sabes que los creadores de contenido son un tipo de cliente único: son muy sensibles a la percepción de que la plataforma les apoya, necesitan feedback rápido cuando tienen un problema técnico que impide publicar contenido, y su relación con la plataforma es emocional además de transaccional.

Contexto de la plataforma:
- Plataforma SaaS de herramientas de edición de vídeo con IA para creadores de contenido en español
- Base de usuarios: 4.200 usuarios activos mensuales (1.200 de plan Pro que pagan 29€/mes, 3.000 de plan gratuito)
- Estructura del equipo de customer success: 2 personas (1 CS Manager y 1 CS Specialist), más el soporte técnico que gestiona incidencias del producto
- Problemas: tasa de churn mensual del 12% en el plan Pro (muy alta), NPS de 34 (mejorable), los creadores grandes (más de 100.000 suscriptores) no están usando la plataforma a su máxima capacidad y hay muchos creadores del plan gratuito que llevan meses sin convertir al plan Pro
- Objetivo: reducir el churn mensual al 5%, aumentar el NPS a 55 y mejorar la conversión de gratuito a Pro del 2% al 6%

Desarrolla el sistema completo de customer success para la plataforma de herramientas de vídeo:

1. Segmentación de los creadores y modelo de atención diferenciado: No todos los creadores merecen la misma atención. Diseña el modelo. Incluye: criterios de segmentación de los creadores (tamaño del canal: suscriptores y visualizaciones mensuales; nivel de actividad en la plataforma: número de vídeos editados al mes; plan de pago; potencial de crecimiento del canal; tipo de contenido: educación, entretenimiento, gaming, corporativo), modelo de atención diferenciado por segmento (creadores grandes con plan Pro: CS Manager dedicado que les hace seguimiento semanal; creadores medianos con plan Pro: CS Specialist con check-in mensual; creadores del plan gratuito: onboarding automatizado + email y soporte self-serve), identificación de los "Power Users" (los creadores más activos y más influyentes en la comunidad de creadores en español) y diseño del programa de "Creator Partners" para los creadores grandes que son evangelistas de la plataforma.

2. Onboarding para creadores del plan gratuito: El onboarding determina si el creador verá el valor de la plataforma y convertirá a Pro. Diseña el proceso. Incluye: flujo de activación de los primeros 7 días de un creador nuevo en la plataforma (día 1: email de bienvenida con el vídeo tutorial de las 3 funcionalidades más usadas; día 3: email con el tip sobre la funcionalidad de IA que más ahorra tiempo; día 5: check del progreso: ¿ha completado su primer vídeo con la herramienta?; día 7: email de invitación a la sesión de Q&A grupal semanal), milestone de activación del creador (el creador que ha publicado su primer vídeo editado con la plataforma tiene 4 veces más probabilidades de convertir a Pro que el que no lo ha hecho: cómo asegurar que todos los nuevos usuarios completan este milestone en los primeros 7 días), secuencia de emails automatizados de nurturing para los usuarios gratuitos que no han convertido a Pro en las primeras 4 semanas (qué enviar, con qué frecuencia, cómo personalizar según el comportamiento en la plataforma) y diseño del momento de upsell al plan Pro (cuándo aparecer el CTA de upgrade, con qué mensaje, ofreciendo qué).

3. Reducción del churn en el plan Pro: El 12% de churn mensual significa que en 8 meses se pierde toda la base de suscriptores Pro. Diseña el sistema de retención. Incluye: señales de churn en los datos de uso de la plataforma (creador que lleva 10 días sin iniciar sesión, creador cuyo volumen de vídeos editados ha caído un 50% respecto al mes anterior, creador que no ha usado las funcionalidades de IA en las últimas 3 semanas aunque fue la razón por la que se suscribió), modelo predictivo de churn que combina esas señales para identificar a los creadores Pro con mayor probabilidad de cancelar en las próximas 2 semanas, protocolo de intervención del CS cuando un creador entra en riesgo de churn (mensaje personalizado en el canal preferido del creador: email, WhatsApp, DM de Instagram si es necesario; análisis del problema real que ha causado la caída de uso; propuesta de solución concreta) y playbook de retención de creadores que quieren cancelar (qué ofrecerles: descuento temporal, acceso a funcionalidades beta, pausa de la suscripción en lugar de cancelación).

4. Éxito del creador como estrategia de retención: Los creadores se quedan en la plataforma si su canal crece usando la herramienta. Diseña el sistema. Incluye: programa de educación sobre crecimiento de canales para los creadores de la plataforma (contenido en el blog, vídeos tutoriales, webinars mensuales sobre cómo optimizar los vídeos para el algoritmo de YouTube o TikTok), sistema de métricas de éxito del creador que van más allá del uso de la plataforma (¿el canal del creador ha crecido en suscriptores desde que usa la herramienta? ¿ha mejorado su watch time? ¿ha aumentado sus visualizaciones?), proceso de celebración de los hitos de los creadores (cuando un creador de la plataforma alcanza 100.000 suscriptores, la plataforma lo celebra públicamente en sus redes sociales: genera lealtad y buzz) y uso de la IA para personalizar las recomendaciones de uso de la plataforma a cada creador (basado en el tipo de contenido que produce y las métricas de su canal).

5. Comunidad de creadores como estrategia de retención: Los creadores que pertenecen a la comunidad tienen el churn más bajo. Diseña el sistema. Incluye: diseño de la comunidad de creadores de la plataforma (canal de Discord o grupo privado de Facebook, con canales o secciones por tipo de contenido, por tamaño del canal, por idioma si hay creadores de diferentes países hispanohablantes), programa de actividad de la comunidad (retos de creación de vídeo mensual, sesiones de Q&A con el equipo de producto, compartición de tips y trucos entre creadores), proceso de moderación de la comunidad (quién modera, cómo se gestionan los conflictos, qué tipo de contenido se fomenta y cuál se prohíbe), diseño del "Creator Council" (un grupo de 10-15 creadores de referencia que participan en las decisiones de producto y son los primeros en probar las nuevas funcionalidades) y cómo convertir la comunidad en un canal de adquisición de nuevos usuarios (los creadores de la comunidad recomiendan la plataforma a sus colegas).

6. Soporte técnico para creadores con necesidades urgentes: Cuando un creador tiene un problema técnico, es una urgencia. Diseña el protocolo. Incluye: clasificación de las incidencias técnicas de los creadores por urgencia (bloqueante: el creador no puede editar ni publicar su vídeo y tiene una fecha límite de publicación; importante: una funcionalidad de IA no funciona correctamente; menor: una pregunta sobre cómo usar una funcionalidad), tiempos de respuesta garantizados por tipo de incidencia y por segmento de creador (los creadores Pro con canal grande tienen SLA más estrictos), proceso de soporte técnico asistido por IA (el chatbot resuelve las preguntas frecuentes, el agente humano interviene para los casos complejos), gestión de los bugs y los errores del producto (cómo comunicar al creador que hay un bug y que se está trabajando en solucionarlo, sin generar más frustración) y proceso de post-mortem de las incidencias más graves para evitar que se repitan.

7. Métricas y gestión del equipo de customer success: Define el sistema de medición. Incluye: KPIs del equipo de customer success (churn mensual del plan Pro, NPS, tasa de conversión de gratuito a Pro, health score de los creadores Pro en riesgo, tiempo de respuesta al primer mensaje de soporte, tasa de resolución en el primer contacto), modelo de health score del creador Pro (combina uso de la plataforma, satisfacción expresada en encuestas y métricas del canal: un creador con canal en crecimiento y que usa la plataforma semanalmente tiene un health score alto; un creador con canal estancado y que no ha iniciado sesión en 2 semanas tiene un health score bajo) y proceso de revisión semanal del equipo de customer success (revisión de los creadores en riesgo, celebración de los éxitos, intercambio de best practices).

Incluye flujo de onboarding automatizado para los primeros 14 días del creador gratuito, plantilla de health score del creador Pro y playbook de retención para creadores que quieren cancelar. Todo adaptado a plataformas SaaS para la economía de creadores de contenido en español.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Reducción del churn del 12% al 5% y aumento del NPS a 55 en plataforma de herramientas de vídeo para creadores de contenido',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultor freelance de producción audiovisual y vídeo marketing con IA',
                'description'      => 'Construye y escala tu práctica independiente como consultor audiovisual o videógrafo freelance usando IA para producir más, gestionar mejor los proyectos y atraer clientes de mayor valor.',
                'prompt_content'   => <<<'EOT'
Eres un videógrafo y consultor de vídeo marketing freelance con 5 años de práctica independiente. Empezaste produciendo vídeos corporativos para PYMEs locales y has ido especializándote en vídeo marketing para empresas medianas: vídeos de producto, casos de éxito de clientes, vídeos para redes sociales y vídeos de formación. La irrupción de las herramientas de IA de vídeo ha cambiado radicalmente tu sector: lo que antes tardabas 3 días en producir ahora puedes hacerlo en 1 día con IA, pero también ha bajado las barreras de entrada para competidores con menor experiencia.

Situación de tu práctica freelance:
- Videógrafo y consultor de vídeo marketing freelance con 5 años de experiencia
- Servicios: producción de vídeos corporativos, vídeos de producto, cases de éxito, vídeos para RRSS, consultoría de estrategia de vídeo
- Clientes actuales: 6 clientes activos, facturación de 72.000 euros anuales
- Modelo de negocio: proyectos one-shot (70% de la facturación) y retención mensual de producción de contenido (30%)
- Objetivo: llegar a 120.000 euros anuales sin contratar personal
- Retos: la IA está permitiendo a diseñadores y agencias de marketing sin experiencia audiovisual producir vídeos básicos que antes solo podía hacer un videógrafo profesional, presionando a la baja los precios del mercado

Desarrolla el sistema completo para escalar tu práctica de videógrafo freelance con IA:

1. Posicionamiento para competir en la era de la IA de vídeo: Si la IA democratiza la producción básica de vídeo, tienes que posicionarte en lo que la IA no puede reemplazar. Diseña tu posicionamiento. Incluye: análisis de qué parte de tu servicio actual puede ser reemplazada por la IA (el B-roll genérico, la animación de textos básica, la locución estándar) y qué no puede serlo todavía (la dirección del cliente durante la grabación, la capacidad de capturar momentos auténticos, el criterio editorial de qué contar y cómo, la comprensión del negocio del cliente), definición de tu nicho de especialización donde la IA es claramente inferior al trabajo humano (historias de empresa, testimonios de clientes, eventos en directo con múltiples cámaras, vídeos de haute gamme para marcas de lujo), propuesta de valor redefinida para el mercado post-IA (ya no vendes "producir un vídeo", vendes "contar la historia de tu empresa de una forma que conecta emocionalmente con tus clientes ideales") y argumentario frente a los clientes que dicen "¿por qué pagarte a ti si con IA puedo hacer el vídeo yo mismo?".

2. Integración de la IA en tu flujo de producción: La IA no es tu enemigo, es tu multiplicador. Diseña tu stack de herramientas. Incluye: uso de IA para acelerar la preproducción (generación del guion con Claude a partir del briefing del cliente, storyboard con Midjourney o Adobe Firefly, scouting de localizaciones con IA), uso de IA en la postproducción para reducir el tiempo de edición (rough cut automático con Descript, generación de subtítulos automáticos con Whisper, selección de la música con IA a partir de la descripción del mood deseado), uso de IA para multiplicar los formatos de entrega del mismo proyecto (el vídeo de 3 minutos del cliente se convierte automáticamente en 5 clips de LinkedIn, 3 Reels, 2 Shorts de YouTube), automatización de los workflows administrativos del proyecto (contrato, factura, seguimiento del pago, briefing del cliente) con herramientas como HoneyBook o Dubsado y flujo de trabajo semanal optimizado con IA por cliente recurrente.

3. Diseño de servicios que escalan mejor que el proyecto one-shot: El modelo de proyecto one-shot tiene un techo. Diseña servicios alternativos. Incluye: paquete de contenido mensual en vídeo para empresas (X vídeos al mes: 1 vídeo largo de marca + 4 clips de RRSS + 1 newsletter con el vídeo destacado, a precio fijo mensual: cómo estructurarlo, cuánto cobrar, cómo producirlo eficientemente), servicio de consultoría de estrategia de vídeo (sin producción: diagnóstico de la situación actual del vídeo de la empresa, estrategia de contenido en vídeo para 12 meses, orientación sobre cómo producir internamente: precio de 1.500-3.000 euros por empresa), formación interna del equipo de marketing de la empresa para que pueda producir vídeo básico de forma autónoma (tú diseñas el proceso, les enseñas a usar las herramientas de IA, les haces la revisión mensual: precio mensual de 500-800 euros) y auditoría del vídeo marketing de la empresa (2 días, entregable: análisis de sus vídeos actuales y plan de mejora: 1.200-2.000 euros).

4. Captación de clientes de mayor presupuesto: Para llegar a 120.000 euros hay que subir el ticket medio. Diseña la estrategia. Incluye: perfil del cliente ideal de la nueva etapa (empresa con facturación mínima de 5 millones que tiene un departamento de marketing y entiende el valor del contenido en vídeo), canales de captación de ese perfil (LinkedIn: contenido de thought leadership sobre vídeo marketing para directores de marketing; referidos de tus clientes actuales que conocen a ese perfil; agencias de marketing que buscan un especialista audiovisual para sus clientes grandes), argumentario de valor para justificar un presupuesto de vídeo de 5.000-15.000 euros por proyecto (ROI del vídeo: cuánto cuesta el vídeo vs. cuánto genera en leads o en ventas), proceso de cualificación de nuevos prospectos para no malgastar tiempo en clientes que no pueden pagar tus nuevas tarifas y proceso de subida de precios con los clientes actuales que pagan menos del nuevo mínimo.

5. Propuesta y venta de servicios audiovisuales premium: Los clientes de mayor presupuesto tienen un proceso de decisión más riguroso. Diseña el proceso. Incluye: estructura de la propuesta audiovisual premium (concepto creativo del vídeo antes del presupuesto: qué vas a contar y cómo, por qué ese enfoque es el más efectivo para los objetivos del cliente; después: presupuesto detallado y timeline), cómo presentar la propuesta en una reunión de 30 minutos (construir el concepto narrativo del vídeo de forma conversacional antes de mostrar el precio), manejo de la objeción de precio "es demasiado caro" (cómo redirigir la conversación al valor generado, no al coste de producción), cuándo y cómo pedir el anticipo del 50% antes de empezar la producción (que es lo profesional y lo que protege al freelance) y proceso de seguimiento cuando el cliente dice "lo pensamos" sin comprometerse.

6. Gestión financiera y estabilidad de ingresos: Los ingresos del freelance audiovisual son muy irregulares. Diseña el sistema. Incluye: modelo de ingresos mixto que combina proyectos one-shot (ingresos puntuales altos) con retenciones mensuales (ingresos predecibles bajos): cuántos clientes recurrentes necesitas para cubrir tus costes fijos, previsión de ingresos para los próximos 6 meses basada en el pipeline actual (probabilidad de cierre ponderada por el valor del proyecto), gestión de los períodos sin proyectos (cómo usarlos: actualizar el portfolio, crear contenido para LinkedIn, desarrollar nuevos servicios, contactar a clientes anteriores para proyectos de follow-up) y decisión de cuándo y cómo subcontratar trabajo a otros freelancers cuando tienes más proyectos de los que puedes abarcar solo.

7. Portfolio, visibilidad y reputación como videógrafo especialista: El portfolio es tu principal herramienta de venta. Diseña el sistema. Incluye: estrategia de portfolio online (qué mostrar: los 5-8 mejores proyectos organizados por tipo de cliente y por objetivo del vídeo; cómo mostrar los resultados del vídeo más allá de la producción: cuántos leads generó, cuántas visualizaciones tuvo, cómo mejoró la conversión de la landing page), estrategia de LinkedIn como canal principal de captación de clientes (qué tipo de contenido publica un videógrafo especializado que atrae a directores de marketing: análisis de campañas de vídeo de referencia, antes y después de producciones propias, opiniones sobre tendencias de vídeo marketing), proceso de solicitud de testimonios y casos de éxito a los clientes actuales y uso de la IA para mantener una presencia constante en LinkedIn con menos tiempo dedicado (generación de borradores de posts con Claude, calendario de publicación automatizado).

Incluye plantilla de propuesta audiovisual para clientes premium, guia de precios para videógrafos freelance en España y sistema de gestión del pipeline de proyectos en Notion o Airtable. Todo orientado a la realidad del videógrafo freelance de vídeo marketing en el mercado español.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 65,
                'use_case'         => 'Escalar práctica freelance de videógrafo de 72.000 a 120.000 euros anuales en la era de la IA de vídeo',
                'vote_score'       => 42,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
