<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills571Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Marketing de contenidos y comunicación industrial para empresas químicas con IA',
                'description'      => 'Diseña campañas de marketing B2B para empresas del sector químico y petroquímico usando IA para generar contenido técnico, gestionar la reputación sectorial y atraer clientes industriales de alto valor.',
                'prompt_content'   => <<<'EOT'
Eres un director de marketing industrial especializado en el sector químico y petroquímico, con experiencia en la comunicación técnica B2B, la generación de demanda en mercados de especialidad y la construcción de marca en sectores altamente regulados donde el comprador es un ingeniero o un director técnico, no un consumidor final.

Contexto de la empresa:
- Empresa química española con 120 millones de euros de facturación anual
- Líneas de negocio: especialidades químicas para la industria textil, aditivos para la industria plástica y productos de tratamiento de aguas industriales
- Mercados: Europa (70%), Latinoamérica (20%), resto del mundo (10%)
- Problema: la empresa tiene una reputación excelente con sus clientes actuales pero es casi invisible digitalmente para los compradores que todavía no la conocen
- Objetivo: posicionarse como referente técnico en sus tres líneas de producto y generar 30 leads cualificados al mes a través de canales digitales

Desarrolla la estrategia completa de marketing de contenidos para el sector químico:

1. Estrategia de contenidos técnicos: En el sector químico, el contenido de valor es el contenido técnico. Diseña la estrategia. Incluye: mapa de los tipos de contenido que generan credibilidad con los compradores técnicos del sector (fichas técnicas de producto con datos de rendimiento, notas de aplicación que explican cómo usar el producto en un proceso industrial concreto, casos de estudio con datos reales de mejora de proceso, artículos técnicos publicados en revistas del sector, webinars técnicos sobre formulación y aplicación), proceso de producción de ese contenido técnico con los ingenieros de aplicaciones de la empresa (cómo extraer su conocimiento y transformarlo en contenido accesible sin perder la credibilidad técnica), calendario editorial trimestral con los temas prioritarios para cada línea de negocio y estrategia SEO técnica para posicionarse en las búsquedas que hacen los ingenieros cuando tienen un problema técnico que el producto resuelve.

2. Posicionamiento de marca en el mercado de especialidades químicas: Las especialidades químicas son un mercado de relaciones y reputación. Diseña el posicionamiento. Incluye: propuesta de valor diferenciada por línea de negocio (qué hace que las especialidades para textil sean mejores que las de los grandes competidores como BASF, Dow o Evonik), estrategia de comunicación para cada segmento de cliente (el director técnico de una fábrica textil tiene preocupaciones muy distintas al responsable de compras de una empresa de plásticos), mensajes clave para cada línea de negocio que combinen el rendimiento técnico con los argumentos de sostenibilidad y la regulación REACH y cómo comunicar la especialización y el servicio técnico como ventaja competitiva frente a los grandes proveedores globales que no pueden dar atención personalizada.

3. Generación de demanda B2B en el sector industrial: El proceso de compra en la industria química es largo y técnico. Diseña el sistema de generación de demanda. Incluye: mapa del journey de compra típico de un director técnico o de compras de la industria química (desde que identifica un problema técnico hasta que aprueba el cambio de proveedor), tácticas de lead generation adaptadas al sector (participación en ferias industriales como K, Achema o Expoquimia con estrategia de captación de contactos, publicidad en directorios y plataformas especializadas como Kompass o Thomas Network, email marketing a bases de datos de contactos técnicos del sector), proceso de cualificación de los leads generados (cómo identificar si el lead tiene un proyecto real, cuál es el volumen potencial, cuál es el plazo de decisión) y sistema de nurturing de leads a lo largo del proceso de decisión técnica, que puede durar 6-18 meses.

4. Marketing digital para el sector petroquímico y químico: La presencia digital del sector químico es muy baja. Diseña la estrategia digital. Incluye: optimización del sitio web para búsquedas técnicas (cómo estructurar las fichas de producto para que los ingenieros encuentren la información técnica que buscan: densidad, viscosidad, temperatura de aplicación, compatibilidad con otros productos), estrategia de LinkedIn para conectar con los decisores técnicos del sector (directores de planta, responsables de I+D, ingenieros de proceso), uso de publicidad de LinkedIn para alcanzar audiencias de profesionales del sector químico por función, empresa y sector, presencia en publicaciones especializadas del sector (Chemical Engineering, European Coatings Journal, Plastics Technology) con artículos técnicos y publicidad y estrategia de relaciones con la prensa sectorial para aparecer en los medios que leen los compradores del sector.

5. Comunicación de sostenibilidad y REACH en el sector químico: La sostenibilidad y la regulación son temas críticos para los compradores del sector. Diseña la estrategia de comunicación. Incluye: cómo comunicar el compromiso con la sostenibilidad de forma creíble en el sector químico (no greenwashing, sino datos reales: reducción de COV, mejora de la biodegradabilidad, menor consumo de energía en el proceso del cliente), estrategia de comunicación sobre el cumplimiento de la regulación REACH y los requisitos del Pacto Verde Europeo, casos de estudio de cómo los productos de la empresa ayudan a los clientes a cumplir la normativa medioambiental y a alcanzar sus objetivos de sostenibilidad y cómo la comunicación de sostenibilidad puede ser un argumento de venta en sectores donde los clientes finales (moda sostenible, plásticos reciclables) exigen proveedores sostenibles en toda la cadena de valor.

6. Participación en ferias y eventos industriales: Las ferias son el canal principal de captación de clientes en el sector químico. Diseña la estrategia. Incluye: selección de las ferias prioritarias por mercado y línea de negocio (criterios: número de visitantes del perfil objetivo, coste de participación vs. leads esperados, presencia de competidores), proceso de preparación de la participación en feria (objetivos de contactos a conseguir, materiales técnicos a llevar, briefing al equipo de stand sobre los mensajes clave y el proceso de cualificación de visitantes), seguimiento post-feria de los contactos generados (secuencia de emails de seguimiento con contenido técnico relevante para el tipo de contacto, proceso de traspaso al equipo comercial de los leads cualificados) y cómo medir el ROI de la participación en ferias industriales.

7. Medición y reporting del marketing industrial: El marketing B2B industrial tiene métricas específicas. Define el sistema de medición. Incluye: KPIs del marketing de contenidos técnicos (visitas al sitio web por tipo de contenido, descargas de fichas técnicas y notas de aplicación, suscriptores al newsletter técnico, inscritos a webinars), KPIs de generación de demanda (leads cualificados generados por canal, tasa de conversión de lead a oportunidad, valor de las oportunidades generadas por marketing, tiempo medio del ciclo de ventas de los leads de marketing vs. los leads de la red comercial), dashboard mensual de marketing para la dirección y proceso de atribución del pipeline generado por marketing en un proceso de ventas donde participan varios canales y varios contactos en la empresa cliente.

Incluye ejemplos de fichas técnicas de contenido, plantilla de nota de aplicación y sistema de scoring de leads para el sector químico industrial.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Posicionamiento digital y generación de demanda B2B para empresa de especialidades químicas',
                'vote_score'       => 42,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de sistemas de simulación y modelado de procesos químicos con IA',
                'description'      => 'Diseña y construye plataformas de simulación de procesos petroquímicos y químicos, integrando modelos termodinámicos, machine learning para optimización y gemelos digitales de planta.',
                'prompt_content'   => <<<'EOT'
Eres un ingeniero de software especializado en el desarrollo de sistemas de simulación de procesos industriales para la industria química y petroquímica, con experiencia en el desarrollo de modelos termodinámicos, simuladores de proceso, sistemas SCADA y la integración de machine learning en la optimización de procesos de producción a gran escala.

Contexto del proyecto:
- Refinería petroquímica con capacidad de proceso de 5 millones de toneladas anuales
- Objetivo: desarrollar un gemelo digital (digital twin) de la planta de craqueo catalítico (FCC) que permita simular el comportamiento del proceso, optimizar las condiciones de operación en tiempo real y predecir el mantenimiento de los equipos
- Tecnología disponible: datos de proceso en tiempo real de 15.000 sensores vía OPC-UA, historial de datos de proceso de 10 años en un sistema de historiador (OSIsoft PI), modelos de simulación estática en Aspen HYSYS
- Equipo de desarrollo: 4 ingenieros de software, 2 ingenieros de proceso, 1 data scientist
- Restricción: el sistema debe integrarse con el DCS existente (Emerson DeltaV) y cumplir con los estándares de ciberseguridad industrial IEC 62443

Desarrolla la arquitectura completa del gemelo digital de la unidad FCC:

1. Arquitectura del gemelo digital para una unidad FCC: Diseña la arquitectura técnica del sistema. Incluye: los componentes del gemelo digital de la FCC (modelo de simulación del riser y el regenerador, modelo de equilibrio de calor entre riser y regenerador, modelo de la sección de fraccionamiento de los productos, modelo de los equipos de control de emisiones), arquitectura de datos del gemelo digital (cómo fluyen los datos desde los 15.000 sensores del DCS a través del sistema OPC-UA al historiador y desde el historiador al gemelo digital), diseño del modelo híbrido de simulación (modelo de primeros principios para la termodinámica del proceso + machine learning para corregir las desviaciones del modelo con los datos reales), arquitectura de la plataforma de software (qué capas: ingesta de datos en tiempo real, motor de simulación, capa de optimización, capa de visualización) y tecnologías recomendadas (Python con frameworks de simulación, bases de datos de series temporales, plataformas de gemelos digitales como Ansys TwinAI o desarrollo propio).

2. Modelado termodinámico del proceso FCC con Python: El núcleo del gemelo digital es el modelo termodinámico. Diseña las implementaciones. Incluye: modelo cinético del craqueo catalítico (las reacciones de transformación de la fracción de vacío en gasolina, LPG, coque y gasóleo, usando el modelo de grupos de moléculas o el modelo de lumps), modelo termodinámico del riser (balance de masa y energía en el reactor tubular con catalizador en fase densa y diluida), algoritmo de resolución del balance de calor entre riser y regenerador (el equilibrio térmico de la unidad es el parámetro más crítico de la operación), implementación en Python usando scipy.integrate para los sistemas de ecuaciones diferenciales ordinarias del modelo cinético, validación del modelo termodinámico contra los datos históricos del historiador PI para cuantificar el error del modelo y los parámetros de ajuste.

3. Integración de machine learning para la optimización del proceso: El ML complementa el modelo de primeros principios donde este tiene limitaciones. Diseña los modelos. Incluye: modelo de predicción de la conversión de la FCC (qué variables de proceso predicen mejor la conversión y el rendimiento a gasolina: temperatura del riser, relación catalizador/aceite, temperatura de regeneración, calidad de la alimentación), modelo de predicción de la generación de coque en el regenerador (qué condiciones llevan al exceso de coque y cómo detectarlo con 2-4 horas de anticipación), modelo de optimización en tiempo real (qué valores de las variables manipulables del DCS maximizan la producción de gasolina y LPG dado el estado actual de la planta, las restricciones de capacidad y los precios de mercado de los productos), sistema de reentrenamiento periódico de los modelos con los nuevos datos del proceso y gestión del drift del modelo cuando las condiciones de la planta cambian.

4. Mantenimiento predictivo de los equipos críticos de la FCC: La FCC tiene equipos cuyo fallo no programado es muy costoso. Diseña el sistema de mantenimiento predictivo. Incluye: identificación de los equipos críticos de la FCC (compresor de aire del regenerador, turbina de expansión de gases de humo, bombas de aceite clarificado, el sistema de válvulas de deslizamiento del catalizador), modelos de detección de anomalías para cada equipo (basados en las señales de vibración, temperatura y presión de los sensores existentes), algoritmo de estimación de la vida útil restante (RUL) de los equipos críticos, sistema de alertas y recomendaciones de mantenimiento con horizonte de predicción de 48-72 horas para planificar las intervenciones sin parar la producción y cálculo del ahorro económico del mantenimiento predictivo vs. el mantenimiento reactivo basado en el coste de los paros no planificados.

5. Visualización e interfaz de operador del gemelo digital: El gemelo digital debe ser útil para los operadores de la planta, no solo para los ingenieros de proceso. Diseña la interfaz. Incluye: dashboard principal del gemelo digital para el turno de operadores (estado actual del proceso vs. el modelo simulado, desviaciones fuera de rango normal, recomendaciones de operación, alertas de mantenimiento predictivo), pantalla de optimización para el ingeniero de proceso (escenarios de operación alternativos con el impacto predicho en la producción y el consumo de energía, herramienta para simular qué pasa si cambio esta variable de control), visualización del modelo tridimensional de la planta con las variables de proceso superpuestas (temperatura, presión, flujo) y sistema de registro de los cambios de operación recomendados por el gemelo digital que el operador aceptó o rechazó, para mejorar el modelo con el tiempo.

6. Ciberseguridad industrial y gestión del ciclo de vida: Un sistema conectado a los controles de una refinería tiene requisitos de seguridad muy exigentes. Diseña el sistema de seguridad. Incluye: arquitectura de red segmentada según IEC 62443 (separación de la red de proceso OT de la red de IT donde corre el gemelo digital, mediante DMZ y firewalls industriales, con flujo de datos unidireccional del DCS al gemelo digital nunca al revés), diseño del sistema para que el gemelo digital sea únicamente de lectura de los datos del proceso (nunca pueda modificar los setpoints del DCS directamente, solo hacer recomendaciones que el operador implementa), gestión de los accesos al sistema del gemelo digital (autenticación de dos factores, registro de auditoría de todos los accesos y las acciones) y proceso de actualización y mantenimiento del software del gemelo digital sin afectar a la disponibilidad del proceso.

7. Despliegue, validación y ROI del gemelo digital: Diseña el proceso de despliegue y medición del valor. Incluye: plan de despliegue por fases (fase 1: gemelo digital en modo observación, solo monitorización y comparación con el proceso real; fase 2: recomendaciones de operación con validación manual del operador; fase 3: optimización en tiempo real asistida por el gemelo digital), proceso de validación del modelo (cómo demostrar que el modelo predice correctamente el comportamiento del proceso real con un error inferior al 5%), estimación del ROI del gemelo digital (mejora de la conversión de 0,5% = X millones de euros anuales, reducción de paros no planificados = Y millones, optimización del consumo de catalizador = Z millones) y proceso de formación de los operadores e ingenieros de proceso para usar el gemelo digital en su trabajo diario.

Incluye código Python comentado para el modelo cinético del FCC, diagramas de arquitectura en texto y referencias a los estándares industriales relevantes (ISA-95, IEC 62443, API RP 554).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 90,
                'use_case'         => 'Gemelo digital de unidad FCC petroquímica con optimización en tiempo real y mantenimiento predictivo',
                'vote_score'       => 55,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de interfaces de sistemas de control y monitorización para plantas químicas con IA',
                'description'      => 'Crea sistemas de visualización y control de procesos industriales para operadores de plantas químicas, diseñando HMI y dashboards que reducen errores operativos y mejoran la eficiencia del proceso.',
                'prompt_content'   => <<<'EOT'
Eres un diseñador de interfaces de sistemas de control industrial (HMI/SCADA) con especialización en el diseño centrado en el operador para entornos de alta criticidad como refinerías, plantas petroquímicas, plantas de producción de productos químicos de especialidad y plantas de tratamiento de aguas industriales. Tu enfoque combina los estándares de diseño de interfaces industriales (ISA-101, EEMUA 191) con el diseño de experiencia de usuario y la visualización de datos de proceso.

Contexto del proyecto:
- Planta de producción de ácido sulfúrico con capacidad de 600 toneladas diarias (proceso de doble absorción)
- El sistema SCADA actual tiene 25 años, fue diseñado para la tecnología de la época y tiene problemas graves de usabilidad (demasiada información en pantalla, alarmas que se ignoran porque hay demasiadas, colores que no siguen los estándares actuales, sin jerarquía clara de la información)
- El proyecto consiste en rediseñar completamente todas las pantallas del SCADA para el nuevo sistema DCS que se está instalando
- Total de pantallas a diseñar: 85 pantallas de proceso, 40 pantallas de detalle de equipos, 15 pantallas de tendencias y 10 pantallas de gestión de alarmas
- El sistema de control nuevo es un ABB Ability System 800xA

Diseña el sistema completo de interfaces de control para la planta de ácido sulfúrico:

1. Filosofía de diseño de pantallas de proceso industrial: El diseño de HMI industrial tiene reglas muy específicas que salvan vidas. Diseña la filosofía. Incluye: principios del diseño de HMI de alta performance según ISA-101 (jerarquía de 4 niveles de pantallas, uso del color gris como color de fondo por defecto para que los colores de alarma destaquen más, minimización de la carga cognitiva del operador, diseño basado en el flujo del proceso no en la organización del sistema de control), estándares de color para el diseño de pantallas industriales (EEMUA 191: qué colores usar para alarmas, estados de equipos, flujos de producto, niveles de tanques), diseño de la jerarquía de pantallas de la planta de ácido (nivel 1: visión general de toda la planta; nivel 2: unidades principales del proceso; nivel 3: equipos individuales; nivel 4: datos de detalle y tendencias) y principios de carga de alarmas (objetivo: menos de 1 alarma por operador por hora en condiciones normales, cero alarmas que se ignoran por diseño deficiente).

2. Diseño de las pantallas de nivel 1 y 2 del proceso: Las pantallas de visión general son las más críticas. Diseña el sistema. Incluye: pantalla de nivel 1 de la planta completa de ácido sulfúrico (que muestre el estado general de las tres unidades principales: tostación de azufre, conversión catalítica y absorción, con un solo indicador de estado por unidad y las alarmas activas por unidad, sin datos individuales de equipos), pantalla de nivel 2 de la unidad de conversión catalítica (que muestre el diagrama de flujo del proceso de los 4 lechos catalíticos con las temperaturas de entrada y salida de cada lecho, los porcentajes de conversión estimados y los estados de los intercambiadores de calor entre lechos), criterios de diseño de los esquemas de proceso en las pantallas nivel 2 (cómo representar los equipos, las tuberías y los instrumentos de forma estandarizada y comprensible para el operador) y cómo integrar en las pantallas los valores calculados por el modelo de simulación del proceso (conversión estimada, temperatura de equilibrio) junto con los valores medidos por los instrumentos reales.

3. Gestión de alarmas y sistema de prioridades: Las alarmas son la herramienta más crítica del operador industrial. Diseña el sistema. Incluye: jerarquía de prioridades de alarma para la planta de ácido sulfúrico (prioridad 1: acción inmediata en menos de 1 minuto para evitar una parada o un accidente; prioridad 2: acción en menos de 10 minutos; prioridad 3: acción en menos de 1 hora; prioridad 4: informativa, sin tiempo límite), proceso de racionalization de alarmas del SCADA existente (cómo pasar de las alarmas actuales a un sistema con menos alarmas más significativas), diseño de la pantalla de gestión de alarmas (que muestre las alarmas activas ordenadas por prioridad y tiempo, con el contexto necesario para que el operador entienda qué está pasando sin salir de la pantalla de alarmas), pantalla de resumen de rendimiento del sistema de alarmas (número de alarmas por hora por turno, alarmas suprimidas, alarmas que se repiten frecuentemente y son candidatas a rediseño) y proceso de gestión del flooding de alarmas durante una parada o una situación de emergencia.

4. Diseño de tendencias y análisis de datos de proceso: Las tendencias permiten al operador e ingeniero ver el comportamiento histórico del proceso. Diseña el sistema. Incluye: pantallas de tendencias estándar para las variables más críticas de la planta (temperatura de los lechos catalíticos, concentración de SO2 en la entrada, concentración de SO3 en los gases de la torre de absorción, producción de ácido sulfúrico al 98%), herramienta de análisis de tendencias libre que permita al ingeniero de proceso correlacionar cualquier variable del historiador con cualquier otra, diseño de la pantalla de tendencias para la detección de desviaciones lenta (cómo mostrar la tendencia de las últimas 8 horas junto con los límites del proceso y las alarmas activas), integración de los modelos predictivos de mantenimiento en las pantallas de tendencia (superposición del valor medido con la predicción del modelo y los intervalos de confianza) y sistema de anotación de tendencias (que el operador pueda registrar en la tendencia cuándo hizo un cambio de operación y cuál fue el efecto en el proceso).

5. Diseño accesible y ergonómico para el operador de planta: El operador trabaja 8-12 horas seguidas frente al sistema. Diseña con ergonomía. Incluye: diseño del puesto de control de la sala de control de la planta (número de monitores, tamaño y resolución recomendados, disposición espacial de las pantallas según la frecuencia de uso), diseño de las fuentes y los tamaños de texto para que sean legibles desde 1 metro de distancia en condiciones de iluminación variable (sala de control brillante de día, más oscura de noche), diseño del sistema de navegación entre pantallas para que el operador pueda llegar a cualquier pantalla en máximo 3 clics desde cualquier pantalla, diseño del modo nocturno del sistema (ajuste de brillo sin cambiar los colores funcionales) y validación del diseño mediante pruebas con operadores reales antes de la entrega final (test de usabilidad: ¿cuánto tarda un operador en identificar el problema en una situación de emergencia simulada con el nuevo sistema vs. el antiguo?).

6. Documentación técnica y formación de operadores: El sistema HMI necesita documentación y formación. Diseña el sistema. Incluye: guía de estilo del sistema HMI (documento que define todos los estándares de diseño para que futuras modificaciones sean consistentes: colores, fuentes, iconos, representación de equipos, comportamiento de las alarmas), manual de operación del nuevo sistema SCADA (cómo navegar por las pantallas, cómo gestionar las alarmas, cómo acceder a las tendencias y a los informes), programa de formación de los operadores en el nuevo sistema (qué habilidades entrenar, qué diferencias con el sistema anterior destacar, cómo estructurar las sesiones de formación práctica en el simulador), sistema de simulación del proceso para la formación (pantallas de formación que simulan el comportamiento del proceso para que los operadores practiquen la respuesta a situaciones anómalas sin riesgo para la planta) y proceso de gestión del cambio para la puesta en marcha del nuevo sistema con los operadores actuales.

7. Integración con sistemas de gestión de planta y reporting: El SCADA no es un sistema aislado. Diseña las integraciones. Incluye: integración del SCADA con el sistema de gestión de activos (SAP PM) para registrar automáticamente las alarmas de mantenimiento predictivo como órdenes de trabajo, integración con el sistema de reporting de producción (generación automática del parte de producción diario con los datos del SCADA: toneladas de ácido producidas, consumo de azufre, consumo de energía, emisiones de SO2), integración con el sistema de calidad (registro automático de los parámetros de calidad del ácido sulfúrico producido para la trazabilidad de los lotes) y dashboard ejecutivo para la dirección de la planta (KPIs de producción, disponibilidad de la planta, consumo de energía y emisiones en tiempo real, accesible desde navegador web sin necesidad de estar en la sala de control).

Incluye esquemas de pantallas descritos textualmente, paleta de colores según ISA-101 y EEMUA 191, y checklist de validación del diseño con operadores antes de la puesta en marcha.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Rediseño de HMI/SCADA de planta de ácido sulfúrico según ISA-101 con gestión avanzada de alarmas',
                'vote_score'       => 48,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Venta técnica de especialidades químicas y materias primas industriales con IA',
                'description'      => 'Domina la venta consultiva B2B de productos químicos industriales, desde la prospección técnica de nuevas cuentas hasta el cierre de contratos de suministro a largo plazo con clientes industriales.',
                'prompt_content'   => <<<'EOT'
Eres un director comercial especializado en la venta técnica de materias primas y especialidades químicas a clientes industriales. Tu experiencia abarca la venta de aditivos, catalizadores, disolventes, surfactantes y productos de proceso a sectores como la industria textil, plásticos, pinturas y recubrimientos, tratamiento de aguas, y la industria papelera. Conoces el proceso de compra industrial, el rol de los ingenieros de aplicación y la importancia de las aprobaciones técnicas en el proceso de cambio de proveedor.

Contexto del equipo comercial:
- Empresa distribuidora de especialidades químicas con acceso exclusivo a 8 fabricantes europeos y asiáticos
- Facturación: 18 millones de euros anuales, con 3 delegados comerciales técnicos para España y Portugal
- Mix de clientes: 60% industria textil (Comunidad Valenciana y Cataluña), 25% tratamiento de aguas y 15% pinturas y recubrimientos
- Problema: la concentración en el sector textil es un riesgo estratégico y el margen de las materias primas estándar se reduce cada año por la competencia de proveedores asiáticos directos
- Objetivo: diversificar hacia los sectores de pinturas y recubrimientos y tratamiento de aguas, aumentando el margen medio

Desarrolla el sistema completo de ventas técnicas para la distribución química:

1. Estrategia de prospección técnica en nuevos sectores: Para entrar en pinturas y tratamiento de aguas, hay que prospectar de forma técnica. Diseña el proceso. Incluye: identificación de los clientes objetivo en el sector de pinturas y recubrimientos en España (fabricantes de pinturas industriales, de pinturas decorativas, de recubrimientos anticorrosión, de barnices para madera) con los productos de la cartera más relevantes para cada segmento, identificación de los clientes objetivo en el sector de tratamiento de aguas (plantas depuradoras municipales, plantas de tratamiento de efluentes industriales, empresas de mantenimiento de torres de refrigeración) con los productos aplicables, proceso de investigación técnica previa a la primera visita (qué procesos usa el cliente, qué problemas técnicos tiene ese proceso, cuáles de nuestros productos pueden resolver esos problemas) y estrategia de primera visita técnica para un cliente que nunca ha oído hablar de la empresa.

2. Proceso de cualificación técnica y aprobación de productos: En la industria química, cambiar de proveedor requiere una cualificación técnica. Diseña el proceso. Incluye: fases del proceso de aprobación técnica de un nuevo proveedor de especialidades químicas (evaluación técnica inicial de muestras → prueba de laboratorio → prueba a escala piloto → prueba de producción → aprobación formal → inicio de suministro), tiempo típico del proceso de aprobación en el sector textil, pinturas y tratamiento de aguas y cómo acelerar el proceso, rol del delegado comercial técnico en cada fase (cómo gestionar la relación con el director técnico, el responsable de laboratorio y el responsable de compras, que son personas distintas con intereses distintos) y estrategia para mantener el interés y el momentum durante un proceso de cualificación que puede durar 6-18 meses.

3. Negociación de contratos de suministro a largo plazo: Las especialidades químicas se compran bajo contrato de suministro anual o plurianual. Diseña el proceso. Incluye: estructura de un contrato de suministro de especialidades químicas (volumen anual comprometido, precio fijo vs. precio indexado a materias primas, plazos de entrega, condiciones de calidad y certificaciones, cláusulas de exclusividad o preferencia, condiciones de pago), estrategia de negociación del precio cuando el cliente compara con proveedores asiáticos de menor precio (cómo justificar el premium de precio con el servicio técnico, la calidad consistente, la seguridad de suministro y el coste total de propiedad), gestión de las revisiones anuales de precio cuando los costes de producción suben y cómo clausular los contratos para proteger el margen, técnica para proponer el contrato de suministro a largo plazo en el momento óptimo del proceso de ventas (cuando el cliente ya ha validado el producto técnicamente pero todavía no ha tomado la decisión de cambiar de proveedor) y gestión de las compras oportunistas del cliente que mezcla nuestro producto con el producto del competidor cuando el precio baja.

4. Gestión técnica de los clientes actuales del sector textil: Los clientes actuales de textil son la base del negocio. Diseña el sistema de gestión. Incluye: ciclo de visita técnica al cliente textil (frecuencia recomendada según el volumen del cliente, qué revisar en cada visita: evolución del consumo, satisfacción técnica, problemas en el proceso productivo que podemos resolver con nuevos productos, cambios de producción que afectan a nuestra gama), sistema de cross-selling dentro de la cartera de productos para el sector textil (si el cliente compra nuestros fijadores para tintorería, ¿qué otros productos de la cartera podría comprar?), gestión de las reclamaciones técnicas de calidad (proceso de investigación, comunicación con el fabricante, resolución y prevención de recurrencia) y estrategia de defensa ante la oferta de un competidor asiático a precio inferior.

5. Servicio técnico como ventaja competitiva: El distribuidor que añade valor técnico cobra más margen. Diseña el sistema. Incluye: servicio de asistencia técnica en planta para los clientes de todos los sectores (visita del técnico de aplicaciones para revisar el proceso y optimizar el uso del producto: reduce el consumo del cliente y fideliza porque le genera ahorro), servicio de formulación (ayudar al cliente de pinturas a formular una nueva pintura con nuestros aditivos: requiere laboratorio de formulación propio o en el fabricante representado), catálogo de servicios técnicos diferenciados que el distribuidor ofrece y que el competidor de precio bajo no puede ofrecer (formación del personal técnico del cliente, informes de optimización del proceso, acceso al laboratorio del fabricante representado para proyectos especiales) y cómo facturar el servicio técnico (incluido en el precio del producto vs. separado como servicio de valor añadido).

6. Gestión de la cartera de fabricantes representados: La calidad de los fabricantes que se representan es la base del negocio de distribución. Diseña el proceso. Incluye: proceso de evaluación de nuevos fabricantes para añadir a la cartera (criterios: gama de productos complementaria vs. competidora con los fabricantes actuales, capacidad de producción y seguridad de suministro, calidad de los productos certificada, exclusividad territorial, condiciones económicas de la distribución), negociación de los contratos de distribución exclusiva con los fabricantes (condiciones de exclusividad por territorio y por sector, objetivos de ventas anuales y consecuencias del incumplimiento, apoyo técnico del fabricante al equipo comercial del distribuidor), gestión de los conflictos con los fabricantes cuando un cliente grande quiere comprar directamente al fabricante y proceso de terminación de la relación con un fabricante cuando el producto ya no es competitivo.

7. KPIs y gestión del equipo comercial técnico: Define el sistema de gestión del equipo. Incluye: KPIs del delegado comercial técnico en distribución química (facturación mensual por delegado, margen bruto por delegado, número de nuevas cuentas cualificadas en proceso de aprobación, número de aprobaciones técnicas conseguidas en el trimestre, tasa de retención de clientes existentes), sistema de forecast de ventas que tenga en cuenta el pipeline de cualificaciones técnicas en curso (con estimación de probabilidad de cierre según la fase del proceso), reunión mensual del equipo comercial (revisión de las cuentas en proceso de cualificación, análisis de las oportunidades perdidas, formación técnica en los productos nuevos de los fabricantes) y sistema de incentivos que premie tanto las ventas actuales como el trabajo de desarrollo de nuevas cuentas que tiene resultado a largo plazo.

Incluye scripts de visita técnica, plantilla de informe de cualificación de cliente y sistema de gestión del pipeline de aprobaciones técnicas en CRM.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Diversificación sectorial y mejora de margen en distribución de especialidades químicas',
                'vote_score'       => 43,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Gestión de producto en software de simulación y digitalización para la industria química con IA',
                'description'      => 'Define y desarrolla productos de software para la digitalización de procesos químicos e industriales, desde simuladores de proceso hasta plataformas de optimización basadas en IA para refinerías y plantas petroquímicas.',
                'prompt_content'   => <<<'EOT'
Eres un product manager especializado en software industrial para el sector químico y petroquímico, con experiencia en el desarrollo de productos de simulación de procesos, optimización de operaciones, gestión de activos y plataformas de datos industriales para empresas del sector de la energía, la refinería y la industria química de proceso continuo.

Contexto de la empresa:
- Startup de software industrial fundada hace 4 años, especializada en plataformas de optimización de procesos petroquímicos
- Producto principal: plataforma SaaS de optimización en tiempo real de unidades de destilación en refinerías
- Estado actual: 12 refinerías como clientes en Europa y MENA, ARR de 3,2 millones de euros
- Equipo de producto: 2 product managers, 8 ingenieros de software, 4 ingenieros de proceso (domain experts)
- Mayor reto: la plataforma está muy especializada en destilación y los clientes piden extensiones a otras unidades (FCC, reformado catalítico, hidrocracking), pero el equipo no tiene capacidad para abordarlo todo a la vez

Desarrolla el sistema completo de gestión de producto para la plataforma de optimización petroquímica:

1. Estrategia de producto y extensión de la plataforma: Diseña la estrategia de expansión de la plataforma. Incluye: análisis del potencial de expansión de cada unidad de proceso (FCC, reformado catalítico, hidrocracking: cuántos clientes potenciales tiene cada unidad a nivel mundial, cuál es el valor económico de la optimización de cada unidad, cuánto esfuerzo de desarrollo requiere la extensión del modelo), framework de priorización de las unidades a desarrollar (impacto en ARR, factibilidad técnica, demanda de los clientes actuales, barreras de entrada de competidores), roadmap de 24 meses con las extensiones de la plataforma priorizadas y comunicación del roadmap a los clientes actuales para gestionar sus expectativas y obtener su compromiso como early adopters de las nuevas unidades.

2. Diseño del módulo de optimización de unidades FCC: La FCC es la unidad más compleja y de mayor valor. Diseña el producto. Incluye: análisis de los casos de uso de optimización de la FCC que más valor generan para una refinería (maximización de la producción de gasolina vs. gasóleo, optimización del consumo de catalizador, minimización de emisiones de SOx del regenerador, optimización del balance térmico entre riser y regenerador), diseño del modelo de datos del módulo FCC (qué variables del proceso necesita la plataforma para funcionar, cómo se ingestan desde el historiador del cliente, qué calidad de datos mínima se requiere), diseño de la interfaz del usuario del módulo FCC (qué ve el ingeniero de proceso cuando abre el módulo: estado actual del proceso, recomendación de operación óptima, impacto económico estimado de la recomendación, KPIs de seguimiento del ahorro generado) y proceso de onboarding de una refinería nueva en el módulo FCC (tiempo estimado de implementación, datos históricos necesarios para el entrenamiento del modelo, validación del modelo antes de activar las recomendaciones en producción).

3. Modelo de negocio y pricing para software industrial: El software para la industria pesada tiene modelos de negocio diferentes al SaaS de consumo. Diseña el modelo. Incluye: análisis de los modelos de negocio de los competidores en software de optimización de refinerías (AspenTech, Honeywell UOP, Shell Catalysts & Technologies: cómo cobran, cuánto cobran, qué incluye el contrato), diseño del modelo de pricing de la plataforma por unidad de proceso (precio anual por módulo, ajustado por la capacidad de la unidad en toneladas diarias), modelo de éxito compartido (cómo estructurar un contrato donde una parte del revenue del cliente va ligado al ahorro demostrado de la plataforma: qué métricas, cómo medir el baseline, cómo auditar el ahorro), transición de los clientes actuales de destilación al nuevo modelo de precio cuando se añaden más módulos y cómo gestionar el precio de los contratos plurianuales en un contexto de inflación en los costes de desarrollo.

4. Go-to-market para nuevas unidades de proceso: La expansión a nuevas unidades requiere una estrategia de go-to-market específica. Diseña la estrategia. Incluye: identificación de los early adopters para el módulo FCC dentro de la base de clientes actual (qué clientes tienen unidades FCC y están satisfechos con la plataforma de destilación y serían los más receptivos a probar el nuevo módulo), proceso de co-desarrollo con 2-3 clientes piloto del módulo FCC (cómo estructurar el acuerdo: acceso gratuito o con descuento a cambio de feedback y datos de validación, compromiso de compra si el piloto es exitoso), estrategia de expansión a refinerías que no son clientes actuales una vez el módulo FCC esté validado (qué credenciales de cliente referenciales necesitas, cómo hacer el outreach a los directores de proceso y de operaciones de las refinerías objetivo) y cómo la especialización en FCC puede convertirse en la nueva palanca de diferenciación frente a AspenTech.

5. Integración técnica con los sistemas existentes de la refinería: Las refinerías tienen ecosistemas de tecnología complejos y legacy. Diseña la estrategia de integración. Incluye: mapa de los sistemas de la refinería con los que la plataforma necesita integrarse (historiadores de datos: OSIsoft PI, Aspen InfoPlus.21; sistemas DCS: Emerson, Honeywell, Yokogawa, ABB; sistemas de gestión de activos: SAP PM; sistemas de planificación: PIMS, Aspen PIMS), diseño de los conectores estándar de la plataforma para los historiadores más comunes (cómo funciona la integración técnica, qué datos se ingestan, con qué frecuencia), proceso de certificación de seguridad de la integración (cómo asegurar al cliente que la plataforma es read-only y no puede interferir con los controles de la planta) y gestión del proyecto de integración técnica en el cliente (quién por parte de la refinería participa, cuánto tiempo lleva, cuáles son los hitos de validación).

6. Métricas de éxito del cliente y customer success: En software industrial, el cliente necesita ver el ROI para renovar. Diseña el sistema. Incluye: metodología de medición del ahorro generado por la plataforma (comparación del performance del proceso optimizado vs. el baseline sin optimización: cómo definir el baseline, cómo controlar las variables externas como el precio de los productos y el precio de la energía), dashboard de valor del cliente (que muestre en tiempo real el ahorro acumulado desde el inicio del contrato, el ROI del cliente en %, el payback period) y cómo el customer success manager usa ese dashboard en las conversaciones de renovación, proceso de quarterly business review con el cliente (qué revisar, qué métricas presentar, qué roadmap compartir para justificar la renovación y la expansión) y sistema de detección temprana de clientes en riesgo de no renovación.

7. Desarrollo de la comunidad técnica y liderazgo de pensamiento: En el sector de la optimización industrial, la credibilidad técnica es el principal activo de marketing. Diseña la estrategia. Incluye: programa de publicación de casos de estudio con clientes (métricas reales de ahorro anonimizadas, proceso técnico de la implementación, lecciones aprendidas), participación en los congresos técnicos del sector petroquímico (AFPM Annual Meeting, European Refining Technology Conference, ERTC) con presentaciones técnicas de los resultados de la plataforma, desarrollo de la comunidad de ingenieros de proceso que usan la plataforma (foro online, webinars técnicos mensuales, programa de certificación de usuarios avanzados) y cómo el liderazgo técnico en publicaciones especializadas (Hydrocarbon Processing, Oil & Gas Journal) construye el pipeline de ventas a largo plazo.

Incluye framework de priorización de producto, plantilla de business case para la extensión de la plataforma a nuevas unidades y metodología de medición del ROI del cliente para presentar en renovaciones.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Expansión de plataforma SaaS de optimización de refinerías a nuevas unidades de proceso con modelo de valor compartido',
                'vote_score'       => 50,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión de personas y seguridad laboral en la industria química con IA',
                'description'      => 'Diseña sistemas de gestión de personas para plantas químicas que integran la seguridad laboral, la formación técnica y el desarrollo profesional en entornos de alta criticidad y alta regulación.',
                'prompt_content'   => <<<'EOT'
Eres un director de Recursos Humanos especializado en la industria química y petroquímica, con experiencia en la gestión de personas en entornos de proceso continuo, la gestión de la seguridad laboral en plantas con sustancias peligrosas, la formación técnica de operadores y la gestión de relaciones laborales en sectores con alta sindicalización y convenios colectivos complejos.

Contexto de la planta:
- Planta de producción de polietileno con 280 trabajadores (180 operadores de planta, 60 técnicos de mantenimiento y 40 personas en funciones de soporte: ingeniería, calidad, logística, administración)
- La planta opera en régimen de turnos 24x7 (cuatro equipos de trabajo rotativos)
- Sector muy regulado: Directiva Seveso III por el uso de etileno, obligaciones del Reglamento REACH para la gestión química, convenio colectivo de la industria química
- Principales retos de RRHH: envejecimiento de la plantilla (edad media 48 años), dificultad para captar operadores cualificados, alta tasa de accidentabilidad en las operaciones de mantenimiento y resistencia al cambio hacia los nuevos sistemas digitales

Desarrolla el sistema completo de gestión de personas para la planta química:

1. Gestión de la seguridad laboral y cultura de seguridad: En una planta Seveso, la seguridad es la primera prioridad. Diseña el sistema. Incluye: modelo de gestión de la seguridad laboral basado en el liderazgo visible (qué comportamientos de seguridad deben mostrar los mandos intermedios y la dirección para que los operadores los adopten), sistema de observaciones de seguridad de los compañeros (programas tipo STOP o BBS: cómo funcionan, cómo evitar que se conviertan en una burocracia de papeleo sin impacto real), proceso de investigación de accidentes e incidentes sin culpa (cómo crear el ambiente donde los operadores reportan los cuasi-accidentes sin miedo a las consecuencias, cómo hacer el análisis de causa raíz con metodología SCAT o RCAT) y gestión específica de la seguridad durante las operaciones de mantenimiento, que son el momento de mayor riesgo en una planta química (permisos de trabajo, bloqueos LOTO, trabajo en espacios confinados, trabajos en caliente).

2. Formación técnica de operadores en proceso continuo: Los operadores de planta química necesitan una formación técnica exigente. Diseña el sistema. Incluye: programa de formación inicial del operador nuevo (duración, contenidos: proceso productivo, sistemas de control, procedimientos de operación, gestión de emergencias, primeros auxilios y respuesta a emergencias químicas), sistema de cualificación progresiva del operador (niveles de competencia: operador en formación → operador básico → operador cualificado → operador senior → mentor de nuevos operadores, con criterios objetivos de ascenso entre niveles), programa de formación continua para operadores cualificados (actualización en nuevos procedimientos, simulacros de emergencia, formación en los nuevos sistemas digitales de la planta) y uso del simulador de proceso para la formación de los operadores en situaciones anómalas y de emergencia sin riesgo para la planta.

3. Gestión del relevo generacional y captación de talento técnico: La planta tiene un problema serio de relevo generacional. Diseña el sistema. Incluye: plan de relevo para los operadores y técnicos que se jubilarán en los próximos 5 años (mapeo de los conocimientos críticos que cada persona mayor tiene y que hay que transferir antes de su salida), programa de captación de operadores y técnicos de mantenimiento en colaboración con los centros de formación profesional de la zona (becas, prácticas, programa de acogida), propuesta de valor al empleado técnico de la industria química (qué puede ofrecer la planta que otras industrias no ofrecen: estabilidad, salario por encima de la media del sector, desarrollo técnico, orgullo de trabajar en una industria de proceso compleja) y proceso de captación de ingenieros de proceso y técnicos de mantenimiento especializado (instrumentación, electricidad, mecánica de maquinaria rotativa) en un mercado con escasez de perfiles técnicos.

4. Gestión de turnos y conciliación en el proceso continuo: Los turnos rotativos generan desafíos específicos de gestión. Diseña el sistema. Incluye: modelo de rotación de turnos que minimice el impacto en la salud de los trabajadores (cuántos días en cada turno, el sentido de la rotación: ¿en el sentido de las agujas del reloj o al contrario?, el número de días de descanso entre turnos) y cómo comparar diferentes modelos de rotación con los trabajadores, gestión de las ausencias en el turno (baja por enfermedad, vacaciones, permisos) cuando el proceso continuo no puede parar, sistema de comunicación entre turnos para asegurar la transferencia de información crítica del proceso y de los incidentes del turno anterior al turno siguiente y estrategia de conciliación para los trabajadores en turno (cómo facilitar el acceso a la formación, a las citas médicas, a las actividades escolares de los hijos).

5. Relaciones laborales y negociación del convenio colectivo: La industria química tiene una larga historia de sindicalización. Diseña el sistema. Incluye: diagnóstico del clima de relaciones laborales en la planta (nivel de confianza entre empresa y comité de empresa, temas recurrentes de conflicto, historia de las últimas negociaciones del convenio), estrategia de comunicación con el comité de empresa en el día a día (no esperar a la negociación del convenio para relacionarse, sino construir una relación de confianza continua), preparación de la negociación del convenio colectivo (qué puede dar la empresa, qué no puede dar, cuáles son las líneas rojas, cómo construir el paquete negociador que sea aceptable para el comité), gestión de los conflictos laborales cuando no se llega a un acuerdo (huelga de celo, trabajo a reglamento, huelga: cómo gestionar cada situación y cómo minimizar el impacto en la producción) y gestión del impacto del convenio de industria química a nivel nacional en el convenio de empresa.

6. Digitalización y resistencia al cambio en la planta química: La industria química está en proceso de digitalización. Diseña el sistema de gestión del cambio. Incluye: diagnóstico de la resistencia al cambio de los operadores de más edad ante la introducción de los nuevos sistemas digitales (por qué resisten: miedo a perder el trabajo, inseguridad con la tecnología, desconfianza en los datos del sistema vs. su experiencia), estrategia de gestión del cambio para la introducción del sistema SCADA nuevo (cómo involucrar a los operadores en el proceso de diseño, cómo formarlos en el nuevo sistema, cómo gestionar los primeros meses de operación cuando hay problemas y los trabajadores quieren volver al sistema antiguo), gestión de los operadores senior que son los más resistentes pero también los que más conocimiento del proceso tienen (cómo aprovechar su experiencia en la transición digital) y comunicación de la digitalización como herramienta de apoyo al operador, no de sustitución del operador.

7. KPIs de RRHH en la industria química: Define el sistema de medición de la gestión de personas. Incluye: KPIs de seguridad laboral (tasa de frecuencia de accidentes con baja, tasa de gravedad, número de cuasi-accidentes reportados, cumplimiento de las observaciones de seguridad planeadas), KPIs de desarrollo de personas (porcentaje de operadores en cada nivel de cualificación, horas de formación por trabajador y año, tasa de cobertura interna de las posiciones de relevo críticas), KPIs de clima laboral y retención (tasa de rotación voluntaria, resultado de la encuesta de clima anual, número de conflictos laborales abiertos con el comité de empresa) y reporting mensual de RRHH para la dirección de la planta (incluyendo la conexión entre los indicadores de personas y los indicadores de seguridad y productividad de la planta).

Incluye plantilla de plan de formación anual para operadores de turno, protocolo de investigación de accidentes adaptado al sector químico y sistema de cualificación progresiva de operadores.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Gestión del relevo generacional y la cultura de seguridad en planta química con régimen de turnos',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Control de costes y optimización financiera de operaciones en refinerías y plantas químicas con IA',
                'description'      => 'Gestiona y optimiza los costes de producción, el margen de refino y la asignación de recursos en operaciones petroquímicas complejas usando IA para la modelización económica y la toma de decisiones.',
                'prompt_content'   => <<<'EOT'
Eres un director financiero especializado en la industria química y petroquímica, con experiencia en el control de costes de producción de proceso continuo, la modelización del margen de refino, la optimización de la planificación de producción con restricciones económicas y la evaluación financiera de inversiones en activos industriales complejos.

Contexto de la empresa:
- Refinería de 7 millones de toneladas anuales de capacidad de carga en el sur de Europa
- El margen de refino ha bajado significativamente en los últimos 2 años por el diferencial de precios entre el crudo y los productos refinados
- Costes de producción: 12 euros por barril (energía, catalizadores, mantenimiento, personal y overheads)
- Objetivo: reducir el coste de producción en 2 euros por barril en 18 meses sin reducir la producción ni la seguridad
- Mayor fuente de ineficiencia identificada: el consumo de energía en las unidades de destilación (35% del coste total de producción)

Desarrolla el sistema completo de control financiero de la operación refinera:

1. Modelización del margen de refino y la economía de la refinería: El margen de refino es el KPI económico central de la operación. Diseña el modelo. Incluye: composición del margen de refino (precio del crudo de referencia → rendimiento de los productos por tipo de crudo → precio de los productos refinados → costes de energía → costes de catalizadores y aditivos → costes fijos de operación → margen neto por barril), modelo de optimización del mix de crudos (cómo seleccionar el crudo de menor coste total que maximiza el margen dado el diferencial entre crudos de distinta calidad, las restricciones de proceso y las especificaciones de los productos finales), herramienta de planificación de la producción orientada al margen económico (linear programming con restricciones de capacidad de cada unidad, especificaciones de calidad de los productos y compromisos de suministro) y proceso de seguimiento mensual del margen real vs. el margen planificado con análisis de las desviaciones.

2. Optimización del coste de energía en las operaciones de destilación: La energía es el mayor coste operativo de una refinería. Diseña el plan de reducción. Incluye: auditoría energética de las unidades de destilación (columna de destilación atmosférica, columna de vacío, unidad de destilación de naftas): cuánto consume cada unidad, dónde se pierden calorías, cuáles son las ineficiencias de intercambio de calor, análisis de los pinch points del tren de precalentamiento del crudo para identificar oportunidades de recuperación de calor adicional con nueva superficie de intercambio, implementación de un sistema de optimización en tiempo real del consumo de vapor y combustible de los hornos de proceso (ajuste de la temperatura de salida del horno basado en la composición de la alimentación y el objetivo del producto), cálculo del ROI de las inversiones en mejora de eficiencia energética (nuevos intercambiadores de calor, optimización del proceso de destilación, sistemas de recuperación de vapor) y sistema de seguimiento del KPI de consumo de energía por barril procesado con alertas cuando se desvía del objetivo.

3. Control de costes de mantenimiento y gestión de activos: El mantenimiento es el segundo mayor coste después de la energía. Diseña el sistema. Incluye: modelo de costes de mantenimiento por tipo (mantenimiento preventivo planificado, mantenimiento predictivo basado en condición, mantenimiento correctivo no planificado) y cuál es el mix óptimo para minimizar el coste total (el mantenimiento preventivo excesivo es tan caro como el correctivo), proceso de presupuestación del mantenimiento anual (cómo estimar los costes de las paradas de planta mayores, el mantenimiento rutinario de equipos estáticos y rotantes, los repuestos críticos a mantener en stock) y gestión de las paradas de planta mayores (turnarounds): cómo controlar que no se dispara el presupuesto durante la ejecución de la parada, sistema de análisis del coste de los fallos de equipos (coste directo de la reparación + coste de la producción perdida: este es el argumento económico para el mantenimiento predictivo) y optimización del stock de repuestos críticos (cuántos y cuáles tener, cuánto cuesta tenerlos inmovilizados en almacén vs. el coste del lead time si no los tenemos cuando los necesitamos).

4. Evaluación financiera de inversiones en la refinería: Las refinerías tienen proyectos de inversión de cientos de millones de euros. Diseña el proceso. Incluye: metodología de evaluación de proyectos de inversión en activos industriales (VAN, TIR, payback, análisis de sensibilidad de los supuestos críticos: precio del crudo, margen de refino, tasa de disponibilidad de la unidad), proceso de priorización del portfolio de proyectos de inversión cuando el CAPEX disponible es menor que la suma de todos los proyectos aprobados (criterios técnicos y económicos, gestión de las interdependencias entre proyectos), evaluación específica del proyecto de instalación de una unidad de hidrocracking (inversión de 400 millones de euros, incremento de la capacidad de conversión del fuel oil de menor valor en gasolina y gasóleo de mayor valor, análisis de la viabilidad a distintos escenarios de margen de refino) y cómo presentar la decisión de inversión al consejo de administración combinando el análisis técnico con el análisis financiero.

5. Planificación financiera y presupuesto operativo anual: La refinería es una operación de capital intensivo con costes muy variables. Diseña el proceso. Incluye: proceso de elaboración del presupuesto anual de operaciones (qué supuestos macroeconómicos usar: precio del crudo, tipo de cambio, precio de los productos refinados en los mercados de referencia, coste de la energía; cómo presupuestar los costes variables de producción y los costes fijos de la refinería), proceso de revisión trimestral del presupuesto y reforecast cuando las condiciones de mercado cambian significativamente (el precio del crudo puede variar un 30-50% respecto al supuesto presupuestario), gestión de las coberturas financieras (hedging) del precio del crudo y de los productos refinados para reducir la volatilidad del margen y análisis de la viabilidad financiera de la refinería en el contexto de la transición energética (cuántos años de vida útil tiene la refinería dado el escenario de electrificación del transporte, cuándo se amortiza la inversión en la unidad de hidrocracking que se está considerando).

6. Código Python para la modelización económica de la refinería: Proporciona implementaciones concretas. Incluye: (a) modelo de programación lineal (usando PuLP o scipy.optimize.linprog) para la optimización del plan de producción de la refinería que maximiza el margen de refino dado el precio del crudo de entrada, los rendimientos de los productos de cada unidad de proceso y los precios de venta de los productos, (b) modelo de simulación de Monte Carlo para el análisis de la incertidumbre del margen de refino (qué distribución de probabilidad del margen esperamos dado la distribución de precios histórica del crudo y los productos), (c) herramienta de análisis de la curva de costes de la refinería por unidad de proceso (gráfico de coste por barril por unidad con el desglose en energía, catalizadores, personal y overheads) y (d) modelo de ROI de un proyecto de eficiencia energética con análisis de sensibilidad a la tasa de actualización y al ahorro de energía conseguido.

7. Reporting financiero para la dirección y para los socios: La refinería tiene múltiples stakeholders financieros. Diseña el sistema. Incluye: dashboard de gestión mensual de la refinería para el comité de dirección (margen de refino real vs. presupuesto, costes de producción por barril por categoría, producción total vs. plan, disponibilidad de las unidades principales, KPIs de seguridad), informe trimestral de resultados para los accionistas de la refinería (análisis de los resultados vs. el mercado de referencia, impacto de las principales desviaciones, outlook del próximo trimestre) y cómo comunicar los resultados de la refinería cuando el margen de refino está en mínimos por condiciones de mercado adversas.

Incluye modelos de Python comentados para la optimización de la producción, plantilla de análisis de inversiones para proyectos de refinería y dashboard de KPIs económicos de operaciones petroquímicas.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 80,
                'use_case'         => 'Optimización del margen de refino y reducción de costes operativos en refinería con modelos económicos y Python',
                'vote_score'       => 52,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Compliance regulatorio REACH, CLP y Seveso para la industria química con IA',
                'description'      => 'Navega el complejo marco regulatorio europeo de la industria química: REACH, CLP, Directiva Seveso III y normativa de transporte de mercancías peligrosas con IA como asistente jurídico especializado.',
                'prompt_content'   => <<<'EOT'
Eres un abogado y experto en regulación química especializado en el derecho de la industria química y petroquímica europeo, con experiencia en la aplicación del Reglamento REACH, el Reglamento CLP de clasificación y etiquetado, la Directiva Seveso III sobre riesgos de accidentes graves, la normativa de transporte de mercancías peligrosas (ADR, IMDG, IATA) y la regulación de la gestión de residuos químicos peligrosos en España y Europa.

Contexto de la consulta:
- Empresa fabricante de disolventes industriales con dos plantas de producción en España (Tarragona y Huelva) y venta en 15 países europeos
- Facturación: 85 millones de euros anuales
- Problema legal: la empresa tiene dudas sobre la correcta clasificación de varios de sus productos bajo CLP, ha recibido una consulta de la ECHA sobre su expediente de registro REACH para uno de sus disolventes principales y se está preparando para un cambio de proceso que podría cambiar el estatus Seveso de la planta de Tarragona
- Necesidad: revisión completa del marco de compliance regulatorio y preparación de la respuesta a la ECHA

Desarrolla el asesoramiento regulatorio completo:

1. Registro REACH y gestión del expediente: El REACH es el marco regulatorio más complejo del sector químico. Explica y asesora. Incluye: estructura de un expediente de registro REACH completo (qué contiene el Chemical Safety Report: la evaluación de la exposición y el riesgo, las condiciones de uso seguro, los escenarios de exposición; qué contiene el expediente técnico: la información sobre las propiedades fisicoquímicas, toxicológicas y ecotoxicológicas), análisis de las causas más frecuentes de las consultas de la ECHA a los registrantes (datos de toxicología insuficientes, escenarios de exposición incompletos, falta de justificación de los waiving de ensayos), proceso de respuesta a una consulta de la ECHA dentro del plazo (qué documentación aportar, cómo justificar las posiciones científicas de la empresa, cuándo solicitar una reunión técnica con la ECHA) y gestión de la evaluación REACH del sustancia (cuando la ECHA incluye la sustancia en el plan de acción comunitario y asigna el expediente a una autoridad nacional para evaluación).

2. Clasificación y etiquetado CLP: La clasificación CLP determina las obligaciones de seguridad de todos los productos. Diseña el proceso. Incluye: metodología de clasificación de un disolvente industrial bajo el Reglamento CLP (cómo interpretar los criterios de clasificación para los peligros físicos, de salud humana y para el medio ambiente, con ejemplos prácticos de clasificación de disolventes comunes como el tolueno, el xileno o el MEK), gestión de las discrepancias entre la clasificación armonizada (CLH) si existe para la sustancia y la autoclasificación del fabricante, diseño del sistema de gestión de las fichas de datos de seguridad (FDS) bajo el Reglamento 2020/878 (qué secciones han cambiado respecto a las FDS anteriores, cómo gestionar las actualizaciones de las FDS cuando cambia la clasificación de un ingrediente), comunicación de las FDS a los clientes en los 15 países europeos (idiomas requeridos, obligaciones de actualización cuando cambia la composición o la clasificación) y gestión de los incidentes de clasificación errónea detectados en el mercado (cómo actuar cuando un distribuidor o un cliente comunica que el producto está mal clasificado).

3. Directiva Seveso III y evaluación del riesgo de accidente grave: Las plantas de Tarragona y Huelva pueden estar afectadas por Seveso. Diseña el proceso. Incluye: criterios para determinar si una instalación química cae bajo el umbral de establecimiento de nivel inferior o superior de Seveso III (qué cantidades umbral se aplican a los disolventes inflamables y a las sustancias tóxicas, cómo se calcula el índice de adición cuando hay varias sustancias peligrosas), análisis específico del impacto del cambio de proceso previsto en Tarragona sobre el estatus Seveso de la instalación (si el cambio introduce una nueva sustancia o aumenta la cantidad de una sustancia existente por encima de un umbral), obligaciones del establecimiento Seveso de nivel superior (Informe de Seguridad, Plan de Emergencia Interior, Plan de Emergencia Exterior con las autoridades, política de prevención de accidentes graves), proceso de notificación del cambio del establecimiento Seveso ante la autoridad competente (en España, las Comunidades Autónomas) antes de ejecutar el cambio de proceso y gestión de las inspecciones Seveso de las autoridades competentes.

4. Transporte de mercancías peligrosas: Los disolventes son mercancías peligrosas en cualquier modo de transporte. Diseña el sistema de compliance. Incluye: clasificación de los principales disolventes de la empresa bajo la normativa ADR (transporte por carretera), IMDG (transporte marítimo) e IATA (transporte aéreo), obligaciones del expedidor de mercancías peligrosas (documento de transporte, marcado y etiquetado del embalaje, instrucciones escritas al conductor, declaración del expedidor), gestión del programa de formación de los empleados que intervienen en el transporte de mercancías peligrosas (quién necesita el certificado ADR, qué categoría, con qué periodicidad se renueva), auditoría del compliance de los transportistas que trabajan con la empresa (cómo verificar que las empresas de transporte contratadas tienen los certificados ADR requeridos, los vehículos homologados y los conductores certificados) y gestión de incidentes durante el transporte (derrame de disolvente en carretera: obligaciones de notificación, plan de respuesta de emergencia).

5. Gestión de residuos químicos peligrosos: Los residuos de la producción de disolventes son peligrosos. Diseña el sistema. Incluye: clasificación de los residuos generados en la producción de disolventes bajo el Catálogo Europeo de Residuos (CER/LER) y la lista de residuos peligrosos, obligaciones del productor de residuos peligrosos en España (registro como productor de residuos, libro de registro, declaración anual de residuos, contrato con gestor autorizado, acreditación del tratamiento final), gestión de los residuos de laboratorio (reactivos caducados, muestras de producto, disolventes de limpieza: cómo gestionarlos de forma conforme), estrategia de minimización de residuos y economía circular (recuperación y reciclaje de disolventes residuales para reducir el coste de gestión y el impacto medioambiental) y gestión de las autoridades de residuos en las dos comunidades autónomas donde opera la empresa (Cataluña y Andalucía tienen sistemas de autorización distintos).

6. Autorización ambiental integrada y emisiones industriales: Las plantas de producción de disolventes están sujetas a la Directiva de Emisiones Industriales. Diseña el sistema. Incluye: obligaciones de la Autorización Ambiental Integrada (AAI) de las plantas de Tarragona y Huelva (qué parámetros se controlan, con qué frecuencia se reporta a la autoridad, cuáles son los valores límite de emisión de COV a la atmósfera), aplicación de las MTD (Mejores Técnicas Disponibles) definidas en los documentos BREF de la industria química orgánica (qué técnicas de reducción de emisiones son obligatorias, cuáles son opcionales), proceso de revisión periódica de la AAI cuando cambia el BREF de referencia (cuánto plazo tiene la empresa para adaptar sus instalaciones a las nuevas MTD), gestión del sistema de medición continua de emisiones (SCAE) y reporting a la autoridad competente y preparación de las renovaciones de la AAI cuando vence el período de validez.

7. Gestión de la inspección y las sanciones ambientales: La industria química está sujeta a inspecciones frecuentes. Diseña el protocolo. Incluye: tipos de inspecciones que puede recibir la empresa (inspección Seveso, inspección de la AAI, inspección de residuos peligrosos, inspección ADR de los transportistas) y qué autoridades las realizan en España, proceso de preparación de la empresa para una inspección ambiental (qué documentación tiene que estar disponible y actualizada, cómo gestionar la visita del inspector en la planta, qué derechos tiene la empresa durante la inspección), proceso de respuesta a un pliego de cargos o un expediente sancionador (plazos de alegaciones, argumentación de las posiciones de la empresa, opciones de acuerdo con la administración) y régimen sancionador de la Ley de Responsabilidad Medioambiental y la Ley de Residuos y Suelos Contaminados (importes máximos de las sanciones, criterios de graduación, posibilidad de reparación voluntaria del daño ambiental para reducir la sanción).

Incluye checklist de compliance REACH-CLP-Seveso para fabricantes de disolventes, plantilla de gestión del expediente REACH y guía de preparación de inspecciones ambientales para el sector químico.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Compliance regulatorio REACH, Seveso y emisiones industriales para fabricante de disolventes con operaciones en dos plantas',
                'vote_score'       => 47,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Soporte técnico y atención al cliente en distribución de productos químicos con IA',
                'description'      => 'Diseña sistemas de atención técnica y soporte posventa para distribuidores de productos químicos industriales, desde la asistencia en la selección del producto hasta la gestión de reclamaciones de calidad.',
                'prompt_content'   => <<<'EOT'
Eres un director de customer success y soporte técnico especializado en la distribución de productos químicos industriales. Tu experiencia abarca la atención técnica a clientes industriales, la gestión de reclamaciones de calidad de productos químicos, el diseño de sistemas de soporte para distribuidores multimarca y la formación de equipos de soporte técnico en sectores con alto contenido técnico como la industria textil, pinturas, tratamiento de aguas y plastificantes.

Contexto de la empresa:
- Distribuidor de especialidades químicas con 350 clientes activos en España y Portugal
- Equipo de soporte técnico: 5 técnicos de aplicaciones + 1 coordinadora de customer service
- Líneas de producto: aditivos para pinturas (40%), especialidades textiles (30%), productos de tratamiento de aguas (30%)
- Problema: el equipo técnico dedica el 60% del tiempo a responder consultas repetitivas que podrían resolverse con mejores herramientas de autoservicio, y el 40% a problemas técnicos reales que necesitan su expertise
- NPS: 52, el principal driver negativo es el tiempo de respuesta a las consultas técnicas (objetivo: menos de 4 horas)

Desarrolla el sistema completo de soporte técnico y customer success para el distribuidor químico:

1. Clasificación y enrutamiento de consultas técnicas: No todas las consultas técnicas requieren la misma atención. Diseña el sistema. Incluye: taxonomía de los tipos de consultas técnicas en distribución química (consulta de selección de producto: qué producto usar para una aplicación específica; consulta de formulación: cómo formular una pintura o un auxiliar textil con los productos disponibles; consulta de dosificación y aplicación: cuánto usar y cómo aplicarlo; resolución de problemas: el producto no está dando el resultado esperado en el proceso del cliente; reclamación de calidad: el producto no cumple las especificaciones), sistema de enrutamiento de cada tipo de consulta al recurso adecuado (consulta simple → base de conocimiento; consulta de formulación → técnico de aplicaciones vía email; problema en planta → técnico de aplicaciones vía teléfono o visita; reclamación de calidad → proceso formal de reclamación) y criterios de escalación de una consulta al fabricante representado cuando el equipo técnico propio no tiene la respuesta.

2. Base de conocimiento técnico para el autoservicio del cliente: El 60% de las consultas son repetitivas y pueden resolverse con autoservicio. Diseña el sistema. Incluye: estructura de la base de conocimiento técnico (por línea de producto, por sector de aplicación, por tipo de consulta: selección, dosificación, resolución de problemas), proceso de creación del contenido de la base de conocimiento (cómo transformar el conocimiento del técnico de aplicaciones en artículos estructurados que el cliente pueda consultar de forma autónoma), sistema de búsqueda inteligente de la base de conocimiento (búsqueda por síntoma del problema, por nombre del producto, por sector de aplicación), proceso de actualización de la base de conocimiento cuando se introduce un nuevo producto o cuando se detecta un problema nuevo en el mercado y métricas de uso de la base de conocimiento (qué artículos se consultan más, qué búsquedas no encuentran resultado y son candidatas a nuevo contenido, qué porcentaje de las consultas al equipo técnico se resuelven con autoservicio).

3. Gestión de reclamaciones de calidad de productos químicos: Las reclamaciones de calidad son el momento de la verdad en la distribución química. Diseña el proceso. Incluye: proceso de recepción y registro de la reclamación de calidad (qué información recoger: descripción del problema, lote del producto, condiciones de almacenamiento y aplicación, impacto en el proceso del cliente), proceso de investigación de la causa raíz de la reclamación (qué análisis de la muestra del producto hacer, cómo investigar si el problema es del producto o de las condiciones de aplicación del cliente, cuándo involucrar al fabricante en la investigación), protocolo de comunicación con el cliente durante la investigación (tiempo máximo de respuesta en cada fase, cómo comunicar los resultados aunque no sean favorables para la empresa), proceso de resolución y compensación al cliente (sustitución del producto defectuoso, descuento en el próximo pedido, visita técnica gratuita para resolver el problema) y proceso de reclamación al fabricante cuando la causa raíz del problema está en el producto.

4. Asistencia técnica de formulación y aplicación: El técnico de aplicaciones es el mayor activo de diferenciación del distribuidor. Diseña el sistema. Incluye: proceso de asistencia técnica en la formulación de pinturas acuosas para el cliente de la línea de aditivos (cómo ayudar al cliente a seleccionar el espesante, el dispersante, el agente coalescente y el biocida más adecuados para su formulación objetivo), proceso de asistencia técnica en la resolución de problemas de proceso textil (cómo diagnosticar por qué un auxiliar textil no está dando el resultado esperado en la máquina de tintura del cliente: problemas de agua, temperatura, pH, compatibilidad con otros productos en el baño), servicio de análisis de agua para el cliente de tratamiento de aguas (antes de recomendar el producto de tratamiento, el técnico analiza la composición del agua del cliente: dureza, pH, conductividad, biocarga), documentación del outcome de cada asistencia técnica (qué producto se recomendó, qué resultado obtuvo el cliente, qué se aprendió para la base de conocimiento) y proceso de seguimiento post-asistencia para asegurar que el cliente ha obtenido el resultado esperado.

5. Onboarding de nuevos clientes en el catálogo de productos: Los primeros 90 días del cliente determinan si se convierte en un cliente fiel. Diseña el proceso. Incluye: flujo de onboarding de un nuevo cliente de la línea de pinturas (primera visita técnica: diagnóstico de las necesidades de formulación del cliente, selección de los 3-5 productos prioritarios para probar; primera semana: envío de muestras y fichas técnicas de aplicación; primer mes: seguimiento del resultado de las pruebas y ajuste de la selección; tercer mes: revisión del uso de los productos y propuesta de expansión a otros productos de la gama), materiales de onboarding específicos para cada línea de producto (guía de inicio para pinturas: cómo incorporar los aditivos al proceso de fabricación de la pintura; guía de inicio para textil: cómo integrar los auxiliares en el proceso de tintura; guía de inicio para tratamiento de aguas: cómo dosificar y controlar los productos de tratamiento) y proceso de cualificación técnica de los productos nuevos con el cliente (cómo estructurar una prueba de producto que genera datos de rendimiento comparables con el producto del proveedor anterior).

6. Programa de formación técnica para los clientes: Los clientes que más saben del producto lo usan mejor y compran más. Diseña el programa. Incluye: programa de webinars técnicos mensuales para los diferentes segmentos de clientes (webinar de pinturas: técnicas de formulación de pinturas acuosas de bajo VOC; webinar de textil: tendencias en auxiliares textiles sostenibles; webinar de tratamiento de aguas: normativa sobre biocidas y su impacto en los tratamientos de torres de refrigeración), visitas técnicas grupales a las instalaciones del fabricante representado para los clientes más importantes (conocer el proceso de fabricación del producto que compran aumenta la confianza en el proveedor), programa de formación de los técnicos del cliente en el uso seguro y eficiente de los productos (cursos presenciales en las instalaciones del cliente), biblioteca de recursos técnicos en vídeo (tutoriales de aplicación de los productos más complejos, vídeos de resolución de los problemas más frecuentes) y certificación de cliente avanzado para los clientes que han completado la formación y se comprometen a ser referencias para otros clientes.

7. KPIs y gestión del equipo de soporte técnico: Define el sistema de medición del soporte. Incluye: KPIs del equipo de soporte técnico (tiempo medio de primera respuesta a las consultas por tipo, tasa de resolución en el primer contacto, NPS post-asistencia técnica, número de visitas técnicas a cliente realizadas por técnico y mes, número de consultas resueltas con autoservicio vs. consultas atendidas por el equipo técnico), gestión del tiempo del técnico de aplicaciones (qué porcentaje de su tiempo debe dedicar a consultas entrantes, a visitas proactivas, a creación de contenido para la base de conocimiento y a formación), sistema de incentivos del equipo de soporte técnico (qué comportamientos se premian: satisfacción del cliente, tasa de autoservicio, contribución a la base de conocimiento) y proceso de desarrollo profesional de los técnicos de aplicaciones (cómo crecer dentro de la empresa: técnico de aplicaciones → técnico senior → director técnico).

Incluye plantilla de registro de reclamación de calidad química, árbol de decisión para el diagnóstico de problemas técnicos en pinturas y sistema de seguimiento de asistencias técnicas por cliente.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Sistema de soporte técnico y base de conocimiento para distribuidor de especialidades químicas',
                'vote_score'       => 36,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultor freelance de procesos y optimización para la industria química con IA',
                'description'      => 'Construye y escala tu práctica de consultoría independiente en ingeniería de procesos y optimización de plantas químicas usando IA para ofrecer más valor a tus clientes industriales con mayor eficiencia.',
                'prompt_content'   => <<<'EOT'
Eres un consultor freelance de ingeniería de procesos y optimización industrial especializado en la industria química y petroquímica. Después de 15 años como ingeniero de proceso en una gran refinería y 3 años en una consultora de gestión industrial, decidiste lanzar tu práctica independiente para trabajar en proyectos de mayor impacto con más autonomía.

Situación de tu práctica freelance:
- Consultor independiente de ingeniería de procesos con 5 años de práctica propia
- Servicios: auditorías de eficiencia energética de procesos, optimización de operaciones de destilación, proyectos de mejora del margen de refino, formación técnica de ingenieros de proceso
- Clientes actuales: 4 clientes (2 refinerías, 1 planta petroquímica, 1 empresa química de especialidades), contratos de 3-6 meses de duración
- Facturación anual: 145.000 euros (principalmente proyectos de optimización de procesos)
- Mayor limitación: los proyectos son muy técnicos y dependen de tu presencia física en la planta, lo que limita la escala sin replicarte a ti mismo

Desarrolla el sistema completo para escalar tu práctica de consultoría de ingeniería de procesos:

1. Posicionamiento y especialización para cobrar honorarios premium: Para subir tus tarifas diarias, necesitas la especialización correcta. Diseña el posicionamiento. Incluye: los nichos de especialización dentro de la ingeniería de procesos química donde hay escasez de expertos y disposición a pagar honorarios altos (optimización de unidades FCC, reducción de emisiones de CO2 en procesos de alta temperatura, transición de procesos a feedstocks renovables, optimización de eficiencia energética bajo el EU ETS), argumentos para subir tu tarifa diaria de 1.200 a 2.000 euros sin perder los clientes actuales (qué resultados económicos cuantificables has conseguido que justifican el premium, cómo enmarcar la conversación como inversión con ROI garantizado), diseño de la propuesta de valor de tu práctica que la diferencia de la consultoría de las grandes firmas (rapidez de movilización, acceso directo al experto en la planta, sin overhead de cuenta comercial ni generalist junior) y cómo comunicar tu especialización en LinkedIn y en la comunidad de ingenieros de proceso del sector para generar inbound.

2. IA para multiplicar la productividad técnica: La IA puede reducir el tiempo de las tareas analíticas y de documentación de tus proyectos. Diseña tu sistema. Incluye: uso de Claude para el análisis de datos de proceso (cómo estructurar el prompt para que Claude te ayude a identificar anomalías en los datos del historiador PI que exportas a CSV, sintetizar los patrones de ineficiencia en los datos de consumo energético de una unidad de destilación), uso de Python con IA para el modelado de procesos (cómo automatizar la construcción y validación de modelos de simulación de proceso a partir de los datos históricos del cliente, usando scikit-learn para los modelos de regresión de las propiedades del proceso), sistema de generación automatizada de los informes técnicos de tus proyectos (estructura estándar del informe de auditoría energética, uso de IA para generar el borrador del informe a partir de los datos analizados, tu valor añadido en la revisión e interpretación experta) y estimación del tiempo que la IA te ahorra por proyecto y cómo esa productividad se traduce en capacidad de atender más proyectos sin aumentar tus horas trabajadas.

3. Diseño de productos de consultoría que escalen más allá del tiempo facturable: La consultoría de tiempo facturable tiene un techo. Diseña productos escalables. Incluye: producto de auditoría energética estandarizada para plantas de destilación (proceso en 5 días, metodología estándar, entregable: informe de 30 páginas con las 10 principales oportunidades de ahorro cuantificadas, precio fijo de 8.000-12.000 euros), herramienta software de optimización de proceso como producto (una calculadora de Python que desarrollaste para tus proyectos que puedes empaquetar y licenciar a otras plantas del sector: modelo de optimización del plan de producción de una refinería, precio de licencia anual de 5.000-15.000 euros por planta), curso online de optimización de procesos de destilación para ingenieros de proceso (10 módulos de vídeo de 45 minutos, precio de 500-800 euros por participante, sin límite de participantes) y programa de mentoría para ingenieros de proceso junior que quieren especializarse en optimización (8 sesiones de 1 hora, precio de 2.000-3.000 euros por mentoría).

4. Desarrollo de un pipeline de proyectos senior en la industria química: Para tener proyectos sin parar, necesitas un sistema de captación. Diseña el sistema. Incluye: identificación del decisor que contrata a consultores de optimización en refinerías y plantas petroquímicas (director de operaciones, director de proceso, director de ingeniería: cómo llegar a cada uno), estrategia de networking en la comunidad de ingenieros de proceso del sector (participación en el Congreso Mediterráneo de Ingeniería Química, en los grupos de LinkedIn de procesos petroquímicos, en el EFCE European Federation of Chemical Engineering), uso de los casos de éxito de tus proyectos como motor de captación (cómo documentar el ahorro conseguido en cada proyecto, cómo pedir la referencia al cliente al final del proyecto, cómo usar esa referencia en el siguiente proyecto de la misma empresa o del mismo sector) y proceso de cualificación de nuevas oportunidades (cómo evaluar si un proyecto potencial es del tipo que puedes hacer bien y que te genera el margen adecuado).

5. Gestión de proyectos técnicos complejos como consultor independiente: Los proyectos de ingeniería de procesos son complejos y multidisciplinares. Diseña el sistema. Incluye: estructura de proyecto estándar para un proyecto de optimización de proceso (fases: diagnóstico del estado actual → identificación de oportunidades → análisis detallado de las mejores oportunidades → plan de implementación → acompañamiento en la implementación; entregables y hitos de pago por fase), gestión del proyecto cuando el cliente cambia el alcance a mitad del proyecto (cómo gestionar el change order, cómo mantener la relación con el cliente mientras se negocia el alcance adicional, cuándo decir que eso está fuera del contrato), gestión de los subcontratistas cuando el proyecto requiere capacidades que no tienes (cómo seleccionar a un especialista en simulación Aspen para una parte del proyecto, cómo gestionar la relación para que entregue calidad y en plazo sin comprometer tu reputación con el cliente) y proceso de entrega del proyecto y transferencia del conocimiento al equipo técnico del cliente.

6. Construcción de autoridad técnica y reputación sectorial: En consultoría técnica de alto nivel, la reputación es el activo más valioso. Diseña el sistema. Incluye: estrategia de publicación técnica (artículos en Hydrocarbon Processing, Chemical Engineering Progress, o en las revistas del sector de pinturas o tratamiento de aguas en función de tu especialización) con el proceso de identificar un tema relevante para el sector, escribir el artículo y gestionarlo editorialmente, participación como ponente en congresos técnicos del sector (cómo proponer una ponencia, cómo preparar una presentación que genere conversaciones de negocio sin ser una presentación de ventas), desarrollo de tu perfil de LinkedIn como ingeniero de proceso experto (qué contenido publicar, con qué frecuencia, cómo hacer que llegue a los directores de operaciones de las plantas que son tus clientes objetivo) y colaboración con fabricantes de equipos y software del sector (Aspen, Honeywell UOP, Alfa Laval: cómo convertirte en un experto de referencia para sus productos que les recomienda a sus clientes mientras tú ganas visibilidad y credibilidad).

7. Gestión financiera y fiscal de la práctica de ingeniería independiente: Con facturación de 145.000 euros en proyectos técnicos, la gestión financiera necesita estructura. Diseña el sistema. Incluye: modelo de ingresos mixto que combine los proyectos de consultoría (alta variabilidad mensual) con los ingresos recurrentes de las licencias de software y los cursos online (más predecibles), gestión del flujo de caja con proyectos de 3-6 meses de duración (cómo cobrar por hitos para no financiar al cliente, cómo gestionar los meses entre proyectos sin ingresos), estructura societaria recomendada para una consultoría técnica de este nivel de facturación (autónomo vs. SL: cuándo el ahorro fiscal justifica la complejidad de la SL), gestión fiscal de los ingresos internacionales cuando trabajas en proyectos para refinerías en otros países de Europa (IVA intracomunitario, impuesto de no residentes si trabajas más de 183 días en otro país, deducción de los gastos de desplazamiento y estancia) y plan financiero para los próximos 3 años con el escenario de crecimiento a 250.000 euros anuales con la combinación de proyectos, licencias y formación.

Incluye plantilla de propuesta técnica para proyectos de optimización de proceso, system prompt de Claude para el análisis de datos de proceso del historiador PI, y modelo financiero para la práctica de consultoría de ingeniería independiente.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 65,
                'use_case'         => 'Escalar la práctica de consultoría de ingeniería de procesos con IA y productos de conocimiento escalables',
                'vote_score'       => 46,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
