<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills602Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Marketing deportivo con IA para clubes de élite y ligas profesionales',
                'description'      => 'Diseña estrategias de marketing innovadoras con inteligencia artificial para clubes deportivos de élite, marcas deportivas y ligas profesionales, aumentando el engagement de fans, los ingresos por patrocinios y la visibilidad internacional.',
                'prompt_content'   => <<<'EOT'
Eres un director de marketing deportivo con experiencia en clubes de élite, ligas profesionales y marcas deportivas globales. Necesito tu ayuda para diseñar una estrategia de marketing completa impulsada por inteligencia artificial para un club de fútbol profesional de Primera División.

Contexto del club:
El club tiene una masa social de 45.000 socios, un estadio con capacidad para 35.000 espectadores con una tasa de ocupación media del 75%, presencia en redes sociales con 2 millones de seguidores en Instagram y 1,5 millones en Twitter/X, y contratos de patrocinio actuales por valor de 8 millones de euros anuales. El objetivo es aumentar los ingresos comerciales (patrocinios, merchandising y derechos digitales) en un 40% en los próximos dos años.

Objetivo de la estrategia:
Desarrolla el plan de marketing con IA que transforma la relación del club con sus fans y multiplica los ingresos comerciales.

Pilar 1 - Inteligencia de fans y segmentación con IA:
Describe cómo usar la IA para construir una visión completa de los distintos segmentos de fans del club. El sistema debe integrar datos de múltiples fuentes: el comportamiento de los socios en el estadio (partidos asistidos, productos comprados en el estadio, interacciones con el personal), el comportamiento en las plataformas digitales del club (app, web, contenidos consumidos), las interacciones en redes sociales (tipos de contenido que más comentan y comparten, hashtags que usan, qué rivales mencionan junto al club) y los datos de transacciones en la tienda oficial y el ecommerce. Define los segmentos más relevantes para la estrategia comercial: el ultrafan que asiste a todos los partidos y compra todo el merchandising (qué le mueve, cómo fidelizarlo), el fan casual que solo ve el partido cuando hay ambiente especial (cómo convertirlo en socio), el fan internacional que nunca ha pisado el estadio pero consume contenido del club en Latinoamérica o Asia (cómo monetizarlo con productos digitales), y el fan joven de menos de 25 años que nació en la era digital (cómo captar su atención frente a otros entretenimientos).

Pilar 2 - Estrategia de contenido digital con IA para redes sociales deportivas:
El deporte de élite tiene un ventaja única en marketing de contenidos: el drama, la emoción y los momentos únicos se generan solos en el campo. Diseña la estrategia de contenido con IA que maximiza el impacto de cada momento deportivo. Describe el sistema de producción de contenido en tiempo real: cómo la IA identifica los momentos de mayor potencial viral durante el partido (el gol, la celebración, la reacción del entrenador, el jugador en el banquillo) y los convierte en posts optimizados para Instagram Reels, TikTok y Twitter en menos de 5 minutos. Define la estrategia de contenido entre partidos: los behind-the-scenes del entrenamiento que generan más engagement, las historias personales de los jugadores que construyen conexión emocional con los fans, el contenido táctico-analítico para el segmento de fans más sofisticados y el contenido de entretenimiento para el fan casual. Describe cómo la IA optimiza el timing, el formato y los hashtags de cada post según el comportamiento histórico de la audiencia.

Pilar 3 - Estrategia de patrocinios con IA y activaciones de valor:
Los patrocinios deportivos representan la principal fuente de ingresos comerciales de los clubes de élite. Describe cómo usar la IA para maximizar el valor de los acuerdos de patrocinio actuales y atraer nuevos partners. Para la prospección de nuevos patrocinadores: el sistema debe identificar marcas con alto potencial de alineación con el club basándose en los valores de la marca, el perfil demográfico de sus clientes y los mercados geográficos donde la marca quiere crecer (si el club tiene fanbase relevante en esos mercados). Para la activación de los patrocinios existentes: describe cómo la IA mide el retorno real de la visibilidad del patrocinador en el estadio, en las transmisiones televisivas y en las redes sociales del club (impresiones, exposición de marca en pantalla, menciones sociales durante y después de los partidos), y cómo usa estos datos para presentar reportes de valor a los patrocinadores que justifican la renovación y el incremento del fee.

Pilar 4 - Experiencia del fan en el estadio con IA:
La experiencia en el estadio es el producto diferencial del deporte en vivo frente al streaming. Describe cómo la IA mejora la experiencia del fan desde antes de llegar al estadio hasta después del partido. Antes del partido: personalización de las comunicaciones previas según el segmento del fan (para el ultranadie el resumen de bajas y posible alineación, para el fan casual el ambiente del partido y la forma de llegar al estadio sin atascos). Durante el partido: aplicación del club con estadísticas en tiempo real personalizadas según el tipo de fan, sistema de pedido de comida y bebida desde el asiento sin hacer cola, y replay de las jugadas clave en el móvil. Después del partido: análisis táctico personalizado del partido enviado al día siguiente, encuesta de satisfacción de la experiencia e invitación personalizada al siguiente partido basada en el comportamiento del fan durante el partido de hoy. Define cómo todos estos touchpoints alimentan el perfil de datos del fan y mejoran la personalización en cada interacción sucesiva.

Pilar 5 - Internacionalización y monetización de la fanbase global con IA:
Los grandes clubes europeos tienen fanases masivas en Asia, América Latina y el Oriente Medio que nunca visitarán el estadio pero son un mercado de ingresos enormemente infraexplotado. Describe la estrategia de monetización de la fanbase internacional con IA. Define la propuesta de valor digital para el fan internacional: suscripciones de contenido premium exclusivo en plataformas OTT propias del club o en acuerdos con DAZN y YouTube Premium, NFTs de momentos históricos del club (goles legendarios, camisetas de campeones) que funcionan como coleccionables digitales para fans globales, y academias virtuales de fútbol con los métodos del primer equipo para jóvenes jugadores de todo el mundo. Describe cómo la IA personaliza la experiencia del fan internacional según su mercado geográfico: el contenido en mandarín para el fan chino, los horarios de publicación adaptados a sus zonas horarias, las referencias culturales específicas de cada mercado y los canales de pago locales que eliminan la fricción en la monetización.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 55,
                'use_case'         => 'Estrategia de marketing deportivo con IA para club de fútbol profesional de élite',
                'vote_score'       => 43,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de plataformas de análisis deportivo con IA y datos de rendimiento',
                'description'      => 'Diseña e implementa sistemas de análisis de rendimiento deportivo con inteligencia artificial para clubes de élite, federaciones y atletas profesionales usando datos de tracking, vídeo y sensores biomecánicos.',
                'prompt_content'   => <<<'EOT'
Eres un ingeniero de software y científico de datos especializado en análisis de rendimiento deportivo e inteligencia artificial aplicada al deporte de élite. Necesito tu guía técnica completa para diseñar e implementar una plataforma de análisis deportivo con IA para un club de fútbol profesional.

Contexto del proyecto:
El club quiere construir una plataforma interna de análisis de rendimiento que integre datos de tracking de jugadores (GPS, acelerómetros), datos de vídeo de partidos y entrenamientos, datos fisiológicos de los jugadores (frecuencia cardíaca, variables de recuperación) y datos estadísticos del partido (pases, tiros, duelos). El objetivo es que los analistas técnicos y el cuerpo técnico puedan acceder a insights accionables en tiempo real durante el entrenamiento y dentro de las 2 horas posteriores a cada partido.

Objetivo técnico:
Diseña la arquitectura completa de la plataforma de análisis deportivo con IA.

Módulo técnico 1 - Ingesta y pipeline de datos deportivos:
Describe la arquitectura del pipeline de datos que integra todas las fuentes de datos del club. Los datos de tracking de jugadores en tiempo real provienen de sistemas GPS como Catapult, STATSports o Kinexon (frecuencia de muestreo de 10 Hz, datos de posición, velocidad, aceleración y distancia recorrida por jugador). Los datos de vídeo provienen de las cámaras de seguimiento óptico del estadio y los campos de entrenamiento (sistemas como Tracab de ChyronHego o VID IO). Los datos estadísticos del partido son proporcionados por proveedores como Opta (Stats Perform), Wyscout o InStat. Los datos fisiológicos son recopilados por el departamento médico (análisis de sangre, HRV, pruebas de esfuerzo). Diseña el data warehouse deportivo que centraliza todas estas fuentes: la capa de ingesta con conectores a cada proveedor (APIs REST, formatos de exportación propietarios), la capa de normalización que estandariza los datos en un modelo de datos común, y la base de datos de series temporales optimizada para consultas de alto rendimiento sobre trayectorias de jugadores.

Módulo técnico 2 - Modelos de IA para análisis de rendimiento físico:
Describe los modelos de machine learning para el análisis del rendimiento físico de los jugadores. Modelo 1: predicción de fatiga y riesgo de lesión muscular usando datos de carga de entrenamiento acumulada (carga aguda vs. crónica, ratio ACWR), patrones de sueño, variables fisiológicas y comparación con el historial de lesiones del jugador. El modelo debe generar un semáforo diario de riesgo de lesión por jugador con las recomendaciones de carga máxima para ese día. Modelo 2: optimización de la carga de entrenamiento colectiva, que recibe los objetivos físicos del próximo partido (distancia total, número de sprints por posición, intensidad media del rival en el modelo de juego analizado) y diseña automáticamente la sesión de entrenamiento óptima para maximizar la preparación física sin sobrepasar los umbrales de riesgo individual. Modelo 3: análisis de la recuperación post-partido con recomendaciones personalizadas de nutrición, sueño y actividad para las 72 horas posteriores al partido según los datos de carga del partido.

Módulo técnico 3 - Análisis táctico con visión artificial:
Describe el sistema de análisis táctico basado en vídeo e inteligencia artificial. El sistema debe realizar seguimiento automático de todos los jugadores y el balón en el vídeo del partido (player tracking con visión artificial), identificar y clasificar automáticamente los eventos del partido (pase, recepción, tiro, falta, presión alta, bloque defensivo), y generar automáticamente los clips de vídeo de cada evento catalogado en una biblioteca de acciones consultable. Define los análisis tácticos que el sistema genera automáticamente después de cada partido: el mapa de calor de posiciones de cada jugador, los patrones de pressing del equipo y del rival, las zonas de pérdida y recuperación del balón, los análisis de las jugadas a balón parado (corners, faltas directas e indirectas) y las transiciones ofensivas y defensivas. Describe cómo el sistema de IA identifica automáticamente los patrones del próximo rival a partir de los datos de sus últimos 5 partidos para preparar el informe de scouting.

Módulo técnico 4 - Dashboard interactivo para el cuerpo técnico:
Diseña la interfaz de usuario de la plataforma para los distintos perfiles del cuerpo técnico. Para el preparador físico: dashboard en tiempo real durante el entrenamiento con los datos de GPS de cada jugador actualizados cada segundo, semáforo de carga acumulada y alertas cuando un jugador supera los umbrales establecidos para esa sesión. Para el analista táctico: interfaz de exploración de datos del partido con filtros por jugador, zona del campo, minuto del partido y tipo de acción, y herramientas de creación de clips de vídeo para la sesión de análisis del día siguiente. Para el entrenador jefe: resumen ejecutivo del partido con los 10 indicadores de rendimiento más relevantes comparados con el modelo de juego objetivo y el rendimiento de los últimos 5 partidos. Define los requisitos técnicos de la interfaz: latencia máxima de visualización de datos en tiempo real, compatibilidad con tablets en el campo de entrenamiento y dispositivos usados en el vestuario.

Módulo técnico 5 - Integración con sistemas externos y arquitectura de datos:
Describe la arquitectura de datos y las integraciones del sistema con el ecosistema tecnológico del club. Define el modelo de datos del jugador: cómo se almacenan y relacionan los datos físicos, técnicos, tácticos y médicos de cada jugador a lo largo de toda su carrera en el club (historial de cargas, historial de lesiones, evolución de indicadores tácticos). Diseña las APIs que exponen los datos a sistemas externos: la integración con el ERP del club para vincular el rendimiento con el valor contractual del jugador, la API para el departamento médico (historia clínica digital integrada con los datos de carga), y la exportación de datos para los informes de scouting de los jugadores del primer equipo que se intercambian con los departamentos de formación. Describe las consideraciones de privacidad y seguridad de los datos de rendimiento de los jugadores: quién tiene acceso a qué datos, cómo se anonimiza la información sensible (datos médicos, datos de GPS fuera del ámbito deportivo) y cuáles son las obligaciones legales del club respecto a los datos personales de los jugadores.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Plataforma de análisis deportivo con IA y tracking de jugadores para fútbol de élite',
                'vote_score'       => 55,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de identidad visual y marca para clubes deportivos con IA',
                'description'      => 'Crea y evoluciona la identidad visual de clubes deportivos de élite usando inteligencia artificial para diseñar escudos, equipaciones, instalaciones y activos digitales que conecten con fans multigeneracionales y mercados internacionales.',
                'prompt_content'   => <<<'EOT'
Eres un director de arte y diseñador de identidad de marca especializado en el branding de clubes deportivos, equipos de élite y organizaciones deportivas internacionales. Necesito tu guía completa para diseñar o renovar la identidad visual de un club deportivo profesional usando inteligencia artificial como herramienta en el proceso creativo.

Contexto del proyecto de branding:
Un club de fútbol profesional fundado en 1919 necesita evolucionar su identidad visual para conectar mejor con los fans más jóvenes y los mercados internacionales, sin perder la identidad histórica que los socios históricos sienten como suya. El reto es enorme: cualquier cambio en el escudo o los colores del club genera una reacción emocional intensa en la afición, por lo que el proceso de diseño debe ser participativo y extremadamente cuidadoso.

Objetivo del proyecto:
Diseña el proceso completo de evolución de la identidad visual del club con soporte de inteligencia artificial, desde el research inicial hasta la implementación.

Sección de diseño 1 - Research de marca y análisis del ecosistema deportivo con IA:
Describe el proceso de research que debe preceder cualquier cambio en la identidad visual de un club histórico. La IA puede analizar miles de conversaciones de fans en redes sociales, foros y grupos de aficionados para identificar los elementos de la identidad actual que generan más orgullo y pertenencia (el color principal, un símbolo del escudo, la tipografía histórica) y los elementos que los fans más jóvenes perciben como anticuados o poco representativos. Describe el análisis del ecosistema de marcas deportivas: cómo la IA puede comparar la identidad visual del club con la de los equipos más admirados por diseño en el mundo (FC Barcelona, Juventus, Paris Saint-Germain, los clubes de la NBA con mejor imagen de marca) e identificar las tendencias de diseño deportivo emergentes. Define el mapa de identidad del club: los valores que la marca debe transmitir (historia, comunidad, competitividad, modernidad) y cómo cada elemento visual actual contribuye o no a transmitirlos.

Sección de diseño 2 - Co-creación con la comunidad y validación con IA:
El proceso de rediseño de la identidad de un club histórico debe ser participativo para evitar el rechazo de la afición. Diseña el proceso de co-creación con la comunidad de fans. Describe las fases de consulta a los socios: encuestas online con ejemplos visuales que permiten a los fans indicar qué les gusta y qué no les gusta de la identidad actual, grupos focales segmentados por edad y vinculación con el club (socios de toda la vida vs. fans jóvenes vs. fans internacionales), y una fase de votación sobre las alternativas de diseño antes del lanzamiento oficial. Explica cómo la IA puede analizar los resultados de estas consultas para identificar los puntos de consenso y los puntos de tensión entre distintos segmentos de la afición, y cómo usar estos insights para tomar decisiones de diseño fundamentadas. Define también el proceso de pruebas A/B de elementos visuales en las redes sociales del club antes del lanzamiento, para medir la reacción real de la audiencia ante distintas opciones de diseño.

Sección de diseño 3 - Diseño del sistema visual con asistencia de IA:
Describe el proceso de diseño del sistema visual del club usando la IA como herramienta creativa. Define los elementos que componen el sistema visual completo: el escudo principal y sus versiones (completo, simplificado para uso digital pequeño, monocromo), la paleta de colores del club (colores primarios, secundarios y colores de acento para uso digital), el sistema tipográfico (la tipografía exclusiva del club o la selección de fuentes comerciales), los patrones y texturas que forman parte de la identidad (los diseños de las equipaciones, los fondos corporativos, los patrones de merchandising), y los activos digitales adaptados a cada plataforma (avatar circular para redes sociales, thumbnail de YouTube, assets de Stories para Instagram). Describe cómo la IA generativa puede usarse para explorar alternativas de diseño de forma rápida en las primeras fases del proceso creativo, y cómo el criterio del diseñador humano determina qué direcciones merecen desarrollo profesional posterior.

Sección de diseño 4 - Diseño de equipaciones con IA y planificación de colecciones:
El diseño de las equipaciones deportivas es el producto de merchandising más estratégico del club. Describe el proceso de diseño de colecciones de equipaciones con asistencia de IA. Define el ciclo de vida de las equipaciones: la primera equipación (la más tradicional y conservadora, referencia obligatoria a los colores históricos del club), la segunda equipación (más experimental y atrevida, mayor libertad creativa para conectar con audiencias más jóvenes) y las equipaciones especiales (edición limitada para aniversarios, equipaciones de inspiración local o cultural que conectan con el territorio del club). Describe cómo la IA puede analizar las tendencias de moda deportiva y streetwear (dado que las camisetas de fútbol son también prendas de moda urbana para muchos fans) y cómo los datos de ventas de temporadas anteriores revelan qué elementos de diseño generaron más ventas y cuáles decepcionaron. Define el proceso de presentación de las nuevas equipaciones: cómo convertir el lanzamiento en un evento de marketing que maximiza el impacto en redes sociales y las ventas en las primeras 48 horas.

Sección de diseño 5 - Implementación de la identidad en el estadio y entornos digitales:
Describe el plan de implementación de la nueva identidad visual en todos los puntos de contacto del club. En el estadio: la señalética exterior e interior, las pantallas del estadio (big screens, perimetrales LED, pantallas de los palcos VIP), el vestuario y las instalaciones vistas en los recorridos de turistas, la tienda oficial en el estadio y el diseño de los uniformes del personal. En los entornos digitales: la web oficial del club, la app para socios, los perfiles de redes sociales y la plataforma OTT propia del club. En el merchandising: las directrices de uso de la marca para los licenciatarios de productos oficiales, el manual de marca que garantiza la coherencia en todos los productos. Define el timeline de implementación: qué elementos se actualizan inmediatamente en el lanzamiento, qué elementos se implementan de forma progresiva y cómo gestionar la transición de la identidad antigua a la nueva sin generar confusión.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Renovación de identidad visual de club deportivo histórico con asistencia de IA',
                'vote_score'       => 37,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Ventas de patrocinios deportivos con IA para clubes y eventos de élite',
                'description'      => 'Desarrolla un proceso de ventas de patrocinios con inteligencia artificial para clubes deportivos de élite, eventos deportivos y federaciones, maximizando el valor de los acuerdos y midiendo el retorno para los patrocinadores.',
                'prompt_content'   => <<<'EOT'
Eres un director comercial especializado en la venta de patrocinios deportivos para clubes de élite, eventos deportivos internacionales y federaciones nacionales. Necesito tu ayuda para construir un proceso de ventas de patrocinios completo, asistido por inteligencia artificial, para maximizar los ingresos comerciales de un club de fútbol profesional.

Perfil del club y su activo de patrocinio:
El club tiene 45.000 socios activos, una audiencia televisiva media de 800.000 espectadores por partido en las retransmisiones nacionales, una audiencia digital de 3,5 millones de seguidores en redes sociales, presencia en competiciones europeas que multiplica la visibilidad internacional, y el estadio recibe 600.000 visitantes anuales entre partidos de liga, copa y eventos. Los ingresos actuales por patrocinio son de 8 millones de euros anuales (jersey sponsor principal, patrocinador del estadio y cuatro patrocinadores regionales).

Objetivo de ventas:
Aumentar los ingresos por patrocinio en un 50% en los próximos dos años, de 8 a 12 millones de euros, con nuevos patrocinadores internacionales y activaciones de mayor valor.

Apartado de ventas 1 - Inteligencia de mercado y prospección con IA:
Describe el sistema de prospección de patrocinadores con IA. El sistema debe identificar las marcas con mayor potencial de alineación con el club analizando: el perfil demográfico de la audiencia del club (edad, poder adquisitivo, intereses, distribución geográfica) cruzado con el target de mercado de las marcas potenciales, el presupuesto histórico de patrocinio deportivo de cada marca (análisis de sus patrocinios actuales y anteriores en España y Europa), los objetivos de negocio específicos que el patrocinio puede cumplir para cada marca (lanzamiento en el mercado español, reposicionamiento de imagen, acceso al segmento joven), y las marcas que actualmente patrocinan a los rivales directos del club (oportunidad de ofrecer una alternativa o de completar una estrategia de saturación del mercado). Define las categorías de patrocinio con mayor potencial de crecimiento: seguros, banca, tecnología, automoción, telecomunicaciones y bebidas energéticas. Para cada categoría, describe el propuesta de valor específica que el club puede ofrecer.

Apartado de ventas 2 - Construcción de la propuesta de valor y el media kit con IA:
Diseña el proceso de construcción de propuestas de patrocinio personalizadas con IA. Cada propuesta debe cuantificar el valor que el patrocinador recibirá por su inversión en términos que el director de marketing y el CFO de la marca puedan evaluar: las impresiones de marca en retransmisiones televisivas (con el equivalente en coste de publicidad convencional), las impresiones en redes sociales del club (calculadas según el CPM del sector), la visibilidad en el estadio y sus enviusos para eventos no deportivos, y las activaciones exclusivas de relación con fans que crean una conexión emocional que la publicidad convencional no puede lograr. Describe cómo la IA procesa los datos de audiencia del club para construir el perfil detallado del fan tipo que verá la marca del patrocinador: si el patrocinador es una marca de coches premium y la audiencia del club tiene un poder adquisitivo acorde con su target, el argumento de venta es mucho más sólido que para un patrocinador genérico. Define el media kit digital interactivo que el equipo de ventas presenta a los prospectos.

Apartado de ventas 3 - Negociación y estructuración de acuerdos de patrocinio:
Describe el proceso de negociación de contratos de patrocinio y los modelos de acuerdo que maximizan el valor para el club. Define los niveles de patrocinio y su estructura de derechos: el patrocinador principal de camiseta (máxima visibilidad, exclusividad en su categoría de producto, derechos de uso de la imagen de los jugadores para publicidad del patrocinador), los patrocinadores sectoriales exclusivos por categoría (solo una marca de seguros, solo una de coches, solo una de cerveza), los patrocinadores de match day (marcas que patrocinan partidos específicos de alta audiencia), y los patrocinadores de activos digitales (sponsor de los vídeos del YouTube oficial del club, de los Stories de Instagram o de la app). Describe cómo estructurar los contratos de patrocinio con kickers de rendimiento: el fee base garantizado más bonificaciones por clasificación deportiva (acceso a Champions League multiplica la visibilidad del patrocinador en un X%), por crecimiento de la audiencia digital o por ventas generadas en las activaciones exclusivas del patrocinador.

Apartado de ventas 4 - Medición del ROI del patrocinio con IA:
La mayor objeción de los patrocinadores potenciales es la dificultad de medir el retorno de un patrocinio deportivo. Diseña el sistema de medición del ROI del patrocinio con IA que elimina esta objeción. Describe las herramientas de medición de visibilidad de marca en retransmisiones televisivas (software de visión artificial que detecta y mide los segundos de visibilidad de la marca del patrocinador en las cámaras de televisión en cada partido), el sistema de monitorización de menciones y engagement de la marca en redes sociales asociadas al club, y la metodología para calcular el equivalente publicitario de cada tipo de visibilidad (cuánto costaría comprar el mismo nivel de exposición en publicidad convencional). Define los informes de patrocinio trimestrales que el club entrega a cada patrocinador: el dashboard con todas las métricas de visibilidad, los highlights más vistos donde aparece la marca del patrocinador, y la comparación con el valor equivalente de publicidad convencional para justificar la renovación del contrato a un precio igual o superior.

Apartado de ventas 5 - Activaciones de patrocinio diferenciales con IA:
Los patrocinios más valiosos son los que van más allá de pegar un logo en una camiseta. Diseña el catálogo de activaciones de patrocinio diferenciales que el club puede ofrecer a sus socios comerciales. Define las activaciones que crean valor real para el fan y para la marca: la "fan experience" donde los mejores clientes del patrocinador tienen acceso a los entrenamientos, el vestuario y una sesión de fotos con los jugadores, el programa de academias de fútbol del patrocinador donde el patrocinador financia las escuelas de fútbol del club en distintas ciudades, el programa de contenido co-branded donde la marca del patrocinador produce contenido junto al club para sus redes sociales (alcance de millones de fans del club que siguen el contenido del patrocinador), y los datos de la audiencia del club compartidos de forma anonimizada para ayudar al patrocinador a entender mejor a sus clientes potenciales. Describe cómo la IA puede personalizar las propuestas de activación para cada patrocinador según sus objetivos de negocio específicos y el historial de engagement de sus clientes con el club.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 55,
                'use_case'         => 'Venta de patrocinios deportivos de alto valor con IA y medición de ROI para clubs de élite',
                'vote_score'       => 40,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Product management de plataformas digitales para el deporte de élite con IA',
                'description'      => 'Define la visión, roadmap y métricas de una plataforma digital deportiva (app de fans, plataforma OTT o herramienta de análisis de rendimiento) usando inteligencia artificial para personalizar la experiencia y maximizar el engagement.',
                'prompt_content'   => <<<'EOT'
Eres un Product Manager con experiencia en plataformas digitales deportivas, apps para fans y tecnología aplicada al deporte de élite. Necesito tu ayuda para definir la estrategia de producto completa de la aplicación oficial de un club de fútbol de élite, que combina experiencia de fan, contenido exclusivo y funcionalidades de comunidad.

Contexto del producto:
La app del club tiene 180.000 descargas, 35.000 usuarios activos mensuales y 12.000 suscriptores de pago al plan premium (que ofrece estadísticas avanzadas, contenido exclusivo y descuentos en la tienda). La retención a 30 días es del 22%, muy por debajo del benchmark del sector (35-40% para apps deportivas de élite). La app es la principal plataforma de comunicación con los socios y la única donde los fans pueden comprar entradas, renovar el abono y acceder al contenido exclusivo.

Objetivo del product management:
Define la estrategia para llevar la retención del 22% al 38% y los suscriptores premium de 12.000 a 25.000 en 18 meses.

Dimensión estratégica 1 - Discovery y comprensión del comportamiento del usuario deportivo:
Describe el proceso de discovery para entender por qué los usuarios abandonan la app y qué les haría volver y suscribirse al plan premium. Analiza el comportamiento on-app con los datos disponibles: qué funcionalidades usan los usuarios que permanecen activos durante más de 6 meses (indicador de valor percibido) y cuáles son los flows que terminan en abandono (el usuario abre la app, navega por 2 pantallas y la cierra sin hacer nada). Define el programa de entrevistas con usuarios: cómo reclutar fans con distintos perfiles de uso para sesiones de 30 minutos donde describen su relación con el club, cómo consumen contenido deportivo en general y qué les falta específicamente en la app actual. Describe cómo la IA puede analizar los datos de comportamiento de la app y las transcripciones de las entrevistas para identificar los jobs-to-be-done más frecuentes: qué trabajos intenta completar el fan cuando abre la app del club (seguir el partido en tiempo real, ver el contenido de los jugadores, renovar el abono, encontrar información del próximo partido).

Dimensión estratégica 2 - Personalización con IA del contenido y la experiencia:
La personalización es el factor diferencial que convierte una app genérica en una experiencia que el fan percibe como suya. Diseña el sistema de personalización con IA de la experiencia en la app. Define los modelos de personalización: el sistema de recomendación de contenido que aprende las preferencias de cada usuario (si el fan siempre mira los vídeos de análisis táctico y nunca los de lifestyle del jugador, la app le muestra más del primero y menos del segundo), el sistema de notificaciones inteligentes que envía la notificación correcta en el momento correcto (no enviar una notificación de preventa de entradas a las 3 de la madrugada ni a un fan que ha demostrado no comprar entradas), y la personalización de la home screen según el estado del fan en relación al siguiente partido (5 días antes: preventa de entradas y previa táctica; día del partido: lineación probable y predicciones; post-partido: análisis y estadísticas).

Dimensión estratégica 3 - Roadmap del producto para maximizar retención y suscripción:
Define el roadmap de funcionalidades para los próximos cuatro trimestres orientado a mejorar la retención y el crecimiento del plan premium. Trimestre 1: sistema de notificaciones inteligentes personalizadas por IA (reducir los opt-out de notificaciones del 40% actual al 15%) y rediseño del onboarding con personalización desde la primera apertura. Trimestre 2: funcionalidad de predicciones de partido con comunidad (los fans predicen la alineación, el resultado y el goleador, con rankings de acertantes y premios del club) que genera una razón semanal de abrir la app. Trimestre 3: plataforma de contenido exclusivo premium con vídeos del vestuario, entrenamientos y entrevistas solo disponibles para suscriptores, producidos con IA para reducir el coste de producción. Trimestre 4: integración del billete digital de abonado con funcionalidades de gamificación (puntos por asistir al estadio, por interactuar con la app, canjeables por experiencias exclusivas con el primer equipo).

Dimensión estratégica 4 - Monetización y modelo de suscripción premium:
Define la estrategia de monetización de la app y el modelo de suscripción premium. Describe la propuesta de valor del plan premium en términos de beneficios concretos que justifican el precio: el acceso al contenido exclusivo (cuántos vídeos exclusivos al mes, con qué tipo de acceso al primer equipo), las funcionalidades avanzadas (estadísticas detalladas de jugadores, comparativas con jugadores de otros equipos, predicciones con IA), los descuentos en la tienda oficial y en la compra de entradas, y el acceso anticipado a la venta de entradas para partidos de alta demanda. Define los distintos niveles de suscripción: un nivel básico gratuito con publicidad que actúa como funnel hacia los planes de pago, un plan mensual para fans más casuales y un plan anual con descuento para los fans más comprometidos (que coincide con la renovación del abono de socio). Describe cómo la IA identifica el momento óptimo para presentar el upgrade al plan premium según el comportamiento del usuario (el fan que ha visto 5 previsualizaciones de contenido exclusivo en la última semana es el candidato ideal para la oferta de trial gratuito).

Dimensión estratégica 5 - Métricas del producto deportivo digital y framework de decisión:
Define el sistema de métricas de la app deportiva que guía las decisiones de producto. Establece la métrica North Star: en una app de fans, la métrica más significativa no es el número de descargas ni los DAU, sino los "días de conexión con el club" (número de días distintos que el usuario abre la app por mes, ponderado por la profundidad de uso). Define el cuadro completo de métricas: retención a 1, 7 y 30 días desglosada por canal de adquisición y por cohorte, revenue por usuario (ARPU) diferenciado entre usuarios gratuitos y premium, tasa de conversión de gratuito a premium y de mensual a anual, NPS de los usuarios premium, y métricas de engagement por funcionalidad (cuántos usuarios usan cada feature al mes y cuánto tiempo dedican). Describe cómo la IA correlaciona las métricas de engagement de la app con los resultados deportivos del equipo: ¿cuánto sube la retención cuando el equipo gana tres partidos seguidos y cuánto baja cuando pierde cuatro? Esta calibración es crítica para separar el impacto del producto del impacto de los resultados deportivos en las métricas.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Estrategia y roadmap de producto para app oficial de club deportivo de élite',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión del talento deportivo y RRHH con IA para clubes de élite',
                'description'      => 'Diseña sistemas de scouting, desarrollo y retención de talento deportivo y organizacional para clubes de élite usando inteligencia artificial para identificar, evaluar y gestionar tanto a los deportistas como al staff técnico y directivo.',
                'prompt_content'   => <<<'EOT'
Eres un director de RRHH y gestión del talento especializado en organizaciones deportivas de élite, con experiencia en clubes de fútbol profesional y federaciones deportivas nacionales. Necesito tu ayuda para diseñar un sistema completo de gestión del talento humano para un club deportivo de Primera División, cubriendo tanto al personal deportivo como al equipo directivo y de gestión.

Contexto de la organización:
El club tiene 85 empleados en la estructura directiva y de gestión (marketing, finanzas, comunicación, operaciones del estadio, académicas, ticketing) y 120 personas en la estructura deportiva (cuerpo técnico del primer equipo, departamento médico, departamento de análisis, departamento de formación de la academia). Los desafíos de RRHH son múltiples: alta rotación del cuerpo técnico vinculada a los resultados deportivos, dificultad para retener talento directivo cualificado que es captado por empresas del sector privado con mejores condiciones económicas, y la necesidad de construir una cultura organizacional que integre los valores del club con las exigencias de profesionalización del fútbol moderno.

Objetivo del programa:
Diseña el sistema de gestión del talento que profesionaliza la organización y reduce la rotación no deseada.

Bloque de talento 1 - Scouting de talento directivo y técnico con IA:
Describe el proceso de identificación y selección de talento directivo para el club. El mercado de directivos especializados en deporte de élite es pequeño y muy específico: los mejores directores de marketing deportivo, directores comerciales de patrocinios y CFOs con experiencia en clubes profesionales son conocidos en el sector y frecuentemente se mueven entre clubes. Describe cómo usar la IA para mapear este mercado de talento: análisis de los perfiles de LinkedIn de los profesionales con experiencia demostrada en clubes de las cinco grandes ligas europeas, seguimiento de los movimientos del mercado directivo en los medios especializados y en las redes sociales del sector, e identificación de los talentos emergentes que están construyendo carreras destacadas en clubes de segunda línea y podrían ser candidatos ideales para un salto a un club de mayor envergadura. Define los criterios de evaluación específicos para cada posición directiva en un club de fútbol: qué combinación de experiencia en deporte y en empresa resulta más efectiva para cada rol.

Bloque de talento 2 - Evaluación y selección de staff técnico con análisis de datos:
Diseña el proceso de evaluación y selección del cuerpo técnico del primer equipo (entrenador jefe, entrenadores asistentes, preparador físico, analista de datos). La decisión de contratar a un entrenador es la más importante y mediática del club, y habitualmente se toma con criterios muy subjetivos. Describe cómo la IA puede enriquecer este proceso: análisis del historial de resultados de los candidatos a entrenador ajustado por el nivel de los clubes entrenados y los recursos disponibles, análisis de los patrones de juego de los equipos que han entrenado (agresividad defensiva, índice de pressing alto, control del balón) y su alineación con la filosofía de juego que el club quiere implementar, y evaluación de las habilidades de gestión de vestuarios complejos a partir de las declaraciones públicas de los jugadores que han trabajado con cada entrenador. Define también el proceso de evaluación de los miembros del staff técnico especialistas: qué datos de rendimiento de los jugadores evidencian la calidad del trabajo del preparador físico o del analista táctico.

Bloque de talento 3 - Desarrollo y formación del personal con IA:
Describe el programa de desarrollo profesional para los empleados directivos y técnicos del club. Para el personal directivo: acceso a programas de formación en gestión deportiva de instituciones como el Johan Cruyff Institute, ISDE Sports Business School o el MBA en Gestión Deportiva del IESE, con un budget de formación de 3.000 a 8.000 euros por persona al año. Define cómo la IA puede personalizar los planes de desarrollo individual: basándose en la evaluación de competencias de cada empleado, el sistema identifica las brechas de habilidades más relevantes para su rol y recomienda los recursos de formación más adecuados. Para el staff técnico deportivo: programa de actualización continua en las últimas tendencias en análisis de rendimiento, biomecánica y metodología de entrenamiento, con visitas de intercambio a otros clubes de élite europeos. Describe cómo el sistema de gestión del conocimiento del club captura y distribuye el aprendizaje organizacional para que las buenas prácticas no se pierdan con la rotación del personal.

Bloque de talento 4 - Gestión del rendimiento y evaluación en una organización deportiva:
Define el sistema de evaluación del rendimiento adaptado a la cultura específica de un club de fútbol profesional. En un club, los resultados deportivos del primer equipo influyen poderosamente en el clima organizacional y en la evaluación de todos los empleados, lo que puede distorsionar las evaluaciones justas del personal cuyo trabajo no depende directamente de los resultados. Diseña un sistema de evaluación que separa claramente el rendimiento individual del empleado (criterios objetivos específicos de su función) del contexto deportivo general del club (el director de marketing puede tener un rendimiento excelente incluso si el equipo está en zona de descenso). Define los OKRs específicos para cada departamento del club: cómo se mide el rendimiento del departamento de marketing, del departamento de ticketing, del departamento de formación de la academia y del departamento médico con criterios objetivos y accionables. Describe el ciclo de evaluación: revisiones trimestrales de progreso de OKRs y evaluación anual de competencias, con especial atención a los momentos de alta presión deportiva donde la evaluación objetiva es más difícil.

Bloque de talento 5 - Retención y cultura organizacional en el club de élite:
Describe las estrategias de retención del talento directivo y técnico en un entorno donde la inestabilidad deportiva es estructural. El mayor riesgo de retención en un club de fútbol es el cambio de entrenador, que frecuentemente arrastra cambios en el staff técnico y puede generar incertidumbre en todo el personal directivo. Diseña el programa de retención que crea vínculos más allá del vínculo con el entrenador: la identificación de los empleados con el proyecto del club a largo plazo (más allá del ciclo del entrenador actual), el plan de carrera que ofrece perspectivas de crecimiento dentro de la organización, y los beneficios que son difíciles de replicar fuera del entorno deportivo (acceso a los partidos, relación con los jugadores, pertenecer a algo que tiene un impacto emocional en millones de personas). Define los rituales de cultura organizacional del club: cómo se celebran los éxitos deportivos con todo el equipo, cómo se gestiona la adversidad deportiva sin que se contagie al resto de la organización, y cómo el club comunica internamente su visión y sus valores de forma que cada empleado entiende su contribución al proyecto colectivo.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 50,
                'use_case'         => 'Sistema de gestión del talento y RRHH para club deportivo profesional de élite',
                'vote_score'       => 35,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Finanzas y gestión económica del deporte de élite con IA',
                'description'      => 'Analiza y optimiza la estructura financiera de clubes deportivos profesionales usando inteligencia artificial para modelizar ingresos, gestionar el fair play financiero y evaluar inversiones en fichajes y infraestructuras.',
                'prompt_content'   => <<<'EOT'
Eres un director financiero con experiencia en la gestión económica de clubes deportivos profesionales y el cumplimiento del Reglamento de Fair Play Financiero de la UEFA y La Liga. Necesito tu ayuda para construir el marco de gestión financiera completo para un club de fútbol de Primera División.

Contexto financiero del club:
El club tiene un presupuesto anual de 65 millones de euros. Los ingresos principales son: derechos televisivos (35% del total), ingresos de taquilla y abonos (25%), patrocinios y publicidad (15%), merchandising y tienda oficial (8%), ingresos de competiciones europeas (10%) y otras fuentes (7%). El gasto de plantilla representa el 72% de los ingresos totales, por encima del 70% recomendado por UEFA y del límite del 50% que busca La Liga Impulso para 2025-2026.

Objetivo de la gestión financiera:
Construye el plan financiero para reducir el ratio de gasto de plantilla al 65% manteniendo la competitividad deportiva, y para asegurar el cumplimiento del Reglamento de Fair Play Financiero de UEFA.

Marco financiero 1 - Modelización de ingresos con IA:
Describe el modelo de proyección de ingresos del club para los próximos 3 años. Los ingresos deportivos tienen una componente de incertidumbre enorme: los ingresos por competición europea dependen de la clasificación deportiva, los ingresos de taquilla dependen del rendimiento del equipo y de la ocupación del estadio, y los ingresos de merchandising tienen una correlación directa con los éxitos deportivos. Describe cómo la IA puede construir un modelo de proyección de ingresos con escenarios múltiples: el escenario base (clasificación para Europa League), el escenario optimista (clasificación para Champions League) y el escenario pesimista (lucha por no descender). Para cada escenario, cuantifica el impacto en cada línea de ingresos: cuánto valen los derechos televisivos de Champions League vs. Europa League, cuánto aumentan los patrocinios cuando el club juega en Europa y cuánto se incrementan los ingresos de ticketing con partidos de competición europea en casa. Define también el modelo de simulación de los derechos televisivos de La Liga para los próximos 3 años, incluyendo el impacto del nuevo contrato de derechos televisivos.

Marco financiero 2 - Gestión del fair play financiero de UEFA y normas de La Liga:
Analiza el cumplimiento del Reglamento de Financial Sustainability de la UEFA (sucesor del Fair Play Financiero clásico) y las reglas económicas de La Liga. El Reglamento de Sostenibilidad Financiera de UEFA, vigente desde 2023, establece que las pérdidas de un club no pueden superar los 60 millones de euros en 3 años (con ajustes por inversiones en academia, infraestructuras e igualdad). Las reglas de La Liga Impulso establecen el límite de coste de plantilla según el EBITDA ajustado del club. Describe el modelo de seguimiento continuo del cumplimiento de ambas normativas: cómo proyectar la evolución del saldo de sostenibilidad UEFA a 3 años según distintos escenarios de resultados y de operaciones de mercado de fichajes, y cómo calcular el límite salarial de La Liga para la próxima temporada según los ingresos y gastos actuales. Define las acciones correctivas disponibles cuando el club está en riesgo de superar los límites: venta de jugadores, reducción de primas variables, aplazamiento de inversiones en infraestructura.

Marco financiero 3 - Valoración y análisis económico de los fichajes con IA:
Describe el modelo de análisis económico de las operaciones de mercado de fichajes. La inversión en fichajes es la decisión financiera más impactante y mediática del club. Diseña el framework de valoración de un jugador que integra el análisis deportivo con el análisis económico: el valor de mercado actual según plataformas como Transfermarkt o CIES, los indicadores de rendimiento deportivo del jugador (goles, asistencias, métricas avanzadas como xG y xA, datos de pressing y duelos) y su proyección en los próximos 3-5 años según su edad y su trayectoria. Describe el modelo de cálculo del retorno de un fichaje: el impacto esperado del jugador en la clasificación del equipo, traducido al impacto en ingresos (si el jugador sube al equipo 3 posiciones en la tabla y eso supone clasificarse para Europa League, el valor económico de esa clasificación es el incremento en derechos televisivos, ingresos europeos y patrocinios). Define también la estrategia de venta de jugadores con IA: cómo identificar el momento óptimo de venta de cada jugador de la plantilla según su curva de valor de mercado y la necesidad financiera del club.

Marco financiero 4 - Gestión del estadio e inversiones en infraestructuras:
Analiza la gestión financiera del estadio como activo económico. El estadio es mucho más que la sede de los partidos de fútbol: es un centro de ingresos que puede explotarse 365 días al año. Describe el modelo de optimización de ingresos del estadio: los partidos de fútbol (la fuente principal), los conciertos y eventos de música (los estadios modernos pueden acoger 2-3 grandes conciertos por temporada con ingresos de 1-3 millones de euros por evento), los eventos corporativos en los palcos y las instalaciones del estadio, los ingresos del estadio-museo y las visitas turísticas, y la posible explotación comercial de la fachada y los espacios exteriores. Define también el análisis de inversiones en infraestructura con IA: cómo evaluar financieramente la inversión en la ampliación del estadio, la construcción de nuevas instalaciones de entrenamiento o la creación de un hotel o complejo de ocio adjunto al estadio, con el modelo de flujos de caja descontados que justifica o descarta cada inversión.

Marco financiero 5 - Reporting financiero y cuadro de mando del club deportivo:
Diseña el sistema de reporting financiero y el cuadro de mando directivo del club. Define las métricas financieras específicas del sector deportivo: el ratio de coste de plantilla sobre ingresos (la métrica de sostenibilidad más importante), el EBITDA ajustado según las normas de La Liga, el Net Debt to EBITDA (nivel de endeudamiento), el Free Cash Flow generado por la operación ordinaria del club (excluyendo plusvalías de ventas de jugadores), y la evolución del valor neto de la plantilla (suma del valor de mercado de todos los jugadores). Describe el cuadro de mando mensual que el director financiero presenta al presidente y al consejo: la comparativa de ingresos real vs. presupuesto por línea de negocio, el estado del cumplimiento del límite salarial de La Liga en tiempo real, la proyección del saldo de sostenibilidad UEFA a cierre de temporada, y las alertas automáticas cuando cualquier métrica se desvía más de un 10% del presupuesto. Define también el calendario de reporting externo: los plazos de presentación de cuentas auditadas a La Liga, a UEFA para los registros de Fair Play Financiero y a las entidades bancarias prestamistas según los covenants de los créditos del club.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 65,
                'use_case'         => 'Gestión financiera y fair play financiero de club de fútbol profesional con IA',
                'vote_score'       => 49,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Derecho deportivo e imagen del deportista con IA para abogados del sector',
                'description'      => 'Navega la regulación del deporte de élite, los contratos deportivos, los derechos de imagen y la responsabilidad de los clubes usando inteligencia artificial para analizar la normativa y estructurar acuerdos complejos.',
                'prompt_content'   => <<<'EOT'
Eres un abogado especializado en derecho deportivo, contratos de deportistas profesionales, derechos de imagen y regulación del deporte de élite. Necesito tu análisis jurídico completo sobre el marco legal que regula la relación entre los clubes de fútbol profesional y sus jugadores en España, con especial atención a los contratos, los derechos de imagen y la regulación de la Real Federación Española de Fútbol y La Liga.

Contexto jurídico:
Un club de fútbol de Primera División necesita revisar su marco de relaciones jurídicas con los jugadores del primer equipo: los contratos laborales deportivos de los jugadores, los acuerdos de derechos de imagen, las cláusulas de rescisión y los bonus de rendimiento, y la relación con los agentes de los jugadores en el contexto de la nueva normativa FIFA sobre intermediarios.

Objetivo del análisis:
Proporciona el mapa jurídico completo de las relaciones entre el club y los jugadores, y las mejores prácticas contractuales para proteger los intereses del club.

Área normativa 1 - El contrato laboral deportivo del jugador profesional:
Analiza el marco jurídico del contrato laboral de un futbolista profesional en España. El Real Decreto 1006/1985, regulador de la relación laboral especial de los deportistas profesionales, establece las condiciones específicas de la relación laboral en el deporte: la duración determinada obligatoria del contrato (sin que sea posible un contrato indefinido), el régimen de vacaciones adaptado al calendario deportivo, el derecho de retención del club sobre el jugador durante la vigencia del contrato, y la indemnización por resolución anticipada. Describe las cláusulas más relevantes que debe contener un contrato de jugador de élite: el salario fijo y las variables (bonus por partidos jugados, por goles, por clasificación del equipo, por premios individuales), la cláusula de rescisión y su importe (que puede ser ejercida por el jugador pagando la indemnización, o por un tercero club que compra al jugador), las obligaciones disciplinarias del jugador y el régimen sancionador del club, y las cláusulas sobre imagen pública y redes sociales del jugador. Describe cómo la IA puede asistir en la negociación de contratos: análisis de los contratos de jugadores de características similares en el mismo club y en clubes competidores para establecer el rango de condiciones de mercado.

Área normativa 2 - Los derechos de imagen del deportista y su cesión al club:
Describe el régimen jurídico de los derechos de imagen de los jugadores profesionales y su relación con el club. Los derechos de imagen del jugador son derechos de personalidad reconocidos en la LO 1/1982 y tienen un régimen fiscal específico establecido en el artículo 92 de la Ley del IRPF (la regla 85/15 que permite que hasta el 15% de los ingresos del jugador provengan de la cesión de derechos de imagen a través de sociedades de imagen, con una tributación más favorable). Analiza la estructura de los contratos de derechos de imagen entre el club y el jugador: el acuerdo de cesión de derechos de imagen al club (que permite al club usar la imagen del jugador en publicidad propia y en activaciones de patrocinadores), la remuneración de esta cesión (que debe ser real y no simulada para no ser recharacterizada como salario por la Agencia Tributaria), y las limitaciones de uso (el jugador puede reservarse derechos de imagen para sus patrocinadores personales que no deben entrar en conflicto con los patrocinadores del club).

Área normativa 3 - Regulación de agentes de jugadores y nueva normativa FIFA:
Analiza el nuevo marco regulatorio de la FIFA sobre intermediarios y agentes de jugadores, en vigor desde octubre de 2023 (Football Agents Regulations, FAR). El nuevo reglamento establece: la obligación de obtener una licencia de la federación nacional para actuar como agente de jugadores, el límite del 3% sobre el salario del jugador que puede cobrar el agente que representa al jugador (o el 3% del precio de la transferencia si representa al club vendedor), la prohibición de dual representation en la misma transferencia (el agente no puede representar simultáneamente al jugador y al club comprador), y las obligaciones de transparencia y registro de los contratos de agencia. Describe las implicaciones prácticas para el club: cómo negociar con los agentes de los jugadores en el nuevo marco, cómo verificar que el agente tiene la licencia correspondiente, y qué riesgos asume el club si paga comisiones a agentes no licenciados. Analiza también las cláusulas de los contratos de agencia más habituales y las que deben evitarse para proteger los intereses del club.

Área normativa 4 - Derecho disciplinario deportivo y resolución de conflictos:
Describe el sistema de resolución de conflictos y el derecho disciplinario aplicable al deporte de élite en España. Los conflictos entre jugadores y clubes pueden resolverse en la jurisdicción laboral ordinaria (los juzgados de lo social), ante el Comité de Resolución de Disputas de La Liga (para conflictos de carácter económico), ante los órganos disciplinarios de la RFEF (para infracciones del Reglamento General) o ante el TAS (Tribunal de Arbitraje Deportivo de Lausana) si están expresamente previsto en el contrato. Describe el protocolo de gestión de una sanción disciplinaria interna del club a un jugador: los requisitos formales del expediente disciplinario (audiencia previa al jugador, proporcionalidad de la sanción, respeto al convenio colectivo), las sanciones posibles (amonestación, multa económica, suspensión temporal) y los límites de las multas en el convenio colectivo de fútbol profesional. Define también el protocolo de gestión de un caso de dopaje: las obligaciones del club cuando un jugador da positivo en un control antidopaje (notificación a la RFEF y a la AMA), el derecho de defensa del jugador y el impacto en el contrato del club durante el período de sanción.

Área normativa 5 - Protección de datos de los deportistas y regulación de tecnologías de análisis:
Analiza las implicaciones del RGPD en el contexto del deporte de élite, donde los clubes recopilan cantidades masivas de datos personales y biométricos de los jugadores. Los sistemas de tracking con GPS, los análisis de vídeo con visión artificial, los datos médicos y los datos biométricos de los deportistas son datos especialmente protegidos por el artículo 9 del RGPD. Describe las obligaciones del club como responsable del tratamiento de datos de los jugadores: la base jurídica del tratamiento (el contrato laboral como base para los datos necesarios para la relación deportiva, el consentimiento explícito para los datos biométricos no estrictamente necesarios), la obligación de información al jugador sobre el uso de sus datos, la evaluación de impacto (EIPD) necesaria para los tratamientos de datos biométricos masivos, y los derechos del jugador sobre sus datos (acceso, rectificación, limitación del tratamiento). Define también qué pasa con los datos de rendimiento del jugador cuando termina su contrato con el club: el club puede retener datos históricos anonimizados para el análisis de rendimiento del equipo, pero los datos nominativos del jugador deben ser tratados según la política de conservación definida en el contrato y comunicada al jugador.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 65,
                'use_case'         => 'Marco legal del deporte profesional, contratos de jugadores y regulación de la IA deportiva',
                'vote_score'       => 41,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención al aficionado y experiencia de fan con IA para clubes deportivos',
                'description'      => 'Diseña sistemas de atención al aficionado y experiencia del fan con inteligencia artificial para clubes deportivos, gestionando consultas de socios, ventas de entradas, incidencias en el estadio y la relación con la comunidad de aficionados.',
                'prompt_content'   => <<<'EOT'
Eres un director de experiencia del aficionado y atención al cliente especializado en clubes deportivos de élite. Necesito tu ayuda para diseñar el sistema completo de atención al aficionado con inteligencia artificial para un club de fútbol profesional con 45.000 socios y 600.000 visitantes anuales al estadio.

Contexto del servicio:
El departamento de atención al socio gestiona actualmente 12.000 consultas al mes a través de teléfono, email, redes sociales y atención presencial en las oficinas del estadio. Los picos de demanda son extremos: en los períodos de renovación de abonos (mayo-junio) y venta de entradas para partidos de alta demanda (clásicos, partidos europeos), el volumen de consultas se multiplica por 5 en 48 horas. El tiempo medio de respuesta actual es de 18 horas para email y 4 horas para redes sociales, muy por encima de las expectativas del aficionado (que espera respuesta en menos de 2 horas para cualquier canal).

Objetivo del sistema:
Diseña el sistema de atención al aficionado con IA que reduce el tiempo medio de respuesta a menos de 30 minutos para el 80% de las consultas.

Componente de atención 1 - Categorización y enrutamiento automático con IA:
Describe el sistema de clasificación automática de las consultas del aficionado que prioriza y enruta cada consulta al canal de resolución más eficiente. Las categorías más frecuentes de consultas en un club de fútbol son: dudas sobre el proceso de renovación del abono, reclamaciones por errores en la facturación, consultas sobre el proceso de compra de entradas para un partido específico, peticiones de cambio de asiento, incidencias con la app del club o el acceso digital al estadio, consultas sobre el merchandising y pedidos de la tienda online, y peticiones de información sobre visitas al estadio. Para cada categoría, define si la IA puede resolverla de forma autónoma (sin intervención humana), si requiere que la IA recopile información del aficionado y la pase a un agente humano ya preparada para resolver, o si debe escalarse directamente a un agente especializado. Describe el sistema de priorización: qué consultas se atienden primero según la urgencia (el aficionado que no puede acceder al estadio 30 minutos antes del partido es prioridad máxima) y según el valor del cliente (el abonado de 20 años recibe atención preferente sobre un comprador esporádico de entradas).

Componente de atención 2 - Gestión de la venta de entradas y la demanda pico:
Diseña el protocolo de gestión de las colas virtuales y la atención al aficionado durante los momentos de máxima demanda, como la apertura de ventas para el clásico o la final de Copa del Rey. Describe el sistema de cola virtual que gestiona la demanda: cómo asigna turnos de compra de forma justa entre los distintos segmentos de aficionados (primero socios con mayor antigüedad, luego socios más recientes, luego compradores del mercado general), cómo comunica proactivamente el tiempo estimado de espera a cada aficionado en la cola, y cómo la IA gestiona las incidencias más frecuentes en la venta de entradas de alta demanda (el aficionado que pierde su turno por un problema técnico, el que compra entradas pero no recibe la confirmación por email, el que quiere cambiar asientos después de comprar). Define también el protocolo de comunicación proactiva cuando hay una incidencia técnica masiva durante la venta: qué mensaje se comunica a los aficionados afectados, en qué canal y con qué promesa de resolución.

Componente de atención 3 - Experiencia en el estadio el día del partido con IA:
Describe el sistema de atención al aficionado durante el partido en el estadio, donde los problemas deben resolverse en tiempo real y la ventana de resolución es de minutos. Define los canales de atención disponibles el día del partido: el chat en la app del club para consultas digitales, los puntos de información físicos del estadio (con personal asistido por IA con acceso inmediato a la información de asientos, cambios de asiento disponibles e incidencias), el sistema de asistencia en el propio asiento para problemas de acceso. Describe los escenarios de atención más frecuentes en el estadio: el aficionado que llega a su asiento y hay otra persona sentada (protocolo de resolución de conflictos de asiento en menos de 5 minutos), el aficionado que ha comprado un producto de la tienda online y quiere recogerlo en el estadio (sistema de click and collect), la petición de asistencia médica (protocolo de escalado inmediato a los servicios médicos del estadio). Define las métricas de experiencia del día del partido: el tiempo medio de resolución de incidencias en el estadio, el NPS del aficionado tras el partido y la correlación entre la experiencia de atención y la intención de renovar el abono.

Componente de atención 4 - Gestión de quejas y resolución de conflictos con aficionados:
Diseña el proceso de gestión de reclamaciones y la resolución de conflictos con los aficionados. Las quejas más comunes en un club de fútbol tienen una carga emocional muy alta: el aficionado que se siente maltratado por el club, que considera que su solicitud no ha sido atendida con el respeto que merece como persona que lleva 30 años siendo socio, puede convertirse en un detractor vocal en redes sociales y en los medios. Describe el protocolo de gestión de quejas complejas: la escucha activa del problema del aficionado sin interrupciones, el reconocimiento del error del club cuando lo ha habido, la propuesta de solución concreta con un plazo de resolución claro, y el seguimiento posterior para confirmar que el aficionado está satisfecho con la resolución. Define las compensaciones proporcionales al tipo de incidencia: un fallo en el sistema de acceso digital que impidió entrar al partido merece una compensación diferente a un error menor en la facturación del abono. Describe también el sistema de alerta temprana que la IA utiliza para identificar aficionados con alto riesgo de no renovar el abono: el historial de quejas no resueltas, la reducción en el uso de los beneficios del abono y el descenso en el engagement con la app del club son señales que deben activar una intervención proactiva del equipo de fidelización.

Componente de atención 5 - Métricas de experiencia del aficionado y mejora continua con IA:
Define el sistema de métricas de calidad del servicio de atención al aficionado en un club de fútbol. Las métricas más relevantes para el sector: el Net Promoter Score de los socios (medido en una encuesta anual y en encuestas post-interacción), el tiempo medio de primera respuesta por canal, el tiempo medio de resolución completa de la consulta, la tasa de resolución en el primer contacto sin necesidad de escalar, el porcentaje de consultas resueltas de forma autónoma por la IA sin intervención humana, y la correlación entre la calidad de la atención recibida y la tasa de renovación del abono. Describe el proceso de mejora continua basado en datos: cómo el sistema de IA analiza semanalmente las consultas no resueltas de forma satisfactoria para identificar gaps en la base de conocimiento del chatbot o deficiencias en los procesos del equipo humano, y cómo estos insights se transforman en actualizaciones del sistema y en formación para el equipo de atención. Define también cómo el club usa el feedback de los aficionados para mejorar los procesos más allá del departamento de atención: si el 30% de las consultas del mes son sobre confusión en el proceso de renovación del abono, la solución no es mejorar la atención sino rediseñar el proceso de renovación para que sea más claro e intuitivo.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 45,
                'use_case'         => 'Sistema de atención al aficionado con IA para club deportivo de élite',
                'vote_score'       => 33,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultoría freelance en gestión y tecnología deportiva con IA',
                'description'      => 'Construye un negocio de consultoría freelance especializado en gestión, marketing y tecnología para clubes deportivos de élite, federaciones y organizaciones del sector deportivo usando la inteligencia artificial como herramienta diferenciadora.',
                'prompt_content'   => <<<'EOT'
Eres un consultor deportivo freelance senior con experiencia en gestión de clubes de élite, marketing deportivo y tecnología aplicada al deporte profesional. Necesito tu ayuda para construir mi negocio de consultoría independiente en el nicho del deporte de élite, usando la inteligencia artificial como ventaja competitiva en mi práctica profesional.

Mi situación actual:
Tengo 10 años de experiencia en el sector deportivo: los primeros 5 en el departamento comercial de un club de fútbol de Segunda División y los últimos 5 como director de marketing en un club de Primera División. He liderado proyectos de patrocinios, digitalización de la experiencia del fan y lanzamiento de plataformas de contenido deportivo. Quiero lanzarme como consultor independiente para trabajar con clubes de distintos deportes, organizaciones deportivas internacionales y marcas que quieren entrar en el mercado deportivo.

Objetivo de la sesión:
Diseña el plan completo para lanzar y escalar mi consultoría freelance en el sector deportivo en los próximos 18 meses.

Pilar estratégico 1 - Posicionamiento como experto en deporte de élite:
Ayúdame a definir mi nicho específico dentro del amplio campo del management deportivo. Analiza cinco especializaciones posibles: consultoría de marketing y patrocinios deportivos para clubes de Segunda División y deportes minoritarios que quieren profesionalizarse (el mercado menos competido donde mi experiencia en Primera es un activo enorme), consultoría de digitalización de la experiencia del fan para clubes que están construyendo su primera app o plataforma digital, consultoría de expansión internacional para clubes españoles que quieren crecer en mercados emergentes (Asia, América Latina, Oriente Medio), consultoría de integración de IA y análisis de datos para departamentos de marketing y operaciones de clubes, y formación en gestión deportiva para directivos de clubes de deportes menos profesionalizados como el baloncesto, el balonmano o el atletismo. Para cada especialización, describe el cliente típico, el ticket promedio por proyecto, la competencia y las barreras de entrada.

Pilar estratégico 2 - Estructura de servicios y propuesta de valor para el sector deportivo:
Diseña el catálogo de servicios de la consultoría con tres niveles de compromiso. Nivel 1 - Diagnóstico estratégico (4-6 semanas, honorarios de 8.000 a 18.000 euros): analizo la situación comercial y de marketing del club, identifico las oportunidades de crecimiento de ingresos con mayor impacto y entrego un plan de acción priorizado. Nivel 2 - Consultoría de proyecto (2-6 meses, 700 a 1.200 euros por día): acompaño al club en la implementación de una iniciativa específica (lanzamiento de la app, proceso de captación de un nuevo patrocinador principal, diseño del programa de fidelización de socios). Nivel 3 - Director Comercial o de Marketing en retainer (6-12 meses, 3.500 a 6.000 euros al mes): actúo como directivo externo a tiempo parcial, liderando el área comercial o de marketing del club sin ser empleado. Define los entregables concretos de cada nivel y los criterios de éxito medibles para cada tipo de proyecto.

Pilar estratégico 3 - Captación de clientes en el sector deportivo:
Propón las estrategias de captación de clientes adaptadas a las particularidades del sector deportivo. Los directivos de los clubes son personas muy visibles pero muy ocupadas que reciben muchas propuestas comerciales. Describe cómo construir autoridad y visibilidad en los canales donde sí están: LinkedIn con análisis del sector deportivo que demuestran tu expertise (comparativas de estrategias de patrocinio entre clubes, análisis de casos de éxito y fracaso en la digitalización de la experiencia del fan), ponencias en congresos del sector (Sports Business Congress, Football Business Summit, SportsPro Live), colaboración con las escuelas de negocio deportivo como ponente invitado (Johan Cruyff Institute, ISDE Sports Business School, Real Madrid Graduate School), y publicación de casos de éxito anonimizados de proyectos anteriores en formato de artículos técnicos. Diseña también la estrategia de referencias: cómo cada cliente satisfecho puede presentarte a 2-3 directivos de otros clubes o federaciones de su red.

Pilar estratégico 4 - Uso de la IA como ventaja competitiva del consultor deportivo:
Describe cómo integrar la IA en tu práctica de consultoría para diferenciarte de los consultores deportivos tradicionales. La IA permite: análisis de benchmarking competitivo más profundo y rápido (puedo analizar la estrategia de marketing y patrocinios de los 20 clubes más comparables al cliente en menos tiempo que un consultor tradicional), generación de informes de diagnóstico con datos más completos y visualizaciones más claras, monitorización continua de las tendencias del sector deportivo global (nuevos modelos de negocio en ligas americanas, estrategias de internacionalización de clubes asiáticos, innovaciones en experiencia del fan de clubes de la Premier League) que me mantiene siempre actualizado, modelización financiera de proyectos de inversión del club (ampliación del estadio, lanzamiento de plataforma OTT propia) con escenarios múltiples, y preparación de presentaciones ejecutivas que el cliente puede usar directamente ante su consejo de administración o sus posibles patrocinadores.

Pilar estratégico 5 - Operativa del negocio freelance en el sector deportivo:
Describe la operativa del negocio de consultoría deportiva freelance. Cubre: la visibilidad en el sector (asistir a los partidos y eventos como observador del sector, no solo como consultor de un club específico), la red de subcontratistas que puedes movilizar para proyectos multidisciplinares (diseñadores gráficos especializados en branding deportivo, desarrolladores de apps para fans, especialistas en análisis de datos deportivos, abogados de derecho deportivo), la gestión de la estacionalidad del sector deportivo en el calendario de proyectos (el verano es el momento de mayor actividad para los clubes de fútbol en términos de fichajes y planificación comercial, mientras que la navidad es tranquila), la gestión de la confidencialidad en un sector donde los rumores y las filtraciones son frecuentes y dañinos (contratos de confidencialidad sólidos y una política estricta de comunicación sobre los proyectos en curso), y el plan de crecimiento hacia una boutique de consultoría deportiva con 3-4 consultores asociados en los años 3-5 del negocio que permita asumir proyectos de mayor complejidad con federaciones nacionales o ligas profesionales.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Plan de negocio para consultoría freelance especializada en gestión del deporte de élite',
                'vote_score'       => 46,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
