<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills574Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Estrategia de marketing de contenidos para editorial digital con IA',
                'description'      => 'Diseña una estrategia de marketing de contenidos completa para una editorial digital, aprovechando la IA para identificar tendencias de lectura, segmentar audiencias y maximizar la visibilidad de los títulos publicados.',
                'prompt_content'   => <<<'EOT'
Eres un director de marketing especializado en el sector editorial y publicaciones digitales, con experiencia en la promoción de libros, revistas digitales y contenidos de autor, así como en el uso de herramientas de inteligencia artificial para el análisis de audiencias lectoras y la optimización de campañas de visibilidad editorial.

Contexto de la editorial:
- Editorial digital independiente con catálogo de 120 títulos en ficción literaria, ensayo y no ficción divulgativa
- Distribución en plataformas: Amazon Kindle, Apple Books, Google Play Books, Kobo, y venta directa en web propia
- Equipo de marketing: 2 personas con presupuesto mensual de 4.000 euros para campañas de pago
- Reto: lanzar 18 nuevos títulos en los próximos 12 meses y aumentar las ventas del catálogo existente un 30%
- Audiencia objetivo: lectores adultos de 28 a 55 años con hábito lector consolidado, principalmente en España y Latinoamérica

Desarrolla la estrategia de marketing editorial completa:

1. Análisis de audiencia lectora con IA: Los lectores digitales dejan rastros de datos que permiten entender sus hábitos. Diseña el sistema de análisis. Incluye: cómo usar herramientas de análisis de tendencias literarias (Google Trends aplicado a géneros y autores, análisis de las listas de bestsellers de Amazon por categoría, monitorización de reseñas en Goodreads para detectar qué atributos de un libro generan más engagement), segmentación de la audiencia de la editorial por comportamiento de compra (compradores de novedades vs. compradores de catálogo, lectores fieles a un autor vs. lectores por género, precio sensibles vs. compradores de valor premium), cómo la IA puede identificar qué lectores del catálogo existente son los más probables compradores de los próximos lanzamientos (análisis de patrones de compra cruzada, modelos de recomendación similares a los de Amazon), y diseño del sistema de captación de datos de primera parte (newsletter con incentivo de descarga gratuita, club de lectura privado con acceso a contenido exclusivo, encuestas post-lectura para obtener preferencias de los lectores).

2. Posicionamiento y lanzamiento de nuevos títulos: Cada lanzamiento editorial es una campaña de marketing en sí misma. Diseña el proceso. Incluye: metodología de posicionamiento del título antes del lanzamiento (análisis de los títulos competidores en la misma categoría de Amazon, identificación del hook narrativo que diferencia el libro de los demás, definición del lector ideal del título con perfil detallado de psicografía y comportamiento), estrategia de preventa y creación de anticipación (campaña de revelación de portada, extractos del primer capítulo como contenido de marketing, early bird pricing para compradores anticipados, estrategia de ARC —Advance Review Copies— para conseguir reseñas antes del lanzamiento oficial), secuencia de lanzamiento en las primeras 72 horas (fundamental para el algoritmo de Amazon: coordinar compras, solicitar reseñas a la lista de correo, activar campañas de PPC en Amazon Advertising y Facebook Ads simultáneamente), y estrategia de larga cola post-lanzamiento (cómo mantener las ventas de un título 6-12 meses después del lanzamiento mediante actualización de keywords, descuentos estratégicos y marketing de catálogo relacionado).

3. Marketing en redes sociales para lectores y comunidad literaria: Las redes sociales del mundo editorial tienen sus propios códigos. Diseña la estrategia. Incluye: estrategia de BookTok en TikTok (el mayor impulsor de ventas de libros actualmente: cómo identificar a los BookTokers relevantes para el catálogo de la editorial, qué tipo de contenido funciona —aesthetic shots, reading vlogs, libro que te cambió la vida, adaptaciones cinematográficas pendientes—, cómo conseguir que los creadores hablen de los libros de la editorial sin presupuesto o con micro-presupuesto), Bookstagram en Instagram (cómo colaborar con los influencers literarios de habla hispana, diseño de contenido visual propio de la editorial que sea compartible, estrategia de hashtags literarios en español), y Goodreads como plataforma de marketing editorial (perfil del autor, listas de Goodreads donde posicionar los títulos, gestión de las reseñas de la comunidad, participación en los Goodreads Choice Awards).

4. Amazon Advertising y SEO editorial: Amazon es el mayor punto de venta de libros digitales. Diseña la estrategia. Incluye: arquitectura de las campañas de Amazon Advertising para libros (Sponsored Products con keywords de género y de autor competidor, Sponsored Brands para visibilidad de la editorial, segmentación por producto con libros de autores similares como targets, lockscreen ads en dispositivos Kindle), optimización del listado de Amazon (keywords en el título, subtítulo y descripción, selección de las 2 categorías de Amazon donde el libro puede alcanzar el ranking de bestseller más fácilmente, A+ Content para editoriales registradas en Brand Registry), y estrategia de pricing dinámico (cuándo bajar el precio para impulsar el ranking, cuándo subir el precio para maximizar el margen, Kindle Countdown Deals y Free Book Promotions en KDP Select como herramientas de marketing).

5. Newsletter y comunidad de lectores como activo de marketing: La lista de correo es el activo de marketing más valioso de una editorial. Diseña el sistema. Incluye: estrategia de captación de suscriptores (magnets literarios: primer libro de una serie gratis, guía de lectura exclusiva, selección del mejor libro del catálogo por género), estructura de la newsletter editorial (frecuencia, secciones fijas: recomendación de la semana, extracto de próximo lanzamiento, entrevista al autor, reseña del equipo, oferta exclusiva para suscriptores), y segmentación de la lista de correo para personalizar las comunicaciones según las preferencias de género literario de cada lector (cómo usar etiquetas y segmentos en Mailchimp o ConvertKit para enviar solo los títulos relevantes para cada lector, reduciendo bajas y aumentando la tasa de apertura).

6. Relaciones con medios, crítica literaria y prescriptores: La cobertura editorial sigue siendo el mejor marketing para el sector del libro. Diseña la estrategia. Incluye: mapa de los medios de comunicación y plataformas de crítica literaria relevantes en España y Latinoamérica (suplementos culturales de los grandes diarios, revistas especializadas en literatura, pódcasts literarios con audiencias superiores a 10.000 oyentes, canales de YouTube de crítica literaria), proceso de gestión de relaciones con los críticos literarios (base de datos de contactos, cuándo y cómo enviar ejemplares de reseña, seguimiento sin ser invasivo, cómo usar una reseña positiva como material de marketing), y estrategia de relaciones públicas para los autores de la editorial (posicionamiento de los autores como expertos entrevistables en medios generalistas cuando el tema del libro es de actualidad, presencia en festivales literarios, firma de libros y eventos presenciales como herramienta de marketing de comunidad).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 45,
                'use_case'         => 'Diseñar una estrategia de marketing editorial completa para lanzar nuevos títulos y crecer el catálogo existente',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Sistema de gestión de contenidos editorial con IA para desarrolladores',
                'description'      => 'Diseña e implementa un sistema CMS personalizado para editoriales digitales que use IA para automatizar flujos de trabajo editoriales, gestionar metadatos de libros y optimizar la distribución multicanal.',
                'prompt_content'   => <<<'EOT'
Eres un arquitecto de software especializado en el desarrollo de sistemas de gestión de contenidos para el sector editorial y publicaciones digitales, con experiencia en la integración de modelos de lenguaje en los flujos de trabajo de producción editorial, la gestión de metadatos bibliográficos y la distribución automatizada en plataformas de venta de libros digitales.

Contexto del proyecto:
- Editorial con 8 empleados que gestiona 120 títulos activos y publica 18 nuevos al año
- Actualmente gestionan los libros con hojas de cálculo de Excel y carpetas compartidas en Google Drive, sin sistema centralizado
- Necesitan un CMS editorial que gestione el ciclo de vida completo de un libro: desde la recepción del manuscrito hasta la distribución en las plataformas
- Stack técnico disponible: Laravel 11, PostgreSQL, Vue.js, integración con API de Claude para funcionalidades de IA
- Presupuesto de desarrollo: 3 meses de trabajo de un desarrollador senior

Diseña la arquitectura e implementación del sistema:

1. Modelo de datos del CMS editorial: El núcleo de cualquier CMS editorial es el modelo de datos que representa los libros y su ciclo de vida. Diseña el esquema. Incluye: esquema de base de datos completo para la entidad Book con todos los campos necesarios (ISBN, título, subtítulo, autor, coautor, ilustrador, traductor, género primario, género secundario, descripción corta, descripción larga, palabras clave, idioma original, idioma de la edición, fecha de recepción del manuscrito, fecha de publicación, precio en cada plataforma, estado del libro en el ciclo editorial), tablas relacionadas necesarias (Authors con bio y foto, Series para libros de una misma serie, Categories con la taxonomía de géneros literarios usando la clasificación BISAC o Thema, Platforms para registrar en qué plataformas está distribuido cada libro y el ID de producto en cada plataforma), y sistema de versionado de los libros (cómo registrar las diferentes ediciones y revisiones de un mismo título, gestión de los archivos EPUB y MOBI de cada versión).

2. Flujo de trabajo editorial automatizado con IA: El proceso editorial tiene fases bien definidas. Diseña la automatización. Incluye: pipeline de procesamiento del manuscrito al recibir un nuevo original del autor (recepción del archivo Word o PDF, extracción del texto con Apache POI o similar, análisis automático del manuscrito con IA para generar: resumen ejecutivo del libro, propuesta de sinopsis para las plataformas de venta, lista de palabras clave sugeridas basadas en el contenido, géneros BISAC recomendados, nivel de lectura estimado, temas principales y subtemas), sistema de gestión de tareas editoriales (creación automática de las tareas del flujo editorial al recibir un manuscrito: primera lectura, corrección de estilo, maquetación, diseño de portada, revisión final, generación de archivos de distribución, con asignación de responsable y fechas límite calculadas desde la fecha de publicación objetivo), y generación automatizada de metadatos de distribución (creación de los archivos de metadatos en formato ONIX 3.0 necesarios para la distribución en Ingram, Amazon y otras plataformas de distribución mayorista).

3. Integración con plataformas de distribución: La distribución digital requiere integrarse con múltiples plataformas con sus propias APIs. Diseña las integraciones. Incluye: integración con Amazon KDP via API (subida automática de archivos EPUB y MOBI, actualización de metadatos, sincronización de precios, recuperación de datos de ventas y royalties), integración con Draft2Digital para distribución múltiple (Apple Books, Kobo, Barnes & Noble, 24symbols, Scribd), sistema de sincronización de precios multicanal (cambiar el precio de un libro en el CMS y que se actualice automáticamente en todas las plataformas donde está distribuido, con control de paridad de precios), y dashboard de ventas unificado (recuperación y normalización de los datos de ventas de cada plataforma para mostrar un dashboard consolidado con ventas por título, por plataforma, por período y tendencias).

4. Motor de búsqueda y recomendación interna: Un CMS editorial necesita encontrar y relacionar contenidos. Diseña el sistema. Incluye: implementación de búsqueda semántica en el catálogo (usando embeddings de Claude para indexar las sinopsis y el contenido de los libros, permitiendo búsquedas como "libros sobre familia disfuncional ambientados en el sur de España" que van más allá del matching de keywords), sistema de recomendaciones basado en similitud semántica (dado un libro, recomendar automáticamente otros 5 títulos del catálogo que los lectores de ese libro probablemente también comprarían, útil para la web de la editorial y para las newsletters), y generación automática de bundles y paquetes de libros complementarios (identificar qué títulos del catálogo se complementan temáticamente para crear colecciones y ofertas de paquetes).

5. API y panel de administración: El CMS necesita una capa de acceso a datos y una interfaz de gestión. Diseña ambos. Incluye: diseño de la API RESTful del CMS (endpoints para la gestión completa del catálogo: CRUD de libros, autores, series y categorías; endpoints de consulta para la web y las apps; webhooks para notificar a sistemas externos cuando cambia el estado de un libro), estructura del panel de administración en Vue.js (vistas de gestión del catálogo con filtrado y búsqueda avanzada, vista del pipeline editorial con los libros en cada fase del flujo de trabajo, vista de ventas con los dashboards de métricas consolidadas, formularios de edición de metadatos con sugerencias de IA en tiempo real), y sistema de control de acceso por roles (editor jefe con acceso completo, editor con acceso a los libros asignados, diseñador con acceso solo a los archivos de portada y maquetación, autor con acceso de solo lectura al estado de su libro).

6. Generación de materiales de marketing desde el CMS: El CMS editorial puede ser también el origen de todos los materiales de marketing. Diseña el sistema. Incluye: generación automática de materiales de marketing al publicar un libro (sinopsis adaptadas para diferentes longitudes: 50 palabras, 150 palabras y 300 palabras para diferentes usos, bio del autor en 3 longitudes, extracto del primer capítulo formateado para compartir, propuesta de publicación en redes sociales con texto y hashtags sugeridos), sistema de gestión de la ficha de prensa del libro (template de nota de prensa generado automáticamente con los datos del libro, lista de medios a los que enviarla basada en el género del libro, seguimiento del estado de cada envío a medios), y exportación de fichas de catálogo para ferias del libro (generación automática de la ficha bibliográfica en el formato requerido por la Feria de Frankfurt, la Feria de Guadalajara y el Salón del Libro de París).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Arquitectar un CMS editorial personalizado con automatizaciones de IA para gestionar el ciclo de vida completo de los libros',
                'vote_score'       => 41,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de portadas de libros y sistema de identidad visual editorial con IA',
                'description'      => 'Crea un sistema de identidad visual coherente para una editorial, con guías de diseño de portadas por colección, plantillas adaptables y directrices para usar herramientas de IA generativa en el proceso creativo editorial.',
                'prompt_content'   => <<<'EOT'
Eres un director de arte especializado en diseño editorial y publicaciones, con experiencia en la creación de identidades visuales para sellos editoriales, el diseño de portadas de libros para diferentes géneros literarios y el uso de herramientas de inteligencia artificial generativa (Midjourney, DALL-E, Stable Diffusion) en el proceso de diseño editorial.

Contexto del encargo:
- Editorial independiente con tres colecciones: "Narrativa" (ficción literaria de autor), "Ensayo" (no ficción divulgativa y académica), y "Origen" (novela negra y thriller)
- Catálogo actual de 120 títulos, 18 nuevos al año (6 por colección)
- El problema de diseño: cada colección tiene una identidad diferente pero los lectores no perciben que pertenecen a la misma editorial, falta cohesión del sello editorial
- El objetivo: crear un sistema de diseño de portadas que sea coherente por colección, reconocible como parte del mismo sello editorial, y que funcione en formato digital (thumbnail en Amazon) y físico (si se hace edición impresa)
- Presupuesto de diseño: 800-1.200 euros por portada con diseñador freelance externo, necesitan un sistema que permita mantener la calidad con ese presupuesto

Diseña el sistema de identidad visual editorial:

1. Auditoría y análisis de referentes de diseño editorial: Antes de crear el sistema es fundamental entender el panorama. Incluye: análisis de las editoriales de referencia en cada género para identificar las convenciones visuales del sector (en narrativa literaria: Anagrama, Random House Mondadori, Seix Barral; en ensayo: Turner, Taurus, Alianza Editorial; en novela negra: RBA, Roca Editorial, Salamandra Black), identificación de los patrones visuales que funcionan en cada género (qué tipo de imágenes, tipografías, paletas de color y composiciones son características de cada categoría y generan expectativas correctas en el lector), y benchmarking de cómo las portadas de cada colección funcionan en los entornos digitales (thumbnail de 160x250 píxeles en Amazon, vista en grid en la categoría de Kindle, compartido en redes sociales como imagen cuadrada de 1080x1080).

2. Sistema tipográfico del sello editorial: La tipografía es el elemento más poderoso de cohesión visual de un sello editorial. Diseña el sistema. Incluye: selección y justificación de la familia tipográfica principal del sello (fuente serif con personalidad literaria para los títulos: opciones como Freight Display, Canela, Capitolina, Lyon Text; justificación de la elección basada en legibilidad en tamaño thumbnail, carácter literario y diferenciación de la competencia), sistema de jerarquía tipográfica en las portadas (tamaño y peso del título, nombre del autor, nombre de la colección, sello editorial en el lomo), tipografías secundarias para los elementos de las portadas (créditos de ilustración, texto del reverso, descripción interior), y guía de uso tipográfico por colección (cómo adaptar el sistema tipográfico al carácter de cada colección: más elegante y clásico para Narrativa, más sobrio y funcional para Ensayo, más tenso y expresivo para Origen).

3. Sistema de diseño de portadas por colección: Cada colección necesita su propio lenguaje visual dentro del sistema del sello. Diseña el sistema de cada una. Incluye: colección Narrativa (lenguaje visual: ilustración o fotografía artística con tratamiento de color sofisticado, paleta de colores de temporada para cada año que unifique los 6 títulos de la colección, uso de espacio en blanco como elemento de lujo, composición centrada o con grid clásico editorial), colección Ensayo (lenguaje visual: tipografía como elemento principal de diseño, uso de fotografía documental o conceptual en blanco y negro o color muy desaturado, grid geométrico y orden visual que transmita rigor intelectual, sistema de color por subcategoría: verde para ciencia, azul para historia, ocre para filosofía y humanidades), y colección Origen (lenguaje visual: fotografía o ilustración atmosférica oscura, paleta de colores fría con acentos de color de alta saturación, composición dinámica y tensión visual, tipografía expresiva con alto contraste entre grueso y fino).

4. Uso de IA generativa en el proceso de diseño de portadas: Las herramientas de IA generativa pueden ser parte del flujo de trabajo de diseño editorial. Diseña el proceso. Incluye: guía de uso de Midjourney para la generación de imágenes de portada (prompts base para cada colección con las especificaciones de estilo, iluminación, composición y estética, proceso de iteración desde el concepto inicial hasta la imagen final usable, cómo ajustar los detalles de la imagen generada con Photoshop o Firefly para adaptarla al diseño final de la portada), workflow de uso responsable (cuándo usar IA generativa vs. contratar a un ilustrador o fotógrafo, cómo gestionar los derechos de las imágenes generadas por IA, política editorial sobre la declaración del uso de IA en el proceso creativo), y proceso de revisión de calidad (cómo evaluar si una imagen generada por IA funciona como portada antes de invertir tiempo en el diseño completo: test de thumbnail, test de coherencia con la colección, test de lectura del texto sobre la imagen).

5. Especificaciones técnicas y guía de entrega: El diseño editorial tiene requisitos técnicos muy específicos. Diseña el sistema de especificaciones. Incluye: especificaciones de archivo para cada formato de entrega (portada para Amazon KDP: 2.560 x 1.600 píxeles, JPG a 72 dpi, espacio de color RGB; portada para impresión: archivo con lomo y reverso, PDF X/1-a, 300 dpi, espacio de color CMYK con perfiles ICC, sangrado de 3mm; portada para redes sociales: versión cuadrada 1080x1080, versión vertical para Stories 1080x1920), sistema de archivos y nomenclatura de los proyectos de diseño (cómo organizar los archivos de diseño de cada portada para que cualquier diseñador del equipo pueda continuar el trabajo: estructura de carpetas, nomenclatura de archivos, registro de fuentes y recursos usados en cada portada), y proceso de control de calidad antes de la aprobación final (checklist de revisión: legibilidad del título a escala thumbnail, contraste entre texto e imagen, coherencia con el sistema de la colección, corrección del ISBN en el código de barras, revisión de los créditos legales en el reverso).

6. Brief creativo estándar para diseñadores freelance: Con un sistema bien documentado, el briefing a los diseñadores externos es más eficiente. Diseña el template. Incluye: estructura del brief creativo estándar de la editorial (información del libro: título, sinopsis de 100 palabras, tema principal, tono emocional, 3 palabras que definen la atmósfera del libro; información del autor: foto, bio de 50 palabras, estilo de escritura que el diseñador debe reflejar; referencias visuales: 5 portadas del sector que se acercan al resultado deseado, 5 que se aleja del resultado deseado; especificaciones técnicas: colección, formatos de entrega, plazo, presupuesto y proceso de revisión), proceso de revisión con el equipo editorial (cómo presentar 3 propuestas de concepto antes de desarrollar el diseño final, criterios de evaluación de cada propuesta, cuántas rondas de revisión están incluidas en el presupuesto), y sistema de aprobación final con el autor (cómo implicar al autor en el proceso sin que el diseño se convierta en un comité, cuándo el criterio del autor prevalece y cuándo el del director de arte de la editorial).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 40,
                'use_case'         => 'Crear un sistema de identidad visual coherente para una editorial con guías de diseño de portadas por colección',
                'vote_score'       => 33,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Estrategia de ventas B2B de suscripciones de contenido editorial con IA',
                'description'      => 'Desarrolla una estrategia de ventas para comercializar suscripciones corporativas de contenido editorial a empresas, bibliotecas y centros educativos, usando IA para identificar prospectos y personalizar el outreach.',
                'prompt_content'   => <<<'EOT'
Eres un director de ventas B2B especializado en la comercialización de suscripciones de contenido editorial a instituciones y empresas, con experiencia en la venta a bibliotecas públicas y universitarias, empresas con planes de formación para empleados, centros educativos de secundaria y formación profesional, y corporaciones que ofrecen acceso a contenido como beneficio para sus empleados.

Contexto del negocio:
- Editorial digital que quiere desarrollar un canal B2B de suscripciones institucionales como fuente de ingresos complementaria a las ventas directas al consumidor
- Catálogo relevante para el canal B2B: 45 títulos de no ficción divulgativa, 30 de ensayo de negocios y liderazgo, 20 de formación profesional
- Modelo de suscripción B2B: acceso ilimitado al catálogo completo para todos los empleados o usuarios de la institución, precio por tramos según el número de usuarios (50-200, 201-1000, más de 1000)
- Equipo de ventas: el director de la editorial quiere vender directamente en la primera fase sin contratar equipo comercial
- Objetivo: 15 contratos de suscripción institucional en los próximos 9 meses, con un ticket medio de 2.400 euros anuales

Desarrolla la estrategia de ventas B2B:

1. Mapa de mercado y segmentación de clientes institucionales: El mercado B2B de contenido editorial tiene segmentos muy diferentes. Incluye: análisis de los segmentos de compradores institucionales más accesibles para una editorial independiente (bibliotecas públicas municipales y redes de bibliotecas de las comunidades autónomas: compradores muy racionales con procesos de licitación pública; bibliotecas universitarias: presupuesto más alto pero procesos más lentos; empresas con planes de formación: decisión más ágil si el contenido es relevante para el desarrollo profesional de los empleados; colegios profesionales: interesados en contenido de actualización para sus colegiados), análisis del proceso de compra en cada segmento (quién decide, cuánto dura el proceso, qué criterios usa para evaluar, qué objeciones son frecuentes), y selección de los segmentos prioritarios para los primeros 9 meses basada en el tamaño del ticket, la velocidad del ciclo de ventas y la alineación con el catálogo de la editorial.

2. Propuesta de valor diferenciada para cada segmento: Cada segmento institucional tiene necesidades diferentes. Diseña las propuestas de valor. Incluye: propuesta de valor para bibliotecas (acceso digital sin gestión de ejemplares físicos, estadísticas de uso por título para justificar la renovación del presupuesto ante la dirección, licencias de acceso remoto para los usuarios de la biblioteca sin necesidad de ir al edificio físico), propuesta de valor para empresas con planes de formación (catálogo curado para el desarrollo de competencias profesionales, integración con las plataformas de LMS corporativas más frecuentes, informes de lectura por empleado para demostrar el ROI del plan de formación ante recursos humanos), propuesta de valor para centros educativos (contenido de apoyo curricular alineado con los programas de las asignaturas, acceso para los alumnos desde cualquier dispositivo, ahorro en la compra de libros de texto complementarios), y materiales de venta diferenciados para cada segmento (onesheet, demo de la plataforma, caso de uso, propuesta económica estándar).

3. Prospecting y calificación de oportunidades con IA: Identificar y calificar a los compradores institucionales es el mayor cuello de botella en ventas B2B. Diseña el proceso. Incluye: cómo usar IA para construir la base de datos de prospectos institucionales (búsqueda de bibliotecas públicas en el directorio del Ministerio de Cultura, búsqueda de empresas en España con más de 100 empleados en sectores donde el catálogo de la editorial es relevante usando LinkedIn Sales Navigator, búsqueda de colegios profesionales por categoría profesional), criterios de calificación de cada prospecto (tamaño del presupuesto estimado, existencia de una persona con autoridad de compra identificable, señales de necesidad: ¿tienen ya alguna suscripción digital de contenido? ¿han hecho compras recientes de libros en lote?), y proceso de enriquecimiento de la base de datos de prospectos con información pública (web institucional, memorias anuales de las bibliotecas, informes de RSC de las empresas donde se menciona el acceso a formación como beneficio).

4. Outreach personalizado y secuencia de ventas: El primer contacto con un comprador institucional es determinante. Diseña la secuencia. Incluye: estrategia de primer contacto para cada segmento (para bibliotecas: email al director de la biblioteca con propuesta de prueba gratuita de 30 días para 10 usuarios; para empresas: email al responsable de RRHH o de formación con caso de uso de otra empresa del mismo sector; para colegios profesionales: llamada de presentación al gerente del colegio con propuesta de descuento para colegiados), secuencia de seguimiento en las 6 semanas posteriores al primer contacto si no hay respuesta (cuándo hacer follow-up, qué añadir en cada contacto para aportar valor adicional sin ser invasivo, cuándo escalar a una llamada de demostración o a una visita presencial), y diseño de la demo de la plataforma para compradores institucionales (qué mostrar en los 20 minutos de demo para un director de biblioteca vs. un responsable de RRHH de una empresa: los criterios de evaluación son completamente diferentes).

5. Negociación y cierre de contratos institucionales: La negociación con instituciones públicas y privadas tiene sus particularidades. Diseña el proceso. Incluye: estructura de precios y descuentos según el volumen de usuarios (precio base por tramo, descuentos por volumen, descuentos por pago anual adelantado, descuento de lanzamiento para los primeros 15 clientes), gestión del proceso de compra en instituciones públicas (licitaciones, contratos menores, procedimientos negociados sin publicidad: qué umbral de gasto en España permite el contrato menor sin licitación pública, cómo preparar la documentación para cada procedimiento), proceso de firma del contrato y onboarding del cliente institucional (integración técnica de la plataforma con el sistema de la institución, alta de usuarios, formación del personal de la institución para la gestión del acceso, proceso de activación del acceso para los usuarios finales), y estrategia de renovación y expansión (cómo asegurar la renovación anual del contrato: qué informes de uso enviar al cliente, cuándo hacer la visita de revisión de cuenta, cómo proponer la expansión a más usuarios o a más unidades de la institución).

6. Métricas y sistema de seguimiento del pipeline B2B: La gestión del pipeline de ventas institucionales requiere un sistema específico. Diseña el sistema. Incluye: definición de las etapas del pipeline de ventas B2B editorial (prospecto identificado, primer contacto enviado, respuesta positiva recibida, demo realizada, propuesta enviada, negociación en curso, contrato firmado, cliente activo), métricas clave para el seguimiento semanal (número de prospectos contactados, tasa de respuesta al primer contacto, tasa de conversión de respuesta a demo, tasa de conversión de demo a propuesta, tasa de cierre de propuesta a contrato, ticket medio, tiempo medio del ciclo de ventas), y diseño del sistema de seguimiento en un CRM simple (cómo configurar Pipedrive o HubSpot CRM gratuito para gestionar el pipeline de 50-100 prospectos institucionales simultáneos, automatizaciones de recordatorio para los seguimientos, informes de pipeline semanales para el director de la editorial).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 45,
                'use_case'         => 'Desarrollar una estrategia de ventas B2B de suscripciones de contenido editorial a instituciones y empresas',
                'vote_score'       => 36,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Roadmap de producto para plataforma de lectura digital editorial con IA',
                'description'      => 'Define la estrategia de producto y el roadmap para una plataforma de lectura digital propia de una editorial, con funcionalidades de IA para personalización de la experiencia lectora y recomendaciones.',
                'prompt_content'   => <<<'EOT'
Eres un product manager especializado en plataformas de contenido digital y experiencia de usuario en entornos de lectura digital, con experiencia en el diseño de productos editoriales digitales, la implementación de sistemas de recomendación de libros y el uso de IA para la personalización de la experiencia lectora.

Contexto del producto:
- Editorial independiente que quiere lanzar su propia plataforma de lectura digital como canal directo al consumidor, complementaria a la distribución en Amazon, Kobo y Apple Books
- Objetivo de la plataforma: construir una relación directa con los lectores para reducir la dependencia de las plataformas de distribución y capturar datos de primera parte sobre el comportamiento lector
- La plataforma debe diferenciarse de Kindle o Kobo por la curaduría editorial, la comunidad de lectores y las funcionalidades de IA personalizadas
- Audiencia objetivo: lectores adultos con hábito lector consolidado que valoran la calidad literaria sobre la cantidad, principalmente en España y México
- Plazo para la primera versión: 6 meses, con un equipo de 2 desarrolladores y 1 diseñador UX

Diseña la estrategia de producto y el roadmap:

1. Definición del MVP y propuesta de valor del producto: El primer desafío de una plataforma editorial propia es diferenciarse de las alternativas existentes. Incluye: análisis de las debilidades de las plataformas actuales desde la perspectiva del lector literario (Kindle: excelente en funcionalidad pero impersonal, el catálogo de Amazon es masivo pero sin curaduría de calidad; Kobo: mejor ecosistema de librerías independientes pero funcionalidades de lectura limitadas; Scribd: buen catálogo pero modelo de suscripción con límites frustrantes; Readerly y similares: muy nicho sin masa crítica de lectores), propuesta de valor diferenciada de la plataforma editorial (la curaduría como diferenciador: solo el catálogo seleccionado de la editorial y títulos de editoriales independientes afines, la comunidad de lectores literarios como valor social, la conversación con los autores como experiencia exclusiva, las notas de lectura y la anotación como herramientas de aprendizaje), y definición del MVP con las 5-7 funcionalidades esenciales para el lanzamiento (qué es imprescindible vs. qué puede esperar a la segunda fase: lector EPUB funcional en web y móvil, biblioteca personal, sistema de recomendaciones básico, notas y subrayados, perfil lector, ¿y qué queda fuera del MVP: club de lectura, chat con autores, lectura social, IA avanzada?).

2. Motor de recomendaciones con IA: Las recomendaciones son la funcionalidad de IA más impactante en una plataforma de lectura. Diseña el sistema. Incluye: arquitectura del sistema de recomendaciones (combinación de filtrado colaborativo basado en el comportamiento de los lectores con similitud semántica basada en el contenido de los libros usando embeddings de IA, cold start para nuevos usuarios sin historial de lectura: onboarding con selección de géneros, autores y libros favoritos), fuentes de datos para las recomendaciones (libros completados y abandonados, tiempo de lectura por sesión y por libro, posición donde el lector paró de leer y si retomó el libro o no, notas y subrayados como señal de engagement profundo, lista de deseos), y diseño de la experiencia de recomendaciones (cuándo y dónde mostrar las recomendaciones en la experiencia de lectura, cómo explicar por qué se recomienda cada libro para generar confianza, cómo incorporar las recomendaciones de los editores y críticos de la editorial como layer sobre las recomendaciones algorítmicas).

3. Funcionalidades de lectura activa y anotación: Una plataforma editorial literaria puede ir más allá de la lectura pasiva. Diseña las funcionalidades. Incluye: sistema de notas y subrayados (sincronizados entre dispositivos, organizables por etiquetas temáticas, exportables en formato compatible con Notion, Obsidian o Word para lectores que toman notas de sus lecturas), funcionalidades de lectura activa con IA (seleccionar un fragmento y pedir a la IA que explique el contexto histórico o literario, generar un resumen del capítulo leído, identificar los temas y motivos literarios del libro, hacer preguntas sobre el argumento o los personajes sin spoilers de lo que el lector no ha leído aún), y diario de lectura (registro automático del progreso de lectura con métricas: páginas leídas por día, tiempo de lectura por sesión, racha de días consecutivos leyendo, predicción de cuándo terminará el libro al ritmo actual).

4. Comunidad de lectores y funcionalidades sociales: La dimensión social puede diferenciar la plataforma de los lectores solitarios. Diseña las funcionalidades. Incluye: perfil lector (biblioteca pública o privada, libros en curso, lista de deseos, reseñas y puntuaciones, estadísticas anuales de lectura estilo Spotify Wrapped pero para lectores), clubs de lectura digitales (grupos de lectores que leen el mismo libro al mismo tiempo con espacio de discusión estructurada por capítulos, moderados por los editores de la editorial o por los propios lectores), conexión con los autores del catálogo (sesiones de preguntas y respuestas con los autores, acceso a material exclusivo del proceso creativo del autor: notas de trabajo, versiones descartadas, inspiraciones), y mecánicas de recomendación social (cómo ver qué están leyendo los lectores que sigues, cómo recomendar un libro a un amigo dentro de la plataforma con una nota personal).

5. Modelo de negocio y monetización: La sostenibilidad económica de la plataforma es fundamental. Diseña el modelo. Incluye: análisis de los modelos de monetización posibles (compra individual de cada libro: simple pero menor recurrencia; suscripción mensual al catálogo completo: predecible pero requiere contenido suficiente para justificar el precio; modelo freemium con catálogo básico gratuito y premium de pago: mejor para la adquisición de nuevos lectores), diseño del modelo de precios por nivel (nivel gratuito: acceso a los 10 primeros títulos del catálogo, sin sincronización entre dispositivos, sin funcionalidades de IA; nivel lector 6,99 €/mes: catálogo completo, sincronización en 3 dispositivos, notas y subrayados, recomendaciones básicas; nivel premium 9,99 €/mes: todo lo anterior más funcionalidades de IA avanzadas, acceso a los clubs de lectura y a los eventos con autores, libros antes de la publicación oficial), y estrategia de conversión de distribuidores externos a plataforma propia (cómo incentivar a los lectores que ya compran libros de la editorial en Amazon a pasarse a la plataforma propia: descuento de bienvenida, migración de sus compras anteriores, contenido exclusivo solo disponible en la plataforma directa).

6. Métricas de producto y sistema de aprendizaje: Un producto digital mejora con los datos. Diseña el sistema de métricas. Incluye: métricas de engagement de lectura (tasa de finalización de libros por título: qué libros se terminan y cuáles se abandonan y dónde; tiempo de lectura activa por semana por usuario; frecuencia de sesiones de lectura; uso de funcionalidades de IA: cuántos usuarios usan las notas, las recomendaciones, las preguntas al libro), métricas de negocio (coste de adquisición de usuario, tasa de conversión de freemium a de pago, tasa de retención mensual y anual, net revenue retention, lifetime value por cohorte de usuarios), y proceso de aprendizaje iterativo del producto (cómo priorizar las funcionalidades de la segunda fase basándose en los datos de uso del MVP, cómo hacer entrevistas de usuario con los lectores para descubrir sus frustraciones y deseos, cómo testear nuevas funcionalidades con grupos pequeños antes del lanzamiento general).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 50,
                'use_case'         => 'Definir el roadmap y estrategia de una plataforma de lectura digital editorial con funcionalidades de IA',
                'vote_score'       => 39,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión del talento editorial y cultura organizativa en editoriales con IA',
                'description'      => 'Diseña la estrategia de recursos humanos para una editorial en transformación digital, incluyendo la evaluación de competencias, el desarrollo del talento editorial y la gestión del cambio hacia el uso de herramientas de IA.',
                'prompt_content'   => <<<'EOT'
Eres un director de recursos humanos especializado en la gestión del talento en empresas de medios de comunicación y publicaciones, con experiencia en la transformación digital de los equipos editoriales, el desarrollo de competencias digitales en perfiles creativos y la gestión del cambio en organizaciones con culturas basadas en el conocimiento y la creación de contenido.

Contexto de la editorial:
- Editorial mediana con 35 empleados: 8 editores, 5 correctores, 3 diseñadores, 4 personas de marketing, 6 de ventas, 3 de producción digital, 3 de administración, y el equipo directivo
- La editorial está en proceso de transformación digital: quiere integrar herramientas de IA en el flujo de trabajo editorial pero hay resistencia de parte del equipo creativo (editores y correctores)
- Problema de talento: dificultad para retener a los editores más capaces que reciben ofertas de plataformas digitales y consultoras de contenidos con salarios más altos
- Objetivo del plan de RRHH: aumentar la competencia digital del equipo, reducir la rotación del talento editorial clave y construir una cultura de innovación compatible con la excelencia editorial

Desarrolla el plan de recursos humanos:

1. Diagnóstico del talento y evaluación de competencias digitales: Antes de desarrollar el talento es fundamental entender el punto de partida. Incluye: diseño del mapa de competencias para cada rol de la editorial (qué competencias digitales necesita un editor en 2025: uso de herramientas de IA para la revisión de manuscritos, análisis de datos de ventas para la toma de decisiones editoriales, comprensión del SEO y del marketing de contenidos, gestión de proyectos digitales; qué competencias necesita un corrector: uso de herramientas de IA para la detección de errores, conocimiento de los formatos digitales de publicación, capacidad para trabajar con flujos de trabajo automatizados), proceso de evaluación de competencias del equipo actual (assessment de competencias digitales mediante test de autodiagnóstico, entrevista estructurada de competencias, evaluación 360 grados para los perfiles de liderazgo, análisis de las brechas entre las competencias actuales y las requeridas por la transformación digital), e identificación del talento clave y los roles críticos para la transformación (quiénes son los early adopters de IA en el equipo y cómo convertirlos en champions del cambio, quiénes son los perfiles más resistentes y cuál es la estrategia para acompañarlos, qué roles externos necesita contratar la editorial que no existen en el equipo actual).

2. Plan de desarrollo de competencias digitales para el equipo editorial: La brecha de competencias digitales en los equipos editoriales tradicionales es real. Diseña el plan. Incluye: programa de formación en herramientas de IA para editores y correctores (formación en el uso de asistentes de IA para la revisión estilística y gramatical, formación en herramientas de análisis de legibilidad y estructura narrativa, taller de uso responsable de IA en el proceso editorial con reflexión sobre dónde aporta valor y dónde puede comprometer la calidad), programa de formación en marketing digital para los editores (los editores del futuro necesitan entender cómo funciona Amazon, cómo se optimizan las descripciones de libros para el SEO, cómo se usan las redes sociales literarias; diseña un programa de 3 meses con sesiones semanales de 2 horas), y formato de aprendizaje adaptado a los perfiles creativos (los editores no aprenden bien en formatos de eLearning masivos: diseña un programa con mentoring entre iguales donde los empleados más avanzados enseñan a los demás, proyectos de aprendizaje en el trabajo con casos reales de la editorial, comunidad de práctica interna sobre innovación editorial).

3. Estrategia de retención del talento editorial: La retención de editores talentosos es el mayor reto de las editoriales independientes. Diseña la estrategia. Incluye: análisis de las causas de la rotación en el sector editorial (los editores más talentosos se van a plataformas digitales por salario, pero la motivación para quedarse en una editorial independiente es diferente: autonomía creativa, relación con los autores, impacto en la cultura, posibilidad de dejar huella; cómo capitalizar estos motivadores intrínsecos en la propuesta de valor al empleado), diseño de la propuesta de valor al empleado editorial (EVP: Employment Value Proposition) diferenciada de los competidores digitales (qué puede ofrecer la editorial que no puede ofrecer una consultora de contenidos: participación en los royalties de los libros que el editor desarrolla, porcentaje del beneficio anual de la editorial, autonomía para proponer y desarrollar nuevas colecciones, crédito editorial en los libros publicados, viajes a ferias del libro internacionales), y sistema de reconocimiento no económico del trabajo editorial (cómo reconocer públicamente la labor de los editores dentro de la cultura de la editorial: premios internos al mejor editor del año, reconocimiento en las comunicaciones externas de la editorial, participación en los eventos con autores y lectores como embajadores de la editorial).

4. Gestión del cambio en la transformación digital editorial: La resistencia al cambio en los equipos creativos tiene características específicas. Diseña la estrategia. Incluye: diagnóstico de las resistencias específicas del equipo editorial a la adopción de la IA (el editor teme que la IA reemplace su criterio literario, el corrector teme que la IA le quite el trabajo, el diseñador teme que la IA generativa haga su rol obsoleto; análisis de cada resistencia y diseño de la narrativa que la aborda: la IA como herramienta que amplifica el criterio editorial, no que lo reemplaza), proceso de co-creación del cambio con el equipo (cómo involucrar a los editores más respetados del equipo en el diseño del proceso de adopción de IA, qué cambios en el flujo de trabajo son negociables con el equipo y cuáles son no negociables por eficiencia del negocio), y plan de comunicación interna durante la transformación (frecuencia y formato de las comunicaciones sobre el proceso de transformación, cómo gestionar los rumores y las preocupaciones del equipo, qué victorias tempranas comunicar para construir momentum positivo).

5. Selección y onboarding de nuevos perfiles digitales: La editorial necesita nuevos perfiles que no existían en el equipo. Diseña el proceso. Incluye: definición de los perfiles digitales nuevos que necesita la editorial (data analyst editorial que analiza los datos de ventas y lectura para informar las decisiones editoriales, growth marketer especializado en el marketing de libros en canales digitales, content strategist que gestiona la presencia de la editorial en redes sociales y en la newsletter), proceso de selección adaptado a los perfiles creativos y digitales (cómo redactar las ofertas de empleo para atraer a los mejores candidatos, qué pruebas de selección son apropiadas para cada perfil, cómo evaluar si un candidato digital tiene sensibilidad por la cultura literaria además de competencias técnicas), y programa de onboarding para los nuevos empleados digitales en una cultura editorial (cómo integrar a un data analyst o un growth marketer en una cultura dominada por editores literarios, qué conocimiento del sector editorial necesitan adquirir en los primeros 3 meses, cómo facilitar la colaboración entre los perfiles editoriales tradicionales y los nuevos perfiles digitales).

6. Cultura organizativa y valores editoriales en la era digital: La cultura de una editorial independiente es un activo diferenciador. Diseña la estrategia de cultura. Incluye: definición de los valores culturales de la editorial que deben mantenerse en la transformación digital (compromiso con la calidad literaria por encima de la velocidad, respeto y cuidado del autor como socio creativo, independencia editorial frente a las modas y las presiones comerciales, impacto cultural como misión más allá del negocio), rituales culturales que refuerzan los valores editoriales (reunión semanal del equipo editorial donde se comparte el estado de los manuscritos en proceso, lectura en voz alta de fragmentos de los libros recién publicados, celebración colectiva de los éxitos de los libros: reseña en un gran diario, premio literario, entrada en la lista de bestsellers), y cómo articular la tensión entre la cultura editorial artesanal y la adopción de herramientas digitales (el marco narrativo que permite al equipo entender que ser más eficiente digitalmente les libera tiempo para lo que realmente importa: la labor editorial de fondo que ninguna IA puede reemplazar).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 40,
                'use_case'         => 'Diseñar la estrategia de RRHH para una editorial en transformación digital con integración de IA',
                'vote_score'       => 30,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Análisis financiero y valoración de editoriales independientes con IA',
                'description'      => 'Realiza un análisis financiero completo de una editorial independiente, incluyendo la valoración del catálogo como activo, el análisis de la rentabilidad por título y colección, y la proyección financiera de la transformación digital.',
                'prompt_content'   => <<<'EOT'
Eres un analista financiero especializado en la valoración y el análisis financiero de empresas del sector editorial y de medios de comunicación, con experiencia en la contabilización de los activos intangibles editoriales (derechos de autor, licencias internacionales, catálogo de backlist), el análisis de la economía del libro y la modelización financiera de los modelos de negocio editorial digital.

Contexto financiero:
- Editorial independiente con 12 años de historia, facturación de 1,8 millones de euros anuales
- Ingresos: 68% venta de libros (60% digital, 40% físico), 22% licencias de derechos internacionales, 10% otros (cursos, eventos)
- Catálogo activo: 120 títulos (30 frontlist publicados en los últimos 2 años, 90 backlist)
- Plantilla: 35 personas, los costes de personal representan el 52% de los costes totales
- Situación: el fundador está considerando si vender la editorial a un grupo más grande o buscar un inversor para acelerar la digitalización, necesita entender el valor real de la empresa

Desarrolla el análisis financiero completo:

1. Análisis de la estructura de ingresos y rentabilidad por título: La rentabilidad en el sector editorial varía enormemente según el título. Incluye: metodología para el análisis de rentabilidad por título (cómo imputar los costes directos a cada título: avance al autor, corrección, diseño, maquetación, impresión si hay edición física, costes de marketing específico del lanzamiento; cómo calcular el margen bruto por título en formato digital y físico; qué umbral de ventas necesita un título para recuperar la inversión inicial), análisis de la curva de ventas del catálogo (la distribución de ingresos en el sector editorial sigue la ley de Pareto: el 20% del catálogo genera el 80% de los ingresos; cómo identificar qué títulos de la backlist siguen siendo rentables y cuáles son activos muertos que consumen recursos de gestión sin generar ingresos significativos), y análisis comparativo de la rentabilidad del canal digital vs. físico (márgenes netos después de las comisiones de las plataformas digitales: Amazon se queda el 30-65% del precio según el precio del libro, Apple Books el 30%, Kobo el 30%; márgenes del canal físico después del descuento a librería del 40-50% y los costes de impresión y distribución; cuál es el canal más rentable para la editorial).

2. Valoración del catálogo como activo principal: El catálogo es el activo más valioso de una editorial. Diseña la metodología de valoración. Incluye: metodología de valoración del catálogo editorial (el catálogo de una editorial se valora como la suma descontada de los flujos de caja futuros que generarán los derechos en el catálogo: método DCF aplicado título por título o por cohorte de publicación, múltiplos de EBITDA ajustado que se usan en las transacciones del sector editorial de 5x a 12x según el crecimiento, la calidad del catálogo y la posición del sello), valoración de los derechos internacionales pendientes de licenciar (el catálogo puede tener valor latente en derechos de traducción no vendidos aún, derechos de adaptación audiovisual de títulos con potencial, derechos de venta de catálogo a plataformas de streaming de audiolibros), y cómo presentar la valoración del catálogo a un potencial inversor o comprador (qué datos necesitan para su due diligence: contratos con los autores, extractos de ventas por título y canal, histórico de licencias internacionales, estado de los royalties pendientes de liquidar a los autores).

3. Modelización financiera de la transformación digital: El inversor querrá ver el impacto financiero de la digitalización. Diseña el modelo. Incluye: modelo financiero de la plataforma de lectura digital propia (inversión requerida: desarrollo de la plataforma, marketing de adquisición de usuarios, coste de mantenimiento anual; proyección de ingresos por suscripción: modelo de crecimiento de usuarios de pago en 3 escenarios pesimista, base y optimista; punto de equilibrio de la plataforma y payback period de la inversión inicial), modelo de ingresos de suscripciones institucionales B2B (proyección de contratos por año, ticket medio por segmento, tasa de renovación, ingresos recurrentes anuales a 3 años), y análisis del impacto de la digitalización en los márgenes de la editorial (cómo cambia la estructura de costes si el porcentaje de ventas digitales crece del 60% al 80%: reducción de costes de impresión y distribución física, pero aumento de costes tecnológicos y de marketing digital).

4. Análisis de la deuda de derechos de autor y gestión de royalties: Las obligaciones con los autores son el pasivo más específico del sector editorial. Incluye: sistema de gestión y proyección de los royalties a pagar a los autores (cómo calcular la deuda de royalties acumulada: avances no recuperados, royalties devengados pendientes de liquidar, proyección de los royalties futuros según las ventas previstas de cada título), análisis del riesgo de la cartera de contratos con autores (contratos con cláusulas de reversión de derechos si las ventas caen por debajo de un umbral: cuántos títulos del catálogo están en riesgo de revertir al autor en los próximos 3 años, qué impacto tendría eso en la valoración del catálogo), y estrategia de renegociación de contratos con autores para la era digital (cómo abordar la renegociación de contratos firmados antes del auge del libro digital que pueden tener condiciones de royalties desfavorables para la editorial en los canales digitales, qué ofrecer al autor a cambio de una revisión de las condiciones económicas).

5. Plan financiero para la captación de inversión: Si la editorial decide buscar un inversor, necesita un plan financiero sólido. Incluye: estructura del plan de negocio financiero para inversores (resumen ejecutivo con la tesis de inversión: por qué esta editorial es una oportunidad de inversión en el mercado editorial español, proyecciones financieras a 5 años con los supuestos detallados, análisis de sensibilidad con los escenarios de variación de los supuestos clave, estrategia de salida para el inversor), análisis de los perfiles de inversor adecuados para una editorial independiente (fondos de capital privado especializados en medios y entretenimiento, grupos editoriales internacionales que buscan catálogos en español, family offices con interés en activos culturales, inversores de impacto que valoran la misión cultural de la editorial), y valoración del impacto de la inversión en la estructura de propiedad y en la autonomía editorial (cómo negociar las condiciones de la inversión para proteger la independencia editorial: qué porcentaje de participación es aceptable, qué cláusulas de gobierno corporativo protegen la visión editorial del fundador, cuál es el precio mínimo de la editorial que hace la inversión financieramente atractiva para el fundador).

6. Gestión de tesorería y planificación financiera operativa: La gestión del flujo de caja es crítica en el sector editorial. Diseña el sistema. Incluye: gestión de las estacionalidades del flujo de caja editorial (los ingresos de ventas tienen picos en septiembre-noviembre por la campaña de otoño y en diciembre por Navidad, pero los costes de producción se adelantan 6-9 meses; cómo financiar la producción de los libros que se publicarán en temporada alta sin tensiones de caja en verano), gestión de los plazos de cobro de las plataformas digitales (Amazon paga con 60 días de retraso, Kobo con 45 días, las librerías físicas con 90-120 días; cómo gestionar el capital circulante con estos plazos de cobro largos), y planificación financiera para el lanzamiento de libros (presupuesto de lanzamiento por título según la apuesta editorial: títulos de gran apuesta con 15.000-25.000 euros de marketing, títulos intermedios con 5.000-8.000 euros, títulos de catálogo sin inversión de marketing adicional; cómo tomar la decisión de inversión en marketing de cada título basándose en las previsiones de ventas y el análisis de rentabilidad esperada).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 55,
                'use_case'         => 'Análisis financiero completo y valoración de una editorial independiente para toma de decisiones de inversión',
                'vote_score'       => 34,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Marco legal de contratos editoriales y gestión de derechos de autor con IA',
                'description'      => 'Analiza el marco legal de los contratos editoriales, la gestión de los derechos de propiedad intelectual en la era digital y las implicaciones legales del uso de IA en el proceso de creación y publicación de contenidos.',
                'prompt_content'   => <<<'EOT'
Eres un abogado especializado en derecho de la propiedad intelectual y en el sector editorial, con experiencia en la redacción y negociación de contratos editoriales, la gestión de los derechos de autor en entornos digitales y las implicaciones legales del uso de la inteligencia artificial en la creación, edición y distribución de contenidos.

Contexto del encargo:
- Editorial independiente que necesita revisar y actualizar toda su base contractual con autores y con distribuidores, adaptarla a la era digital y abordar las nuevas cuestiones legales relacionadas con el uso de IA en el proceso editorial
- La editorial tiene contratos con 80 autores diferentes, muchos firmados hace más de 10 años con cláusulas que no contemplan los formatos digitales actuales ni el uso de IA
- Situación urgente: un autor está reclamando que el uso de IA para generar la contraportada de su libro sin su autorización explícita constituye una modificación de la obra que requiere su consentimiento
- Necesidad: auditoría completa de la base contractual y actualización del modelo de contrato editorial para los próximos años

Desarrolla el análisis legal completo:

1. Auditoría del modelo de contrato editorial vigente: La base contractual de la editorial puede tener lagunas significativas. Incluye: revisión de las cláusulas más críticas en los contratos editoriales actuales (cesión de derechos: qué derechos de explotación cede el autor a la editorial y durante cuánto tiempo, si la cesión es exclusiva o no exclusiva, en qué territorio, para qué formatos —la cláusula de formatos desconocidos al tiempo de la firma es fundamental para los contratos de hace 10 años—; royalties: qué porcentaje del precio de venta al público o del precio neto recibe el autor en cada formato y canal; avance: condiciones de recuperación del avance, qué pasa si el libro no recupera el avance), análisis de las lagunas de los contratos pre-digitales (contratos firmados antes de 2010 que no contemplan explícitamente los libros electrónicos, los audiolibros, las suscripciones en plataformas como Scribd o Kindle Unlimited, la venta del catálogo en lote a plataformas institucionales; qué cláusulas generales pueden aplicarse y cuáles crean incertidumbre jurídica), y ranking de riesgo contractual de la cartera de contratos (cuáles son los contratos con mayor riesgo de conflicto con los autores basándose en la ambigüedad de sus cláusulas y en el valor comercial del título).

2. El marco legal del uso de IA en el proceso editorial: Las implicaciones legales del uso de IA en la editorial son complejas y nuevas. Incluye: análisis del caso concreto de la contraportada generada con IA (qué dice el contrato editorial sobre el derecho del autor a ser consultado sobre las modificaciones de su obra, si la contraportada forma parte de la obra en el sentido legal o es un elemento editorial de la editorial, si la generación con IA del texto de la contraportada puede considerarse una obra derivada o una modificación que requiere el consentimiento del autor según el artículo 21 del Texto Refundido de la Ley de Propiedad Intelectual español), marco jurídico del uso de IA para la creación de contenidos editoriales (quién es el titular de los derechos de autor de un texto generado total o parcialmente con IA según la legislación española y europea: el AI Act europeo, las directrices del EUIPO sobre propiedad intelectual e IA, la postura de la Oficina de Copyright de Estados Unidos relevante para los derechos en el mercado anglosajón), y obligaciones de transparencia y etiquetado del contenido generado con IA (si la editorial usa IA para generar partes del proceso editorial es obligatorio declararlo, qué información debe proporcionar al autor y qué al lector final, diferencia entre uso de IA en el proceso editorial interno como herramienta de trabajo vs. contenido generado con IA que llega al lector).

3. Cláusulas para el nuevo modelo de contrato editorial: La editorial necesita actualizar su modelo de contrato. Diseña las cláusulas clave. Incluye: nueva cláusula de derechos digitales y formatos futuros (cesión que cubra todos los formatos digitales existentes y futuros, incluyendo explícitamente: EPUB, PDF, audiolibro, lectura en streaming en plataformas de suscripción, adaptación para plataformas de IA de lectura y resumen, eventual adaptación a formatos de realidad aumentada o virtual; redacción de la cláusula que no genere conflicto con el autor pero que proteja a la editorial), nueva cláusula de uso de IA en el proceso editorial (qué usos de IA puede hacer la editorial con la obra del autor sin necesidad de autorización explícita: corrección ortográfica asistida por IA, análisis de estilo para coherencia interna, generación de materiales de marketing basados en la sinopsis del libro; qué usos requieren autorización explícita del autor: generación de contenido que se presentará como escrito por el autor, entrenamiento de modelos de IA con la obra del autor), y cláusula de remuneración adicional por usos en plataformas de IA (si la editorial licencia el catálogo a plataformas de IA para entrenamiento de modelos o para servicios de resumen y análisis, cómo se reparte esa remuneración con el autor: porcentaje estándar que reconozca el derecho del autor en esos nuevos usos).

4. Gestión de las licencias internacionales de derechos: Las licencias de traducción y distribución internacional son un área de alto valor y alto riesgo. Incluye: proceso legal de la cesión de derechos de traducción (qué debe incluir un contrato de licencia de traducción: territorio, idioma, plazo de la licencia, royalty para el autor original, plazo para la publicación de la traducción, qué pasa si la editorial extranjera no publica la traducción en el plazo pactado), gestión de los contratos de agencia literaria (muchos autores tienen un agente literario que gestiona los derechos internacionales: qué implica para la editorial trabajar con un agente, cuáles son las obligaciones de reporting y de liquidación de royalties, qué conflictos pueden surgir entre la editorial y el agente sobre la gestión de los derechos), y protección del catálogo en mercados con débil protección de la propiedad intelectual (qué medidas puede tomar la editorial para proteger los derechos de sus autores en mercados con alto nivel de piratería digital, registro de copyright en los mercados prioritarios, uso de DRM en los archivos digitales: balance entre protección y experiencia del lector).

5. Regulación de la distribución digital y acuerdos con plataformas: Los acuerdos con las plataformas de distribución tienen implicaciones legales importantes. Incluye: análisis de las condiciones de Amazon KDP y las demás plataformas desde el punto de vista de los derechos del autor y la editorial (qué cede la editorial a Amazon al publicar en KDP, las cláusulas de exclusividad del programa KDP Select y si son compatibles con la distribución en otras plataformas, los derechos de Amazon para usar el contenido de los libros en sus sistemas de IA como Alexa o los resúmenes de libros de Kindle), derechos de la editorial ante el incumplimiento de las plataformas (qué pasa si Amazon retira un libro de la venta sin previo aviso, si Amazon cambia unilateralmente las condiciones económicas, si hay un error en los sistemas de Amazon que causa una pérdida de ventas para la editorial), y análisis del Reglamento de Mercados Digitales (Digital Markets Act europeo) y su impacto en la distribución de libros digitales (si el DMA obliga a Amazon a dar acceso a los datos de ventas y de lectores a las editoriales, si crea obligaciones de interoperabilidad relevantes para la distribución editorial).

6. Gestión de conflictos con autores y resolución de disputas: Las relaciones entre editoriales y autores pueden deteriorarse. Diseña el sistema de prevención y gestión. Incluye: sistema de gestión proactiva de las relaciones contractuales con los autores (calendar de hitos contractuales: cuándo vencen los contratos, cuándo hay que liquidar royalties, cuándo hay que informar al autor del estado de los derechos internacionales; reporting proactivo al autor para evitar la percepción de opacidad que es la principal fuente de conflictos editorial-autor), procedimiento de mediación y arbitraje para conflictos con autores (muchos contratos editoriales modernos incluyen una cláusula de mediación obligatoria antes de acudir a los tribunales: ventajas de la mediación frente al litigio para las editoriales que quieren mantener la relación comercial con el autor a pesar del conflicto, qué organismos de mediación especializados en propiedad intelectual existen en España), y protocolo de respuesta a una reclamación de un autor (cuando un autor o su abogado envía una carta de reclamación, cuál es el procedimiento interno de la editorial para responder: investigar los hechos, consultar el contrato, evaluar el riesgo legal, decidir si negociar o litigar, cómo comunicarse con el autor durante el proceso para evitar el escalado del conflicto).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 50,
                'use_case'         => 'Analizar el marco legal de contratos editoriales y las implicaciones jurídicas del uso de IA en el proceso editorial',
                'vote_score'       => 37,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención al lector y gestión de la comunidad editorial con IA',
                'description'      => 'Diseña un sistema de atención al lector y gestión de la comunidad de lectores de una editorial, usando IA para personalizar las respuestas, gestionar las reseñas y fidelizar a los lectores más comprometidos.',
                'prompt_content'   => <<<'EOT'
Eres un especialista en la gestión de comunidades de lectores y en la atención al cliente en el sector editorial digital, con experiencia en la construcción de comunidades literarias online, la gestión de las reseñas y el feedback de los lectores en plataformas como Goodreads y Amazon, y el uso de la inteligencia artificial para personalizar la comunicación con los lectores y mejorar la experiencia post-compra.

Contexto de la editorial:
- Editorial digital con 8.000 lectores registrados en la newsletter, 15.000 seguidores en Instagram, 6.000 en TikTok
- El equipo de atención al lector es de 1 persona a tiempo parcial que gestiona los emails, los comentarios en redes sociales y las reseñas en Goodreads y Amazon
- Principales problemas de atención al lector: lectores que reclaman libros prometidos que se han retrasado, lectores con problemas técnicos para descargar o leer los archivos digitales, lectores que escriben reseñas negativas en Amazon por problemas que podrían haberse resuelto antes de llegar a la reseña pública, y lectores muy comprometidos que merecen un trato especial pero no hay tiempo para darlo
- Objetivo: con la misma persona a tiempo parcial, mejorar la calidad de la atención al lector y construir una comunidad más comprometida usando herramientas de IA

Diseña el sistema de atención al lector y gestión de comunidad:

1. Sistema de gestión de consultas y soporte con IA: La mayoría de las consultas de los lectores son repetitivas. Diseña el sistema. Incluye: categorización de las tipologías de consultas más frecuentes de los lectores de una editorial (problemas técnicos con la descarga del archivo EPUB o MOBI, problemas de compatibilidad con su lector electrónico o dispositivo, dudas sobre el estado de un pedido o de un libro prometido, reclamaciones sobre la calidad de la edición —erratas, páginas en blanco, corrupción del archivo—, preguntas sobre la agenda del autor o los próximos lanzamientos, solicitudes de entrevistas o colaboraciones), diseño del sistema de respuestas automatizadas con IA para las consultas más frecuentes (base de conocimiento de la editorial con las respuestas estándar a cada tipología de consulta, prompt de Claude para generar respuestas personalizadas que no suenen a plantilla pero que partan de la respuesta correcta, sistema de escalado para las consultas que requieren intervención humana), y proceso de gestión del soporte técnico de los libros digitales (árbol de diagnóstico de los problemas técnicos más frecuentes con los pasos de resolución para cada dispositivo: Kindle, Kobo, iPad con Apple Books, Android con Google Play Books; cómo enviar el archivo en un formato compatible cuando el lector tiene problemas con el formato original).

2. Gestión de reseñas en plataformas digitales: Las reseñas en Amazon y Goodreads son críticas para las ventas. Diseña el sistema. Incluye: estrategia de gestión proactiva de las reseñas (cómo identificar a los lectores que probablemente van a dejar una reseña positiva antes de que lo hagan: lectores que terminaron el libro en tiempo récord, que lo recomendaron a otros, que escribieron un comentario positivo en redes sociales; cómo contactarles para agradecerles y animarles a dejar una reseña en Amazon o Goodreads), proceso de respuesta a las reseñas negativas (cuándo y cómo responder a una reseña negativa en Amazon: no todas las negativas merecen respuesta, solo las que contienen información incorrecta que puede disuadir a compradores o las que plantean un problema de calidad que la editorial ha corregido; tono y extensión de la respuesta; cómo evitar que la respuesta empeore la situación), y sistema de monitorización de reseñas en todas las plataformas (alertas automáticas cuando aparece una nueva reseña en Amazon, Goodreads o en blogs y medios de comunicación, dashboard con el rating medio por plataforma y por título, identificación de los libros con peor rating para investigar si hay un problema de calidad real que corregir).

3. Programa de lectores beta y early reviewers: Los lectores más comprometidos pueden convertirse en un activo de marketing. Diseña el programa. Incluye: diseño del programa de lectores beta de la editorial (criterios de selección de los lectores beta: lectores de la newsletter con alta tasa de apertura, lectores que ya han dejado reseñas de calidad en plataformas anteriores, lectores con presencia en redes sociales literarias aunque no sean grandes influencers; compromisos del lector beta: leer el libro antes de la publicación, dejar una reseña el día del lanzamiento en Amazon y Goodreads, compartir en sus redes sociales; qué recibe a cambio: acceso gratuito al libro antes de la publicación, acceso anticipado a las novedades futuras, mención en los agradecimientos del libro), gestión del programa de early reviewers con herramientas como NetGalley o BookSirens (cómo funciona la plataforma, qué tipo de lectores se encuentran en ella y si son el perfil adecuado para el catálogo de la editorial, cómo gestionar las solicitudes de descarga y el seguimiento de las reseñas prometidas), y evaluación del impacto del programa en las ventas del lanzamiento (correlación entre el número de reseñas en el día del lanzamiento y las ventas de la primera semana, coste del programa de lectores beta vs. el impacto en las ventas).

4. Comunidad de lectores en redes sociales literarias: Construir una comunidad de lectores comprometidos requiere una estrategia específica. Diseña la estrategia. Incluye: gestión de la comunidad en Goodreads (perfil del sello editorial con todos los títulos del catálogo, grupos de Goodreads organizados por colección o por autor, participación activa en los grupos de Goodreads relevantes para el género del catálogo, gestión del programa de Goodreads Giveaways para los nuevos lanzamientos), estrategia de BookTok y Bookstagram para la comunidad de la editorial (qué tipo de contenido genera más engagement en la comunidad lectora de TikTok e Instagram, cómo involucrar a los lectores de la editorial como creadores de contenido: repost de sus fotos con los libros de la editorial, programa de afiliación para los lectores que recomiendan los libros a sus seguidores), y club de lectura de la editorial como comunidad propia (estructura del club de lectura mensual: selección del título, calendario de lectura por semanas, hilo de discusión online moderado por el editor del libro, sesión de preguntas y respuestas con el autor al final del mes; herramientas para gestionar el club de lectura: Discord, grupo de WhatsApp o comunidad privada en la plataforma de la editorial).

5. Personalización de la comunicación con lectores usando IA: La IA permite personalizar la comunicación a escala. Diseña el sistema. Incluye: segmentación de la base de lectores para comunicaciones personalizadas (lectores por género preferido, lectores por frecuencia de compra: fans que compran todos los títulos vs. lectores ocasionales, lectores que han comprado pero no han interactuado con la comunidad vs. lectores muy activos en redes sociales), uso de IA para generar comunicaciones personalizadas a escala (cómo crear emails de recomendación personalizados para cada segmento de lector usando los datos de compra y de preferencias declaradas, generación de mensajes de seguimiento post-compra que pregunten cómo va la lectura y ofrezcan ayuda si hay algún problema técnico, personalización de los mensajes de renovación de suscripción basados en el historial de lectura del suscriptor), y diseño del programa de fidelización de los lectores más comprometidos (identificación automática de los lectores con mayor lifetime value y mayor nivel de engagement, programa de lectores VIP con beneficios exclusivos: acceso anticipado a los lanzamientos, invitación a los eventos de la editorial, posibilidad de participar en el proceso editorial como primeros lectores de un manuscrito, regalo de los libros firmados por el autor).

6. Métricas de comunidad y satisfacción del lector: La calidad de la atención al lector y el estado de la comunidad necesitan medirse. Diseña el sistema de métricas. Incluye: métricas de atención al lector (tiempo medio de primera respuesta a una consulta, tasa de resolución en el primer contacto, satisfacción del lector después de la interacción: encuesta NPS de una pregunta enviada automáticamente después de cada resolución, tasa de reseñas negativas en Amazon como consecuencia de problemas de atención que no se resolvieron a tiempo), métricas de comunidad (crecimiento de la newsletter mes a mes, tasa de apertura y de clic de la newsletter por segmento de lectores, engagement en redes sociales: no solo los seguidores sino los comentarios, los compartidos y las menciones espontáneas de los libros de la editorial, número de miembros activos del club de lectura y tasa de participación en las sesiones con autores), y sistema de feedback del lector para la toma de decisiones editoriales (cómo canalizar el feedback de los lectores sobre los libros leídos hacia los editores de la editorial para que informe las decisiones sobre próximos títulos, encuestas anuales a la comunidad sobre las preferencias temáticas y de género para la programación editorial del año siguiente).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 35,
                'use_case'         => 'Diseñar un sistema de atención al lector y gestión de comunidad editorial usando IA para personalizar la comunicación',
                'vote_score'       => 29,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Freelance editorial: servicios de corrección y edición profesional con IA',
                'description'      => 'Define la propuesta de servicios, la estrategia de captación de clientes y el flujo de trabajo de un freelance especializado en corrección y edición de textos que usa herramientas de IA para ser más productivo y competitivo.',
                'prompt_content'   => <<<'EOT'
Eres un consultor de negocio especializado en el asesoramiento a profesionales freelance del sector editorial, con experiencia en la definición de propuestas de valor para correctores, editores independientes y escritores fantasma, el posicionamiento en plataformas de servicios freelance y el uso de herramientas de IA para aumentar la productividad y la calidad del trabajo editorial.

Contexto del freelance:
- Correctora y editora freelance con 7 años de experiencia en el sector editorial, trabajo en editoriales durante 5 años y lleva 2 años como autónoma
- Servicios actuales: corrección ortotipográfica, corrección de estilo y edición de manuscritos de ficción y no ficción
- Clientes actuales: 3 editoriales pequeñas como cliente recurrente y autores independientes que se autopublican en Amazon
- Problema de negocio: la facturación es irregular (buena en septiembre-febrero, mala en primavera y verano), los precios que cobra son más bajos que los del mercado porque tiene miedo de perder clientes, y siente que las herramientas de IA amenazan su trabajo pero no sabe cómo usarlas a su favor
- Objetivo: aumentar la facturación un 40% en los próximos 12 meses, estabilizar los ingresos y posicionarse como experta en edición con IA en lugar de verse amenazada por ella

Diseña la estrategia de negocio para el freelance editorial:

1. Redefinición de la propuesta de valor y posicionamiento: El mercado de correctores freelance está cambiando con la IA. Diseña el posicionamiento. Incluye: análisis de la diferenciación posible para un corrector freelance en la era de la IA (la IA puede detectar errores ortográficos y gramaticales básicos pero no puede: entender el estilo propio del autor y mantenerlo, detectar inconsistencias de personajes o de la voz narrativa en una novela larga, tener el criterio para saber cuándo una transgresión de la norma es un recurso estilístico deliberado del autor, hacer sugerencias de mejora estructural de un texto con el tacto y la sensibilidad que requiere la relación editor-autor), diseño del posicionamiento diferenciado (en lugar de competir en precio con los servicios de corrección automática de IA, posicionarse como experta en edición profunda de manuscritos con criterio literario asistida por IA para la eficiencia en las tareas mecánicas), y definición de la especialización temática o de género (¿en qué tipo de textos es realmente experta y puede cobrar un precio premium? ¿novela de ciencia ficción y fantasía? ¿ensayo de divulgación científica? ¿memorias y autobiografías? la especialización permite precios más altos y referencias dentro del nicho).

2. Nuevo catálogo de servicios con precios premium: El catálogo de servicios debe reflejar el nuevo posicionamiento. Diseña el catálogo. Incluye: estructura del catálogo de servicios editorial (corrección ortotipográfica básica asistida por IA: precio por 1.000 palabras, incluye uso de herramientas de IA para la primera pasada y revisión humana experta; edición de estilo: revisión profunda del flujo narrativo, la voz del autor, la coherencia del vocabulario y el registro; edición estructural o de desarrollo: trabajo con el autor en la estructura del manuscrito antes de la corrección; lectura beta profesional: informe detallado sobre el manuscrito desde la perspectiva del lector ideal del libro; escritura fantasma de capítulos o de libros completos para autores que tienen las ideas pero no la escritura), estrategia de precios (cómo subir los precios un 30% en los próximos 6 meses sin perder a los clientes actuales: comunicación del cambio de tarifas con anticipación, justificación del precio en el valor entregado no en las horas trabajadas, paquetes de servicios que hacen que el precio más alto sea percibido como mejor valor que el precio más bajo actual), y diseño de paquetes de servicios para autores que se autopublican (paquete completo de preparación de un manuscrito para la autopublicación: edición de estilo + corrección ortotipográfica + informe de lectura beta + revisión de la descripción para Amazon y los metadatos; precio paquete con descuento vs. servicios por separado).

3. Flujo de trabajo con herramientas de IA para aumentar la productividad: La IA bien usada multiplica la capacidad del corrector freelance. Diseña el flujo. Incluye: proceso de corrección ortotipográfica asistida por IA (paso 1: ejecución de la corrección automática con LanguageTool o ProWritingAid para detectar errores obvios; paso 2: revisión del informe de errores detectados por la IA y decisión humana sobre cuáles aceptar, modificar o rechazar; paso 3: revisión final del texto completo por la correctora para detectar lo que la IA no ha detectado: errores de coherencia, ambigüedades de sentido, problemas de flujo; paso 4: informe de corrección para el autor con un resumen de los cambios principales y las observaciones de estilo), uso de IA para acelerar el informe de edición (cómo usar Claude para generar el esquema del informe de edición de un manuscrito a partir de las notas tomadas durante la lectura, cómo usar la IA para detectar inconsistencias de personajes o de la línea temporal en una novela larga que serían muy difíciles de encontrar manualmente), y gestión del tiempo con IA (estimación automática del tiempo necesario para cada proyecto basándose en el tipo de texto, su extensión y el nivel de intervención requerido, para dar presupuestos más precisos a los clientes).

4. Estrategia de captación de clientes y marketing del freelance editorial: La captación de clientes es el mayor reto para un freelance editorial. Diseña la estrategia. Incluye: presencia online para el freelance editorial (web profesional con portfolio de proyectos (con permiso de los autores o anonimizados), blog sobre temas de edición y escritura que posicione a la correctora como experta, perfil de LinkedIn optimizado para que los directores editoriales y los autores independientes la encuentren, presencia en comunidades de escritores y autores en grupos de Facebook y en foros de escritura), estrategia de captación en plataformas de freelance (Reedsy, la plataforma especializada en servicios editoriales para autores anglosajones: cómo construir un perfil de Reedsy atractivo; MaletaEdit y los directorios de profesionales editoriales en España; Fiverr y Upwork para clientes internacionales de habla hispana), y programa de referidos y fidelización de clientes actuales (cómo convertir a los 3 clientes editoriales actuales en fuentes de referencias constantes: sistema de agradecimiento por referencias recibidas, comunicaciones proactivas con novedades relevantes para ellos, primera opción para nuevos proyectos).

5. Gestión financiera y estabilización de ingresos: La irregularidad de los ingresos es el mayor problema del freelance editorial. Diseña la solución. Incluye: análisis de la estacionalidad del trabajo editorial y estrategias para mitigarla (los meses de verano tienen menos trabajo porque los autores están de vacaciones y las editoriales pausan los proyectos; cómo usar esos meses para marketing y captación de proyectos de otoño, cómo ofrecer retainer mensual a los clientes editoriales para tener ingresos garantizados independientemente de si tienen proyectos o no, cómo desarrollar productos de información —cursos online, guías, talleres— que generen ingresos pasivos en los meses bajos), sistema de pricing para estabilizar los ingresos (precio por proyecto vs. precio por horas: cuándo cobrar por proyecto —servicios con entregable claro como la corrección de un manuscrito completo— y cuándo por horas —consultoría editorial, trabajo iterativo con el autor que no tiene un alcance definido—, sistema de depósito del 50% antes de empezar para protegerse de impagos y de cancelaciones de proyectos), y planificación financiera del freelance editorial (cómo calcular la tarifa mínima por hora necesaria para cubrir todos los gastos fijos del autónomo y el salario objetivo, cómo gestionar las facturas de los clientes lentos en pagar, provisión para los meses bajos).

6. Desarrollo profesional y especialización continua: El mercado editorial cambia continuamente y el freelance debe evolucionar con él. Diseña el plan. Incluye: plan de formación continua para el freelance editorial (cursos de edición específicos por género: si se especializa en ciencia ficción, qué conocimiento del género necesita dominar para ser una editora de referencia; formación en nuevas herramientas de IA relevantes para la edición; formación en el mercado de la autopublicación porque los autores independientes son un cliente cada vez más relevante; inglés profesional para acceder al mercado editorial anglosajón que paga mejor), comunidades profesionales de correctores y editores en español (Asociación Española de Correctores de Textos AECIT, Club de Corrección en redes sociales, grupos de profesionales editoriales freelance en LinkedIn), y construcción de la marca personal como experta en edición con IA (artículos de opinión sobre el papel de la IA en el trabajo editorial publicados en medios del sector, participación como ponente en jornadas de escritura y edición, newsletter propia para escritores y autores sobre consejos de escritura y edición que posicione a la correctora como referente en su nicho).
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 35,
                'use_case'         => 'Definir propuesta de valor, servicios y estrategia de negocio para una freelance editorial que usa IA para ser más productiva',
                'vote_score'       => 32,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
