<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills572Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Marketing de contenidos y comunidad para marcas deportivas y de fitness con IA',
                'description'      => 'Diseña estrategias de marketing digital para marcas deportivas y de fitness usando IA para crear contenido que conecta con atletas, entusiastas del deporte y comunidades activas.',
                'prompt_content'   => <<<'EOT'
Eres un director de marketing especializado en el sector deportivo y el fitness, con experiencia en el desarrollo de comunidades activas, la gestión de marcas deportivas y el marketing de contenidos para audiencias que comparten una pasión por el deporte y el estilo de vida activo. Conoces las dinámicas de las comunidades running, ciclismo, crossfit, yoga, fitness en sala y deporte de equipo.

Contexto de la empresa:
- Marca española de ropa técnica y equipamiento de running con 8 millones de euros de facturación anual
- Canales propios: tienda online (55% de la facturación), 12 tiendas físicas (45%), tienda en Amazon (10%)
- Comunidad digital: 180.000 seguidores en Instagram, 45.000 en TikTok, newsletter de 60.000 suscriptores
- Problema: la marca tiene mucha comunidad pero poca conversión directa desde redes sociales a la venta
- Objetivo: aumentar el ratio de conversión de la comunidad en un 40% y lanzar una línea de equipamiento trail running

Desarrolla la estrategia completa de marketing de comunidad para la marca de running:

1. Estrategia de comunidad para marcas deportivas: Las marcas deportivas exitosas construyen comunidades, no audiencias. Diseña la estrategia. Incluye: diferencia entre una audiencia (personas que siguen la marca) y una comunidad (personas que se relacionan entre sí alrededor de la marca y del deporte), pilares de contenido para la comunidad de running (entrenamiento: planes, técnica, consejos de entrenadores; nutrición: alimentación para el rendimiento deportivo; competición: preparación de carreras, análisis de resultados; motivación: historias de runners, superación de barreras; producto: uso del producto en contexto real, no solo fotografía de producto), modelo de los tres círculos de la comunidad (núcleo: 1.000 runners más comprometidos que son embajadores espontáneos; activos: 20.000 seguidores que interactúan regularmente; pasivos: 160.000 seguidores que consumen el contenido), estrategia para mover a las personas del círculo externo al núcleo (qué programas, eventos y experiencias fidelizan al runner casual y lo convierten en embajador de la marca) y métricas de salud de la comunidad (tasa de participación, User Generated Content generado, menciones orgánicas, referencias de comunidad a ventas).

2. Contenido de entrenamiento y running como motor de la comunidad: El contenido de entrenamiento es el tipo de contenido de mayor valor para el runner. Diseña el sistema. Incluye: planes de entrenamiento gratuitos como lead magnet (plan de 12 semanas para primera media maratón, plan de 8 semanas para bajar de 4 minutos el kilómetro, plan de trail running para principiantes), sistema de publicación del contenido de entrenamiento (calendario editorial: lunes plan de la semana, miércoles vídeo de técnica de carrera, viernes motivación y comunidad), formato del contenido de entrenamiento en cada canal (Instagram: posts de carrusel con el plan de la semana, Stories con los ejercicios de movilidad; TikTok: vídeos cortos de técnica de carrera con correcciones comunes; newsletter: análisis en profundidad de aspectos del entrenamiento; YouTube: vídeos largos de entrenamientos completos o de análisis técnico), colaboración con entrenadores de running reconocidos para la producción del contenido de entrenamiento y cómo el contenido de entrenamiento genera conversación y UGC cuando los runners comparten sus resultados usando los planes de la marca.

3. Lanzamiento de la línea de trail running: El lanzamiento de una nueva línea es el proyecto de marketing más importante. Diseña la estrategia. Incluye: estrategia de prelaunch (3 meses antes del lanzamiento: contenido de trail running en todos los canales para preparar a la comunidad, colaboración con trail runners reconocidos para el testing del producto en condiciones reales, campaña de waitlist con incentivos para los primeros compradores), estrategia de lanzamiento (momento del año óptimo para lanzar equipamiento trail: otoño coincidiendo con la temporada de carreras de montaña, activación del lanzamiento en las principales carreras de trail del calendario español: Ultra Trail Sierra Nevada, Buff Epic Trail), estrategia de contenido de trail running diferenciado del contenido de running en asfalto (paisajes de montaña, aventura, naturaleza, comunidad trail muy diferente a la comunidad de running urbano), co-creación del producto con la comunidad (cómo involucrar a los trail runners más activos de la comunidad en el proceso de diseño, qué beneficios les das a cambio, cómo comunicar ese proceso de co-creación) y estrategia de PR deportivo para conseguir presencia en medios especializados de trail running.

4. Influencer marketing y embajadores deportivos: Las marcas deportivas dependen de los embajadores. Diseña la estrategia. Incluye: diferentes tipos de embajadores para una marca de running (atleta de élite: credibilidad de rendimiento pero audiencia distante; atleta de rendimiento mid-pack: más relatable para la comunidad objetivo; runner creativo de contenido: mejor conversión pero menos credibilidad de rendimiento), proceso de selección de embajadores que encajan con los valores de la marca (no solo por el número de seguidores: por la alineación de valores, la calidad de la comunidad, la autenticidad del contenido), estructura del programa de embajadores (niveles: embajador de élite con contrato de representación y exclusividad; embajador de comunidad con producto y comisión de afiliación; runner brand friend con producto sin compromisos de contenido), briefing de los embajadores para el contenido de la línea trail (cómo dar libertad creativa dentro de las guías de la marca para que el contenido sea auténtico) y medición del ROI del programa de embajadores.

5. Eventos deportivos como canal de comunidad y ventas: Las carreras y los eventos deportivos son el punto de encuentro de la comunidad runner. Diseña la estrategia. Incluye: programa de patrocinio de carreras populares y trail runs del calendario español (criterios de selección: participantes del perfil objetivo, visibilidad de la marca en el evento, posibilidad de activación más allá del stand), activación de la marca en los eventos deportivos patrocinados (zona de marca en la salida/llegada, foto booth de la marca para el UGC, sorteo de producto exclusivo del evento entre los participantes, sesión de análisis de carrera con el entrenador de la marca), organización de carreras y eventos propios de la marca (running club de la marca en las principales ciudades, reto mensual de distancia con premio), estrategia de contenido en los eventos (cómo documentar la experiencia en todos los canales para llegar a las personas que no pudieron asistir) y cómo los eventos generan UGC masivo que alimenta los canales de la marca.

6. Email marketing y CRM para la comunidad runner: El email es el canal de mayor conversión en ecommerce deportivo. Diseña el sistema. Incluye: segmentación de la base de 60.000 suscriptores por perfil de runner (nivel de rendimiento, modalidad running/trail/triatlón, historial de compras, participación en los planes de entrenamiento), flujos de email automatizados para cada segmento (flujo de bienvenida para el nuevo suscriptor: 5 emails en 2 semanas presentando la comunidad, el contenido de entrenamiento y los productos clave; flujo de preparación de carrera para el runner que se registró en una maratón: emails de entrenamiento + producto adecuado para la carrera), estrategia de email para el lanzamiento de la línea trail (secuencia de prelanzamiento, email de lanzamiento, emails de seguimiento con testimonios de los primeros compradores) y análisis del lifecycle del cliente runner (cuándo compra más un runner durante el año, qué productos tiene más potencial de cross-sell según la modalidad del corredor).

7. Medición y atribución en el marketing de comunidad deportiva: El marketing de comunidad es difícil de atribuir directamente a ventas. Define el sistema de medición. Incluye: modelo de atribución multi-touch para un proceso de compra que incluye múltiples touchpoints de comunidad antes de la conversión (seguimiento en Instagram → contenido de entrenamiento → newsletter → compra online), KPIs de la comunidad que predicen las ventas futuras (tasa de participación, UGC generado, aperturas de newsletter, asistencia a eventos propios), análisis de la contribución del programa de embajadores a las ventas (por qué el ROAS del embajador calculado en last-click subestima el impacto real del embajador en la decisión de compra) y cómo presentar el valor del marketing de comunidad a la dirección de la empresa de forma que justifique la inversión frente a canales de performance con ROAS más fácil de medir.

Incluye calendario editorial mensual para la comunidad running, plantilla de briefing de embajadores y sistema de scoring de la salud de la comunidad deportiva.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Lanzamiento de línea trail running y crecimiento de comunidad activa para marca deportiva española',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de apps de seguimiento deportivo y análisis de rendimiento con IA',
                'description'      => 'Diseña y construye aplicaciones móviles de tracking deportivo, análisis biomecánico y coaching personalizado con IA para atletas de todos los niveles.',
                'prompt_content'   => <<<'EOT'
Eres un arquitecto de software especializado en el desarrollo de aplicaciones de fitness y deporte, con experiencia en el procesamiento de datos de sensores wearables, la implementación de modelos de análisis de rendimiento deportivo, el desarrollo de sistemas de coaching con IA y la integración con plataformas como Strava, Garmin Connect, Apple Health y Google Fit.

Contexto del proyecto:
- Startup de tecnología deportiva que quiere desarrollar una app de coaching de running personalizado con IA
- La app analiza los datos de entrenamiento del corredor (GPS, frecuencia cardíaca, cadencia, potencia en las últimas versiones de relojes Garmin) y genera planes de entrenamiento personalizados y recomendaciones de mejora de la técnica de carrera
- Mercado objetivo: runners recreativos de nivel medio que quieren mejorar su rendimiento pero no pueden permitirse un entrenador personal
- Tecnología: React Native para la app móvil (iOS y Android), backend en Python (FastAPI), base de datos PostgreSQL, integración con la API de Garmin Connect y Strava API
- Fase de desarrollo: MVP en 6 meses, equipo de 3 desarrolladores y 1 data scientist

Desarrolla la arquitectura completa de la app de coaching de running con IA:

1. Arquitectura del sistema de análisis de datos de running: La app necesita procesar múltiples fuentes de datos. Diseña la arquitectura. Incluye: diseño del modelo de datos para los entrenamientos de running (estructura de un workout: tracks GPS con timestamps, datos de frecuencia cardíaca beat-to-beat, cadencia de zancada, longitud de zancada, potencia si está disponible, temperaturas, desnivel acumulado), pipeline de ingesta de datos desde las APIs de Garmin Connect y Strava (autenticación OAuth2, webhooks para recibir los nuevos entrenamientos del usuario automáticamente, procesamiento asíncrono de los datos con Celery + Redis), diseño de la base de datos de rendimiento del atleta (tablas de entrenamientos, métricas calculadas por entrenamiento, historial de forma física, modelos de fatiga y recuperación) y arquitectura de la capa de análisis (qué métricas se calculan en tiempo real al ingestar un entrenamiento, qué análisis se hacen en batch para el modelo de rendimiento del atleta).

2. Modelo de análisis de rendimiento y forma física del corredor: El corazón de la app es el modelo de rendimiento. Diseña los modelos. Incluye: modelo de estimación del VO2max del corredor a partir de los datos de GPS y frecuencia cardíaca (métodos: Firstbeat, cálculo a partir de la relación velocidad/FC en las sesiones, modelo de regresión con variables de entrenamiento a corto y largo plazo), modelo de fatiga y recuperación basado en el Training Load (ATL: acute training load = fatiga de los últimos 7 días; CTL: chronic training load = forma física de los últimos 42 días; TSB: Training Stress Balance = diferencia entre forma y fatiga = freshness), estimación de los tiempos objetivo del corredor en diferentes distancias (5K, 10K, media maratón, maratón) a partir de sus métricas actuales de rendimiento, modelo de predicción de riesgo de lesión basado en el incremento del volumen de entrenamiento y el ratio fatiga/forma (el aumento superior al 10% semanal es el principal predictor de lesión por sobreuso) y sistema de calibración de los modelos con los datos reales de rendimiento del usuario en competición.

3. Motor de generación de planes de entrenamiento con IA: El plan de entrenamiento es el producto principal de la app. Diseña el motor. Incluye: proceso de onboarding del nuevo corredor para calibrar el modelo (qué datos de entrada necesita el sistema para generar el primer plan: objetivo de carrera y fecha, historial de entrenamiento reciente, test de rendimiento inicial), algoritmo de generación del plan de entrenamiento semanal (cómo distribuir los tipos de sesión en la semana: rodaje suave de base, series de velocidad, tempods, carrera larga, descanso activo; basado en el nivel de forma, la fatiga actual y los días disponibles para entrenar), sistema de adaptación dinámica del plan (cómo el plan se ajusta automáticamente cuando el corredor hace menos o más de lo previsto, cuando tiene una semana de descanso o cuando la fatiga acumulada es demasiado alta), generación de las sesiones de entrenamiento específicas con IA (descripción detallada del calentamiento, la parte principal y la vuelta a la calma; zonas de frecuencia cardíaca o de ritmo objetivo; justificación del objetivo fisiológico de la sesión) y proceso de feedback del corredor sobre las sesiones (cómo el corredor valora la sesión y cómo ese feedback mejora las recomendaciones futuras).

4. Análisis de técnica de carrera con sensores: La técnica de carrera puede analizarse con los datos de los wearables. Diseña el sistema. Incluye: métricas de técnica de carrera extraíbles de los datos de un reloj Garmin (cadencia de zancada, oscillation vertical, ground contact time, stride length, left-right balance) y qué dicen sobre la técnica del corredor, algoritmo de detección de ineficiencias de técnica (cadencia baja = frenado excesivo; oscillation vertical alta = pérdida de energía vertical; desequilibrio izquierda-derecha = riesgo de lesión asimétrica), generación de recomendaciones de mejora de técnica personalizadas basadas en los datos (no recomendaciones genéricas sino basadas en la métrica específica del corredor en comparación con la distribución de corredores de su nivel de rendimiento), sistema de seguimiento de la evolución de las métricas de técnica a lo largo del tiempo para mostrar la mejora al corredor y cuándo recomendar al corredor que consulte a un fisioterapeuta deportivo cuando las métricas de desequilibrio o de contacto superen los umbrales de riesgo de lesión.

5. App móvil y experiencia de usuario: La app tiene que ser simple y motivante para el corredor recreativo. Diseña la UX. Incluye: pantalla principal del dashboard del corredor (qué información mostrar: forma física actual (CTL), frescura (TSB), semana de entrenamiento en curso con el progreso de las sesiones, próxima sesión de entrenamiento, estadísticas del mes), pantalla de detalle del entrenamiento realizado (mapa del recorrido, gráfico de ritmo y frecuencia cardíaca a lo largo del entrenamiento, métricas de técnica, valoración del esfuerzo percibido, comparación con entrenamientos similares del historial), pantalla del plan de entrenamiento (vista semanal con cada sesión descrita, opción de ajustar la sesión si el corredor tiene menos tiempo o más energía), sistema de notificaciones motivantes (recordatorio de la sesión de entrenamiento con la descripción de la sesión, mensaje de felicitación cuando se consigue una mejora personal) y diseño del flujo de onboarding de la app para el corredor nuevo (qué preguntar y en qué orden para calibrar el modelo sin aburrir al usuario).

6. Integración con el ecosistema de wearables y plataformas deportivas: La app necesita integrarse con el ecosistema existente del corredor. Diseña las integraciones. Incluye: integración con Garmin Connect API (proceso de autorización OAuth, descarga de los datos de actividad en formato FIT, webhook para recibir automáticamente los nuevos entrenamientos), integración con Strava API (OAuth2, lectura de actividades, write scope para subir los entrenamientos planeados al calendario de Strava del corredor), integración con Apple Health y Google Fit (para leer datos de pasos, sueño y recuperación que complementan el análisis del entrenamiento), gestión de los conflictos de datos cuando el corredor usa varios dispositivos o plataformas (cómo deduplicar los entrenamientos, cómo reconciliar las métricas de diferentes fuentes) y proceso de importación del historial de entrenamientos para el corredor nuevo (cómo usar los últimos 6-12 meses de datos de Strava o Garmin para calibrar los modelos desde el primer día).

7. Monetización y modelo de negocio de la app de coaching: Diseña el modelo de negocio y la estrategia de crecimiento. Incluye: modelo de precios (freemium con funcionalidades básicas gratis: conexión de Strava, visualización de entrenamientos, plan de entrenamiento básico; premium de 9,99 euros/mes: plan adaptativo con IA, análisis de técnica, coach chat, análisis de rendimiento avanzado), estrategia de captación de usuarios en la comunidad running (presencia en las apps donde ya están los corredores: Strava Clubs, grupos de WhatsApp de running clubs, patrocinio de pódcasts de running), proceso de retención de usuarios premium (qué funcionalidades reducen el churn, cómo detectar usuarios en riesgo de cancelación antes de que cancelen, qué campañas de winback funcionan), modelo de crecimiento basado en la comunidad Strava (cómo aprovechar el grafo social de Strava para la captación viral de nuevos usuarios) y timeline de evolución del modelo de negocio desde el MVP hasta el producto maduro.

Incluye código Python para el cálculo del CTL/ATL/TSB y la estimación del VO2max, esquema de la base de datos del atleta y mockup textual de las pantallas principales de la app.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 85,
                'use_case'         => 'App de coaching de running con IA basada en datos de wearables y planificación adaptativa del entrenamiento',
                'vote_score'       => 57,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de espacios deportivos y experiencia visual de marca fitness con IA',
                'description'      => 'Crea la identidad visual, el diseño de instalaciones y la experiencia de marca para gimnasios, centros deportivos y clubes de fitness que quieren destacar en un mercado muy competitivo.',
                'prompt_content'   => <<<'EOT'
Eres un director creativo especializado en el diseño de marca y espacios para el sector del fitness y el deporte. Tu experiencia abarca el branding de gimnasios boutique, el diseño de interiores de instalaciones deportivas, la creación de identidades visuales para apps de fitness y el diseño de la experiencia del miembro en centros deportivos que compiten con las grandes cadenas de bajo coste.

Contexto del proyecto:
- Cadena de 5 gimnasios boutique de crossfit y functional fitness en Madrid y Barcelona
- Posicionamiento: gimnasios de comunidad con entrenadores de alto nivel, distinta a las cadenas de bajo coste y a los boxes de crossfit más funcionales
- Problema: la identidad visual de los 5 gimnasios es inconsistente (cada uno tiene su propio estilo visual) y la experiencia del miembro varía mucho entre locales
- Objetivo: rediseñar la identidad de marca unificada y el sistema de diseño de los espacios para el rollout a nuevas ciudades

Desarrolla el sistema completo de diseño de marca y espacios para la cadena de fitness:

1. Estrategia de marca para gimnasios boutique de alta gama: La marca de un gimnasio boutique comunica un estilo de vida. Diseña la estrategia. Incluye: posicionamiento de marca que diferencie la cadena de los competidores (las grandes cadenas de bajo coste: precio muy bajo pero sin comunidad ni calidad de coaching; los boxes de crossfit: muy funcionales pero sin la experiencia premium del espacio; los centros de bienestar de lujo: servicio excelente pero sin la intensidad del entrenamiento de alta intensidad), arquetipos de marca para el sector fitness (el guerrero: motivación y superación; el explorador: aventura y descubrimiento; el sabio: ciencia y metodología del entrenamiento) y cuál encaja mejor con este posicionamiento, historia de marca (brand narrative) que conecta emocionalmente con el miembro objetivo: ¿qué siente el miembro cuando entrena en este gimnasio? ¿qué cambia en su vida?, propuesta de valor diferenciada para cada perfil de cliente objetivo (el ejecutivo que necesita eficiencia y comunidad, el deportista que quiere mejorar su rendimiento, la persona que se incorpora al fitness con la necesidad de un entorno motivante) y paleta de valores de marca que guía todas las decisiones de diseño y comunicación.

2. Identidad visual y sistema de diseño de la cadena: El sistema de diseño debe ser coherente y adaptable. Diseña el sistema. Incluye: decisiones de identidad visual (paleta de colores primaria y secundaria con los códigos de color para imprenta y pantalla; tipografías para los titulares, el cuerpo de texto y las aplicaciones de texto de gran formato en el espacio; sistema de iconografía específico para los tipos de entrenamiento: crossfit, functional fitness, movilidad, nutrición), logo y sus variaciones (logo principal, versiones horizontales y verticales, versión en negativo para fondo oscuro, versión simplificada para aplicaciones pequeñas como favicon o pin de solapa), sistema de marca para los diferentes gimnasios de la cadena (cómo mantener la identidad unificada mientras cada local tiene su propio carácter según el barrio donde está), aplicaciones de la identidad visual (señalética del local, uniformes de los entrenadores, botella de agua de marca, camiseta del miembro, app móvil, redes sociales) y guía de estilo de marca (brand book) que permite que diseñadores externos mantengan la coherencia en las futuras aplicaciones.

3. Diseño de la experiencia del espacio del gimnasio boutique: El espacio es el producto más importante de un gimnasio boutique. Diseña el sistema. Incluye: mapa de la experiencia del miembro en el gimnasio (desde que entra hasta que sale: llegada y recepción, vestuarios y taquillas, zona de entrenamiento, zona de recuperación si la hay, cafetería o smoothie bar si la hay) y cómo el diseño del espacio refuerza la experiencia de marca en cada punto del journey, principios de diseño del espacio de entrenamiento (qué transmite el diseño: energía, calidad, comunidad; iluminación: cómo la iluminación afecta el rendimiento y el ambiente del entrenamiento; materiales: qué materiales comunican durabilidad y calidad en un entorno de alta intensidad), diseño de la señalética motivacional del espacio (frases en las paredes, murales, elementos gráficos que inspiran durante el entrenamiento), sistema de diseño del espacio que permita la coherencia de marca entre los diferentes locales de la cadena con las adaptaciones necesarias según el tamaño y la distribución de cada local y concepto de diseño para la zona social del gimnasio (el espacio donde los miembros se relacionan antes y después del entrenamiento es crucial para la comunidad).

4. Identidad visual digital y diseño de la app: La experiencia digital tiene que ser coherente con la física. Diseña el sistema. Incluye: diseño de la app de los miembros de la cadena (reservas de clases, seguimiento del progreso, comunicación con los entrenadores, contenido de entrenamiento complementario: criterios de diseño de la interfaz que reflejan la identidad de marca), sistema de diseño de las redes sociales (templates para los diferentes tipos de contenido: anuncio de clase, resultado del WOD del día, testimonial de miembro, motivación matutina; cómo usar la identidad visual de forma coherente en el feed sin que sea monótona), diseño del email marketing de la cadena (plantilla de newsletter mensual, email de bienvenida al nuevo miembro, email de renovación), diseño del material de ventas digital (página web: estructura y contenido de la home page para convertir al visitante en prueba gratuita; landing page de captación con las distintas ofertas de membership) y cómo la identidad visual digital atrae al tipo de persona que encaja con la comunidad del gimnasio.

5. Fotografía y contenido visual de la marca fitness: El contenido visual del gimnasio boutique debe ser aspiracional pero auténtico. Diseña el sistema. Incluye: guía de fotografía de marca del gimnasio (qué fotografiar: a los miembros entrenando con la intensidad del WOD, los entrenadores en acción demostrando movimientos, el espacio del gimnasio transmitiendo calidad y energía, la comunidad en los momentos sociales; cómo fotografiarlo: ángulos, iluminación, estilo editorial vs. reportaje de vida real), sistema de fotografía escalable (criterios para seleccionar al fotógrafo, brief de la sesión fotográfica, banco de imágenes que permite a cada local tener contenido propio respetando la identidad de marca), guía de vídeo para las redes sociales (cómo grabar los WODs del día, los tutoriales de movimientos, los testimoniales de miembros, los behind the scenes del gimnasio) y uso de IA generativa para crear variaciones visuales (cómo usar herramientas como Midjourney o Adobe Firefly para crear composiciones visuales de marca cuando no hay presupuesto para una sesión fotográfica).

6. Diseño de la experiencia de onboarding del nuevo miembro: Los primeros 30 días determinan si el nuevo miembro se queda. Diseña la experiencia. Incluye: journey del nuevo miembro desde la primera visita (visita de prueba gratuita: qué experiencia vive en esa primera sesión, quién le atiende y cómo, qué información recibe sobre la metodología de entrenamiento y la comunidad), material de bienvenida al nuevo miembro que se une (kit de bienvenida: qué incluye, cómo lo recibe, qué comunicación recibe en las primeras 4 semanas), diseño de la primera clase de introducción a los movimientos del functional fitness (cómo se estructura la clase, qué aprende el nuevo miembro, cómo se relaciona con los otros miembros de su grupo de iniciación) y sistema de seguimiento del nuevo miembro por parte del entrenador en las primeras 4 semanas (cómo se asegura el gimnasio de que el nuevo miembro vuelve, progresa y se integra en la comunidad).

7. Rollout del nuevo sistema de marca a los 5 locales: El diseño es inútil si no se implementa bien. Diseña el plan de rollout. Incluye: diagnóstico del estado actual de cada uno de los 5 locales (distancia a la nueva identidad de marca, inversión necesaria en señalética y diseño del espacio, materiales que se pueden adaptar vs. los que hay que reemplazar), priorización de las intervenciones de diseño por impacto y coste (qué cambia primero: la señalética con la nueva identidad, los uniformes de los entrenadores, los materiales digitales; qué puede esperar: la renovación del espacio completo), plan de comunicación del rebranding a los miembros actuales (cómo comunicar el cambio de identidad sin que los miembros fieles sientan que la marca ha perdido lo que les gustaba) y proceso de validación del diseño con los miembros y los entrenadores antes del lanzamiento oficial.

Incluye brand book resumido con los principales elementos del sistema de diseño, cronograma del rollout del rebranding y briefing de fotografía de marca para los 5 locales.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Rebranding unificado y sistema de diseño de espacios para cadena de gimnasios boutique de functional fitness',
                'vote_score'       => 41,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Ventas de membresías y programas premium en gimnasios y centros deportivos con IA',
                'description'      => 'Domina las técnicas de venta y captación de nuevos socios para gimnasios y centros deportivos, desde la primera visita de prueba hasta el cierre de la membresía y la reducción del churn.',
                'prompt_content'   => <<<'EOT'
Eres un director de ventas especializado en el sector del fitness y el deporte, con experiencia en la venta de membresías de gimnasios, la captación de nuevos socios, la gestión del churn y el diseño de procesos de ventas para centros deportivos que compiten en un mercado muy saturado entre las cadenas de bajo coste y los gimnasios boutique de alta gama.

Contexto del gimnasio:
- Centro deportivo independiente de gama media en Madrid con 4.500 socios activos y 2.800 metros cuadrados
- Oferta: sala de máquinas, clases dirigidas (60 clases semanales), zona de aquafitness, squash (4 pistas) y fisioterapia
- Problema comercial: captación de 120 socios nuevos al mes pero pérdida de 135 socios al mes (churn neto negativo de 15 socios/mes)
- Ticket medio mensual: 52 euros, ticket premium con servicios adicionales: 89 euros
- Equipo de ventas: 3 comerciales y 1 director comercial

Desarrolla el sistema completo de ventas y retención de socios para el centro deportivo:

1. Proceso de venta de membresías en la visita de prueba: La visita de prueba es el momento de máxima oportunidad de venta. Diseña el proceso. Incluye: protocolo de bienvenida al visitante potencial (qué preguntas hacerle en los primeros 2 minutos para entender sus motivaciones: perder peso, ponerse en forma, salud, deporte específico; qué preguntas hacerle sobre su experiencia previa en gimnasios y por qué dejó el anterior), tour personalizado del centro (cómo mostrar las instalaciones de forma que resalte lo que más interesa a ese visitante específico, basándote en las preguntas de diagnóstico del inicio), presentación de la oferta adaptada al visitante (no una sola presentación estándar sino una presentación que conecta las instalaciones y los servicios con los objetivos específicos del visitante), técnica de cierre en la visita (cuándo proponer la membresía, qué oferta de bienvenida usar para acelerar la decisión, cómo manejar las objeciones más frecuentes: necesito pensarlo, es caro, voy a esperar a enero) y qué hacer cuando el visitante no compra en la primera visita (proceso de seguimiento en los 7 días siguientes).

2. Segmentación y ofertas de membresía para maximizar el ticket: El centro tiene clientes con perfiles muy distintos. Diseña el sistema. Incluye: segmentación de los socios actuales por perfil de uso y por motivación (el usuario de máquinas de mañana, el participante de clases de tarde, el usuario de piscina y aquafitness, el jugador de squash, el usuario mixto) y cómo adaptar la oferta a cada perfil, diseño del portfolio de membresías para maximizar el ticket medio sin alejar a los clientes sensibles al precio (membresía básica de acceso en horario valle, membresía estándar de acceso total, membresía premium con servicios adicionales incluidos: sesiones de fisioterapia, nutricionista, entrenador personal), upselling a los socios de base hacia membresías de mayor ticket (qué argumentos funcionan para convencer a un socio de la membresía básica de que vale la pena pagar 15 euros más al mes por los servicios premium) y gestión de las tarifas especiales (descuentos por pago anual, tarifas corporativas para empresas del entorno, tarifas familiares).

3. Diagnóstico y reducción del churn de socios: El centro pierde más socios de los que capta. Diseña el plan de reducción del churn. Incluye: análisis de las causas del churn en el centro (encuesta de salida a los socios que se van: cuáles son las principales razones reales de la baja: precio, falta de tiempo, cambio de lugar de residencia, experiencia insatisfactoria, alternativa más atractiva), señales de riesgo de churn que se pueden detectar antes de que el socio pida la baja (reducción de las visitas semanales por debajo de 1, ausencia de más de 21 días sin ninguna visita, no renovación de la tarifa anual, baja de las clases dirigidas que hacía regularmente), protocolo de intervención cuando un socio entra en riesgo de churn (llamada de su instructor favorito, oferta de una sesión gratuita con un entrenador personal para retomar el hábito, descuento en la cuota mensual durante 3 meses) y proceso de win-back de socios que ya se han dado de baja.

4. Ventas de servicios premium: fisioterapia, entrenamiento personal y nutrición: Los servicios premium son el mayor margen del centro. Diseña el sistema. Incluye: proceso de captación de socios para el servicio de fisioterapia (quién en el equipo del centro puede derivar a la consulta de fisio, cómo detectar a los socios con dolores o limitaciones de movimiento que se beneficiarían de fisioterapia, cómo hacer el primer contacto con el socio para presentar el servicio), proceso de venta del entrenamiento personal (cómo los entrenadores del centro pueden identificar a los socios que necesitan un entrenador personal, cómo hacer la propuesta de venta del paquete de sesiones de forma no invasiva, cómo conseguir que el socio de entrenamiento personal sea fiel al centro porque su entrenador está en ese centro), venta del servicio de nutrición (qué perfil de socio está más dispuesto a combinar el entrenamiento con el asesoramiento nutricional, cómo integrar el servicio de nutricionista en la oferta de bienvenida a los nuevos socios) y sistema de comisiones para los entrenadores y fisioterapeutas que captan clientes para sus servicios.

5. Marketing y captación de nuevos socios: El centro necesita más captación para compensar el churn. Diseña la estrategia. Incluye: estrategia de captación por zonas de influencia del centro (radio de 15-20 minutos a pie, al que pertenecen el 80% de los socios de cualquier gimnasio urbano): reparto de material en el barrio, colaboración con comercios y empresas del entorno, presencia en eventos del barrio, programa de referidos de socios actuales (incentivos para que los socios traigan a un amigo: mes gratis, sesión de entrenamiento personal gratuita), estrategia de captación en los momentos de mayor disposición a unirse a un gimnasio (enero, septiembre, antes del verano): oferta de captación de temporada con condiciones especiales, captación en las carreras y eventos deportivos del barrio y la ciudad (stand de la marca, prueba gratuita del centro para los participantes) y captación digital (Google Local Ads para las búsquedas de gimnasio + barrio, gestión de Google My Business para las reseñas, publicidad en Meta Ads para audiencias del entorno geográfico del centro).

6. Gestión de los periodos de menor afluencia y los socios de baja temporada: La estacionalidad es uno de los mayores retos de un gimnasio. Diseña el sistema. Incluye: análisis de la estacionalidad del centro (en qué meses hay más bajas, en qué meses hay más captación, cómo varía la afluencia diaria y semanal) y estrategia para suavizar los valles, gestión de los socios que quieren dar de baja en verano (oferta de congelación de cuota de 2-3 meses para no perder el socio en lugar de la baja completa), oferta de captación en los meses de menor actividad de los competidores (agosto: cuando los grandes cadenas están al mínimo, una campaña agresiva puede captar socios descontentos) y análisis de la ocupación de las clases y las pistas de squash para detectar horarios con capacidad disponible donde hacer promociones especiales.

7. KPIs y gestión del equipo de ventas del centro deportivo: Define el sistema de gestión comercial. Incluye: KPIs del equipo de ventas (altas mensuales por comercial, tasa de conversión de visitas de prueba en membresía, ticket medio de las nuevas altas, porcentaje de socios de base que se convierten a membresía premium, ventas de servicios premium por mes), sistema de forecast mensual de socios y facturación (proyección de las altas, las bajas y la facturación del mes siguiente), reunión semanal del equipo comercial (revisión de las visitas de prueba de la semana, del pipeline de seguimiento de visitas no convertidas, de las alertas de churn del CRM) y sistema de incentivos del equipo de ventas que alinea con los objetivos del centro (comisión por alta nueva + bonus por reducción del churn + bonus por venta de servicios premium).

Incluye script de la visita de prueba, plantilla de seguimiento de leads no convertidos y sistema de alertas de churn en CRM para centros deportivos.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Inversión del churn y crecimiento de socios en centro deportivo independiente de gama media',
                'vote_score'       => 40,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Gestión de producto en plataformas de entrenamiento online y tecnología deportiva con IA',
                'description'      => 'Define y desarrolla productos digitales para el sector del fitness y el deporte, desde apps de entrenamiento personalizado hasta plataformas de coaching online y wearables de análisis biomecánico.',
                'prompt_content'   => <<<'EOT'
Eres un product manager especializado en tecnología deportiva y fitness con experiencia en el desarrollo de apps de entrenamiento, plataformas de coaching online, hardware wearable deportivo y soluciones de gestión para centros deportivos. Conoces las dinámicas del consumidor de fitness y deporte, los estándares de integración con el ecosistema de wearables y las métricas de retención críticas en el sector.

Contexto de la empresa:
- Plataforma de entrenamiento online con 120.000 usuarios activos y 18.000 suscriptores de pago
- Producto: biblioteca de entrenamientos en vídeo + planes de entrenamiento semanales + comunidad + seguimiento del progreso
- Métricas actuales: churn mensual del 8% (muy alto para SaaS), DAU/MAU del 22% (los usuarios no entrenan suficientemente), NPS de 38
- Competidores: Peloton (equipamiento + contenido), Nike Training Club (gratuito pero sin comunidad), Freeletics (comunidad + IA), Fitbod (IA de fuerza)
- Objetivo: reducir el churn al 4% y aumentar el DAU/MAU al 35% en 12 meses

Desarrolla el sistema completo de gestión de producto para la plataforma de entrenamiento:

1. Diagnóstico del churn y análisis de retención: Para reducir el churn hay que entender por qué los usuarios se van. Diseña el análisis. Incluye: análisis de los patrones de uso que predicen el churn (cuántas sesiones de entrenamiento por semana tiene el usuario que no hace churn vs. el que hace churn, cuántos días llevan sin entrenar los usuarios en riesgo de churn, qué tipos de contenido usan los usuarios que se quedan vs. los que se van), análisis de las entrevistas de cancelación de los usuarios que se van (qué dicen sobre el motivo de cancelación, cuáles son las diferencias entre lo que dicen y el comportamiento real que muestran los datos), análisis de los usuarios que reactivaron su suscripción después de cancelarla (qué les trajo de vuelta, qué estaban haciendo en el período en que no eran suscriptores), análisis de cohortes de churn (qué meses de suscripción tienen mayor riesgo de churn, si hay un mes 3 o mes 6 donde se concentran las cancelaciones) y segmentación de los usuarios por riesgo de churn y potencial de retención para priorizar las intervenciones.

2. Diseño del sistema de adherencia al entrenamiento: El problema real es que los usuarios no entrenan. Diseña el sistema. Incluye: análisis de los motivadores y barreras del entrenamiento regular (por qué los usuarios con buenas intenciones no entrenan: falta de tiempo, cansancio, aburrimiento de la rutina, falta de accountability, no saber qué entrenamiento hacer cada día), diseño del sistema de plan semanal de entrenamiento personalizado con IA (que genera automáticamente los 4-5 entrenamientos de la semana adaptados al nivel, al tiempo disponible y al historial reciente del usuario, eliminando la fricción de decidir qué hacer), sistema de notificaciones inteligentes (no notificaciones genéricas de "es hora de entrenar" sino notificaciones personalizadas basadas en el comportamiento del usuario: cuándo suele entrenar, qué entrenamientos le han gustado más, qué excusas suele poner para no entrenar) y mecanismos de accountability social dentro de la plataforma (retos con amigos, grupos de entrenamiento, tabla de clasificación de la comunidad).

3. Roadmap de producto para los próximos 12 meses: Diseña el roadmap centrado en la retención. Incluye: análisis de las funcionalidades que más impacto tienen sobre la retención (basado en el análisis de los usuarios que se quedan: qué funcionalidades usan más los usuarios con churn bajo vs. alto), propuesta de las 5 apuestas de producto de los próximos 12 meses con el impacto esperado en churn y DAU/MAU, sistema de priorización (ICE score o RICE score) aplicado al portfolio de ideas de producto actual, diseño del proceso de discovery para validar las hipótesis de producto antes de construir (qué tipo de investigación de usuario hacer para cada tipo de apuesta: entrevistas para insights cualitativos, experimentos A/B para validar el impacto cuantitativo) y cómo comunicar el roadmap a los usuarios para que sientan que la plataforma mejora constantemente y se involucren en el proceso de co-creación.

4. Personalización con IA para mejorar la relevancia del contenido: La falta de personalización es una de las principales causas de churn. Diseña el sistema. Incluye: modelo de recomendación de entrenamientos (qué features usar para predecir qué entrenamiento le va a gustar al usuario y le va a ayudar a progresar: historial de entrenamientos realizados, valoraciones de los entrenamientos, nivel actual, objetivos, disponibilidad de tiempo y equipamiento), sistema de adaptación del plan de entrenamiento cuando el usuario no ha completado todas las sesiones de la semana (cómo ajustar el plan de la semana siguiente cuando el usuario se ha saltado sesiones), personalización del contenido de la home de la plataforma (qué entrenamientos mostrar primero para maximizar la probabilidad de que el usuario empiece uno en esa sesión de uso de la app) y proceso de calibración continua del modelo de personalización con el feedback explícito (valoraciones del usuario) e implícito (completó vs. no completó el entrenamiento, tiempo de pantalla en cada tipo de contenido).

5. Comunidad y gamificación como palancas de retención: Los usuarios conectados con la comunidad tienen mucho menos churn. Diseña el sistema. Incluye: diseño del sistema de retos comunitarios (reto mensual de la plataforma donde todos los usuarios tienen el mismo objetivo: X sesiones en el mes, X kilómetros corridos, X días de movilidad; gamificación del reto con tabla de clasificación y celebración de los resultados), sistema de conexión entre usuarios con objetivos similares (cómo conectar a dos usuarios que quieren entrenar a la misma hora, que tienen el mismo objetivo de pérdida de peso, que hacen el mismo tipo de entrenamiento) de forma que se genere accountability mutuo, programa de streaks de entrenamiento (racha de días consecutivos entrenando: uno de los mecanismos de gamificación con más impacto en la adherencia al ejercicio) y diseño de los hitos de progreso del usuario que se celebran y comparten en la comunidad (primera semana de 5 entrenamientos, primera marca personal de fuerza, primer mes completado al 100% del plan).

6. Monetización y expansión del modelo de negocio: La plataforma tiene oportunidades de ingresos más allá de la suscripción. Diseña el modelo. Incluye: análisis del potencial de upselling dentro de la plataforma (qué servicios premium puede contratar el suscriptor dentro de la plataforma: sesiones de coaching en directo con un entrenador profesional, plan de nutrición personalizado integrado con el plan de entrenamiento, análisis de movimiento con feedback de un entrenador), diseño del programa de coaching en directo como servicio premium (cómo integrar videollamadas de entrenamiento personal en la plataforma, cómo gestionar la calidad y la disponibilidad de los coaches, qué precio puede soportar el mercado), modelo de partnership con marcas de equipamiento deportivo y suplementación (oportunidades de integración de productos y marcas en la experiencia de entrenamiento) y evaluación del modelo de licencias B2B (vender la plataforma a gimnasios y centros deportivos como herramienta de engagement de sus socios fuera del gimnasio).

7. Métricas de producto y cultura de datos: Define el sistema de medición del producto. Incluye: North Star Metric de la plataforma (la métrica que mejor predice el éxito a largo plazo: número de sesiones de entrenamiento completadas por usuario activo y semana; por qué esta métrica captura mejor el valor que el DAU simple), sistema de métricas de producto en cascada (North Star → métricas de cada área del producto: adquisición, activación, retención, ingresos; OKRs del equipo de producto alineados con las métricas de retención) y proceso de revisión semanal de las métricas del producto con el equipo de producto y los stakeholders.

Incluye framework de análisis de churn, plantilla de discovery de producto y North Star Metric dashboard para plataforma de fitness.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Reducción del churn y mejora de la retención en plataforma de entrenamiento online con IA y comunidad',
                'vote_score'       => 51,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión de equipos de entrenadores y staff en centros deportivos con IA',
                'description'      => 'Diseña sistemas de gestión del talento para gimnasios, clubes deportivos y centros de fitness, desde la selección y formación de entrenadores hasta la evaluación del desempeño y la retención del equipo.',
                'prompt_content'   => <<<'EOT'
Eres un director de RRHH especializado en el sector del fitness y el deporte, con experiencia en la gestión de equipos de entrenadores personales, instructores de clases colectivas, técnicos deportivos y personal de recepción en centros deportivos, clubes de fitness boutique y cadenas de gimnasios con múltiples locales.

Contexto del centro deportivo:
- Cadena de 8 gimnasios en Madrid con 320 trabajadores (160 entrenadores y monitores de clases, 80 de personal de recepción y administración, 80 de mantenimiento y limpieza)
- Problema de RRHH: rotación del 55% anual en el equipo de entrenadores y monitores (la rotación del sector es alta pero este nivel está por encima del benchmark)
- Segundo problema: la calidad del servicio varía mucho entre locales porque cada local tiene un jefe de sala con distinto nivel de gestión de personas
- Cultura: muy orientada a resultados comerciales (cuántas membresías se venden) pero con poco foco en la experiencia del miembro
- Objetivo: reducir la rotación de entrenadores al 30% y mejorar el NPS de los miembros al 55

Desarrolla la estrategia completa de gestión del equipo de la cadena de gimnasios:

1. Diagnóstico de la rotación del equipo de entrenadores: Para reducir la rotación hay que entender las causas reales. Diseña el proceso. Incluye: proceso de entrevistas de salida con los entrenadores que se van (cuáles son las razones reales de la salida: salario, horarios, trato del jefe de sala, falta de desarrollo profesional, expectativas no cumplidas en la contratación) y cómo crear el ambiente de confianza necesario para que el entrenador sea honesto, encuesta de clima laboral específica para entrenadores de fitness (dimensiones a medir: autonomía en el diseño de las clases y los programas de entrenamiento, calidad de las instalaciones y del material disponible, relación con el jefe de sala, oportunidades de formación continua y de desarrollo profesional, reconocimiento por los miembros y por la dirección) y análisis del momento del ciclo de vida del entrenador donde más se producen las salidas (los primeros 6 meses, el año 2 cuando ya tienen experiencia y son reclutados por la competencia, los 5 años cuando sienten que han llegado al techo de la carrera en la empresa).

2. Propuesta de valor al entrenador de fitness: ¿Por qué un buen entrenador debería trabajar en esta cadena? Diseña la propuesta. Incluye: análisis de lo que valoran más los entrenadores de fitness en un empleo (más allá del salario: la calidad de los miembros con quienes trabajan, la libertad para diseñar sus programas de entrenamiento, el acceso a formación de calidad, la posibilidad de tener clientes de entrenamiento personal además de las clases colectivas, el orgullo de trabajar en un entorno de alta calidad), diseño de los beneficios específicos del sector fitness que la cadena puede ofrecer (tiempo libre para competir en su deporte si son atletas, acceso a las instalaciones fuera del horario laboral para su propio entrenamiento, descuento en servicios para sus familiares, tarjeta de formación anual para cursos y certificaciones de su disciplina) y cómo comunicar la propuesta de valor al entrenador potencial durante el proceso de selección y a los entrenadores actuales para que sientan que la empresa los valora.

3. Selección y onboarding de entrenadores y monitores: El proceso de selección determina en gran medida la calidad y la rotación del equipo. Diseña el proceso. Incluye: perfil del entrenador ideal para la cadena (no solo la titulación y las certificaciones, sino también: orientación al cliente, capacidad para motivar a personas de distintos niveles, actitud de aprendizaje continuo, habilidades de comunicación y empatía, valores alineados con la cultura del centro), proceso de selección específico para entrenadores y monitores de fitness (clase práctica de demostración con evaluación por criterios objetivos: estructura de la clase, cueing verbal, relación con los alumnos, corrección de la técnica; entrevista de valores y situaciones; verificación de referencias de empleos anteriores) y programa de onboarding del nuevo entrenador en sus primeras 8 semanas (formación en los sistemas y protocolos de la cadena, mentoría por un entrenador senior del local, feedback estructurado de las primeras clases, integración en el equipo del local).

4. Desarrollo profesional y formación continua del equipo técnico: En el sector del fitness, el conocimiento caduca rápido. Diseña el sistema. Incluye: mapa de carrera para los entrenadores de la cadena (monitor de clases → entrenador de sala → entrenador personal → jefe de sala → director técnico del local) con los criterios objetivos de ascenso entre niveles, programa de formación continua financiado por la empresa (certificaciones en nuevas disciplinas, congresos del sector como FIBO, Fitnessclub o ClubSalud, cursos de entrenadores de élite invitados a impartir formación en la cadena), sistema de desarrollo del jefe de sala como gestor de personas (la mayoría de los jefes de sala son buenos técnicos que no han tenido ninguna formación en gestión de equipos) y proceso de succession planning para los puestos clave de la cadena (quién puede ser el próximo director de un nuevo local, cómo se le prepara para el rol).

5. Evaluación del desempeño del entrenador y el monitor: La evaluación del desempeño en el fitness tiene dimensiones técnicas y comerciales. Diseña el sistema. Incluye: criterios de evaluación del desempeño del entrenador (dimensión técnica: nivel de ocupación de sus clases, valoración de sus clases por los miembros en la app, feedback del jefe de sala sobre la calidad del coaching y la seguridad; dimensión comercial si es entrenador personal: volumen de sesiones de entrenamiento personal vendidas y realizadas; dimensión de cultura y equipo: colaboración con el resto del equipo, cumplimiento de los protocolos del centro), proceso de evaluación trimestral del desempeño (quién evalúa al entrenador, con qué herramientas, cómo se comunica el resultado, cómo se construye el plan de desarrollo) y sistema de reconocimiento del entrenador de alto desempeño (entrenador del trimestre: incentivo económico + visibilidad en las comunicaciones del centro hacia los miembros + plaza en un curso de formación premium).

6. Gestión de los entrenadores de entrenamiento personal: Los entrenadores personales tienen un modelo de trabajo diferente. Diseña el sistema. Incluye: modelo de relación entre la cadena y los entrenadores personales (empleado con salario fijo que vende sus sesiones para el centro vs. autónomo que paga una cuota al centro por usar las instalaciones y se queda con el 100% de sus honorarios), sistema de captación de clientes de entrenamiento personal para los entrenadores (cómo el centro facilita que los nuevos socios conozcan a los entrenadores personales disponibles y las pruebas gratuitas de valoración), gestión de los conflictos entre entrenadores personales (disputas sobre clientes compartidos, competencia desleal en precios entre entrenadores del mismo centro) y proceso de salida del entrenador personal cuando se va de la cadena (qué pasa con sus clientes, cómo la cadena gestiona la transición para no perder el cliente).

7. KPIs de RRHH para cadena de gimnasios: Define el sistema de medición. Incluye: KPIs del equipo de RRHH de la cadena (tasa de rotación anual por categoría de trabajador y por local, tiempo medio de cobertura de las vacantes, resultado de la encuesta de clima por local, tasa de ascensos internos vs. cobertura externa de puestos de responsabilidad), correlación entre los indicadores de RRHH y los indicadores de negocio (correlación entre la rotación de entrenadores de un local y el NPS de los miembros del local, correlación entre el clima del equipo del local y la tasa de churn de socios) y reporting mensual de RRHH para la dirección de la cadena con los indicadores de personas por local y la alerta de los locales con mayor riesgo.

Incluye plantilla de evaluación del desempeño del entrenador, guión de la entrevista de selección con demostración práctica y plan de formación anual para entrenadores de fitness.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_cause'        => 'Reducción de la rotación de entrenadores y mejora de la experiencia del miembro en cadena de gimnasios',
                'use_case'         => 'Reducción de la rotación de entrenadores y mejora de la experiencia del miembro en cadena de gimnasios',
                'vote_score'       => 37,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Control financiero y modelo de negocio de centros deportivos y clubes con IA',
                'description'      => 'Gestiona y optimiza las finanzas de gimnasios, clubs deportivos y centros de fitness usando IA para analizar la rentabilidad, controlar el churn y maximizar el valor de vida del socio.',
                'prompt_content'   => <<<'EOT'
Eres un director financiero especializado en el sector del fitness y el deporte, con experiencia en el modelo de negocio de centros deportivos, clubs de tenis y golf, academias deportivas y plataformas digitales de entrenamiento. Conoces las particularidades financieras del sector: la importancia crítica del churn de socios, la estacionalidad del negocio, los costes fijos elevados y la dificultad de escalar sin duplicar la infraestructura.

Contexto del negocio:
- Red de 6 centros de fitness en ciudades medianas de España (no Madrid ni Barcelona), con 2.800 socios por centro de media
- Facturación total: 8,4 millones de euros anuales (cuota mensual media de 42 euros)
- EBITDA actual: 12% (muy bajo para el sector, que tiene benchmarks del 18-25%)
- Principales costes: personal (45%), alquiler (25%), suministros energéticos (12%), mantenimiento y equipamiento (8%), marketing (5%), otros (5%)
- Objetivo: llegar al 18% de EBITDA en 24 meses sin reducir la calidad del servicio ni despedir personal

Desarrolla el sistema completo de control financiero para la red de centros deportivos:

1. Modelo económico del centro deportivo y el lifetime value del socio: El LTV del socio es el KPI financiero más importante. Diseña el modelo. Incluye: modelo de LTV del socio (ticket medio mensual × meses de permanencia media − coste de captación del socio: cómo calcular el LTV por segmento de cliente, cómo proyectar el LTV de un socio nuevo con base en los datos históricos del segmento al que pertenece), análisis de la relación entre el coste de captación y el LTV (LTV/CAC: el benchmark del sector es un LTV/CAC superior a 3; cuándo vale la pena invertir más en captación y cuándo hay que priorizar la retención), modelo de reducción del EBITDA en función del churn (cuántos euros de EBITDA se pierden por cada punto porcentual de aumento del churn mensual) y análisis de la contribución marginal de cada centro (cuáles de los 6 centros generan más EBITDA por metro cuadrado, cuáles están por debajo del break-even).

2. Optimización del coste de personal sin reducir la calidad: El personal es el 45% de los costes. Diseña el plan. Incluye: análisis de la productividad del personal por centro (ratio socios activos/empleado, ingresos por empleado, coste de personal por socio como porcentaje de la cuota mensual) y comparación con el benchmark del sector, modelo de optimización de los turnos de los entrenadores para reducir el sobrecoste de horas extra en las horas punta (cómo usar los datos de ocupación de las instalaciones por hora del día para diseñar los turnos más eficientes), análisis del mix entre empleados fijos y trabajadores con contrato a tiempo parcial o por obra y servicio para las actividades estacionales (clases de verano al aire libre, campamentos deportivos de verano) y evaluación de la externalización de ciertos servicios (limpieza, mantenimiento de equipamiento, seguridad) y su impacto en el coste vs. la calidad del servicio.

3. Gestión del coste de energía en instalaciones deportivas: La energía es el 12% de los costes. Diseña el plan. Incluye: auditoría energética de los 6 centros (cuánto consume cada centro en kWh por metro cuadrado y por socio, cuáles son las horas de mayor consumo: la piscina climatizada en invierno, los vestuarios, la climatización de la sala de máquinas), inversiones de eficiencia energética con mayor ROI para el sector deportivo (LED en todas las instalaciones, sistema de climatización con control por zonas y por horarios, placas solares en los techos de los centros si son de su propiedad) y análisis financiero de cada inversión (VAN, TIR, payback), sistema de seguimiento y control del consumo energético en tiempo real con alertas cuando un centro supera el consumo objetivo y gestión de los contratos de suministro eléctrico (cuando renuevan, negociación del precio con el mercado libre).

4. Estrategia de pricing y optimización del revenue: El precio de la membresía es la palanca de revenue más poderosa. Diseña el sistema. Incluye: análisis de la elasticidad precio de los socios (cuántos socios se pierden por cada euro de subida de precio en los distintos segmentos del mercado objetivo), estrategia de pricing dinámico por horario (precio más bajo para las membresías de acceso en horas valle, precio premium para las membresías de acceso total), análisis del potencial de upselling de servicios premium (entrenamiento personal, clases especializadas de yoga o pilates, nutricionista, fisioterapia) y su contribución al ticket medio por socio, estrategia de pricing de los contratos corporativos (cuándo vale la pena dar un descuento corporativo para un cliente que trae 50 socios nuevos de golpe) y evaluación de la subida anual de precios (cuándo y cómo comunicar la subida de precios para minimizar las bajas).

5. Planificación financiera y presupuesto por centro: Cada centro es un centro de beneficio independiente. Diseña el sistema. Incluye: proceso de presupuestación anual de cada centro (cómo construir el presupuesto de ingresos: socios actuales × probabilidad de retención + socios nuevos esperados × ticket medio; cómo construir el presupuesto de costes: costes fijos + costes variables en función del nivel de actividad), cuadro de mando financiero mensual por centro (ingresos reales vs. presupuesto, socios actuales vs. objetivo, churn del mes vs. objetivo, EBITDA mensual vs. objetivo) y proceso de corrección cuando un centro se desvía del presupuesto, proceso de inversión en mejoras de instalaciones de los centros (criterios para priorizar: ROI esperado, urgencia de la inversión para mantener la calidad, capacidad de financiación de la cadena) y evaluación financiera de la apertura de nuevos centros o el cierre de centros con EBITDA negativo persistente.

6. Código Python para el análisis financiero de la red de centros: Proporciona implementaciones concretas. Incluye: (a) modelo de proyección de socios y facturación para los próximos 12 meses que tenga en cuenta la estacionalidad histórica, el churn mensual por segmento de cliente y las campañas de captación planificadas, (b) análisis de la contribución de cada centro a la facturación y al EBITDA de la red con el gráfico de cascada (waterfall chart) de la evolución del EBITDA, (c) modelo de análisis de la rentabilidad por segmento de socio (membresía básica vs. estándar vs. premium: cuál tiene mayor LTV y menor churn) y (d) simulador del impacto en el EBITDA de la red de diferentes escenarios de precio y churn.

7. Reporting financiero para los inversores y la dirección: Define el sistema de reporting. Incluye: cuadro de mando mensual de la dirección (los KPIs más importantes de los 6 centros en una sola página: socios, churn, ingresos, EBITDA, caja generada por las operaciones), informe trimestral para los inversores financieros de la cadena (análisis del rendimiento vs. el plan de negocio, explicación de las desviaciones, outlook del trimestre siguiente y del año completo) y cómo comunicar a los inversores una mala noticia (un trimestre con EBITDA por debajo del plan) de forma profesional y constructiva.

Incluye modelos de Python para la proyección financiera, plantilla del cuadro de mando mensual por centro y modelo de LTV por segmento de socio para centros deportivos.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Mejora del EBITDA de red de centros deportivos mediante optimización de costes y pricing con modelos financieros',
                'vote_score'       => 49,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Marco legal de contratos deportivos, derechos de imagen y compliance de clubs con IA',
                'description'      => 'Navega el marco legal del deporte profesional y amateur: contratos de deportistas, derechos de imagen, convenios colectivos deportivos y compliance de clubes deportivos con IA como asesor jurídico.',
                'prompt_content'   => <<<'EOT'
Eres un abogado especializado en derecho deportivo con experiencia en la negociación y redacción de contratos de deportistas profesionales, la gestión de derechos de imagen en el deporte, el asesoramiento a clubes y federaciones deportivas, la regulación del deporte profesional en España (Ley del Deporte, Ley del Deporte Profesional, convenios colectivos de futbolistas y baloncestistas) y la regulación de las apuestas deportivas y el dopaje.

Contexto del club:
- Club de fútbol de Segunda División española con un presupuesto de 8 millones de euros anuales
- Plantilla: 24 futbolistas profesionales + 8 del filial que entrenan con el primer equipo
- Problema legal: el club está en proceso de negociación de la renovación de 6 contratos de jugadores, tiene una disputa laboral con un jugador que quiere rescindir su contrato por impago de salarios y está considerando fichar a un jugador extranjero fuera del mercado de la UE
- Necesidad: revisión del marco legal de los contratos de la plantilla y asesoramiento para las negociaciones de renovación

Desarrolla el asesoramiento jurídico completo para el club deportivo:

1. Marco legal del contrato del deportista profesional en España: El contrato laboral del futbolista tiene reglas especiales. Explica el marco. Incluye: regulación específica del contrato del deportista profesional bajo el Real Decreto 1006/1985 (en qué se diferencia del contrato laboral ordinario: la temporalidad es la norma, no la excepción; la rescisión por mutuo acuerdo; el régimen especial de indemnizaciones) y cómo el convenio colectivo del fútbol profesional de la RFEF modifica o complementa ese marco, elementos esenciales del contrato del futbolista profesional de Segunda División (duración, retribución fija y variables, derechos de imagen, cláusula de rescisión, derechos de formación, cláusulas de rendimiento deportivo), régimen de extinción del contrato del futbolista (cuándo puede el futbolista rescindir el contrato por causa justificada, cuándo puede el club extinguir el contrato por causas deportivas o por causas económicas) y gestión de las disputas laborales ante el Comité de Resolución de Disputas de LaLiga o ante la jurisdicción ordinaria.

2. Negociación de renovaciones de contratos de jugadores: Las renovaciones son negociaciones complejas. Diseña el proceso. Incluye: estrategia de negociación de la renovación de un jugador titular que tiene 1 año de contrato restante (el club quiere renovar, el jugador también pero quiere una mejora salarial y una cláusula de rescisión que le dé movilidad), análisis del marco de referencia para la negociación (qué salarios pagan los competidores del mismo nivel por un perfil similar, cuál es el valor de mercado del jugador según plataformas como Transfermarkt, cuánto puede pagar el club manteniendo el equilibrio económico de la plantilla), estructura de los contratos de renovación (retribución fija base + primas de rendimiento colectivo por clasificación final + primas individuales por partidos jugados + derechos de imagen; cómo equilibrar estos componentes para que el club tenga flexibilidad si el jugador rinde menos y el jugador tenga incentivo a rendir más) y gestión de la relación con el agente del jugador durante la negociación (el agente representa los intereses del jugador, no los del club; cómo mantener la confianza con el agente aunque los intereses sean opuestos).

3. Disputa laboral por impago de salarios: El impago de salarios es la causa de rescisión más frecuente en el fútbol. Diseña el proceso. Incluye: análisis del derecho del futbolista a rescindir el contrato cuando el club no paga los salarios (artículo 49.1.b del Estatuto de los Trabajadores aplicado al caso del deportista profesional: cuántos meses de impago justifican la rescisión, cuál es el procedimiento para ejercer ese derecho), estrategia de defensa del club cuando el futbolista ha iniciado el proceso de rescisión (si el club tiene argumentos para refutar el impago o si la situación económica del club justifica un plan de pago a plazos acordado con el jugador) y consecuencias para el club si el futbolista consigue la rescisión con causa (pago de los salarios pendientes + indemnización por los salarios que hubiera cobrado hasta el final del contrato + posible sanción deportiva de LaLiga si el impago es reiterado).

4. Fichaje de jugadores extracomunitarios y permisos de trabajo: El fichaje de un jugador de fuera de la UE requiere un proceso administrativo complejo. Diseña el proceso. Incluye: requisitos legales para que un club de fútbol profesional español pueda fichar a un jugador no comunitario (el número de fichas de no comunitarios está limitado por la normativa del fútbol profesional español, cómo funciona el sistema de cupos por categoría), proceso de obtención del permiso de trabajo y residencia para el jugador no comunitario (documentación necesaria, plazos de tramitación, riesgo de que el proceso no se resuelva antes del inicio de temporada), tratamiento del contrato del jugador no comunitario cuando tiene cláusulas vinculadas a la obtención del permiso de trabajo (cómo redactar el contrato para proteger al club si el permiso no se concede) y gestión de la situación si el jugador no comunitario ha fichado pero todavía no tiene el permiso de trabajo y el equipo necesita usarlo en un partido oficial.

5. Derechos de imagen de los deportistas y del club: Los derechos de imagen en el deporte son económicamente muy relevantes. Diseña el marco. Incluye: separación entre el contrato laboral del deportista y la cesión de los derechos de imagen del deportista al club (cuánto se puede ceder en concepto de derechos de imagen como porcentaje de la retribución total, cuáles son los límites fiscales del 15% que establece la normativa española), modelo de gestión de los derechos de imagen del club (qué derechos tiene el club para usar la imagen de sus futbolistas en acciones comerciales, patrocinios y publicidad), contratos de patrocinio del club que incluyen el uso de la imagen de los jugadores (cómo redactar la cláusula de cesión de imagen para los patrocinadores del club, qué pasa si un jugador se niega a aparecer en la publicidad de un patrocinador con el que tiene un conflicto de intereses por sus propios patrocinios personales) y gestión de los derechos de imagen en las redes sociales de los jugadores (cuándo las publicaciones del jugador en sus redes son de su esfera personal y cuándo son una obligación del contrato laboral).

6. Compliance del club deportivo y buen gobierno: El deporte profesional tiene requisitos específicos de compliance y buen gobierno. Diseña el sistema. Incluye: obligaciones de compliance del club de fútbol profesional (certificación de licencias UEFA o LaLiga, control económico del fútbol profesional, normativa sobre la propiedad de los derechos federativos de los jugadores, prohibición de la propiedad de terceros sobre los derechos de los jugadores bajo el Reglamento FIFA), sistema de compliance anti-corrupción en el deporte (qué tipo de conductas están prohibidas: amaño de partidos, insider information en las apuestas deportivas, relaciones con grupos de apuestas deportivas; qué programa de compliance debe tener el club para detectar y prevenir estas conductas), gestión de las obligaciones del club como empleador en materia de prevención de riesgos laborales para los futbolistas (cobertura del riesgo de accidente deportivo, plan de prevención específico para el fútbol profesional) y régimen fiscal del club de fútbol como sociedad anónima deportiva (SAD) o como club deportivo sin ánimo de lucro.

7. Regulación de los agentes de futbolistas: La relación del club con los agentes es crucial. Diseña el marco. Incluye: nuevo Reglamento de Representantes de la FIFA de 2023 y sus implicaciones para los clubes españoles (límites a las comisiones de los agentes, obligación de registro de los representantes, limitación de la representación doble cuando el agente representa simultáneamente al jugador y al club), obligaciones del club de fútbol profesional cuando contrata los servicios de un agente de futbolistas (declaración a la federación nacional de los contratos con agentes, límite del 3% de la retribución anual bruta del jugador que el club puede pagar al agente del jugador en una operación de contratación) y gestión de los conflictos con los agentes cuando la negociación de un traspaso fracasa y el agente recibe igualmente una comisión del jugador por el trabajo realizado.

Incluye plantilla de contrato de futbolista profesional de Segunda División, checklist de due diligence de un traspaso internacional y guía de compliance anti-corrupción para clubes de fútbol profesional.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 65,
                'use_case'         => 'Asesoramiento jurídico integral para club de fútbol de Segunda División en contratos, renovaciones y fichajes',
                'vote_score'       => 46,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención al socio y experiencia del miembro en gimnasios y clubes deportivos con IA',
                'description'      => 'Diseña sistemas de atención al cliente y experiencia del miembro para centros deportivos que reducen el churn, aumentan la satisfacción y convierten a los socios en embajadores activos del club.',
                'prompt_content'   => <<<'EOT'
Eres un director de experiencia del cliente especializado en el sector del fitness y los centros deportivos, con experiencia en el diseño de sistemas de atención al socio, la reducción del churn mediante intervenciones proactivas, la gestión de reclamaciones de miembros y la construcción de comunidades de socios que se convierten en embajadores de la marca.

Contexto del club deportivo:
- Club de tenis y pádel con 1.800 socios activos en una ciudad de 350.000 habitantes
- Servicios: 8 pistas de tenis, 12 pistas de pádel, sala de fitness, restaurante, vestuarios premium
- Problema de atención al cliente: el NPS es de 32 (bajo para el sector, que tiene benchmarks de 50-60) y el principal driver negativo es la dificultad para reservar pistas en horario punta, la falta de respuesta rápida a las incidencias y la sensación de no sentirse conocido por el personal del club
- Churn anual: 22% (muy alto para un club de este tipo, donde el benchmark es 12-15%)
- Equipo de atención: 4 recepcionistas + 1 directora de socios

Desarrolla el sistema completo de atención al socio y experiencia del miembro:

1. Diseño de la experiencia del socio a lo largo de su ciclo de vida: El NPS bajo sugiere que hay momentos del journey del socio que están fallando. Diseña el análisis. Incluye: mapa del journey completo del socio del club de tenis y pádel (desde la primera visita hasta que se da de baja: captación → primera visita y prueba → proceso de alta → primeras semanas → socio activo → momentos de la verdad: reclamación, incidencia, renovación de cuota → riesgo de baja → momento de la baja si se produce), identificación de los momentos más críticos del journey donde la experiencia positiva genera fidelización y la experiencia negativa genera churn, diagnóstico detallado de los momentos negativos actuales (por qué es difícil reservar pistas en horario punta: cuántas pistas hay, cuánto tiempo antes se pueden reservar, qué porcentaje de las reservas las hacen los socios más veteranos que tienen ventaja de reserva; por qué no se responde rápido a las incidencias: qué canales de contacto hay, cuánto tarda el equipo de recepción en responder) y propuesta de mejoras prioritarias en los momentos críticos del journey.

2. Sistema de reservas de pistas y gestión de la demanda punta: La dificultad para reservar pistas es el principal problema. Diseña el sistema. Incluye: modelo de gestión de la disponibilidad de pistas que equilibra el acceso para todos los socios (cuánto tiempo por adelantado puede reservar un socio según su categoría de socio, cómo evitar que los mismos socios acaparen siempre los mejores horarios, sistema de cancelación con penalización para reducir las no-shows), sistema de lista de espera para los horarios más demandados (cómo funciona la lista de espera, cómo se notifica al socio cuando hay una pista disponible), diseño de la app o el sistema digital de reserva de pistas (qué información mostrar, cómo facilitar al máximo el proceso de reserva, cómo mostrar la disponibilidad en tiempo real) y estrategia para aumentar la oferta en las horas punta sin construir nuevas pistas (iluminación nocturna, tarifas valle-punta que incentivan a los socios a jugar en horarios menos demandados).

3. Sistema de atención al socio y gestión de incidencias: La lentitud en la respuesta a incidencias es el segundo problema. Diseña el sistema. Incluye: canales de atención al socio del club (WhatsApp Business: para incidencias urgentes y reservas de última hora; email: para comunicaciones no urgentes; app del club: para reservas, renovaciones, pagos; recepción presencial: para incidencias que requieren asistencia inmediata), tiempos de respuesta garantizados por canal y tipo de incidencia (WhatsApp: respuesta en menos de 30 minutos en horario de apertura; email: respuesta en 24 horas; incidencia en pista: atención inmediata), proceso de gestión de las incidencias más frecuentes en un club de tenis y pádel (pista mojada o en mal estado, avería de las luces, robo en el vestuario, conflicto entre socios por el uso de la pista, socio que no respeta el tiempo de juego reservado) y sistema de seguimiento post-incidencia para asegurar que el socio ha quedado satisfecho con la resolución.

4. Programa de fidelización y reconocimiento del socio: El socio que se siente conocido y valorado no se va. Diseña el programa. Incluye: sistema de conocimiento del socio por parte del personal del club (base de datos que muestra al recepcionista, cuando el socio entra o llama, su nombre, cuánto tiempo lleva como socio, su deporte favorito, si tiene alguna preferencia o incidencia reciente, si tiene algún evento importante próximo: cumpleaños, aniversario en el club), programa de reconocimiento de los socios más antiguos y más activos del club (ventajas exclusivas para los socios de más de 10 años: reserva anticipada, acceso a eventos exclusivos, mesa reservada en el restaurante los días de torneo) y sistema de felicitaciones y atenciones personalizadas (felicitación por el aniversario de socio, reconocimiento cuando un socio gana un torneo del club, llamada personal de la directora de socios cuando un socio activo lleva 3 semanas sin venir al club).

5. Gestión de la comunidad y los eventos del club: La comunidad es lo que hace único a un club deportivo vs. un gimnasio. Diseña el sistema. Incluye: programa de torneos y competiciones internos del club (torneo de pádel mixto mensual, liga interna de tenis por niveles, torneo benéfico anual del club) como motor de comunidad y de retención de socios, eventos sociales del club que construyen comunidad más allá del deporte (comida de Navidad de los socios, fiesta de final de temporada, charlas de tenistas o padelers profesionales), sistema de grupos de juego organizados por nivel y horario que facilitan que los socios encuentren compañeros de juego compatibles (uno de los principales problemas de los socios nuevos es encontrar con quién jugar) y newsletter del club con las noticias del club, los resultados de los torneos, las novedades de las instalaciones y las historias de los socios como herramienta de comunidad.

6. Proceso de prevención y win-back de socios en riesgo de baja: El churn del 22% es demasiado alto. Diseña el sistema. Incluye: señales de riesgo de baja que el sistema del club puede detectar (reservas de pistas que disminuyen por debajo de 1 por semana durante 3 semanas, no renovación de la cuota en la fecha habitual, solicitud de información sobre las condiciones de baja, ningún registro de acceso al club en las últimas 3 semanas), protocolo de intervención proactiva cuando un socio entra en riesgo de baja (llamada personal de la directora de socios, no del recepcionista, para preguntar si todo está bien y si el club puede hacer algo, oferta de una clase gratuita con el monitor de pádel o de tenis para retomar la actividad) y proceso de win-back de socios que ya se han dado de baja (cuándo contactarles: 1 mes y 3 meses después de la baja; qué ofrecerles: condiciones especiales de reincorporación, acceso a las novedades del club que no conocieron, reconocimiento de su historial como socio del club).

7. KPIs y gestión del equipo de atención al socio: Define el sistema de medición. Incluye: KPIs de la experiencia del socio (NPS por segmento de socio y por tipo de interacción, tasa de churn mensual por segmento, tiempo medio de respuesta a incidencias por canal, tasa de resolución de incidencias en el primer contacto, ocupación de las pistas por horario) y cómo estos KPIs guían las decisiones del equipo de atención, sistema de formación continua del equipo de recepción en habilidades de atención al socio (cómo gestionar a un socio enfadado por no conseguir pista en horario punta, cómo detectar y escalar las señales de churn) y proceso de feedback 360 del equipo de atención al socio (qué feedback reciben los recepcionistas de los socios, del equipo de entrenadores y de la directora de socios, cómo usan ese feedback para mejorar).

Incluye mapa del journey del socio del club de tenis y pádel, plantilla de seguimiento de socios en riesgo de churn y script de la llamada de retención de la directora de socios.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Reducción del churn y mejora del NPS en club de tenis y pádel mediante atención proactiva y comunidad',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultor freelance de rendimiento deportivo y coaching con IA',
                'description'      => 'Construye tu práctica independiente de coaching deportivo y consultoría de rendimiento usando IA para personalizar los programas de entrenamiento, analizar datos de rendimiento y escalar tu impacto más allá del tiempo facturable.',
                'prompt_content'   => <<<'EOT'
Eres un coach y consultor freelance de rendimiento deportivo con experiencia trabajando con atletas recreativos y semi-profesionales, equipos deportivos amateur y clubes deportivos que quieren mejorar el rendimiento de sus deportistas. Después de 8 años como preparador físico en un club de fútbol profesional y 3 como entrenador personal en un centro de alto rendimiento, decidiste lanzar tu práctica independiente.

Situación de tu práctica freelance:
- Consultor independiente de rendimiento deportivo con 4 años de práctica propia
- Servicios: coaching de running y triatlón (atletismo recreativo), consultoría de rendimiento físico para equipos amateur de fútbol sala y baloncesto, talleres de entrenamiento de fuerza para runners
- Clientes actuales: 22 atletas individuales (coaching mensual), 3 equipos amateur (consultoría trimestral), 2 empresas que te contratan para talleres de bienestar y salud
- Ingresos: 58.000 euros anuales, objetivo de 95.000 en 18 meses
- Mayor limitación: el modelo de coaching 1-a-1 tiene un techo claro porque tus horas son finitas

Desarrolla el sistema completo para escalar tu práctica de coaching deportivo:

1. Posicionamiento y nicho de especialización para cobrar más: La especialización es la clave para subir tus tarifas. Diseña el posicionamiento. Incluye: análisis de los nichos de coaching deportivo donde hay más disposición a pagar tarifas premium y menos competencia (coaching de triatlón de larga distancia Ironman, coaching de ultratrail, coaching de fuerza y rendimiento para atletas masters de más de 50 años, preparación física para la prueba de acceso a Fuerzas y Cuerpos de Seguridad, rendimiento deportivo para ejecutivos que hacen deporte como hobby de alta exigencia), argumentos para subir tus tarifas de coaching individual de 150 a 250 euros al mes (qué resultados cuantificables has conseguido con tus atletas actuales, cómo comunicar el valor del coaching de rendimiento vs. el entrenador de un gimnasio genérico), diseño del posicionamiento de tu práctica (una frase que captura quién eres, para quién es y qué resultado consigue el atleta) y cómo ese posicionamiento aparece en tu perfil de LinkedIn, en tu web y en tus redes sociales.

2. IA para personalizar y escalar los programas de entrenamiento: La IA multiplica tu capacidad de personalización. Diseña el sistema. Incluye: uso de Claude para el análisis de los datos de entrenamiento de tus atletas (cómo estructurar el prompt para que Claude analice el CSV de las últimas 8 semanas de entrenamiento de un triatleta de Strava y te ayude a identificar los patrones de fatiga, las semanas de sobrecarga y las sesiones que están generando el mejor progreso), sistema de generación de planes de entrenamiento personalizados asistida por IA (cómo usas la IA para generar el borrador del plan semanal de cada atleta basándote en los datos de rendimiento y el objetivo de la próxima competición, tu valor añadido en la revisión y el ajuste final), uso de herramientas de análisis biomecánico con IA (apps de análisis de carrera con la cámara del móvil: Runlab, Sportsbox, Coach's Eye) para dar feedback de técnica a distancia a tus atletas y sistema de feedback y seguimiento de tus atletas con IA (cómo automatizar el análisis del checkin semanal del atleta para detectar señales de fatiga o de desequilibrio entre carga y recuperación).

3. Diseño de programas de grupo y productos escalables: El coaching 1-a-1 tiene un techo. Diseña productos que escalen. Incluye: programa de coaching de grupo online (8-12 runners con el mismo objetivo, por ejemplo "preparar tu primera media maratón en menos de 2 horas": mismo plan base con ajustes individuales, sesión grupal quincenal por videollamada, chat de grupo para la comunidad y el accountability, precio de 80-100 euros al mes por persona vs. 200 del 1-a-1 pero con 10 personas en el grupo), curso online de entrenamiento para una especialidad concreta (6 módulos de vídeo sobre "cómo entrenar la fuerza para mejorar tu rendimiento en running": contenido perenne, precio de 200-350 euros por participante, sin límite de participantes), libro digital o guía técnica de tu especialidad que se vende en tu web o en Amazon (cómo entrenar para tu primera Ironman, la guía definitiva de la técnica de carrera para el atleta masters) y taller presencial trimestral de un día en tu ciudad (análisis de técnica de carrera + planificación de la temporada + sesión de fuerza para runners, precio de 150-200 euros por participante, hasta 12 personas).

4. Captación de nuevos atletas y equipos: Para crecer necesitas un sistema de captación que no dependa de que salgas a buscar clientes manualmente. Diseña el sistema. Incluye: estrategia de LinkedIn para llegar al triatleta o runner de nivel medio-alto que quiere mejorar (qué contenido publicar: análisis de errores comunes de entrenamiento, casos de éxito de tus atletas anonimizados, tu opinión sobre los debates del mundo del running como el debate fuerza vs. volumen), presencia en la comunidad running online (grupos de Strava, grupos de Facebook de running y triatlón, pódcasts del sector donde puedes aparecer como experto invitado), estrategia de colaboración con fisioterapeutas, nutricionistas deportivos y médicos del deporte que atienden a tu perfil de atleta objetivo (acuerdos de derivación mutua), programa de referidos de tus atletas actuales (qué incentivo ofreces al atleta que te presenta a un atleta nuevo que se convierte en cliente) y cómo usar tus resultados deportivos propios si compites como parte de tu credencial de coach.

5. Coaching online y herramientas de seguimiento a distancia: El coaching online multiplica tu mercado. Diseña el sistema. Incluye: stack de herramientas para el coaching online (TrainingPeaks o Final Surge para la planificación y el seguimiento de los entrenamientos, Zoom o Google Meet para las reuniones de análisis, Loom para los vídeos de feedback de técnica, WhatsApp o Slack para la comunicación diaria), proceso de onboarding del nuevo atleta en el coaching online (sesión inicial de diagnóstico de 90 minutos: objetivos, historial deportivo, nivel actual, disponibilidad de tiempo, equipamiento disponible; proceso de definición del plan de la temporada; configuración de las herramientas de seguimiento), ritmo del coaching semanal (qué hace el atleta sin ti: registra sus entrenamientos y completa el checkin semanal; qué haces tú: revisas los datos y el checkin, ajustas el plan si es necesario, das feedback por escrito o en vídeo; qué haces mensualmente: sesión de revisión de la progresión y planificación del mes siguiente) y cómo gestionar el coaching de 22 atletas a la vez sin que ninguno sienta que no tiene tu atención.

6. Construcción de autoridad y reputación en el sector del running y el triatlón: En el coaching deportivo, la credibilidad se construye con resultados y presencia. Diseña el sistema. Incluye: documentación y comunicación de los resultados de tus atletas (cómo documentar el progreso de cada atleta con datos: mejora del VO2max, mejora del tiempo en su distancia objetivo, primera marca personal en maratón; cómo pedir el testimonio al atleta después de un éxito y cómo usarlo en tus comunicaciones de marketing), participación en las carreras de tu zona y en las carreras grandes del calendario nacional como oportunidad de visibilidad y networking (aparecer en la línea de salida con tu camiseta de marca, celebrar los resultados de tus atletas en redes, reunirte con potenciales clientes en el ambiente social de las carreras), pódcast propio o apariciones en pódcasts del sector de running y triatlón (cómo proponer tu participación a los pódcasts más escuchados del sector) y colaboración con marcas de equipamiento deportivo como asesor técnico o embajador (cómo proponer la colaboración, qué valor puedes aportar a la marca, qué consigues tú a cambio).

7. Gestión financiera y crecimiento de la práctica de coaching deportivo: Con 58.000 euros escalando a 95.000, el modelo de ingresos necesita cambiar. Diseña el sistema. Incluye: modelo de ingresos para los próximos 18 meses que combina el coaching individual (15 atletas a 250 euros/mes = 3.750/mes), el coaching de grupo (3 grupos de 10 atletas a 90 euros/mes = 2.700/mes), los cursos online (estimación de ventas mensuales del curso), los talleres presenciales (1 al trimestre × 12 participantes × 180 euros = 2.160 cada trimestre) y la consultoría a equipos (3 equipos a 500 euros/trimestre), gestión del calendario y el tiempo facturable (cómo organizar la semana para atender a tus atletas individuales, preparar y revisar los planes de entrenamiento, producir contenido de marketing y dar los talleres sin quemarte), decisión de cuándo contratar a un co-coach que te ayude con la revisión de los datos de los atletas o con la impartición de los talleres y modelo fiscal de la práctica como autónomo o como SL para la facturación de 95.000 euros.

Incluye plantilla de plan de temporada para atleta de triatlón de larga distancia, system prompt de Claude para el análisis semanal de datos de entrenamiento y modelo financiero de la práctica de coaching deportivo online + presencial.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 65,
                'use_case'         => 'Escalar la práctica de coaching deportivo freelance con IA, grupos online y talleres presenciales',
                'vote_score'       => 45,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            // Remove any accidental duplicate key
            unset($data['use_cause']);
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
