<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills603Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Marketing de empresas de logística frigorífica y cadena de frío con IA',
                'description'      => 'Diseña estrategias de marketing B2B con inteligencia artificial para operadores logísticos de cadena de frío, empresas de transporte frigorífico y proveedores de almacenamiento en temperatura controlada dirigidas a la industria alimentaria y farmacéutica.',
                'prompt_content'   => <<<'EOT'
Eres un experto en marketing B2B industrial y estrategia de comunicación para el sector de la logística frigorífica y la cadena de frío. Necesito tu ayuda para diseñar una estrategia de marketing completa con inteligencia artificial para una empresa de logística de cadena de frío que opera almacenes frigoríficos y flota de transporte en temperatura controlada en España.

Contexto de la empresa:
La empresa opera 6 almacenes frigoríficos con un total de 45.000 m³ de capacidad en temperatura controlada entre -25°C y +8°C, y dispone de una flota de 85 vehículos frigoríficos. Sus clientes actuales son empresas de la industria alimentaria (congelados, lácteos, carnes, pescados, frutas y verduras). Quiere diversificar hacia el sector farmacéutico (distribución de medicamentos termosensibles y vacunas) y el sector de la cosmética y la parafarmacia.

Objetivo de la estrategia:
Desarrolla el plan de marketing con IA para posicionar a la empresa como operador de referencia en cadena de frío para el sector farmacéutico y captar 8 nuevos clientes de este sector en los próximos 18 meses.

Pilar 1 - Inteligencia de mercado y análisis del sector pharma cold chain con IA:
Describe cómo usar la IA para entender el mercado farmacéutico de cadena de frío en España. El sistema debe analizar: el mercado de distribución de medicamentos termosensibles (volumen del mercado, principales operadores logísticos que operan para la industria farmacéutica, regulación específica de GDP - Good Distribution Practice), las publicaciones de las empresas farmacéuticas sobre sus necesidades logísticas y sus iniciativas de sostenibilidad en la cadena de frío, las licitaciones públicas de servicios de distribución de medicamentos convocadas por hospitales, comunidades autónomas y la Administración General del Estado, y los informes de las asociaciones del sector como Farmaindustria, ALAFARPE o AECOC sobre tendencias en la cadena de suministro farmacéutica. Define los buyers de la industria farmacéutica que el equipo comercial debe contactar: el director de supply chain de los laboratorios farmacéuticos, el director de logística de los distribuidores farmacéuticos mayoristas (Cofares, BIDAFARMA, Alliance Healthcare) y el responsable de aprovisionamiento de las cadenas de farmacias.

Pilar 2 - Posicionamiento y diferenciación en el mercado pharma:
El sector farmacéutico tiene requisitos de calidad y trazabilidad muy superiores a la alimentación. Diseña el posicionamiento diferenciado de la empresa como operador de cold chain farmacéutico de confianza. Define los argumentos de diferenciación: la certificación GDP (Good Distribution Practice) que acredita el cumplimiento de las guías europeas para la distribución de medicamentos, la inversión en tecnología de monitorización de temperatura continua y trazabilidad (el cliente farmacéutico necesita evidencia de que su medicamento ha estado en temperatura correcta en todo momento, con registros disponibles para auditorías), la cualificación IQ/OQ/PQ de los almacenes frigoríficos que exige la industria farmacéutica (Instalation Qualification, Operational Qualification, Performance Qualification), y el equipo humano formado en los estándares de Buenas Prácticas de Distribución. Describe cómo el marketing de contenidos con IA puede construir esta credibilidad: whitepapers sobre los retos de la distribución farmacéutica en última milla, casos de estudio de gestión de incidencias de temperatura, y guías para que los directores de supply chain farmacéutico evalúen la madurez de un operador logístico para el sector.

Pilar 3 - Contenido técnico con IA para posicionarse como experto en cold chain:
Define la estrategia de thought leadership basada en contenido técnico de cadena de frío. Los compradores logísticos farmacéuticos son perfiles técnicos muy exigentes que evalúan al operador antes de contratar basándose en la credibilidad técnica demostrada. Propón los formatos de contenido más efectivos: los artículos técnicos en LinkedIn sobre regulación GDP y cómo cumplirla en la práctica (escrito por el director técnico de la empresa), los webinars sobre la gestión de desviaciones de temperatura durante el transporte farmacéutico, las guías descargables sobre los requisitos de cualificación de almacenes para la industria farmacéutica, y los vídeos de visita virtual a las instalaciones que permiten al cliente farmacéutico evaluar el nivel tecnológico del operador antes de visitarlo físicamente. Describe cómo la IA acelera la producción de este contenido técnico especializado sin comprometer la precisión regulatoria.

Pilar 4 - Estrategia de eventos y certificaciones como palanca de marketing:
En el sector de la logística farmacéutica, las certificaciones y la presencia en los foros del sector son el marketing más efectivo. Describe la estrategia de eventos y credenciales de confianza. Define los eventos donde la empresa debe tener presencia activa: Logistics Spain (feria de logística), pharmalogistic en Alemania (el evento europeo de referencia para la cold chain farmacéutica), AECOC Supply Chain Forum y los congresos de Farmaindustria. Diseña el proceso de consecución de certificaciones que actúan como argumento de ventas: la auditoría GDP por una entidad notificada europea, la cualificación del almacén según los estándares de un laboratorio farmacéutico de referencia (ser el operador cualificado por un cliente farmacéutico de primer nivel abre puertas con todos los demás del sector), y la certificación de sostenibilidad en cold chain (reducción de emisiones por kilómetro de transporte frigorífico, eficiencia energética de los almacenes).

Pilar 5 - Medición y atribución del marketing B2B en logística industrial:
Define el sistema de medición del marketing para un negocio de logística industrial B2B con ciclos de venta largos. Los contratos logísticos farmacéuticos tienen ciclos de decisión de 6 a 18 meses y múltiples touchpoints antes de que el cliente firme. Describe cómo la IA atribuye la influencia del marketing en los deals cerrados: qué contenido descargó el contacto antes de la primera reunión comercial, a qué webinar asistió antes de solicitar una visita a las instalaciones, y qué artículo de LinkedIn leyó el día que envió la solicitud de propuesta. Define las métricas del marketing B2B industrial: coste por lead cualificado del sector farmacéutico (diferenciado del lead alimentario), tasa de conversión de lead a oportunidad comercial calificada, impacto del marketing en el acortamiento del ciclo de venta, y el revenue atribuido al marketing en los nuevos contratos cerrados con clientes farmacéuticos. Propón el proceso de revisión mensual donde el director de marketing y el director comercial analizan juntos el pipeline de oportunidades farmacéuticas y deciden qué acciones de marketing pueden acelerar las oportunidades en negociación avanzada.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 55,
                'use_case'         => 'Estrategia de marketing B2B para operador logístico de cadena de frío farmacéutica con IA',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de sistemas de monitorización de cadena de frío con IoT e IA',
                'description'      => 'Diseña e implementa plataformas de monitorización continua de temperatura y trazabilidad para cadenas de frío alimentarias y farmacéuticas usando sensores IoT, inteligencia artificial y análisis predictivo.',
                'prompt_content'   => <<<'EOT'
Eres un ingeniero de software y arquitecto de sistemas IoT especializado en tecnología para cadena de frío, logística de temperatura controlada y trazabilidad de productos perecederos. Necesito tu guía técnica completa para diseñar e implementar una plataforma de monitorización inteligente de cadena de frío que use sensores IoT e inteligencia artificial para garantizar la integridad de la temperatura en toda la cadena logística.

Contexto del proyecto:
Un operador logístico de cadena de frío necesita una plataforma tecnológica que monitorice en tiempo real la temperatura en sus 6 almacenes frigoríficos (con 120 cámaras de temperatura controlada) y en su flota de 85 vehículos frigoríficos. La plataforma debe cumplir con los requisitos de trazabilidad del Reglamento (CE) 853/2004 para alimentos de origen animal y con las guías GDP para medicamentos termosensibles. Los datos de temperatura deben estar disponibles para auditorías con una retención de 2 años.

Objetivo técnico:
Diseña la arquitectura completa de la plataforma de monitorización de cadena de frío con IA y define el plan de implementación.

Módulo técnico 1 - Arquitectura de sensores IoT para almacenes y vehículos frigoríficos:
Describe la arquitectura de sensorización para los almacenes frigoríficos y la flota de transporte. Para los almacenes: los sensores de temperatura y humedad necesarios en cada cámara frigorífica (distribución de sensores según el volumen de la cámara para garantizar la representatividad de las mediciones), los protocolos de comunicación inalámbrica más adecuados en entornos frigoríficos (LoRaWAN para largos alcances con bajo consumo energético, Zigbee para redes de sensores densas en áreas pequeñas, o WiFi industrial con certificación IP67 para entornos con alta humedad), y los requisitos de certificación de los sensores para uso farmacéutico (calibración trazable a patrones nacionales, certificados de calibración con validez máxima de 12 meses según GDP). Para los vehículos frigoríficos: los data loggers con conectividad 4G/LTE que transmiten los datos de temperatura en tiempo real durante el trayecto, los sensores de apertura de puertas que registran cada apertura del compartimento de carga y correlacionan la duración con el impacto en la temperatura, y los sistemas de geolocalización GPS integrados que permiten conocer la posición del vehículo y la temperatura de la carga simultáneamente.

Módulo técnico 2 - Plataforma de datos y pipeline de procesamiento en tiempo real:
Diseña la arquitectura del sistema de datos que procesa la información de los sensores en tiempo real. Describe el pipeline completo: la ingesta de datos de los sensores (frecuencia de medición mínima de 10 minutos para almacenes y 5 minutos para vehículos según los estándares GDP), el sistema de mensajería en tiempo real (Apache Kafka o AWS IoT Core para manejar los miles de mensajes por hora de todos los sensores), la base de datos de series temporales para almacenar los registros históricos (InfluxDB, TimescaleDB o Amazon Timestream), y la capa de API que expone los datos a los dashboards, a los clientes farmacéuticos que quieren verificar la temperatura de sus envíos y a los sistemas de trazabilidad externos. Define también los requisitos de integridad de datos para el cumplimiento regulatorio: cómo garantizar que los registros de temperatura no pueden ser modificados retroactivamente (inmutabilidad del log), cómo gestionar las brechas en la telemetría cuando un sensor pierde la conectividad temporalmente, y cómo generar los informes de temperatura en el formato requerido por las auditorías farmacéuticas.

Módulo técnico 3 - Modelos de IA para predicción y gestión de desviaciones:
Describe los modelos de inteligencia artificial para anticipar y gestionar las desviaciones de temperatura en la cadena de frío. Modelo 1: predicción de desviaciones de temperatura en almacenes basándose en variables como la temperatura exterior (en verano el riesgo de desviación aumenta significativamente), el número de aperturas de puertas previstas (días de carga y descarga intensa), el estado de mantenimiento de la unidad de frío (el consumo energético histórico del equipo es un predictor de averías próximas) y la carga de producto en la cámara (una cámara llena de producto congelado tiene una inercia térmica muy superior a una cámara semivacía). El modelo debe generar alertas preventivas con 4-8 horas de antelación para que el equipo pueda actuar antes de que se produzca la desviación real. Modelo 2: detección de anomalías en el comportamiento de los equipos de frío para el mantenimiento predictivo: patrones de temperatura que indican que un evaporador está acumulando hielo (defrost incompleto), que el compresor está trabajando en condiciones anómalas o que hay una fuga en el circuito frigorífico, con antelación suficiente para programar una intervención de mantenimiento antes de la avería.

Módulo técnico 4 - Dashboard de control y gestión de alertas para operadores logísticos:
Diseña la interfaz de usuario de la plataforma para los distintos perfiles de usuario. Para el operador de almacén: pantalla de control en tiempo real con el mapa de temperatura de cada cámara (representación visual del estado térmico de cada punto de medición), semáforo de estado por cámara y por vehículo (verde = temperatura correcta, amarillo = cerca del límite, rojo = desviación activa), y sistema de alertas configurables por criticidad (alerta inmediata por SMS y llamada telefónica para desviaciones en cámaras con productos farmacéuticos, alerta por email para acercamientos al límite en almacenes alimentarios). Para el responsable de calidad: módulo de gestión de incidencias donde cada desviación de temperatura registrada se vincula con un protocolo de actuación (producto afectado identificado, decisión de destino adoptada, documentación de la no conformidad), histórico de incidencias por cámara para identificar equipos problemáticos, e informes automáticos de temperatura para auditorías GDP en formato estandarizado. Para el cliente farmacéutico externo: portal de trazabilidad donde el cliente puede consultar el registro de temperatura de sus envíos específicos en tiempo real y descargar el informe de cadena de frío de cada expedición.

Módulo técnico 5 - Cumplimiento regulatorio y arquitectura de seguridad de los datos:
Describe las consideraciones de cumplimiento regulatorio y seguridad de la plataforma. Define los requisitos técnicos del Reglamento GDP (Guías de Buenas Prácticas de Distribución de Medicamentos de la Agencia Europea de Medicamentos): la calibración trazable de los sensores, la validación del sistema informático según el Anexo 11 de las GMP (21 CFR Part 11 para sistemas computarizados), la gestión de usuarios con control de acceso basado en roles (quién puede ver los datos de temperatura, quién puede gestionar alertas, quién puede exportar informes para auditorías), y los requisitos de backup y recuperación ante desastres para garantizar la disponibilidad de los registros históricos durante los 2 años reglamentarios. Describe también la arquitectura de ciberseguridad para proteger los datos sensibles de los clientes farmacéuticos: cifrado de los datos en tránsito y en reposo, autenticación multifactor para el acceso al sistema, y el plan de respuesta a incidentes de seguridad que garantiza la integridad de los registros de temperatura ante un posible ataque.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Plataforma IoT e IA para monitorización de cadena de frío farmacéutica y alimentaria',
                'vote_score'       => 56,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de instalaciones de cadena de frío con IA y simulación energética',
                'description'      => 'Optimiza el diseño de almacenes frigoríficos, cámaras de temperatura controlada y centros de distribución de productos perecederos usando inteligencia artificial para maximizar la eficiencia energética y cumplir los estándares regulatorios.',
                'prompt_content'   => <<<'EOT'
Eres un ingeniero de instalaciones frigoríficas y arquitecto especializado en el diseño de almacenes en temperatura controlada, centros de distribución de productos perecederos y cadenas de frío de alta eficiencia energética. Necesito tu guía completa para diseñar una instalación frigorífica de nueva planta usando inteligencia artificial y herramientas de simulación digital.

Contexto del proyecto de diseño:
Diseñar un centro de distribución frigorífico de 12.000 m² con tres zonas de temperatura controlada: una cámara de congelación a -20°C (6.000 m²), una cámara de refrigeración a +2°C/+4°C (4.000 m²) y una zona de temperatura ambiente controlada a +15°C (2.000 m²). El centro debe cumplir con los requisitos de almacenamiento de productos alimentarios y debe estar preparado para obtener la certificación GDP para el almacenamiento de medicamentos termosensibles en las cámaras de refrigeración.

Objetivo del diseño:
Usar IA y simulación digital para crear el diseño óptimo de la instalación antes de la construcción.

Sección de diseño 1 - Análisis de la envolvente y diseño del aislamiento con IA:
Describe el proceso de diseño del aislamiento térmico de la instalación frigorífica con asistencia de IA. El aislamiento es la inversión más importante en una instalación frigorífica: un mal diseño del aislamiento genera un gasto energético recurrente durante toda la vida útil del almacén. Explica cómo calcular el espesor óptimo de los paneles de poliuretano para cada zona de temperatura (el cálculo debe considerar la diferencia de temperatura entre el interior y el exterior en las peores condiciones climáticas del emplazamiento, la transmitancia térmica del material de aislamiento, el coste de la energía y el coste del material de aislamiento para encontrar el punto de mínimo coste total de ciclo de vida). Describe cómo la simulación térmica con software como IDA ICE o EnergyPlus permite modelizar el comportamiento térmico de la instalación ante distintos escenarios: olas de calor extremas, puertas abiertas durante la carga y descarga, avería del sistema de frío durante 2 horas. Define los puentes térmicos críticos que deben eliminarse en el diseño: las uniones entre paneles, los pasos de instalaciones a través de la envolvente y los marcos de las puertas frigoríficas.

Sección de diseño 2 - Diseño del sistema de refrigeración con IA y simulación energética:
Describe el proceso de diseño del sistema de refrigeración con herramientas de simulación asistidas por IA. Define la arquitectura del sistema frigorífico: la elección del refrigerante (amoniaco NH3 para sistemas de gran escala por su eficiencia energética y bajo impacto ambiental, CO2 transcrítico para sistemas de media escala por su seguridad y reglamentación favorable, o HFOs para instalaciones donde el NH3 no es aceptable por proximidad a población). Describe el proceso de dimensionamiento de la potencia frigorífica necesaria con simulación: cuánta carga calorífica generan las operaciones normales de la instalación (entrada de producto caliente, aperturas de puertas, iluminación, presencia de personas, transmisión a través de la envolvente), y cómo dimensionar el sistema para manejar los picos sin sobredimensionar en exceso (lo que generaría un coste de inversión mayor y un sistema ineficiente en condiciones normales). Define cómo la IA puede analizar el perfil de operación previsto (cuántas entradas y salidas de mercancía, en qué horas del día, con qué temperatura de entrada del producto) para optimizar el dimensionamiento del sistema y la estrategia de acumulación de frío en horas valle.

Sección de diseño 3 - Layout operativo y flujo de mercancías:
Diseña el layout de la instalación para maximizar la eficiencia operativa. Describe la metodología de diseño del flujo de mercancías: cómo organizar las zonas de recepción, almacenamiento y expedición para minimizar las distancias recorridas por las mercancías y los operarios, cómo separar los flujos de producto congelado y refrigerado para evitar contaminaciones cruzadas de temperatura, y cómo diseñar las puertas de muelles y los andenes de carga para maximizar la velocidad de las operaciones de carga y descarga. Propón la distribución de la estantería de paletización: la altura óptima de estanterías (determinada por la altura libre interior después del aislamiento y de las instalaciones aéreas), los sistemas de almacenamiento más adecuados para cada zona de temperatura (estanterías convencionales de paleta, estanterías de entrada por gravedad, almacenes autoportantes con transelevadores), y las zonas de staging para la preparación de pedidos. Describe cómo la IA puede simular el flujo de mercancías con distintas configuraciones de layout para identificar los cuellos de botella operativos antes de la construcción.

Sección de diseño 4 - Eficiencia energética y sostenibilidad del almacén frigorífico:
Aborda el diseño de la instalación desde la perspectiva de la eficiencia energética y la sostenibilidad. La refrigeración industrial es uno de los mayores consumidores de energía en el sector logístico: un almacén frigorífico de 12.000 m² puede consumir entre 2 y 4 millones de kWh al año. Describe las estrategias de eficiencia energética que deben integrarse en el diseño desde el inicio: la instalación fotovoltaica en la cubierta (cuántos kWh puede generar según la orientación y la superficie disponible, y cómo su producción se puede gestionar con el sistema de frío para cargar las baterías de frío en horas de máxima generación solar), el sistema de recuperación de calor del condensador para usos de calefacción en las zonas de trabajo (el calor generado por el sistema de refrigeración puede calentar las zonas de oficinas, los muelles y los vestuarios sin coste adicional de energía), y las puertas de alta velocidad y los vestíbulos de presión positiva que minimizan las entradas de calor en las zonas de operación. Define las certificaciones de sostenibilidad a las que puede aspirar el diseño: BREEAM Industrial, LEED Warehouse, o el certificado de edificio de consumo de energía casi nulo (EECN) del Código Técnico de la Edificación español.

Sección de diseño 5 - Cualificación de instalaciones para uso farmacéutico (IQ/OQ/PQ):
Describe el proceso de cualificación de la instalación para el almacenamiento de medicamentos termosensibles según las guías GDP de la EMA. La cualificación farmacéutica es un proceso formal que valida que la instalación cumple con los requisitos técnicos para el almacenamiento de medicamentos y que está documentado para las auditorías de los laboratorios farmacéuticos y de las agencias regulatorias. Define las tres fases de la cualificación: la Qualificación de Instalación (IQ) que verifica que todos los equipos e instrumentos están instalados correctamente según las especificaciones del fabricante y del diseño, la Qualificación Operacional (OQ) que verifica que todos los sistemas de refrigeración, alarmas y registros funcionan correctamente dentro de los rangos especificados, y la Qualificación de Rendimiento (PQ) que consiste en un mapeo térmico de la cámara en condiciones reales de carga máxima y mínima, en verano y en invierno, para demostrar que todos los puntos del espacio de almacenamiento se mantienen dentro de las temperaturas especificadas. Describe cómo la IA puede asistir en el proceso de mapeo térmico: el análisis de los datos de los sensores colocados en múltiples puntos de la cámara durante el estudio de mapping, la identificación de las zonas frías y calientes de la cámara y la determinación de los puntos de monitorización continua óptimos para el uso operativo posterior.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 65,
                'use_case'         => 'Diseño de almacén frigorífico con IA, simulación energética y cualificación farmacéutica GDP',
                'vote_score'       => 42,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Ventas B2B de servicios logísticos de cadena de frío con IA',
                'description'      => 'Desarrolla un proceso de ventas consultivo con inteligencia artificial para comercializar servicios de logística frigorífica, almacenamiento en temperatura controlada y distribución de perecederos a la industria alimentaria y farmacéutica.',
                'prompt_content'   => <<<'EOT'
Eres un director de ventas especializado en la comercialización de servicios logísticos de cadena de frío para la industria alimentaria, farmacéutica y de gran consumo. Necesito tu ayuda para construir un proceso de ventas consultivo completo, asistido por inteligencia artificial, para un operador logístico de cadena de frío que quiere crecer en el segmento farmacéutico.

Perfil del servicio:
Vendemos servicios de almacenamiento frigorífico (alquiler de espacio en cámaras a -20°C y +2°C/+8°C), transporte en temperatura controlada (distribución de producto perecedero en camiones frigoríficos con monitorización de temperatura en tiempo real), y servicios de valor añadido para la industria farmacéutica (cualificación GDP de las instalaciones, informes de temperatura para auditorías, cadena de custodia documentada para ensayos clínicos). El precio de los servicios de almacenamiento oscila entre 8 y 25 euros por palet y mes según la temperatura y el nivel de servicio (estándar o farmacéutico). El transporte se factura por kilómetro y por camión, con suplementos para el servicio farmacéutico con monitorización continua certificada.

Objetivo de ventas:
Cerrar contratos de almacenamiento y transporte con 8 nuevos clientes farmacéuticos en los próximos 18 meses, con un valor de contrato anual de entre 150.000 y 500.000 euros cada uno.

Apartado de ventas 1 - Identificación y cualificación de oportunidades farmacéuticas con IA:
Describe el proceso de prospección de clientes en la industria farmacéutica usando IA. El mercado farmacéutico está bien estructurado y documentado: la Agencia Española de Medicamentos y Productos Sanitarios (AEMPS) publica los registros de autorización de comercialización de medicamentos, que identifican a todos los laboratorios que comercializan medicamentos termosensibles en España. El sistema debe identificar las empresas farmacéuticas que tienen medicamentos de cadena de frío registrados (vacunas, insulinas, anticuerpos monoclonales, productos biológicos) y que por tanto necesitan servicios logísticos especializados. Define el modelo de cualificación de oportunidades: qué tamaño de laboratorio (por volumen de ventas de medicamentos refrigerados) puede generar un contrato logístico del tamaño objetivo, cuáles tienen logística propia vs. cuáles subcontratan a operadores terceros, y cuáles tienen contratos que están próximos a vencer con sus operadores logísticos actuales (señal de oportunidad de cambio).

Apartado de ventas 2 - Discovery técnico con compradores farmacéuticos:
Diseña el proceso de discovery con los responsables de supply chain y calidad de los laboratorios farmacéuticos. La venta a la industria farmacéutica tiene características únicas: el interlocutor principal no es solo el director de supply chain (como en alimentación) sino también el director de garantía de calidad (QA), que debe aprobar la cualificación técnica del proveedor logístico antes de que el contrato pueda cerrarse. Define las preguntas de discovery para el director de supply chain: qué volúmenes de producto refrigerado gestiona actualmente, cuál es la distribución geográfica de sus entregas a hospitales, farmacias y distribuidores mayoristas, cuál es su mayor problema con su operador logístico actual. Y las preguntas para el director de QA: qué certificaciones mínimas exige a sus operadores logísticos, cuándo fue la última auditoría a su operador actual y cuál fue el resultado, qué requisitos específicos tiene para la trazabilidad y la documentación de temperatura de sus productos. Describe cómo la IA procesa las notas del discovery para identificar el argumento técnico-comercial más sólido para cada cliente y los riesgos que el cliente percibirá en el cambio de operador logístico.

Apartado de ventas 3 - Proceso de cualificación técnica y auditoría del operador:
Describe el proceso de evaluación técnica que realiza el cliente farmacéutico antes de contratar un operador logístico de cadena de frío. En la industria farmacéutica, el proceso de aprobación de un proveedor logístico incluye obligatoriamente una auditoría in-situ a las instalaciones del operador por el equipo de QA del laboratorio farmacéutico. Diseña cómo preparar y gestionar esta auditoría como parte del proceso de ventas: la documentación que el operador debe tener lista antes de la auditoría (manuales de calidad, procedimientos de operación estándar, registros de calibración de sensores, informes de cualificación IQ/OQ/PQ, historial de incidencias y acciones correctivas), cómo conducir la visita a las instalaciones para que el equipo de QA del cliente observe los puntos más importantes del sistema de calidad, y cómo gestionar las desviaciones que el auditor identifique (un plan de acciones correctivas bien documentado con plazos definidos es mejor recibido que una instalación perfecta con cero observaciones, porque demuestra madurez en el sistema de calidad). Define también el proceso de negociación del acuerdo de calidad (Quality Agreement) que el cliente farmacéutico exigirá firmar antes del inicio del contrato, estableciendo las responsabilidades de ambas partes en la gestión de la cadena de frío.

Apartado de ventas 4 - Propuesta económica y negociación de contratos logísticos:
Describe el proceso de elaboración de propuestas económicas y negociación de contratos logísticos farmacéuticos. Define la estructura de la propuesta: el modelo de precios de almacenamiento (precio por palet y mes por zona de temperatura, con descuentos por volumen comprometido y por contrato de larga duración), el modelo de precios del transporte (precio por ruta estándar con variables según el volumen y la frecuencia), los servicios de valor añadido con tarifa específica (elaboración de informes de temperatura para auditorías, servicio de guardia 24/7 para gestión de incidencias fuera de horario, servicio de urgencia para distribución de productos críticos). Describe las variables de negociación más frecuentes en los contratos logísticos farmacéuticos: el plazo del contrato (el operador quiere contratos largos de 2-3 años para amortizar la inversión en cualificación; el cliente prefiere contratos cortos con posibilidad de salida), las penalizaciones por incumplimiento de temperatura (el cliente farmacéutico querrá penalizaciones económicas por desviaciones de temperatura; el operador debe establecer los límites razonables que puede asumir), y los niveles de servicio (SLA) mínimos garantizados para el transporte urgente.

Apartado de ventas 5 - Fidelización y expansión de contratos con IA:
Describe la estrategia de fidelización y expansión de la relación con los clientes farmacéuticos una vez firmado el contrato. Los contratos logísticos farmacéuticos son relaciones a largo plazo: el coste de cambio de operador para un laboratorio farmacéutico (nueva cualificación técnica, nueva auditoría, formación del personal, actualización de procedimientos) es tan alto que los clientes satisfechos raramente cambian de proveedor. Define el programa de éxito del cliente para los primeros 12 meses del contrato: las revisiones de operación mensuales donde se analizan los KPIs de servicio (incidencias de temperatura, tiempos de entrega, incidencias de documentación), los informes de calidad trimestrales que demuestran el rendimiento del sistema de cadena de frío, y el proceso de gestión de las auditorías que el cliente realizará al operador durante la vida del contrato. Describe cómo la IA identifica oportunidades de upselling: si el cliente empieza con almacenamiento y luego lanza un nuevo producto que necesita transporte especializado, el sistema detecta esta necesidad a partir de las noticias sobre el pipeline de la empresa y las conversaciones con el responsable de supply chain, y alerta al comercial para que proponga proactivamente la ampliación del servicio.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 55,
                'use_case'         => 'Proceso de venta B2B de servicios logísticos de cadena de frío farmacéutica con IA',
                'vote_score'       => 37,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Product management de software para gestión de cadena de frío con IA',
                'description'      => 'Define la visión, roadmap y métricas de una plataforma de gestión de cadena de frío que usa inteligencia artificial para optimizar la trazabilidad, predecir desviaciones de temperatura y reducir el desperdicio de productos perecederos.',
                'prompt_content'   => <<<'EOT'
Eres un Product Manager con experiencia en software para la cadena de suministro de productos perecederos, tecnología de cadena de frío y soluciones SaaS para el sector de la logística alimentaria y farmacéutica. Necesito tu ayuda para definir la estrategia de producto completa de una plataforma de gestión inteligente de cadena de frío que usa inteligencia artificial para optimizar la trazabilidad y reducir el desperdicio de perecederos.

Contexto del producto:
La plataforma es un SaaS para operadores logísticos de cadena de frío y empresas alimentarias que integra monitorización de temperatura en tiempo real (a través de sensores IoT), trazabilidad de lotes de producto, gestión de alertas y predicción de desviaciones con IA. Tenemos 35 clientes (operadores logísticos, distribuidores alimentarios y exportadores de frutas y verduras) en España y Portugal, y queremos expandirnos a Italia y Francia en los próximos 18 meses. El churn anual actual es del 12%, y el objetivo es reducirlo al 5%.

Objetivo del product management:
Construye el marco de gestión de producto para reducir el churn y acelerar la expansión internacional.

Dimensión estratégica 1 - Discovery y comprensión del valor entregado al cliente:
Describe el proceso de discovery para entender por qué el 12% de los clientes cancela la suscripción y qué caracteriza a los clientes que permanecen y crecen. Diseña el programa de entrevistas de cancelación: qué preguntas permiten distinguir si el churn se debe a que el producto no entrega suficiente valor, a que el cliente cierra su negocio o a que la competencia ofrece algo mejor. Define también las entrevistas con los clientes más satisfechos (los que llevan más de 2 años y han ampliado el número de sensores o el número de instalaciones): qué valor concreto y medible han obtenido del producto (incidencias de temperatura detectadas antes de convertirse en pérdidas, ahorro en seguros por tener la cadena de frío documentada, reducción de rechazos de clientes farmacéuticos por no conformidad de temperatura). Describe cómo la IA puede analizar los patrones de uso en la plataforma para identificar las funcionalidades que predicen la retención (los clientes que configuran alertas predictivas y las revisan semanalmente tienen un churn del 3%, mientras que los que solo usan el registro de temperatura básico tienen un churn del 20%).

Dimensión estratégica 2 - Funcionalidades de IA que diferencian el producto:
Define las capacidades de inteligencia artificial que convierten la plataforma en un producto difícilmente reemplazable. Describe las funcionalidades de IA más valiosas para los clientes actuales: el motor de predicción de desviaciones de temperatura que alerta 4-6 horas antes de que se produzca la desviación real (el cliente evita pérdidas de producto actuando preventivamente), el sistema de detección de anomalías en el comportamiento de los equipos de frío que detecta el deterioro de los sistemas antes de la avería (reducción de costes de mantenimiento y de interrupciones no planificadas), y el módulo de optimización de la disposición del producto en cámara que, basándose en los patrones de temperatura históricos de la cámara (zonas frías y zonas cálidas), recomienda dónde colocar cada tipo de producto según su sensibilidad térmica. Propón las nuevas capacidades de IA para el roadmap: el optimizador de rutas de transporte que minimiza el tiempo de tránsito para reducir la exposición térmica de los productos más sensibles, y el módulo de predicción de vida útil residual del producto que, combinando los datos de temperatura acumulada con los datos de la especie y el historial del lote, estima cuántos días de vida útil quedan al producto para optimizar su distribución.

Dimensión estratégica 3 - Roadmap de producto para la expansión internacional:
Define el roadmap de adaptaciones del producto para la expansión a Italia y Francia en 18 meses. Describe las adaptaciones regulatorias: las diferencias en los requisitos de trazabilidad alimentaria entre España, Italia y Francia derivadas de la implementación nacional del Reglamento (CE) 178/2002, los requisitos específicos de temperatura de almacenamiento para distintas categorías de producto que pueden variar entre países (las normativas nacionales complementan al reglamento europeo), y los estándares de documentación que exigen los principales distribuidores alimentarios de cada mercado (Carrefour Francia, Conad Italia). Define también las adaptaciones comerciales: los idiomas de la interfaz, la moneda y los métodos de pago locales, y las integraciones con los ERPs más usados en cada mercado para la automatización de los documentos de trazabilidad. Propón el enfoque de entrada al mercado: expansión directa con un equipo comercial local, o partnership con operadores logísticos de referencia en cada mercado que actúen como distribuidores del software.

Dimensión estratégica 4 - Estrategia de integración con el ecosistema de software logístico:
Define la estrategia de integraciones que hace la plataforma más valiosa y más difícil de reemplazar. Describe las integraciones prioritarias: con los ERPs del sector alimentario más usados en España (SAP S/4HANA para grandes empresas, Microsoft Dynamics 365, Sage X3 para medianas empresas y Odoo para pequeñas empresas), con los sistemas de gestión de almacenes (WMS: Manhattan, SAP EWM, Mecalux Easy WMS), con los sistemas de gestión de transporte (TMS: Transsegur, Transics, Trimble), y con las plataformas de trazabilidad estándares del sector como GS1 y las plataformas de intercambio de datos sectoriales (Orderentree para el sector hortofrutícola). Para cada integración, define el valor que aporta al cliente: si la plataforma se integra automáticamente con el WMS del operador logístico, el registro de temperatura se vincula automáticamente con cada movimiento de mercancía sin intervención manual, lo que elimina el mayor punto de fricción en el uso del sistema.

Dimensión estratégica 5 - Métricas de producto y modelo de negocio:
Define el sistema de métricas de la plataforma de cadena de frío y el modelo de negocio para escalar. Establece la métrica North Star: para una plataforma de cadena de frío, la métrica más significativa es las "incidencias de temperatura detectadas y resueltas antes de causar pérdida de producto", porque cuantifica el valor real que el producto entrega al cliente. Define el cuadro completo de métricas: retención de clientes a 12 y 24 meses, Net Revenue Retention (crecimiento de los clientes existentes por expansión del número de sensores o instalaciones), coste de adquisición de cliente (CAC) por canal, LTV por segmento de cliente (operadores logísticos grandes vs. medianos vs. pequeñas empresas alimentarias exportadoras), y time-to-value (cuánto tiempo tarda un nuevo cliente en detectar su primera incidencia de temperatura con el sistema). Describe también el modelo de pricing para la expansión internacional: precio por sensor conectado (permite al cliente empezar pequeño y crecer), precio por instalación (cámara o vehículo), o precio por volumen de alertas gestionadas; cuál de estos modelos maximiza el LTV en el segmento de operadores logísticos medianos que son el cliente más rentable del negocio.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Estrategia de producto para plataforma SaaS de gestión inteligente de cadena de frío',
                'vote_score'       => 43,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión de personas en operaciones de cadena de frío con IA',
                'description'      => 'Diseña programas de gestión del talento, formación en inocuidad alimentaria y prevención de riesgos laborales para equipos que trabajan en almacenes frigoríficos y logística de productos perecederos, usando inteligencia artificial para personalizar el aprendizaje y garantizar el cumplimiento normativo.',
                'prompt_content'   => <<<'EOT'
Eres un director de RRHH especializado en la gestión de personas en operaciones de cadena de frío, almacenes frigoríficos y logística de productos perecederos. Necesito tu ayuda para diseñar un programa completo de gestión del talento y desarrollo de personas para un operador logístico de cadena de frío con 280 empleados.

Contexto de la organización:
La plantilla está compuesta por: 120 operarios de almacén que trabajan en cámaras frigoríficas entre -20°C y +8°C (con todos los riesgos de salud asociados al trabajo en frío), 85 conductores de vehículos frigoríficos, 25 técnicos de refrigeración industrial, 30 personas en administración y atención al cliente, y 20 personas en dirección, calidad y ventas. La rotación de operarios es del 35% anual, muy alta y costosa. El mayor desafío de RRHH es atraer y retener operarios de almacén en un mercado donde hay escasez de mano de obra y competencia de sectores con condiciones de trabajo menos exigentes.

Objetivo del programa:
Diseña el programa de gestión del talento que reduce la rotación de operarios al 15% y mejora las condiciones de seguridad y salud laboral.

Bloque de talento 1 - Atracción y selección de personal para trabajo en frío con IA:
Describe el proceso de atracción y selección de operarios de almacén frigorífico. El trabajo en cámaras frigoríficas tiene requisitos específicos de aptitud médica (el reconocimiento médico debe evaluar la tolerancia al frío y descartar contraindicaciones como enfermedades cardiovasculares, problemas de circulación o Raynaud) y requiere una dotación de EPI específica (ropa térmica, calzado de seguridad con aislamiento, guantes contra el frío). Diseña la propuesta de valor del empleador que atrae candidatos a pesar de las condiciones de trabajo exigentes: el plus salarial por trabajo en condiciones especiales (el convenio colectivo de almacenes frigoríficos establece pluses por trabajo en frío), la estabilidad laboral (los operadores logísticos de alimentación son negocios anticíclicos con alta estabilidad en comparación con otros sectores), las oportunidades de ascenso (de operario a carretillero, de carretillero a encargado de turno, de encargado a jefe de almacén) y la posibilidad de formación en técnicas de refrigeración para los más interesados. Describe cómo la IA puede mejorar el proceso de selección: filtrado de CVs según los criterios objetivos del puesto, programación automática de entrevistas y reconocimientos médicos, y gestión del pool de candidatos para cubrir bajas imprevistas.

Bloque de talento 2 - Formación en inocuidad alimentaria, GDP y prevención de riesgos:
Diseña el programa de formación obligatoria y de desarrollo para todos los perfiles de la empresa. Para los operarios de almacén: formación en inocuidad alimentaria (APPCC, higiene personal y del entorno, gestión de incidencias de temperatura), formación en prevención de riesgos laborales específica para trabajo en frío (reconocimiento de síntomas de hipotermia y congelación, pausas de calentamiento obligatorias, uso correcto de los EPI), y formación en el uso del sistema de gestión del almacén (WMS) y los dispositivos de registro de temperatura. Para los conductores frigoríficos: formación en la verificación pre-viaje del equipo de frío (cómo revisar que la unidad frigorífica funciona correctamente antes de cargar), en los procedimientos de gestión de incidencias de temperatura durante el transporte, y en los requisitos de documentación de temperatura que exigen los clientes farmacéuticos. Describe cómo la IA puede personalizar el plan de formación de cada empleado: basándose en las incidencias en las que ha estado involucrado, las evaluaciones de competencias y los módulos que ha completado, el sistema genera un plan de formación individual con las prioridades más relevantes para su puesto.

Bloque de talento 3 - Salud y seguridad en el trabajo en frío con IA:
Describe el programa de seguridad y salud laboral específico para el trabajo en entornos frigoríficos. Las enfermedades y accidentes más frecuentes en almacenes frigoríficos son: las afecciones músculo-esqueléticas por el manejo manual de cargas en temperatura negativa (los músculos fríos tienen mayor riesgo de lesión), los accidentes por suelos resbaladizos (la condensación y el hielo son una causa frecuente de caídas), el síndrome del túnel carpiano agravado por las vibraciones de las carretillas en frío, y los accidentes de tráfico de carretillas en espacios reducidos. Define el programa de ergonomía con IA: el sistema de análisis de movimientos que registra las posturas de carga de los operarios (mediante sensores wearable o análisis de vídeo) y genera alertas cuando detecta patrones de movimiento de alto riesgo. Describe el protocolo de pausas de calentamiento obligatorias para el trabajo en cámaras de congelación: la regulación establece los tiempos máximos de exposición y los períodos de descanso en zona caliente, y el sistema de control de turnos con IA garantiza que se respetan sin intervención manual.

Bloque de talento 4 - Retención y motivación de operarios en condiciones exigentes:
Diseña el programa de retención de operarios de almacén frigorífico que reduce la rotación del 35% al 15%. El análisis de las causas de abandono más frecuentes en este sector revela que los motivos principales son: las condiciones de trabajo (el frío extremo, los horarios nocturnos y de fin de semana en operaciones que trabajan 24/7), el salario (en un mercado con escasez de mano de obra, el salario es la variable más sensible), la falta de perspectivas de carrera (muchos operarios no ven cómo pueden crecer dentro de la empresa), y la cultura del equipo (el trabajo en cámaras es solitario y puede generar sensación de aislamiento). Propón las iniciativas de retención: el plan de carrera transparente (operario > carretillero > encargado de turno > jefe de almacén > técnico de refrigeración, con los requisitos de formación y experiencia para cada paso claramente definidos), el programa de reconocimiento de la seguridad (puntos por meses sin incidentes, canjeables por días de vacaciones adicionales o cheques regalo), y la mejora de las condiciones del puesto de trabajo (calidad de la ropa térmica, zonas de descanso calientes y equipadas, calidad de la iluminación en las cámaras).

Bloque de talento 5 - KPIs de personas y mejora continua con IA:
Define el sistema de métricas de RRHH para el sector de la cadena de frío. Las métricas más relevantes para reducir la rotación y mejorar la seguridad: la tasa de rotación mensual desglosada por turno y por sección del almacén (para identificar si el problema de retención está concentrado en el turno de noche o en las cámaras de congelación), el índice de frecuencia y gravedad de los accidentes laborales (comparado con el benchmark del sector de almacenamiento frigorífico de la estadística de accidentes de trabajo del MITES), la tasa de absentismo por enfermedad diferenciada entre bajas cortas (síntoma de clima laboral o condiciones de trabajo) y bajas largas (accidentes o enfermedades laborales), la evolución del resultado del reconocimiento médico anual (qué porcentaje de la plantilla presenta afecciones músculo-esqueléticas o cardiovasculares que indican daño por el trabajo en frío), y el Net Promoter Score interno (¿recomendarías esta empresa como lugar de trabajo a un familiar o amigo?). Describe cómo la IA analiza estas métricas para identificar las acciones de mayor impacto en la retención: si el sistema detecta que la rotación es tres veces mayor en el turno de noche y en los primeros 3 meses de empleo, la intervención prioritaria es mejorar el proceso de onboarding nocturno y asignar un mentor experimentado a cada nuevo operario durante sus primeros 90 días.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 50,
                'use_case'         => 'Gestión del talento y reducción de rotación en operaciones de cadena de frío con IA',
                'vote_score'       => 32,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Finanzas y optimización de costes en operaciones de cadena de frío con IA',
                'description'      => 'Analiza y optimiza la estructura de costes de operadores logísticos de cadena de frío usando inteligencia artificial para modelizar los costes energéticos, optimizar la ocupación de almacenes frigoríficos y evaluar inversiones en tecnología.',
                'prompt_content'   => <<<'EOT'
Eres un director financiero con experiencia en la gestión económica de operadores logísticos de cadena de frío y empresas de distribución de productos perecederos. Necesito tu ayuda para construir el marco de gestión financiera completo para un operador logístico de cadena de frío con un presupuesto anual de 18 millones de euros.

Contexto financiero:
Los ingresos de la empresa provienen de: almacenamiento frigorífico (45% de los ingresos), transporte en temperatura controlada (40%) y servicios de valor añadido como el picking, la preparación de pedidos y los servicios farmacéuticos especiales (15%). Los tres mayores costes son: la energía eléctrica de los sistemas de refrigeración (28% de los costes operativos), los costes de personal (35%) y los costes de mantenimiento de flota y equipos de frío (15%). El margen EBITDA actual es del 11%, por debajo del benchmark sectorial del 14-16%.

Objetivo de la gestión financiera:
Construye el plan de mejora del margen EBITDA del 11% al 15% en 24 meses.

Marco financiero 1 - Modelización y optimización de costes energéticos con IA:
Describe el modelo de gestión y optimización del coste energético de los sistemas de refrigeración. La energía es el mayor coste variable del negocio y tiene una alta volatilidad de precio en el mercado eléctrico español. Define el modelo de gestión energética con IA: cómo el sistema analiza el perfil de consumo energético de cada cámara frigorífica (consumo por hora del día, por temperatura exterior, por carga de producto), identifica las oportunidades de desplazamiento de consumo a las horas de precio más bajo de la tarifa eléctrica, y optimiza el ciclo de enfriamiento para acumular frío en el producto durante las horas baratas y reducir el consumo durante las horas punta. Describe el modelo de contratación eléctrica óptimo para una empresa con alto consumo: la comparación entre la tarifa PVPC (precio del mercado regulado) y los contratos de precio fijo a largo plazo con las comercializadoras, la viabilidad de la autogeneración con solar fotovoltaica en la cubierta del almacén, y la participación en el mercado de servicios de ajuste de REE como consumidor flexible (el operador logístico puede ofrecer su capacidad de modulación de consumo al operador del sistema eléctrico a cambio de una remuneración).

Marco financiero 2 - Optimización de la ocupación del almacén frigorífico:
Analiza el modelo de gestión de la ocupación de las cámaras frigoríficas como palanca de mejora del margen. El coste fijo de mantener una cámara frigorífica en temperatura es prácticamente independiente del nivel de ocupación (el sistema de frío consume casi lo mismo esté la cámara llena o vacía), por lo que maximizar la ocupación es la palanca de rentabilidad más poderosa para un operador logístico de cadena de frío. Define el modelo de pricing dinámico de almacenamiento: cómo la IA puede ajustar el precio del espacio de almacenamiento según la ocupación actual de cada cámara (precio base cuando la ocupación es alta y hay lista de espera, precio reducido para atraer nueva carga cuando la ocupación es inferior al 70%), sin canibalizar los contratos a largo plazo con clientes fidelizados. Describe el modelo de previsión de ocupación a 3-6 meses que permite anticipar los meses de menor ocupación y preparar acciones comerciales con suficiente antelación para evitar los valles de inactividad que destrozan el margen.

Marco financiero 3 - Modelo de rentabilidad por cliente y por servicio:
Define el modelo de análisis de rentabilidad por cliente y por línea de servicio. En un negocio de logística de cadena de frío, la cuenta de resultados consolidada puede ocultar que algunos clientes o algunos servicios son cronicamente deficitarios mientras que otros financian el negocio. Describe la metodología de cálculo de la rentabilidad real por cliente: la asignación de los costes directos (horas de personal dedicadas, metros cúbicos ocupados, kilómetros de transporte) y de los costes indirectos (energía asignada por m³ de producto almacenado, costes administrativos distribuidos por número de operaciones) a cada cliente. Analiza los resultados esperados de este análisis: los clientes con alta rotación de mercancía (muchas entradas y salidas de pequeños volúmenes) consumen muchos recursos de personal por unidad de ingreso, mientras que los clientes con grandes volúmenes y pocas operaciones de entrada/salida son mucho más rentables. Define el plan de acción para los clientes cronicamente deficitarios: renegociación de tarifas con los que tienen potencial de crecimiento, o descontinuación controlada de la relación con los que no pueden ser rentables por la naturaleza de sus operaciones.

Marco financiero 4 - Evaluación de inversiones en tecnología y flota con IA:
Describe el framework de evaluación de inversiones de capital para el operador logístico de cadena de frío. Las inversiones más frecuentes en el sector son: la renovación de la flota de vehículos frigoríficos (ticket unitario de 120.000 a 180.000 euros para un camión frigorífico de 82 m³), la inversión en tecnología de monitorización IoT y plataformas de gestión de la cadena de frío, la instalación de paneles fotovoltaicos en la cubierta del almacén, y las inversiones en automatización del almacén (sistemas de picking automático, cintas transportadoras en las zonas de entrada y salida). Define el modelo de evaluación financiera de cada tipo de inversión: el ROI de la renovación de flota (el camión nuevo es más eficiente en combustible y tiene menores costes de mantenimiento, pero el valor de capital inmovilizado es alto), el payback de la instalación fotovoltaica (depende de la tarifa eléctrica actual y futura, el precio de los paneles y las horas de sol del emplazamiento), y el VAN de la inversión en automatización (reducción de costes de personal vs. coste de la inversión y los costes de mantenimiento del sistema automático).

Marco financiero 5 - Cuadro de mando financiero para logística de cadena de frío:
Diseña el sistema de reporting financiero y el cuadro de mando directivo para el operador logístico. Define las métricas financieras específicas del sector: el coste energético por m³ almacenado y por grado centígrado de diferencia (métrica de eficiencia energética), el coste operativo por paleta manipulada (métrica de eficiencia operativa), el coste por kilómetro de transporte frigorífico (descompuesto entre coste de combustible, peajes, conductor y amortización del vehículo), el margen bruto por línea de servicio (almacenamiento vs. transporte vs. servicios de valor añadido), y el ratio de ocupación media de las cámaras por zona de temperatura. Describe el cuadro de mando mensual que el director financiero presenta al comité de dirección: la evolución de los costes energéticos vs. el precio de mercado eléctrico (para evaluar la efectividad de la estrategia de compra de energía), la comparativa de margen por cliente (los 10 clientes más rentables y los 5 menos rentables), la evolución del ciclo de conversión de caja (el período medio de cobro a clientes alimentarios es de 30-60 días, pero el período de pago a proveedores de mantenimiento puede ser de 90 días, lo que genera un efecto de caja positivo que debe gestionarse estratégicamente). Define las alertas automáticas de desviación que el sistema de BI genera cuando el coste energético mensual supera el presupuesto en más de un 8% o cuando la ocupación de alguna cámara cae por debajo del 65% durante más de 7 días consecutivos.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 60,
                'use_case'         => 'Optimización financiera y de costes para operador logístico de cadena de frío con IA',
                'vote_score'       => 46,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Cumplimiento normativo en cadena de frío alimentaria y farmacéutica con IA',
                'description'      => 'Navega la regulación de trazabilidad alimentaria, GDP farmacéutico y APPCC en la cadena de frío usando inteligencia artificial para gestionar el cumplimiento normativo, documentar los controles y preparar las auditorías de clientes y autoridades.',
                'prompt_content'   => <<<'EOT'
Eres un abogado y consultor de calidad especializado en la regulación de la cadena de frío alimentaria y farmacéutica, con expertise en el Reglamento (CE) 178/2002, el Reglamento (CE) 853/2004, las guías GDP de la EMA y la normativa española de seguridad alimentaria. Necesito tu análisis jurídico completo sobre el marco regulatorio que aplica a un operador logístico de cadena de frío que opera almacenes frigoríficos y flota de transporte en temperatura controlada para la industria alimentaria y farmacéutica.

Contexto jurídico:
El operador quiere diversificar hacia el mercado farmacéutico y necesita entender qué cambios regulatorios y operativos debe implementar para operar legalmente en ambos sectores. Actualmente está registrado como operador de almacenamiento de alimentos ante la AESAN y tiene implementado un sistema APPCC básico. Para el sector farmacéutico, necesita obtener la autorización de almacenamiento de medicamentos de la AEMPS y cumplir con las guías GDP.

Objetivo del análisis:
Proporciona el mapa regulatorio completo para operar en cadena de frío alimentaria y farmacéutica en España con todas las autorizaciones y sistemas de gestión necesarios.

Área normativa 1 - Marco regulatorio europeo y español de la cadena de frío alimentaria:
Analiza el marco regulatorio aplicable al almacenamiento y transporte de alimentos en temperatura controlada. El Reglamento (CE) 852/2004 de higiene de los alimentos establece las obligaciones generales de todos los operadores de la cadena alimentaria, incluyendo los almacenes frigoríficos y transportistas. El Reglamento (CE) 853/2004 establece requisitos específicos para alimentos de origen animal (carnes, pescados, lácteos, huevos) que son los productos más habituales en la cadena de frío: las temperaturas máximas de almacenamiento y transporte para cada categoría de producto, los requisitos de higiene de los vehículos de transporte y los almacenes, y la documentación que debe acompañar a los envíos de productos de origen animal. Describe también el Real Decreto 176/2013 y las disposiciones específicas españolas sobre la cadena del frío, los registros sanitarios de los establecimientos frigoríficos ante la AESAN y los controles oficiales realizados por los servicios veterinarios de las comunidades autónomas. Define las obligaciones de trazabilidad del artículo 18 del Reglamento (CE) 178/2002 para un operador logístico de cadena de frío: qué información debe registrar sobre los lotes de producto que almacena y transporta para garantizar la trazabilidad hacia adelante y hacia atrás en caso de una alerta alimentaria.

Área normativa 2 - APPCC y autocontroles en el almacén frigorífico y el transporte:
Describe las obligaciones del sistema APPCC para operadores logísticos de cadena de frío. El sistema APPCC (Análisis de Peligros y Puntos de Control Crítico) es obligatorio para todos los operadores de la cadena alimentaria bajo el Reglamento (CE) 852/2004. Para un almacén frigorífico, los Puntos de Control Crítico (PCC) más relevantes son: la temperatura de almacenamiento de cada cámara (con los límites críticos definidos para cada categoría de producto, el sistema de monitorización continua y el procedimiento de acción correctiva ante una desviación), la temperatura de los vehículos de transporte durante las operaciones de carga, trayecto y descarga, y las condiciones de higiene en las operaciones de manipulación del producto. Define los procedimientos de verificación del sistema APPCC que el operador debe ejecutar periódicamente: la calibración de los sistemas de medición de temperatura, las analíticas microbiológicas del ambiente de las cámaras, y las auditorías internas del cumplimiento de los procedimientos. Describe cómo la IA puede asistir en la gestión del APPCC: el sistema analiza automáticamente los registros de temperatura de todas las cámaras y vehículos, identifica las desviaciones de los límites críticos, genera automáticamente el registro de la no conformidad y notifica al responsable de calidad para que gestione la acción correctiva y la documentación.

Área normativa 3 - Autorización GDP y cumplimiento para almacenamiento de medicamentos:
Analiza el proceso de obtención de la autorización de almacenamiento de medicamentos ante la AEMPS y los requisitos de cumplimiento continuo. Las Guías de Buenas Prácticas de Distribución (GDP) de la Agencia Europea de Medicamentos establecen los requisitos mínimos que deben cumplir los distribuidores y almacenistas de medicamentos en la UE. Describe el proceso de solicitud de autorización ante la AEMPS: la documentación técnica que debe presentarse (descripción detallada de las instalaciones, planos de las cámaras con la distribución de sensores de temperatura, procedimientos de operación estándar para las actividades de almacenamiento, cualificación técnica del personal responsable), el proceso de inspección previa de las instalaciones por los inspectores de la AEMPS, y los plazos de resolución habituales. Define los requisitos GDP de cumplimiento continuo una vez obtenida la autorización: el sistema de gestión de la calidad documentado (Quality Management System), el responsable técnico farmacéutico (que debe ser farmacéutico colegiado en activo), los procedimientos de gestión de las reclamaciones de los clientes farmacéuticos y de los retiros de medicamentos del mercado (recalls), y los requisitos de formación continua del personal en los estándares GDP.

Área normativa 4 - Responsabilidad civil y gestión de incidencias de temperatura:
Analiza el régimen de responsabilidad civil del operador logístico de cadena de frío ante sus clientes cuando se produce una incidencia de temperatura que deteriora el producto. En el sector alimentario, una desviación de temperatura que provoca la pérdida de un lote de producto genera responsabilidad contractual del operador logístico ante su cliente. Describe las cláusulas de limitación de responsabilidad más frecuentes en los contratos logísticos: los límites económicos de responsabilidad por operación o por expedición (basados en el valor declarado de la mercancía), los supuestos de exoneración de responsabilidad (avería imprevisible del equipo de frío, fuerza mayor, entrega de mercancía ya deteriorada por parte del cliente sin informar al operador), y los requisitos de seguro de responsabilidad civil del transportista (el seguro de mercancías transportadas y el seguro de responsabilidad del almacenista). En el sector farmacéutico, la responsabilidad es más grave porque una desviación de temperatura puede afectar a la eficacia de un medicamento ya en manos de pacientes. Describe el procedimiento de gestión de una incidencia de temperatura con producto farmacéutico: la notificación inmediata al cliente, la cuarentena del producto afectado, el proceso de evaluación del riesgo sanitario conjunto con el cliente, y la documentación completa de la incidencia para el expediente de calidad.

Área normativa 5 - Protección de datos y ciberseguridad en sistemas de trazabilidad:
Analiza las implicaciones del RGPD y la regulación de ciberseguridad en los sistemas de trazabilidad y monitorización de la cadena de frío. Los sistemas de monitorización IoT de la cadena de frío recopilan grandes volúmenes de datos sobre las operaciones del cliente (qué productos almacena, en qué cantidades, con qué frecuencia de movimiento, destinados a qué clientes del cliente), que pueden constituir información comercialmente sensible sujeta a obligaciones de confidencialidad. Define el tratamiento de estos datos bajo el RGPD: si los datos de trazabilidad incluyen datos de personas (por ejemplo, el nombre del conductor de la expedición o el destinatario final del producto), qué base jurídica justifica su tratamiento, cuánto tiempo pueden conservarse y quién tiene acceso a ellos. Describe también la regulación de ciberseguridad aplicable a los sistemas de control de temperatura de instalaciones frigoríficas: el Real Decreto-ley 12/2018 sobre seguridad de redes y sistemas de información (transposición de la Directiva NIS) puede aplicar a operadores logísticos que son proveedores de servicios esenciales para la cadena alimentaria, obligándoles a implementar medidas de seguridad específicas y a notificar los incidentes de ciberseguridad significativos. Define el plan de protección de datos y ciberseguridad para el sistema de monitorización IoT: la arquitectura de seguridad de los datos, el plan de respuesta ante una brecha de seguridad que comprometa los registros de temperatura de un cliente farmacéutico, y las cláusulas contractuales que deben incluirse en los contratos con los clientes sobre la confidencialidad y la seguridad de sus datos de operaciones.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Marco regulatorio APPCC, GDP y trazabilidad para operador logístico de cadena de frío',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención al cliente en logística de cadena de frío con IA',
                'description'      => 'Diseña sistemas de atención al cliente y gestión de incidencias con inteligencia artificial para operadores logísticos de productos perecederos, gestionando alertas de temperatura, reclamaciones por daños y consultas de trazabilidad en tiempo real.',
                'prompt_content'   => <<<'EOT'
Eres un director de atención al cliente especializado en el sector de la logística de cadena de frío y distribución de productos perecederos. Necesito tu ayuda para diseñar el sistema completo de atención al cliente con inteligencia artificial para un operador logístico de cadena de frío con 150 clientes activos entre la industria alimentaria y farmacéutica.

Contexto del servicio:
El operador gestiona almacenamiento frigorífico, transporte y distribución de perecederos. Las consultas más frecuentes de los clientes son: solicitudes de información sobre el estado de temperatura de sus lotes de producto almacenados (crítico para los clientes farmacéuticos), reclamaciones por retrasos en la entrega de perecederos que han generado mermas por temperatura, consultas sobre el estado de las expediciones en tránsito, solicitudes de documentación de temperatura para auditorías de los clientes de los clientes, y gestión de incidencias cuando se produce una alarma de temperatura en una cámara que contiene producto del cliente.

Objetivo del sistema:
Diseña el sistema de atención al cliente que resuelve el 70% de las consultas de forma autónoma y gestiona las incidencias críticas en menos de 15 minutos.

Componente de atención 1 - Portal de trazabilidad y autoservicio con IA para clientes:
Describe el sistema de autoservicio que permite a los clientes resolver sus consultas sin intervención del equipo de atención. Define las funcionalidades del portal de cliente: el acceso en tiempo real al estado de temperatura de sus lotes almacenados (con gráfica histórica de temperatura de las últimas 24/48/72 horas), el seguimiento de sus expediciones en tránsito (posición GPS del vehículo + temperatura de la carga + hora estimada de entrega), la descarga de los informes de temperatura para auditorías en el formato estándar que requiere la industria farmacéutica (PDF certificado con firma electrónica), y el historial de movimientos de su stock en el almacén (entradas, salidas, inventario actual). Describe cómo la IA puede responder de forma autónoma las consultas más frecuentes que actualmente llegan por email o teléfono: el cliente que pregunta "¿a qué temperatura está mi producto ahora mismo?" puede obtener la respuesta directamente en el portal sin necesidad de contactar con ningún agente humano. Define los criterios que determinan qué consultas pueden resolverse de forma autónoma y cuáles requieren siempre la intervención del equipo humano.

Componente de atención 2 - Gestión de alertas de temperatura en tiempo real con IA:
Diseña el protocolo de gestión de alertas de temperatura cuando se produce una desviación en una cámara o vehículo que contiene producto de un cliente. Las alarmas de temperatura en cadena de frío tienen distintos niveles de urgencia: una desviación de 0,5°C durante 10 minutos en una cámara de refrigeración es diferente a una desviación de 5°C durante 2 horas en una cámara de congelación con producto farmacéutico. Define el protocolo de notificación al cliente según el nivel de urgencia: para una alarma crítica de producto farmacéutico, el cliente debe ser notificado en menos de 5 minutos con la información completa (cámara afectada, temperatura actual, duración de la desviación, lotes de producto potencialmente afectados, acciones correctivas en curso). Para una alarma de baja urgencia en producto alimentario de baja sensibilidad, la notificación puede ser una alerta en el portal digital que el cliente verá cuando acceda. Describe el sistema de gestión de la incidencia post-alarma: cómo el operador documenta automáticamente todos los datos de la alarma (con registro inmutable de timestamp), cómo el cliente puede acceder a toda esta documentación, y cómo se gestiona la decisión de destino del producto afectado (liberación, cuarentena o destrucción) con el protocolo de responsabilidades definido en el contrato.

Componente de atención 3 - Gestión de reclamaciones por daños en perecederos con IA:
Describe el proceso de gestión de reclamaciones cuando un cliente afirma que su producto ha llegado a destino en condiciones deficientes de temperatura o de integridad física. Las reclamaciones en logística de perecederos son especialmente sensibles porque los productos afectados pueden representar pérdidas económicas significativas (un palet de langostinos congelados o un lote de medicamentos biológicos pueden valer decenas de miles de euros). Define el protocolo de gestión de reclamaciones: la recepción de la reclamación con la captura automática de los datos clave (expedición reclamada, descripción del daño, valor de la mercancía, evidencias fotográficas del cliente), la verificación automática de los registros de temperatura de la operación en cuestión para determinar si hubo desviación en la fase bajo responsabilidad del operador, la gestión de la peritación cuando el operador y el cliente discrepan sobre la causa del daño, y el proceso de resolución y compensación. Describe cómo la IA puede asistir en la evaluación de las reclamaciones: el análisis automático del registro de temperatura completo de la operación, la comparación con los límites contractuales acordados, y la generación de un informe técnico que documenta objetivamente lo ocurrido para facilitar la resolución de la disputa.

Componente de atención 4 - Preparación de documentación para auditorías de clientes:
Los clientes de cadena de frío, especialmente los del sector farmacéutico, realizan auditorías periódicas a sus operadores logísticos y solicitan documentación específica. Diseña el sistema de gestión de solicitudes de documentación con IA que agiliza la preparación de los paquetes de documentación para auditorías. Los documentos más frecuentemente solicitados en una auditoría logística farmacéutica son: los certificados de calibración de los sensores de temperatura (con la trazabilidad a los patrones nacionales de medida), los registros de temperatura de las cámaras durante los últimos 12 meses, los informes de las desviaciones de temperatura registradas y las acciones correctivas adoptadas, los registros de las cualificaciones y formaciones del personal en GDP, y el informe de la última auditoría interna del sistema de calidad con el estado de cierre de las observaciones encontradas. Describe cómo la IA puede automatizar la recopilación y el empaquetado de esta documentación: cuando el cliente solicita el paquete de documentación para su auditoría anual, el sistema genera automáticamente el índice de documentos, los recupera de los sistemas de gestión documental del operador y los empaqueta en un expediente ordenado listo para enviar, reduciendo el tiempo de preparación de 2-3 días a menos de 2 horas.

Componente de atención 5 - Métricas de calidad del servicio y mejora continua:
Define el sistema de métricas de calidad del servicio de atención al cliente para un operador logístico de cadena de frío. Las métricas más relevantes en este sector: el tiempo medio de notificación al cliente desde la detección de una alarma de temperatura (el objetivo para clientes farmacéuticos debe ser inferior a 5 minutos), el tiempo medio de resolución completa de las reclamaciones por daños (incluyendo el proceso de peritación y compensación), el porcentaje de consultas resueltas de forma autónoma por el portal de autoservicio sin contacto con el equipo humano, el NPS de los clientes farmacéuticos (segmento de mayor valor y mayor exigencia), y el porcentaje de auditorías de clientes que concluyen sin hallazgos críticos (indicador de la madurez del sistema de calidad del operador). Describe el proceso de mejora continua: cómo el equipo de calidad analiza mensualmente las reclamaciones recibidas para identificar los fallos sistémicos que deben corregirse (si el 40% de las reclamaciones son por entregas fuera de ventana horaria, el problema no es de atención al cliente sino de planificación del transporte), y cómo el feedback de los clientes se incorpora al plan de mejora anual del sistema de gestión de la calidad del operador. Define también el sistema de comunicación proactiva con los clientes: cómo el operador comunica a sus clientes las mejoras realizadas en el sistema de cadena de frío (nueva tecnología de monitorización instalada, resultados del mapeo térmico actualizado de las cámaras, nuevas cualificaciones GDP obtenidas) para reforzar la confianza y reducir la necesidad de auditorías extraordinarias.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 45,
                'use_case'         => 'Sistema de atención al cliente y gestión de incidencias de temperatura con IA para logística frigorífica',
                'vote_score'       => 30,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultoría freelance en cadena de frío y logística de perecederos con IA',
                'description'      => 'Construye un negocio de consultoría freelance especializado en cadena de frío, logística de productos perecederos y cumplimiento regulatorio alimentario y farmacéutico, usando la inteligencia artificial como herramienta diferenciadora.',
                'prompt_content'   => <<<'EOT'
Eres un consultor de logística de cadena de frío freelance senior con experiencia en proyectos de optimización de operaciones frigoríficas, cumplimiento GDP y tecnología IoT para la industria alimentaria y farmacéutica. Necesito tu ayuda para construir mi negocio de consultoría independiente en el nicho de la cadena de frío y la logística de perecederos, usando la inteligencia artificial como herramienta diferenciadora.

Mi situación actual:
Tengo 14 años de experiencia en el sector de la cadena de frío: los primeros 7 como técnico de refrigeración industrial y responsable de calidad en un almacén frigorífico, y los últimos 7 como director de operaciones en un operador logístico de cadena de frío farmacéutica con certificación GDP. He liderado la implementación de sistemas de monitorización IoT, procesos de cualificación GDP y la obtención de autorizaciones de la AEMPS. Quiero lanzarme como consultor freelance para ayudar a operadores logísticos de la industria alimentaria a entrar en el mercado farmacéutico y a empresas farmacéuticas a seleccionar y auditar a sus operadores logísticos de cadena de frío.

Objetivo de la sesión:
Diseña el plan completo para lanzar y escalar mi consultoría freelance en cadena de frío en los próximos 18 meses.

Pilar estratégico 1 - Posicionamiento como experto en cadena de frío:
Ayúdame a definir mi nicho específico dentro del campo de la cadena de frío y la logística de perecederos. Analiza cuatro especializaciones con su mercado potencial: consultoría de transición al mercado farmacéutico para operadores logísticos alimentarios (ayudo a empresas con experiencia en cadena de frío alimentaria a obtener la certificación GDP y captar clientes farmacéuticos, mercado con alta demanda por la escasez de operadores GDP cualificados), auditorías de proveedores logísticos para laboratorios farmacéuticos (el laboratorio me contrata para auditar la cadena de frío de sus operadores actuales o potenciales, servicio de alta especialización que los consultores generalistas no pueden prestar), consultoría de tecnología IoT e implementación de sistemas de monitorización de temperatura (ayudo a operadores logísticos a seleccionar e implementar las mejores soluciones tecnológicas de monitorización de su cadena de frío), y formación y cualificación de personal en GDP y normativa de cadena de frío para equipos de calidad y operaciones. Para cada especialización, describe el cliente típico, el ticket promedio y la escasez de consultores especializados.

Pilar estratégico 2 - Estructura de servicios y propuesta de valor:
Diseña el catálogo de servicios con tres niveles de compromiso. Nivel 1 - Diagnóstico y gap analysis (2-3 semanas, honorarios de 5.000 a 10.000 euros): analizo el estado actual de la cadena de frío del operador (instalaciones, sistemas de monitorización, documentación de calidad, formación del personal) y entrego un informe con las brechas respecto a los requisitos GDP y un plan de acción priorizado para obtener la autorización de la AEMPS. Nivel 2 - Proyecto de implementación GDP (3-9 meses, 800 a 1.200 euros por día): acompaño al operador en la implementación completa del sistema de gestión de la calidad GDP, la cualificación de las instalaciones (IQ/OQ/PQ), la preparación de la documentación técnica y el proceso de inspección de la AEMPS. Nivel 3 - Auditor externo de cadena de frío en retainer (12 meses, 2.500 a 4.000 euros al mes): actúo como responsable externo de garantía de calidad para la cadena de frío del cliente, revisando mensualmente el cumplimiento de los estándares GDP y preparando al operador para las auditorías de sus clientes farmacéuticos. Define los entregables concretos y los criterios de éxito para cada nivel.

Pilar estratégico 3 - Captación de clientes en el sector de la cadena de frío:
Propón las estrategias de captación de clientes adaptadas a este nicho muy específico. El mercado de la cadena de frío es pequeño y muy especializado: todos los actores relevantes se conocen entre sí. Describe cómo construir autoridad y visibilidad: las publicaciones técnicas en LinkedIn sobre errores frecuentes en la implementación GDP y cómo evitarlos (este tipo de contenido es muy valorado por los directores de calidad de los laboratorios farmacéuticos), las ponencias en las jornadas técnicas de AECOC sobre cadena de frío y en los congresos de Farmaindustria sobre distribución de medicamentos, la colaboración con las principales asociaciones del sector (Astic para transportistas, Aldeasa para almacenistas frigoríficos, Feafar para distribuidores farmacéuticos) como referente técnico, y la publicación de guías prácticas sobre la normativa GDP en formato descargable gratuito que atrae orgánicamente a los responsables de calidad que buscan esta información. Define también la estrategia de referencias: el sector farmacéutico es muy pequeño y las referencias de los directores de calidad son el canal de captación más efectivo.

Pilar estratégico 4 - Uso de la IA como ventaja competitiva del consultor de cadena de frío:
Describe cómo integrar la IA en tu práctica de consultoría para diferenciarte de los consultores tradicionales del sector. La IA permite: análisis masivo de registros de temperatura históricos para el diagnóstico de ineficiencias en la cadena de frío (puedo analizar años de datos de temperatura de todas las cámaras de un operador en horas, identificando patrones de desviación que serían imposibles de detectar manualmente), generación de la documentación GDP (procedimientos de operación estándar, planes de validación, informes de cualificación) con una calidad y exhaustividad superior a la que un consultor individual podría producir sin asistencia de IA, investigación continua de los cambios regulatorios (las guías GDP se actualizan periódicamente por la EMA y los reguladores nacionales; la IA me permite estar al día de todos los cambios sin dedicar horas a leer documentos regulatorios en múltiples idiomas), y preparación de informes de auditoría estructurados con las observaciones clasificadas por nivel de riesgo (crítico, mayor, menor) y con las referencias normativas exactas para cada hallazgo.

Pilar estratégico 5 - Operativa del negocio freelance en el sector de la cadena de frío:
Describe la operativa del negocio de consultoría de cadena de frío freelance. Cubre: la credibilidad técnica como base de negocio (en un sector donde la responsabilidad del consultor puede llegar a afectar a la seguridad de medicamentos destinados a pacientes, la reputación y la rigurosidad técnica son más importantes que el precio), la red de especialistas complementarios que puedes movilizar para proyectos complejos (técnicos de refrigeración industrial para la parte técnica de las cualificaciones, validadores de sistemas informáticos para el Anexo 11 de GMP si el cliente tiene sistemas informatizados de registro de temperatura, y laboratorios de calibración acreditados para los servicios de calibración de sensores), la gestión del seguro de responsabilidad civil profesional (un consultor que asesora sobre el almacenamiento de medicamentos asume una responsabilidad significativa si un error en su asesoramiento genera un problema de calidad del medicamento), y el plan de crecimiento a largo plazo: cómo expandir la práctica de consultoría a otros países europeos donde la implementación GDP también es obligatoria (Francia, Italia, Alemania, Polonia) aprovechando la experiencia acumulada en España y las relaciones con los laboratorios farmacéuticos internacionales que operan también en esos mercados.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Plan de negocio para consultoría freelance en cadena de frío farmacéutica y logística perecedera',
                'vote_score'       => 45,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
