<?php
namespace Database\Seeders;
use App\Models\Skill;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TopSearchedSkills568Seeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $skills = [
            [
                'profession_id'    => 1,
                'title'            => 'Comunicación digital de servicios públicos y campañas institucionales con IA',
                'description'      => 'Diseña y ejecuta estrategias de comunicación digital para organismos públicos y administraciones usando IA para llegar a la ciudadanía con mensajes claros, accesibles y en los canales adecuados.',
                'prompt_content'   => <<<'EOT'
Eres un director de comunicación digital con amplia experiencia en el sector público y la administración institucional. Has gestionado estrategias de comunicación para ministerios, ayuntamientos, comunidades autónomas y organismos reguladores. Sabes que la comunicación pública tiene particularidades únicas: el lenguaje debe ser accesible para toda la ciudadanía, los mensajes deben cumplir requisitos de transparencia e imparcialidad, y los canales y recursos son más limitados que en el sector privado.

Contexto del organismo:
- Ayuntamiento de una ciudad mediana española con 120.000 habitantes
- Área de comunicación: 4 personas (director/a de comunicación, 2 técnicos y 1 community manager)
- Canales digitales: web municipal, app del ayuntamiento, redes sociales (Facebook, Twitter/X, Instagram), newsletter ciudadana con 18.000 suscriptores
- Retos: la ciudadanía no conoce muchos de los servicios disponibles, la imagen del ayuntamiento está ligada a la política y no a los servicios, y hay mucha diversidad demográfica (personas mayores, inmigrantes, jóvenes)
- Objetivo: mejorar la comunicación de los servicios municipales para que la ciudadanía los use más y esté más satisfecha

Desarrolla la estrategia completa de comunicación digital municipal:

1. Auditoría de la comunicación municipal actual: Antes de diseñar la estrategia, hay que entender el punto de partida. Diseña el proceso de auditoría. Incluye: análisis de los canales digitales actuales (web: navegación, accesibilidad, velocidad; redes sociales: seguidores, engagement, tipo de contenido publicado; newsletter: tasa de apertura, tasa de clic, segmentación de listas), análisis del lenguaje y el tono de la comunicación actual (¿es comprensible para una persona sin estudios universitarios?, ¿usa jerga administrativa que la ciudadanía no entiende?), mapa de los servicios municipales más importantes que la ciudadanía desconoce (encuesta rápida para identificar los 5 servicios más infrautilizados por falta de conocimiento), análisis de las preguntas más frecuentes que recibe el ayuntamiento por teléfono y en presencia (estas son las necesidades reales de comunicación que hay que resolver) y benchmarking de la comunicación de ayuntamientos de referencia en España (Madrid, Barcelona, Zaragoza, Valladolid).

2. Estrategia de contenidos para servicios municipales: El contenido es el motor de la comunicación pública. Diseña el plan editorial. Incluye: categorías de contenido prioritarias para la ciudadanía (servicios sociales, educación, cultura, transporte, urbanismo, participación ciudadana, emergencias), calendario editorial anual alineado con los eventos clave del municipio (inicio del curso escolar, campaña de declaración de renta, temporada de incendios, navidades, elecciones locales si aplica), principios de claridad del lenguaje administrativo (cómo reescribir un comunicado de prensa burocrático en lenguaje ciudadano comprensible), formatos de contenido para cada canal (carrusel de Instagram para explicar un trámite en 5 pasos, hilo de Twitter para novedades de planeamiento urbanístico, vídeo de 60 segundos para TikTok o Reels con un consejo del servicio de mediación) y estrategia de contenido útil vs. contenido institucional (el 80% del contenido debe ser de utilidad práctica para el ciudadano, el 20% institucional).

3. Comunicación multicanal y accesibilidad: La ciudadanía es diversa y no todos usan los mismos canales. Diseña la estrategia de inclusión. Incluye: estrategia para llegar a las personas mayores que no usan redes sociales (tablones de anuncios digitales en centros de mayores, canal de WhatsApp del ayuntamiento, colaboración con las asociaciones de vecinos), estrategia de comunicación en otros idiomas para la población inmigrante (qué idiomas priorizar, cómo usar IA para traducir comunicados de forma accesible), accesibilidad digital: cómo cumplir con el Real Decreto 1112/2018 de accesibilidad de las webs del sector público (subtítulos en vídeos, audiodescripción, contraste de colores, versión de lectura fácil), comunicación en lenguaje de fácil lectura para personas con discapacidad intelectual y estrategia para la brecha digital de los ciudadanos sin acceso o habilidades digitales.

4. Uso de la IA en la comunicación municipal: La IA puede multiplicar la capacidad de un equipo pequeño de comunicación. Diseña el sistema. Incluye: uso de IA para generar borradores de comunicados, publicaciones en redes sociales y respuestas a preguntas frecuentes (con revisión humana obligatoria antes de publicar), IA para traducir documentos municipales y comunicados a otros idiomas de la población local, uso de IA para analizar el sentimiento de los comentarios de la ciudadanía en redes sociales y detectar temas de preocupación emergentes, chatbot municipal con IA para responder preguntas frecuentes en la web (trámites, horarios, teléfonos de contacto) y reducir la carga del teléfono de atención ciudadana y sistema de IA para transcribir y resumir los plenos municipales para hacerlos accesibles a la ciudadanía que no puede asistir.

5. Gestión de la comunicación de crisis en el sector público: Las crisis en el sector público son inevitables. Diseña el protocolo. Incluye: tipología de crisis más frecuentes en la administración local (incidencias en servicios básicos: agua, luz, recogida de basuras; emergencias meteorológicas; accidentes en infraestructuras; conflictos políticos que afectan a la imagen del ayuntamiento; bulos y desinformación sobre servicios municipales), protocolo de comunicación de crisis en 24 horas (quién decide, quién habla, por qué canales, con qué frecuencia de actualización), principios de comunicación de crisis en el sector público (transparencia máxima, información verificada antes de publicar, no especular, mantener la calma), uso de canales de emergencia (sistema ES-Alert, alertas en la app municipal, mensajes de texto a los vecinos de la zona afectada) y gestión de los bulos en redes sociales sobre servicios municipales o decisiones del ayuntamiento.

6. Medición y transparencia de la comunicación municipal: La comunicación pública debe rendir cuentas. Diseña el sistema de evaluación. Incluye: KPIs de la comunicación digital municipal (alcance total mensual en redes sociales, tasa de engagement por canal, número de visitas a la web de cada servicio municipal, tasa de apertura de la newsletter, número de preguntas respondidas por el chatbot vs. derivadas a atención telefónica), informe trimestral de comunicación para el gobierno municipal (qué ha comunicado el área, cuánta ciudadanía ha alcanzado, qué servicios se han beneficiado de mayor visibilidad), portal de transparencia de la comunicación (cuánto gasta el ayuntamiento en comunicación, qué agencias o herramientas usa, qué campañas ha realizado y con qué resultados) y proceso de consulta ciudadana sobre la comunicación municipal (encuesta anual sobre satisfacción con la información que recibe el ayuntamiento).

7. Colaboración con medios locales y periodismo de servicio público: Los medios locales son aliados estratégicos. Diseña la relación. Incluye: política de relaciones con los medios de comunicación locales (periódicos, radios, televisiones y medios digitales locales), protocolo de distribución de notas de prensa y comunicados (qué merece nota de prensa, qué va directamente a redes sociales, cómo adaptar el contenido para cada medio), colaboración con medios locales para el periodismo de datos sobre servicios municipales (apertura de datos del ayuntamiento que los medios pueden usar para periodismo de interés ciudadano) y gestión de las solicitudes de información de los periodistas locales: proceso de respuesta ágil que refuerce la transparencia del ayuntamiento.

Incluye plantilla de calendario editorial municipal, checklist de accesibilidad de contenido digital y ejemplos de reescritura de comunicados administrativos en lenguaje ciudadano.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 55,
                'use_case'         => 'Modernización de la comunicación digital de un ayuntamiento mediano para mejorar el conocimiento y uso de los servicios',
                'vote_score'       => 38,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 2,
                'title'            => 'Desarrollo de plataformas de administración electrónica y servicios públicos digitales con IA',
                'description'      => 'Diseña y construye sistemas de tramitación electrónica, portales ciudadanos y plataformas de gestión pública usando IA para mejorar la eficiencia administrativa y la experiencia del ciudadano.',
                'prompt_content'   => <<<'EOT'
Eres un arquitecto de software especializado en el desarrollo de sistemas para la administración pública y el e-government. Tienes experiencia construyendo plataformas de tramitación electrónica, portales de sede electrónica, sistemas de gestión documental y soluciones de identidad digital para organismos públicos. Conoces la normativa española de administración electrónica (Ley 39/2015, Ley 40/2015, RGPD en el sector público, el Esquema Nacional de Seguridad y el Esquema Nacional de Interoperabilidad).

Contexto del proyecto:
- Diputación provincial que da servicio tecnológico a 45 municipios de la provincia
- Estado actual: la mayoría de los municipios pequeños (<5.000 habitantes) todavía tramitan muchos procedimientos en papel, sin sede electrónica propia
- Objetivo: desarrollar una plataforma compartida de administración electrónica que los 45 municipios puedan usar sin necesidad de tener personal técnico propio
- Tecnología: stack basado en Java/Spring Boot para el backend, Angular para el frontend, PostgreSQL para bases de datos, infraestructura en la nube del sector público (Centro de Proceso de Datos de la SGAD)
- Restricciones: cumplimiento obligatorio del ENS (Esquema Nacional de Seguridad) nivel medio, integración con los servicios comunes de la SGAD (Cl@ve, FACE, Notific@, SIR)

Desarrolla la arquitectura completa de la plataforma de administración electrónica:

1. Arquitectura de la plataforma compartida de e-administración: Diseña la arquitectura técnica de una plataforma multi-tenant que sirva a los 45 municipios. Incluye: modelo de multitenancy (un tenant por municipio con aislamiento de datos pero infraestructura compartida), arquitectura de microservicios para los módulos principales (gestión de expedientes, registro electrónico, sede electrónica, notificaciones, gestión documental), capa de integración con los servicios comunes de la Administración General del Estado (Cl@ve para autenticación, FACE para facturas electrónicas, Notific@ para notificaciones electrónicas, SIR para el registro interadministrativo), diseño del modelo de datos que permita a cada municipio tener sus propios tipos de expediente y procedimientos sin duplicar la infraestructura y estrategia de configuración por municipio (cada ayuntamiento configura sus propios procedimientos, tasas, plazos y flujos de trabajo sin necesidad de código personalizado).

2. Sistema de gestión de expedientes (BPM): El corazón de la plataforma es la gestión de los procedimientos administrativos. Diseña el módulo. Incluye: motor de workflows configurable para los procedimientos administrativos más comunes (licencias de obras, empadronamiento, subvenciones, multas de tráfico, licencias de actividad), sistema de plantillas de procedimientos que los municipios pueden activar con un click (el catálogo de procedimientos compartido), gestión del estado de los expedientes con trazabilidad completa de todas las actuaciones (quién hizo qué y cuándo, cumpliendo con la Ley 39/2015), sistema de plazos y alertas automáticas (notificación al funcionario cuando un expediente está próximo a superar el plazo legal, notificación al ciudadano cuando debe aportar documentación), integración con el sistema de firma electrónica para la firma de resoluciones y actos administrativos y gestión del archivo electrónico único que cumpla con la Política de Gestión de Documentos del ENI.

3. Sede electrónica y portal ciudadano: El ciudadano accede a la administración a través de la sede electrónica. Diseña el portal. Incluye: arquitectura del portal ciudadano multilingüe y accesible (cumplimiento WCAG 2.1 AA y el Real Decreto 1112/2018), autenticación ciudadana a través de Cl@ve (Cl@ve PIN para trámites de baja seguridad, Cl@ve Permanente y certificado digital para trámites de alta seguridad), catálogo de procedimientos electrónicos con buscador inteligente (el ciudadano describe lo que necesita en lenguaje natural y el sistema le sugiere el procedimiento correcto), formularios inteligentes que se adaptan al tipo de solicitante y al municipio (solo muestran los campos relevantes para cada caso), carpeta ciudadana donde el ciudadano puede consultar el estado de sus expedientes, descargar sus notificaciones y gestionar sus representantes y sistema de pago electrónico integrado (tasas y tributos municipales a través de pasarela de pago certificada).

4. Integración con IA para la tramitación asistida: La IA puede automatizar partes del proceso de tramitación. Diseña el sistema. Incluye: IA para la revisión automática de la documentación aportada por el ciudadano (detectar si falta algún documento requerido, si la documentación está en el formato correcto, si los datos declarados son consistentes), asistente virtual para el ciudadano que le guía en la cumplimentación de los formularios y le aclara dudas sobre el procedimiento (integrado en la sede electrónica), IA para la clasificación automática de los documentos del registro de entrada (identificar el tipo de documento, el procedimiento al que corresponde y asignárselo al funcionario correcto), sistema de IA para la detección de expedientes similares que pueden servir de precedente para la resolución del expediente actual y automatización de las comunicaciones de trámite más frecuentes (requerimientos de subsanación, comunicaciones de inicio, notificaciones de resolución) mediante plantillas inteligentes que se personalizan con los datos del expediente.

5. Seguridad y cumplimiento del Esquema Nacional de Seguridad: El ENS es obligatorio para todos los sistemas de las administraciones públicas. Diseña la arquitectura de seguridad. Incluye: proceso de categorización del sistema según el ENS (impacto sobre las dimensiones de seguridad: disponibilidad, integridad, confidencialidad, autenticidad, trazabilidad) y justificación del nivel medio, medidas de seguridad obligatorias del ENS nivel medio que la plataforma debe implementar (control de acceso basado en roles, cifrado de datos en tránsito y en reposo, gestión de logs y auditoría, plan de continuidad de negocio, copias de seguridad), proceso de certificación del ENS (quién hace la auditoría, documentación necesaria, plazos de renovación), gestión de incidentes de seguridad según el Reglamento de Desarrollo del ENS (plazos de notificación al CCN-CERT) y cumplimiento del RGPD en el tratamiento de datos personales de los ciudadanos (registro de actividades de tratamiento, evaluación de impacto para los tratamientos de alto riesgo).

6. Interoperabilidad e integración con otros organismos: La plataforma debe integrarse con los sistemas de la Administración General del Estado y de la Comunidad Autónoma. Diseña las integraciones. Incluye: integración con el Padrón Municipal a través de los servicios del INE (verificación de datos de empadronamiento sin que el ciudadano tenga que aportar certificado), integración con el Catastro para verificar datos de propiedad en licencias de obras, integración con la Agencia Tributaria para verificar datos fiscales relevantes para subvenciones (declaración de estar al corriente de obligaciones tributarias), integración con el sistema de la Seguridad Social para verificar cotizaciones en procedimientos de contratación pública, conexión con el sistema SIR (Sistema de Interconexión de Registros) para el intercambio de asientos registrales entre administraciones y diseño del sistema de intermediación de datos que cumple con el artículo 28 de la Ley 39/2015 (el ciudadano no tiene que aportar documentos que ya obran en poder de la Administración).

7. Operación y soporte multi-municipio: La diputación opera la plataforma para 45 municipios. Diseña el modelo operativo. Incluye: modelo de gobierno de la plataforma (quién decide las prioridades de desarrollo, cómo se gestionan las peticiones de cada municipio, cómo se aprueba la incorporación de nuevos procedimientos al catálogo compartido), sistema de monitorización y alertas (disponibilidad de la plataforma, rendimiento por municipio, errores en las integraciones con los servicios comunes), modelo de soporte a los funcionarios de los municipios (helpdesk de primer nivel en la diputación, base de conocimiento, formación online de los nuevos usuarios) y proceso de actualización de la plataforma cuando cambia la normativa o los servicios comunes de la SGAD.

Incluye diagramas de arquitectura descritos en texto, referencias a la normativa española de administración electrónica y ejemplos de implementación de los servicios comunes de la SGAD.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 90,
                'use_case'         => 'Plataforma compartida de e-administración para diputación provincial con 45 municipios beneficiarios',
                'vote_score'       => 55,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 3,
                'title'            => 'Diseño de servicios públicos digitales centrado en el ciudadano con IA',
                'description'      => 'Aplica el diseño de servicios y la experiencia de usuario al sector público para crear trámites, portales y aplicaciones que los ciudadanos encuentren fáciles de usar y que reduzcan la burocracia.',
                'prompt_content'   => <<<'EOT'
Eres un diseñador de servicios especializados en el sector público con experiencia en la aplicación de metodologías de diseño centrado en el usuario (UX/CX) a los servicios de las administraciones públicas. Conoces las particularidades del diseño en el entorno público: las restricciones legales y normativas, la necesidad de accesibilidad universal, los usuarios con menor alfabetización digital y la complejidad de los procedimientos administrativos. Has colaborado con ayuntamientos, comunidades autónomas y organismos del Estado para rediseñar servicios que antes eran una pesadilla burocrática y convertirlos en experiencias simples y digitales.

Contexto del proyecto de diseño:
- Consejería de Bienestar Social de una comunidad autónoma
- Servicio a rediseñar: el proceso de solicitud de la Renta Mínima de Inserción (RMI), una prestación económica para familias en situación de exclusión social
- Situación actual: el trámite requiere desplazarse en persona a la oficina de servicios sociales, llevar una lista de 18 documentos, esperar una media de 3 semanas para la primera cita y 4 meses para obtener la resolución. El 35% de las solicitudes se deniegan por documentación incompleta o incorrecta
- Objetivo: diseñar un proceso que se pueda completar digitalmente, reducir el tiempo de resolución a 6 semanas y eliminar las denegaciones por errores de documentación
- Restricciones: los solicitantes tienen baja alfabetización digital, muchos no tienen ordenador propio y acceden desde el móvil

Desarrolla el proyecto completo de diseño del servicio:

1. Investigación con usuarios en situación de vulnerabilidad: Diseñar para ciudadanos en exclusión social requiere una investigación empática y responsable. Diseña el proceso. Incluye: técnicas de investigación apropiadas para usuarios en situación de vulnerabilidad (entrevistas en contexto en las oficinas de servicios sociales, observación del proceso actual, co-design sessions con trabajadores sociales que son intermediarios clave), protocolo ético para la investigación con personas en situación de exclusión (cómo obtener consentimiento informado sin presión, cómo garantizar que la participación es voluntaria, cómo proteger la información sensible), perfil de los usuarios principales y sus barreras de acceso (personas sin smartphone propio, personas con escasa alfabetización digital, personas con barreras idiomáticas, personas con diversidad funcional), mapa de empatía del solicitante de la RMI (qué piensa, qué siente, qué escucha, qué ve durante el proceso actual) y roles intermediarios clave: los trabajadores sociales y las entidades del tercer sector que ayudan a los solicitantes.

2. Mapa del servicio actual (as-is) y rediseño (to-be): Antes de diseñar el futuro, hay que documentar el presente. Diseña ambos mapas. Incluye: service blueprint del proceso actual de solicitud de la RMI (acciones del ciudadano visibles, acciones del trabajador social, procesos internos de la administración, sistemas de soporte, puntos de dolor identificados en la investigación), análisis de las causas raíz de los principales puntos de dolor (el 35% de denegaciones: ¿por qué se producen realmente? ¿documentación mal entendida? ¿requisitos cambiantes? ¿errores del funcionario?), diseño del servicio futuro (to-be service blueprint) que integra el canal digital con el presencial para quienes no pueden completar el trámite online y definición de los principios de diseño del nuevo servicio (comprensible para todos, proactivo, que no pida lo que ya tiene la administración, que no castigue los errores del solicitante).

3. Diseño del formulario digital accesible: El formulario es el corazón del trámite digital. Diseña el sistema. Incluye: principios de diseño de formularios para usuarios con baja alfabetización digital (un campo por pantalla, lenguaje de nivel A2-B1, iconos de apoyo al texto, ejemplos de cómo rellenar cada campo), diseño del flujo adaptativo del formulario (el formulario solo muestra los pasos relevantes según el perfil del solicitante: con o sin hijos, con o sin empleo, con o sin vivienda propia), sistema de ayuda contextual en cada campo (qué significa este dato, dónde encontrarlo, qué pasa si no se tiene), diseño del proceso de aportación de documentación (cómo un usuario sin escáner puede fotografiar con el móvil y subir un DNI o un contrato de alquiler), sistema de guardado automático para que el solicitante pueda interrumpir y continuar en otro dispositivo y diseño de la pantalla de confirmación y seguimiento del expediente (cómo el solicitante sabe en qué punto está su solicitud).

4. Accesibilidad universal del servicio digital: El servicio debe ser accesible para todos. Diseña el sistema. Incluye: cumplimiento de las WCAG 2.1 nivel AA (contraste de colores, tamaño de texto, navegación por teclado, compatibilidad con lectores de pantalla), diseño de la versión para móvil como experiencia principal (mobile-first porque la mayoría de usuarios sin ordenador propio acceden desde el smartphone), diseño del modo de alto contraste y del modo de texto grande para usuarios con baja visión, consideraciones de diseño para usuarios con diversidad cognitiva (estructura simple, sin información innecesaria, progreso visible, mensajes de error claros y sin culpabilización), versión del formulario con soporte de voz (para personas con dificultad para escribir) y diseño de la alternativa presencial para quienes no pueden completar el trámite digital (proceso asistido en la oficina o a través de entidades del tercer sector colaboradoras).

5. Diseño de la experiencia del trabajador social: El trabajador social es un actor clave del servicio. Diseña su experiencia. Incluye: dashboard del trabajador social para la gestión de expedientes (vista del estado de cada solicitud, alertas de expedientes que requieren intervención, acceso a la documentación aportada), herramienta de revisión asistida por IA de la documentación (el sistema verifica automáticamente si está completa y correcta, el trabajador social valida), sistema de comunicación con el solicitante integrado en la herramienta (mensajes de requerimiento de documentación adicional, notificaciones de resolución) y diseño del proceso de entrevista social digital (videollamada con el solicitante desde la herramienta cuando es necesaria sin que el solicitante tenga que desplazarse).

6. Prototipado y validación con usuarios reales: El diseño debe validarse con los usuarios antes de desarrollarlo. Diseña el proceso. Incluye: creación del prototipo de baja fidelidad del formulario (wireframes del flujo completo con las pantallas principales), protocolo de test de usabilidad con solicitantes reales de la RMI (en las entidades del tercer sector colaboradoras, con consentimiento informado), métricas de éxito del prototipo (tasa de completitud del formulario sin ayuda, número de errores cometidos, tiempo para completar el formulario, comprensión de los mensajes de error) y proceso iterativo de mejora del diseño a partir de los resultados del test.

7. Implementación por fases y gestión del cambio: El rediseño del servicio afecta a ciudadanos, trabajadores sociales y sistemas informáticos. Diseña el plan. Incluye: estrategia de lanzamiento por fases (piloto con un territorio concreto, evaluación de resultados, extensión al resto de la comunidad autónoma), plan de comunicación a los solicitantes sobre el nuevo proceso digital (en colaboración con las entidades del tercer sector que trabajan con esta población), formación de los trabajadores sociales en el nuevo sistema y en las nuevas herramientas digitales y métricas de éxito del nuevo servicio (tasa de solicitudes completadas digitalmente, tasa de denegación por documentación incorrecta, tiempo medio de resolución, satisfacción del ciudadano con el proceso).

Incluye ejemplos de contenido en lenguaje claro para el formulario, plantilla de service blueprint y protocolo de research con usuarios vulnerables. Todo desde la perspectiva del diseño de servicios públicos en España.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Rediseño del proceso de solicitud de la Renta Mínima de Inserción para facilitar el acceso a personas en exclusión social',
                'vote_score'       => 42,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 4,
                'title'            => 'Licitación y ventas de soluciones tecnológicas al sector público con IA',
                'description'      => 'Domina el proceso de contratación pública para vender software, consultoría y soluciones de IA a administraciones públicas, desde la prospección de licitaciones hasta la presentación de ofertas ganadoras.',
                'prompt_content'   => <<<'EOT'
Eres un director comercial y de desarrollo de negocio con especialización en la venta de soluciones tecnológicas al sector público. Llevas más de diez años participando en licitaciones públicas en España y en Europa, desarrollando propuestas para contratos de software, consultoría de transformación digital, sistemas de administración electrónica y proyectos de inteligencia artificial para organismos públicos. Conoces a fondo la Ley de Contratos del Sector Público (LCSP), los procedimientos de licitación y las claves para desarrollar propuestas técnicas ganadoras.

Contexto de la empresa:
- Empresa española de tecnología con 85 empleados, especializada en soluciones de e-administración e inteligencia artificial para el sector público
- Facturación actual: 8 millones de euros anuales, el 65% con administraciones públicas
- Cartera de clientes: 12 ayuntamientos, 3 comunidades autónomas, 2 ministerios y 4 organismos autónomos
- Objetivo: crecer a 14 millones en 2 años mediante contratos de mayor envergadura con la Administración General del Estado y con la Comisión Europea (fondos Next Generation EU)
- Problema: el equipo comercial tiene experiencia en contratos menores y procedimientos abiertos simplificados, pero necesita capacitarse para los procedimientos abiertos de mayor cuantía y para los proyectos financiados con fondos europeos

Desarrolla la estrategia completa de ventas al sector público:

1. Inteligencia de mercado y prospección de licitaciones: Para ganar más contratos hay que identificarlos antes de que se publiquen. Diseña el sistema. Incluye: fuentes de información para la prospección de licitaciones en España (Plataforma de Contratación del Sector Público, BOE, DOUE, plataformas autonómicas, servicios de alertas como Pixelware o Vortal), sistema de alertas automáticas personalizadas por tipo de contrato (tecnología, consultoría, IA) y por organismo objetivo, proceso de pre-licitación: cómo relacionarse con el organismo antes de que publique el pliego para entender sus necesidades reales y posicionarse (visitas comerciales, participación en mesas sectoriales, respuesta a consultas preliminares al mercado), análisis de las licitaciones publicadas antes de presentar oferta (¿quién redactó el pliego? ¿qué empresa tiene el contrato actual? ¿cuáles son los criterios de adjudicación y qué peso tienen?), búsqueda de oportunidades en los programas de fondos europeos relevantes para el sector tecnológico público (Mecanismo de Recuperación y Resiliencia, Fondos FEDER, Horizonte Europa).

2. Estrategia de propuesta técnica ganadora: La propuesta técnica es el diferencial en las licitaciones de tecnología. Diseña el sistema de desarrollo. Incluye: estructura de la propuesta técnica para un contrato de desarrollo de software para la administración pública (descripción de la solución propuesta, metodología de desarrollo ágil adaptada al sector público, plan de proyecto con hitos y entregables, equipo técnico propuesto con perfiles y certificaciones, gestión de riesgos, plan de formación y transferencia de conocimiento), técnicas para diferenciarse de la competencia en la propuesta técnica (proponer valor añadido más allá de lo exigido en el pliego, demostrar experiencia específica en el organismo o en organismos similares con casos de éxito concretos), uso de IA para acelerar la redacción de propuestas (cómo usar Claude para generar borradores de secciones específicas de la propuesta a partir del pliego y de los materiales de la empresa) y proceso de revisión interna de la propuesta antes de presentarla.

3. Criterios de adjudicación y puntuación de ofertas: Entender cómo te van a puntuar es fundamental para ganar. Diseña el análisis. Incluye: tipos de criterios de adjudicación en contratos tecnológicos (precio, propuesta técnica evaluable mediante juicio de valor, criterios automáticos: garantía, soporte, SLAs), estrategia de pricing para las licitaciones públicas (cómo calcular el precio óptimo que te permite ganar sin comprometer el margen, análisis de las ofertas ganadoras anteriores del organismo), cómo maximizar la puntuación en los criterios técnicos evaluados por juicio de valor (la propuesta técnica debe ser clara, estructurada y responder exactamente a lo que pide el pliego sin ambigüedades), análisis de la baja temeraria: qué ocurre cuando tu oferta económica está muy por debajo de la media y cómo defenderte ante el comité de valoración y estrategia de presentación de la oferta económica en contratos con múltiples lotes.

4. Gestión de consorcios y UTE para contratos grandes: Los contratos de mayor cuantía suelen requerir la presentación en consorcio. Diseña el proceso. Incluye: cuándo presentarse en UTE (Unión Temporal de Empresas) o en consorcio con otros socios y cuándo hacerlo en solitario, criterios para la selección de socios complementarios (qué competencia técnica aporta el socio que tu empresa no tiene, cuál es su reputación en el sector público, cómo es su capacidad financiera), negociación del acuerdo de UTE (distribución del trabajo por porcentaje, quién lidera la UTE, reparto de riesgos y de beneficios, gestión de los conflictos internos), gestión de la relación con el socio de UTE durante la ejecución del contrato (coordinación del equipo mixto, resolución de discrepancias técnicas, gestión de los cambios de alcance) y ventajas e inconvenientes de las UTE en el sector tecnológico público.

5. Proyectos de fondos europeos: Next Generation EU y FEDER: Los fondos europeos son una oportunidad enorme para las empresas tecnológicas. Diseña la estrategia. Incluye: diferencias entre los contratos públicos financiados con fondos europeos y los contratos ordinarios (requisitos adicionales de justificación, auditorías, visibilidad del logo EU), proceso de identificación de los programas y convocatorias de fondos europeos relevantes para soluciones de e-administración e IA (Plan de Digitalización de las Administraciones Públicas 2021-2025, PERTE de Digitalización del Ciclo del Agua, etc.), estrategia para participar como subcontratista en proyectos de fondos europeos liderados por integradores grandes (Indra, Atos, T-Systems) cuando el contrato es demasiado grande para abordar en solitario y requisitos de trazabilidad y justificación de los gastos en proyectos financiados con fondos europeos.

6. Relación con el cliente público durante la ejecución del contrato: La gestión del contrato en curso es clave para renovar y ampliar. Diseña el modelo. Incluye: proceso de arranque del proyecto con la administración cliente (kick-off, presentación del equipo, validación del plan de proyecto, establecimiento de los canales de comunicación), gestión de los cambios de alcance que son inevitables en los proyectos tecnológicos públicos (cómo documentarlos, cómo tramitar las modificaciones contractuales según la LCSP), reporting de seguimiento del proyecto al organismo (informes mensuales de avance, reuniones de seguimiento con el responsable del contrato), gestión de los problemas técnicos con el organismo (cómo comunicar un retraso o un problema sin generar desconfianza) y estrategia de posicionamiento para la renovación del contrato o la ampliación del alcance.

7. Cumplimiento legal y administrativo de la contratación pública: La burocracia de la contratación pública es exigente. Diseña el sistema de gestión. Incluye: documentación administrativa obligatoria para participar en licitaciones (DEUC, declaraciones responsables, solvencia técnica y económica, registro de licitadores), gestión de los recursos especiales en materia de contratación cuando una licitación es irregular (plazos para interponer el recurso, ante quién, qué se puede impugnar), cumplimiento de las condiciones especiales de ejecución frecuentes en contratos tecnológicos públicos (obligación de contratar personas en riesgo de exclusión, formación del personal del organismo, mantenimiento tras la finalización del contrato) y gestión de la subcontratación en el sector público (requisitos de comunicación y autorización de subcontratistas según la LCSP).

Incluye plantilla de análisis de pliego antes de presentar oferta, estructura de propuesta técnica para contrato de software y checklist de documentación administrativa para licitaciones públicas. Todo orientado a empresas tecnológicas medianas que quieren crecer en el sector público español.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Crecimiento de empresa tecnológica en el mercado de contratación pública española mediante licitaciones de mayor envergadura',
                'vote_score'       => 49,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 5,
                'title'            => 'Gestión de producto en proyectos de transformación digital pública con IA',
                'description'      => 'Define y lidera productos digitales para la administración pública aplicando metodologías ágiles adaptadas al entorno público, donde los usuarios son ciudadanos y los stakeholders son funcionarios y cargos políticos.',
                'prompt_content'   => <<<'EOT'
Eres un product manager especializado en el sector público con experiencia liderando proyectos de transformación digital en administraciones públicas. Sabes que el product management en el entorno público tiene peculiaridades únicas: los usuarios no son clientes que pagan, los requisitos los marca la normativa además de las necesidades reales, los stakeholders incluyen cargos políticos con agendas cambiantes y el presupuesto viene determinado por el ciclo presupuestario público. Has gestionado productos en organismos como la SGAD, el SEPE, ayuntamientos grandes y comunidades autónomas.

Contexto del proyecto:
- Ministerio de Inclusión, Seguridad Social y Migraciones
- Proyecto: rediseño del portal de gestión de prestaciones económicas del SEPE (Servicio Público de Empleo Estatal) para ciudadanos
- Estado actual: el portal fue diseñado hace 12 años, no es mobile-friendly, tiene una tasa de abandono del 68% y el 40% de los trámites de prestaciones se siguen haciendo en persona en las oficinas del SEPE
- Objetivo: en 18 meses, que el 70% de los trámites se realicen digitalmente, reduciendo la carga de las oficinas presenciales
- Equipo: eres el product manager del equipo de producto (8 personas), y trabajas con un equipo técnico externo de 20 personas de una empresa contratista

Desarrolla la estrategia completa de product management para la transformación digital del SEPE:

1. Discovery y definición del producto: En el sector público, el discovery tiene características propias. Diseña el proceso. Incluye: investigación con los usuarios reales del SEPE (personas en situación de desempleo, con diferentes niveles de alfabetización digital y en situaciones de vulnerabilidad económica), análisis de las restricciones normativas que condicionan el producto (Ley de Empleo, Ley 39/2015 de procedimiento administrativo, RGPD, ENS), entrevistas con los stakeholders internos (técnicos del SEPE, directivos, sindicatos del personal, representantes políticos del ministerio), análisis de las métricas actuales del portal (tasa de abandono por paso del proceso, páginas más visitadas, errores más frecuentes, volumen de llamadas al teléfono de atención) y definición de los principios de producto del nuevo portal (accesible, comprensible, proactivo, que no pida lo que ya tiene la administración).

2. Roadmap en el entorno de contratación pública: El ciclo presupuestario y la contratación pública condicionan el roadmap. Diseña el proceso de planificación. Incluye: cómo estructurar el roadmap en torno a los hitos del contrato de desarrollo (entregables contractuales, plazos de la licitación, fases del proyecto según el pliego), gestión de los cambios de alcance que son inevitables en proyectos de esta escala (cuándo aceptarlos, cómo tramitar la modificación contractual, cómo comunicarlo a los stakeholders), proceso de priorización adaptado al sector público (impacto en ciudadanos, obligación normativa, factibilidad técnica, prioridad política), gestión del backlog con un equipo técnico externo (contratista) que no está bajo tu autoridad directa y cómo explicar el roadmap a stakeholders políticos que quieren resultados visibles antes de las próximas elecciones.

3. Metodología ágil adaptada al entorno público: Las metodologías ágiles necesitan adaptarse al sector público. Diseña el marco de trabajo. Incluye: adaptación de Scrum o Kanban al entorno de la contratación pública (los entregables contractuales forzados no siempre coinciden con los sprints ágiles), proceso de validación con usuarios en el sector público (cómo hacer research y testing con ciudadanos cuando hay restricciones de comunicación externa en el organismo), gestión de las aprobaciones: cómo integrar los procesos de aprobación política y directiva (que son lentos) en un proceso de desarrollo ágil, relación con el equipo técnico contratista bajo metodología ágil (reuniones de sprint, revisiones, retrospectivas con un equipo que es externo y tiene sus propios incentivos) y cómo gestionar la deuda técnica en sistemas públicos que se mantienen durante décadas.

4. Diseño de las funcionalidades clave del nuevo portal: Define las principales funcionalidades del portal rediseñado. Incluye: sistema de autenticación con Cl@ve que no sea una barrera de acceso para los ciudadanos menos digitalizados (proceso simplificado de alta en Cl@ve dentro del propio portal), dashboard del ciudadano con el estado de su prestación (cuánto cobra, cuándo le ingresan, cuándo vence, qué obligaciones tiene como beneficiario: renovar la demanda de empleo, realizar acciones de búsqueda de empleo activa), proceso de solicitud de nueva prestación completamente digital (con verificación automática de requisitos mediante consulta de datos que ya tiene la Seguridad Social y el SEPE), sistema de notificaciones proactivas (recordatorio de la renovación de la demanda de empleo antes de que se agote el plazo, aviso cuando el expediente requiere documentación adicional) y proceso de gestión de incidencias del ciudadano sin necesidad de ir a la oficina (solicitud de revisión de la resolución, aportación de documentación adicional, cambio de cuenta bancaria para el cobro).

5. Accesibilidad y brecha digital: El portal del SEPE es usado por ciudadanos en situación de desempleo, con perfiles muy diversos. Diseña la estrategia de inclusión. Incluye: diseño del portal con accesibilidad WCAG 2.1 AA como requisito no negociable (con el proceso de auditoría y certificación de accesibilidad), estrategia para los ciudadanos con baja alfabetización digital (diseño simplificado para el trámite más frecuente: la renovación de la demanda, que debe completarse en menos de 3 pasos), diseño del proceso asistido en las oficinas para quienes no pueden completar el trámite digitalmente (el funcionario asiste al ciudadano en el portal, no hace el trámite por él) y version en lectura fácil de los textos más importantes del portal.

6. Medición del impacto y definición del éxito: ¿Cómo sabrás que el nuevo portal ha funcionado? Diseña el framework de métricas. Incluye: métricas principales del producto (tasa de trámites completados digitalmente vs. presencialmente, tasa de abandono del proceso de solicitud, tiempo medio para completar un trámite, número de errores en los formularios), métricas de impacto en la organización (reducción de las visitas presenciales en las oficinas, reducción de las llamadas al teléfono de atención, reducción del tiempo de tramitación para el funcionario), proceso de reporting a los stakeholders políticos (dashboard ejecutivo con los KPIs principales, informe mensual para la dirección del SEPE) y cómo ajustar el roadmap basándote en los datos de uso del portal en producción.

7. Gestión de stakeholders en el entorno político y administrativo: En el sector público, la gestión de stakeholders es especialmente compleja. Diseña el proceso. Incluye: mapa de stakeholders del proyecto (dirección del SEPE, Secretaría de Estado, sindicatos de funcionarios, empresas contratistas, organizaciones de defensa de los ciudadanos, medios de comunicación), estrategia de comunicación diferenciada para cada stakeholder (qué necesita saber cada uno, con qué frecuencia, en qué formato), gestión de la presión política para acelerar plazos o añadir funcionalidades no planificadas (cómo decir "no" o "todavía no" a un cargo político de forma constructiva), gestión de la resistencia de los funcionarios al cambio digital (los funcionarios de las oficinas pueden percibir la digitalización como una amenaza a su puesto de trabajo) y gestión de la comunicación pública del proyecto cuando hay un problema grave (error técnico, brecha de seguridad, reclamación mediática de una asociación de ciudadanos).

Incluye plantilla de roadmap adaptado al sector público, framework de priorización para administraciones públicas y guía de gestión de stakeholders políticos para product managers. Todo basado en la experiencia real de proyectos de transformación digital en la Administración General del Estado.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Rediseño del portal de prestaciones del SEPE para aumentar la tasa de tramitación digital del 32% al 70%',
                'vote_score'       => 51,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 6,
                'title'            => 'Gestión del talento y transformación digital de los recursos humanos en el sector público con IA',
                'description'      => 'Diseña estrategias de gestión de personas adaptadas a las particularidades de la administración pública: funcionarios, procesos de selección oposicional, negociación con sindicatos y gestión del cambio en entornos de alta estabilidad laboral.',
                'prompt_content'   => <<<'EOT'
Eres un director de Recursos Humanos especializado en el sector público con experiencia en la gestión de personas en administraciones públicas de diferente tamaño: desde ayuntamientos medianos hasta organismos de la Administración General del Estado. Conoces las particularidades únicas de la gestión de personas en el entorno público: el régimen de los funcionarios de carrera, el personal laboral, los interinos, los procesos de oposición y concurso, la negociación con los sindicatos en la mesa general de negociación y la complejidad del cambio cultural en organizaciones con muy alta estabilidad laboral.

Contexto del organismo:
- Comunidad Autónoma con 18.000 empleados públicos
- Distribución: 12.000 funcionarios de carrera, 4.000 personal laboral fijo, 2.000 interinos
- Problema principal: tasa de envejecimiento muy alta (edad media de 52 años), con el 40% de la plantilla jubilándose en los próximos 8 años
- Segundo problema: las competencias digitales del personal son muy bajas, y la transformación digital de los servicios públicos requiere capacidades que la plantilla actual no tiene
- Tercer problema: la tasa de absentismo es del 9,2%, casi el doble que en el sector privado
- Contexto político: el cambio de gobierno en las últimas elecciones autonómicas ha traído nuevas prioridades de política de personal

Desarrolla la estrategia completa de gestión del talento en el sector público:

1. Diagnóstico de la situación de los recursos humanos: Diseña el proceso de diagnóstico integral. Incluye: análisis demográfico de la plantilla (distribución por edad, sexo, cuerpo o categoría profesional, área de actividad, antigüedad), proyección de jubilaciones por área y por cuerpo para los próximos 10 años (cuántos puestos críticos van a quedar vacantes y cuándo), análisis de las competencias actuales vs. las competencias futuras necesarias para la transformación digital (qué competencias digitales tiene la plantilla actual, cuáles necesitará en 5 años), estudio de las causas del absentismo (diferenciando ausencias por enfermedad, accidente laboral, permisos y licencias) y diagnóstico del clima laboral mediante encuesta a la plantilla (motivación, compromiso, percepción de la dirección, factores de satisfacción e insatisfacción).

2. Planificación de la oferta de empleo público y procesos selectivos: La renovación de la plantilla se hace a través de la OPE. Diseña el proceso. Incluye: metodología para calcular las necesidades de incorporación por área y por categoría teniendo en cuenta las jubilaciones proyectadas, las vacantes actuales y los objetivos de la Administración, diseño de la Oferta de Pública de Empleo (OPE) plurianual para los próximos 4 años (cuántas plazas en cada convocatoria, qué cuerpos o categorías priorizar, cómo justificar la OPE ante la Intervención General y el Ministerio de Hacienda), modernización del proceso selectivo para las oposiciones (cómo incorporar pruebas prácticas de competencias digitales y de resolución de problemas reales junto a los exámenes tipo test teóricos), reducción del plazo de los procesos selectivos (que actualmente duran entre 3 y 5 años desde la convocatoria hasta la toma de posesión) y sistema de integración de los nuevos funcionarios en la organización (período de acogida, mentor, formación inicial en los primeros 6 meses).

3. Plan de formación y desarrollo de competencias digitales: La transformación digital requiere que la plantilla adquiera nuevas competencias. Diseña el plan. Incluye: diagnóstico de las competencias digitales de la plantilla mediante el marco DigComp de la Unión Europea (5 áreas de competencia digital: información, comunicación, creación de contenidos, seguridad, resolución de problemas) para identificar los gaps por colectivo, plan de formación diferenciado por colectivos (formación básica en ciudadanía digital para el 60% de la plantilla con menor nivel, formación avanzada para los puestos con mayor necesidad de competencias digitales específicas, formación de élite para los dinamizadores del cambio digital en cada área), sistema de formación flexible que respete la jornada laboral de los empleados públicos (formación online, en píldoras de 20 minutos, accesible en horas de trabajo con autorización del responsable) y alianzas con el INAP (Instituto Nacional de Administración Pública) y con las escuelas de administración pública autonómicas para la certificación de las competencias adquiridas.

4. Reducción del absentismo: El 9,2% de tasa de absentismo tiene un coste económico y operativo enorme. Diseña el plan de intervención. Incluye: análisis de las causas del absentismo (diferenciando el absentismo por incapacidad temporal de origen médico, el absentismo justificado por permisos y licencias legales y el absentismo no justificado), medidas de prevención del absentismo por causas médicas (programa de salud laboral, evaluaciones de riesgos psicosociales, programa de apoyo psicológico para empleados), medidas de gestión del absentismo ya existente (protocolo de seguimiento de los empleados en IT de larga duración, proceso de reincorporación progresiva, gestión de los casos de plurienfermedad), marco legal de las medidas de control del absentismo en el sector público (qué se puede y qué no se puede hacer en el sector público respecto al absentismo, dado el régimen estatutario) y medición del impacto de las medidas (objetivo: reducir del 9,2% al 6% en 3 años).

5. Negociación con los sindicatos: En el sector público, los sindicatos tienen un papel fundamental. Diseña la estrategia. Incluye: marco de la negociación colectiva en el sector público (Mesa General de Negociación, Mesas Sectoriales, qué materias son negociables y cuáles no según el EBEP), estrategia de relación con los sindicatos para los proyectos de transformación digital (cómo involucrar a los sindicatos desde el inicio para reducir la resistencia, cómo gestionar sus preocupaciones sobre el impacto de la digitalización en el empleo), proceso de negociación del Plan de Formación con los sindicatos (los planes de formación en el sector público se negocian en la mesa sectorial), gestión de los conflictos cuando los sindicatos se oponen a las medidas de la dirección (huelgas, denuncias ante la Inspección de Trabajo, recursos judiciales) y cómo construir una relación de confianza a largo plazo con los representantes sindicales más allá de la negociación formal.

6. Gestión de los interinos y la tasa de temporalidad: La alta tasa de interinos es un problema estructural del sector público. Diseña la estrategia. Incluye: contexto legal de la reforma del EBEP sobre la reducción de la temporalidad en el sector público (la obligación de convocar plazas estructurales cubiertas por interinos) y sus implicaciones para la gestión de los recursos humanos, proceso de estabilización de los interinos: cuántos plazas estabilizar, en qué condiciones, qué proceso selectivo se aplica (concurso vs. concurso-oposición con valoración de méritos), gestión de los interinos que no superan el proceso de estabilización (qué ocurre, cuáles son sus derechos, cómo gestionar el impacto humano y organizativo) y prevención de la nueva temporalidad (cómo diseñar el modelo de cobertura de vacantes temporales que no genere nuevos interinos de larga duración).

7. Sistema de evaluación del desempeño en el sector público: El EBEP prevé la evaluación del desempeño pero muy pocas administraciones la han implantado. Diseña el sistema. Incluye: marco legal de la evaluación del desempeño en el sector público (artículo 20 del EBEP, requisitos para que la evaluación del desempeño tenga consecuencias en la carrera y en las retribuciones), modelo de evaluación del desempeño adaptado al entorno público (qué se evalúa: objetivos, competencias, conductas; quién evalúa: el responsable directo; con qué frecuencia; con qué consecuencias en la carrera profesional horizontal), proceso de negociación con los sindicatos de la implantación de la evaluación del desempeño (los sindicatos suelen oponerse porque puede ser un elemento de discriminación) y sistema piloto de evaluación del desempeño en un área de la Administración antes de extenderlo al conjunto de la organización.

Incluye plantilla de diagnóstico de competencias digitales basada en DigComp, modelo de plan de formación para empleados públicos y protocolo de negociación sindical para proyectos de transformación digital. Todo adaptado a la normativa española del empleo público.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 70,
                'use_case'         => 'Transformación de la gestión de personas en una comunidad autónoma con plantilla envejecida y baja digitalización',
                'vote_score'       => 44,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 7,
                'title'            => 'Gestión presupuestaria y control del gasto público con IA',
                'description'      => 'Aplica herramientas de inteligencia artificial y análisis de datos al presupuesto público para mejorar la planificación, el control del gasto, la detección de ineficiencias y la rendición de cuentas.',
                'prompt_content'   => <<<'EOT'
Eres un director de presupuesto y control de gestión con especialización en el sector público. Tienes experiencia en la elaboración y seguimiento de presupuestos en administraciones públicas de diferente tamaño, en el control del gasto público, en la elaboración de los Presupuestos Generales del Estado y de administraciones territoriales, y en la aplicación de nuevas metodologías de gestión presupuestaria como los presupuestos por programas, el presupuesto basado en resultados y el análisis del gasto público.

Contexto del organismo:
- Ministerio con un presupuesto anual de 4.200 millones de euros
- Estructura presupuestaria: 3 programas de gasto principales, 12 subprogramas, 450 partidas presupuestarias
- Problemas actuales: el gasto se ejecuta de forma muy desigual a lo largo del año (el 40% se ejecuta en el último trimestre, lo que genera ineficiencias y riesgo de proyectos mal ejecutados por prisas), hay partidas presupuestarias históricas que nadie cuestiona aunque su justificación sea débil, y el control del gasto se hace manualmente con Excel, sin herramientas de análisis
- Objetivo: implementar un sistema de gestión presupuestaria basado en datos que mejore la planificación, el seguimiento y la rendición de cuentas del gasto

Desarrolla el sistema completo de gestión presupuestaria con IA:

1. Diagnóstico del gasto público actual: Antes de reformar, hay que entender la situación. Diseña el proceso de análisis. Incluye: análisis de la ejecución presupuestaria de los últimos 3 años (qué programas y partidas tienen mayor infraejecución, qué tendencias hay en el gasto, dónde se concentra el gasto de cierre de año), análisis de la estructura presupuestaria (¿las partidas presupuestarias reflejan objetivos claros de política pública o son categorías históricas sin sentido estratégico?), análisis de la cadena de valor del gasto (input: recursos presupuestarios; output: bienes y servicios producidos; outcome: impacto en la ciudadanía): ¿el ministerio puede medir los tres niveles?, identificación de las áreas de gasto con menor justificación de eficacia (gasto que se repite cada año porque siempre ha estado ahí, sin evidencia de su impacto) y benchmarking del gasto de este ministerio con ministerios equivalentes de otros países de la OCDE.

2. Presupuesto por programas y presupuesto basado en resultados: La modernización del presupuesto público pasa por orientarlo a resultados. Diseña el sistema. Incluye: diseño del mapa de programas presupuestarios del ministerio alineados con los objetivos de política pública (cada programa tiene un objetivo claro, indicadores de resultado medibles y un responsable político identificado), sistema de indicadores de resultado para cada programa (qué medir, cómo medirlo, con qué periodicidad, qué objetivo de resultado se establece para el año), proceso de revisión del gasto (spending review) que evalúe de forma sistemática la eficacia y la eficiencia de cada programa y proponga mejoras o supresiones, integración del presupuesto basado en resultados con el ciclo presupuestario anual (cómo los datos de resultados influyen en la asignación del presupuesto del año siguiente) y cómo presentar el presupuesto por resultados al Parlamento y a la ciudadanía de forma comprensible.

3. Sistema de seguimiento del gasto en tiempo real con IA: El seguimiento manual con Excel es insuficiente para un ministerio de 4.200 millones. Diseña la plataforma. Incluye: arquitectura del sistema de información presupuestaria (integración con el sistema de contabilidad público SOROLLA2 o SICALWIN para la extracción automática de los datos de ejecución presupuestaria), dashboard de seguimiento del gasto en tiempo real para la dirección del ministerio (por programa, por tipo de gasto, por mes, con comparación vs. el mismo período del año anterior y vs. el objetivo de ejecución), alertas automáticas cuando la ejecución se desvía significativamente del plan (partidas infraejecutadas al 50% en junio, partidas sobreejecutadas que pueden agotar el crédito antes de fin de año) y uso de IA para el análisis predictivo de la ejecución presupuestaria (proyección del gasto de fin de año basada en el ritmo de ejecución actual y en los compromisos ya adquiridos).

4. Gestión de la tesorería y la liquidez pública: La gestión de la tesorería tiene sus propias particularidades en el sector público. Diseña el sistema. Incluye: planificación de la tesorería del ministerio (cuándo se van a producir los pagos principales a lo largo del año: nóminas, pagos a proveedores, transferencias a beneficiarios), sistema de previsión de necesidades de liquidez (para que el ministerio pueda solicitar anticipadamente las transferencias necesarias del Tesoro), gestión del Período Medio de Pago (PMP) a proveedores y cumplimiento de la Ley de Morosidad (30 días para las administraciones públicas), alertas de riesgo de mora y proceso de priorización de pagos cuando hay restricciones de liquidez y análisis del impacto de los retrasos en el pago a proveedores en la ejecución de los proyectos del ministerio.

5. Control interno y auditoría del gasto: El gasto público debe estar sometido a un control interno riguroso. Diseña el sistema. Incluye: marco del control interno en el sector público español (Intervención General de la Administración del Estado, función interventora, control previo y control posterior), uso de IA para la detección de anomalías en el gasto (patrones inusuales de contratación, proveedores recurrentes sin proceso competitivo, facturas duplicadas, pagos fuera de los canales habituales), proceso de auditoría interna del gasto de los programas presupuestarios (qué se audita, con qué metodología, con qué frecuencia, qué pasa con los hallazgos), gestión de las observaciones del Tribunal de Cuentas (proceso de respuesta, plan de corrección, seguimiento de la implementación de las recomendaciones) y sistema de gestión de los riesgos presupuestarios (qué puede salir mal en la ejecución del presupuesto y cómo mitigarlo).

6. Transparencia y rendición de cuentas del gasto público: El gasto público es dinero de los ciudadanos y debe rendirse cuentas. Diseña el sistema. Incluye: portal de transparencia presupuestaria del ministerio (datos de ejecución presupuestaria en formato abierto y reutilizable, en cumplimiento de la Ley de Transparencia y la normativa de datos abiertos), informe anual de resultados del ministerio que conecte el gasto realizado con los resultados de política pública conseguidos (para el Parlamento, para la ciudadanía y para los medios de comunicación), proceso de participación ciudadana en el presupuesto (presupuestos participativos para una parte del gasto, consultas públicas sobre prioridades de política pública) y gestión de las solicitudes de información sobre el gasto del ministerio (periodistas, investigadores, organizaciones de la sociedad civil, ciudadanos a través de la Ley de Transparencia).

7. Código Python para el análisis del gasto público: Proporciona implementaciones concretas de: (a) análisis de la ejecución presupuestaria con pandas (carga de datos de ejecución mensuales, cálculo de tasas de ejecución por programa y por tipo de gasto, identificación de los 10 programas con mayor desviación respecto al plan), (b) modelo de predicción del gasto de fin de año con regresión lineal o ARIMA basado en las series históricas de ejecución mensual, (c) visualización del ritmo de ejecución presupuestaria a lo largo del año comparando el año actual con los 3 años anteriores usando matplotlib y (d) detección de anomalías en el gasto con métodos estadísticos básicos (Z-score, IQR) para identificar partidas con comportamiento inusual.

Incluye plantilla de dashboard presupuestario, sistema de indicadores de resultado para un programa de gasto público y metodología de spending review. Todo adaptado al marco legal y los sistemas contables de la Administración General del Estado española.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 80,
                'use_case'         => 'Modernización del sistema de seguimiento y control del presupuesto de un ministerio con 4.200 millones de euros de gasto',
                'vote_score'       => 53,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 8,
                'title'            => 'Marco legal de la inteligencia artificial en el sector público y compliance con el AI Act con IA',
                'description'      => 'Analiza el impacto del Reglamento Europeo de Inteligencia Artificial en las administraciones públicas, identifica los sistemas de IA de alto riesgo en el sector público y diseña el proceso de compliance.',
                'prompt_content'   => <<<'EOT'
Eres un abogado especializado en derecho digital y tecnología con expertise en la aplicación del Reglamento Europeo de Inteligencia Artificial (AI Act) a las administraciones públicas. Llevas años asesorando a organismos públicos europeos sobre el marco legal de la IA, la protección de datos en el sector público, la contratación pública de soluciones de IA y el cumplimiento de los derechos fundamentales en la implementación de sistemas automatizados de toma de decisiones. Conoces en profundidad el AI Act, el RGPD, la Carta de Derechos Fundamentales de la UE y la normativa española de procedimiento administrativo.

Contexto de la consulta legal:
- Comunidad Autónoma que ha iniciado un proceso de adopción de IA en varios servicios públicos
- Sistemas de IA que está implantando o considerando implantar: (1) sistema de scoring para priorización de familias en lista de espera para vivienda social, (2) herramienta de análisis de expedientes de prestaciones sociales para detección de fraude, (3) chatbot para atención ciudadana en primera línea, (4) sistema de reconocimiento facial en edificios públicos, (5) IA para la clasificación automática de documentos del registro de entrada
- El área jurídica necesita un análisis completo de los riesgos legales y el proceso de compliance para cada sistema

Desarrolla el análisis legal completo del uso de IA en el sector público:

1. Marco del AI Act para el sector público: El AI Act tiene categorías específicas para la IA en el sector público. Explica en detalle: la estructura de clasificación del AI Act (IA prohibida, alto riesgo, riesgo limitado, riesgo mínimo) y los criterios que determinan en qué categoría cae cada sistema, los sistemas de IA de alto riesgo que aparecen en el Anexo III del AI Act y que son especialmente relevantes para el sector público (servicios esenciales: agua, gas, electricidad, calefacción; educación y formación profesional; empleo y gestión de trabajadores; acceso a prestaciones y servicios públicos esenciales; aplicación de la ley; gestión de la migración, el asilo y el control fronterizo; administración de justicia), obligaciones específicas para los proveedores y usuarios de IA de alto riesgo en el sector público (gestión de riesgos, datos y gobernanza de datos, documentación técnica, registro de actividad, transparencia, supervisión humana, exactitud, solidez y ciberseguridad) y el régimen sancionador del AI Act y cómo aplica a las administraciones públicas.

2. Análisis de cada sistema de IA de la Comunidad Autónoma: Analiza los 5 sistemas mencionados. Para cada uno incluye: clasificación según el AI Act (¿es prohibido, de alto riesgo, de riesgo limitado o de riesgo mínimo? ¿por qué?), análisis de los derechos fundamentales afectados (dignidad, no discriminación, intimidad, protección de datos, tutela judicial efectiva), obligaciones legales específicas que se derivan de esa clasificación, riesgos jurídicos identificados si se implanta sin el proceso de compliance adecuado y recomendaciones concretas (¿se puede implantar? ¿con qué condiciones? ¿hay alguno que no debería implantarse?). Análisis del sistema de reconocimiento facial: este es el más sensible dado que el AI Act contiene restricciones específicas sobre la biometría en espacios públicos por parte de autoridades públicas.

3. Proceso de conformidad para sistemas de IA de alto riesgo: Los sistemas de alto riesgo requieren un proceso de conformidad antes de desplegarse. Diseña el proceso. Incluye: evaluación de conformidad para sistemas de IA de alto riesgo en el sector público (qué documentos hay que elaborar, qué pruebas hay que hacer, quién valida la conformidad), registro de los sistemas de IA de alto riesgo en la base de datos de la UE (qué información hay que registrar, cuándo, quién es responsable), elaboración de la Evaluación de Impacto sobre los Derechos Fundamentales (FRIA - Fundamental Rights Impact Assessment) que exige el AI Act para determinados sistemas de IA en el sector público, proceso de supervisión humana efectiva de los sistemas de IA de alto riesgo (quién supervisa, con qué criterios, cuándo puede el supervisor anular la decisión del sistema) y proceso de revisión periódica de los sistemas una vez desplegados (cuándo se revisa, qué se revisa, cuándo hay que actualizar la evaluación de conformidad).

4. RGPD y toma de decisiones automatizada en el sector público: La IA en el sector público suele implicar el tratamiento de datos personales. Diseña el análisis. Incluye: aplicación del artículo 22 del RGPD a las decisiones automatizadas en el sector público (cuándo se puede tomar una decisión automatizada con efecto jurídico sobre un ciudadano, cuándo es obligatorio mantener la intervención humana), Evaluación de Impacto de Protección de Datos (EIPD) obligatoria para los sistemas de IA de alto riesgo en el sector público (qué sistemas la requieren, cómo se hace, cuándo se consulta a la AEPD), principios del RGPD aplicados a los sistemas de IA (limitación de la finalidad: la IA no puede usarse para una finalidad diferente a la que la justificó; minimización de datos; exactitud de los datos de entrenamiento; limitación del plazo de conservación), derechos de los ciudadanos frente a las decisiones administrativas adoptadas con apoyo de sistemas de IA (derecho a explicación, derecho a impugnar la decisión automatizada, derecho a que la decisión sea revisada por un ser humano) y cómo integrar los requisitos del RGPD y del AI Act en el proceso de adquisición o desarrollo de sistemas de IA.

5. Contratación pública de sistemas de IA: Cuando la administración compra IA a un proveedor externo, el contrato es clave. Diseña el marco contractual. Incluye: cláusulas obligatorias en los pliegos de contratación de sistemas de IA para el sector público (requisitos de transparencia del algoritmo, obligación de documentación técnica del AI Act, propiedad de los datos de entrenamiento y de los modelos, derecho de auditoría del organismo, obligaciones de mantenimiento y actualización), gestión de la responsabilidad entre la administración pública (usuario del sistema) y el proveedor de IA (proveedor del sistema) cuando el sistema causa un perjuicio a un ciudadano, cláusulas de compliance del AI Act en los contratos públicos de IA (obligación del proveedor de actualizar el sistema si la normativa cambia) y proceso de due diligence técnica y legal de los sistemas de IA antes de contratarlos.

6. Transparencia y explicabilidad de la IA en la Administración: Los ciudadanos tienen derecho a saber que una IA ha intervenido en las decisiones que les afectan. Diseña el sistema. Incluye: obligaciones de información al ciudadano cuando una decisión administrativa ha sido adoptada con apoyo de un sistema de IA (en la resolución: qué información debe incluirse sobre el papel de la IA, qué datos usó, cuál fue su recomendación), diseño de la explicación de las decisiones de IA en lenguaje comprensible para el ciudadano (no "el modelo asignó una puntuación de 0,72 basada en 47 features", sino una explicación de las razones principales de la decisión en lenguaje llano), proceso de impugnación de las decisiones administrativas asistidas por IA (cómo el ciudadano puede recurrir, ante qué órgano, con qué plazo, y cómo se garantiza que la revisión es realmente humana y no otro sistema de IA) y gestión del derecho de acceso a los algoritmos por parte de los ciudadanos, los medios y los investigadores.

7. Gobernanza de la IA en la Administración Pública: La administración necesita una estructura de gobernanza interna para la IA. Diseña el modelo. Incluye: creación del Comité de Ética y Gobernanza de la IA de la Comunidad Autónoma (composición: juristas, técnicos, representantes ciudadanos, DPO; funciones: revisar los sistemas antes de implantarlos, monitorizar los sistemas en producción, gestionar las reclamaciones de los ciudadanos), elaboración de la Estrategia de IA de la Comunidad Autónoma (qué principios guían el uso de IA, qué sistemas se van a impulsar, cuáles se descartan por razones éticas o legales), inventario de los sistemas de IA actualmente en uso en la administración (dónde se usa IA ya, aunque no se llame así: scoring de fraude, priorización de expedientes, análisis de documentos) y proceso de revisión continua del marco de gobernanza a medida que el AI Act se desarrolla y la tecnología avanza.

Incluye checklist de evaluación de conformidad con el AI Act para sistemas en el sector público, plantilla de FRIA (Evaluación de Impacto sobre Derechos Fundamentales) y cláusulas de contratación pública de IA. Todo aplicado a la normativa española y europea vigente.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'advanced',
                'estimated_minutes'=> 75,
                'use_case'         => 'Compliance del AI Act para los sistemas de IA implantados por una Comunidad Autónoma en servicios públicos',
                'vote_score'       => 57,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 9,
                'title'            => 'Atención ciudadana digital y gestión de la experiencia del ciudadano en la administración con IA',
                'description'      => 'Diseña sistemas de atención ciudadana multicanal para administraciones públicas usando IA para mejorar la resolución en el primer contacto, reducir las esperas y ofrecer un servicio más cercano y eficiente.',
                'prompt_content'   => <<<'EOT'
Eres un director de atención ciudadana y experiencia del cliente en la administración pública con experiencia en el diseño e implementación de sistemas omnicanal de atención a la ciudadanía. Conoces las particularidades de la atención en el sector público: los ciudadanos no son clientes que eligen, el servicio es universal y obligatorio, hay colectivos vulnerables que necesitan atención especial, y los funcionarios que atienden al público tienen un estatuto y una cultura de trabajo muy diferente a los agentes de un contact center privado.

Contexto del organismo:
- Ayuntamiento de una ciudad de 350.000 habitantes
- Canales de atención actuales: teléfono de atención (15.000 llamadas/mes), oficina de atención presencial (8.000 visitas/mes), email (3.000 consultas/mes), sede electrónica para trámites (5.000 trámites/mes)
- Problemas: tiempo medio de espera telefónica de 12 minutos (objetivo: menos de 3), el 65% de las llamadas son consultas sobre el estado de expedientes o sobre cómo hacer un trámite (información que está disponible en la web pero los ciudadanos no encuentran), los funcionarios del call center tienen una rotación del 18% anual y bajo nivel de satisfacción laboral
- Objetivo: implementar un sistema de atención ciudadana inteligente que resuelva el 40% de las consultas sin intervención humana

Desarrolla el sistema completo de atención ciudadana digital:

1. Diagnóstico de los canales de atención actuales: Diseña el análisis integral. Incluye: análisis de la distribución de las consultas por tipo (qué pregunta la ciudadanía: estado del expediente, cómo hacer un trámite, queja o reclamación, información sobre servicios municipales, emergencia) y por canal (teléfono, presencial, email, web), identificación de los top 20 motivos de contacto que representan el 80% del volumen (siguiendo el principio de Pareto), análisis de la resolución en el primer contacto (cuántas consultas se resuelven en la primera llamada sin necesidad de derivación o de que el ciudadano llame otra vez), análisis de la experiencia del ciudadano en cada canal (tiempo de espera, satisfacción con la respuesta, facilidad para completar el trámite) y análisis de la experiencia del funcionario de atención (qué tareas les resultan más frustrantes, cuáles podrían automatizarse, dónde necesitan más información o herramientas).

2. Chatbot ciudadano con IA: El chatbot puede resolver el 40% de las consultas sin intervención humana. Diseña el sistema. Incluye: definición de los casos de uso del chatbot (los 20 motivos de contacto más frecuentes que pueden responderse de forma automatizada: estado del expediente, horarios de las oficinas, cómo obtener un certificado de empadronamiento, cómo pagar una multa de tráfico, etc.), diseño conversacional del chatbot adaptado a los ciudadanos que no están acostumbrados a hablar con robots (lenguaje natural, sin menús complicados, con opción de escalar a un agente humano en cualquier momento), integración del chatbot con los sistemas de gestión de expedientes del ayuntamiento (para que pueda consultar el estado real del expediente del ciudadano de forma personalizada), diseño del proceso de escalado al agente humano cuando el chatbot no puede resolver la consulta (traspasar el contexto de la conversación para que el ciudadano no tenga que repetir su problema) y gestión de la accesibilidad del chatbot (versión de voz para personas que no pueden leer, versión en lenguaje simplificado para personas con discapacidad cognitiva).

3. Optimización del canal telefónico: A pesar de la digitalización, el teléfono sigue siendo el canal preferido por muchos ciudadanos. Diseña el sistema. Incluye: sistema de IVR (Interactive Voice Response) inteligente que dirige al ciudadano al agente más adecuado o le resuelve directamente la consulta (autenticación por voz, consulta del estado del expediente sin necesidad de agente), gestión de la cola de espera con IA (predicción del tiempo de espera, opción de devolución de llamada, priorización de llamadas urgentes), sistema de asistencia al agente en tiempo real (mientras el ciudadano habla, el sistema transcribe la conversación, busca la información relevante en las bases de datos del ayuntamiento y la muestra al agente para que pueda responder más rápido), análisis de las llamadas con IA para la mejora continua (categorización automática de los motivos de contacto, detección de problemas recurrentes que podrían resolverse con mejoras en la web o en los procesos del ayuntamiento) y proceso de supervisión de calidad de las llamadas con IA (revisión automática de una muestra de llamadas para asegurar el cumplimiento de los estándares de calidad).

4. Gestión del canal presencial: La atención presencial sigue siendo necesaria para determinados colectivos. Diseña el modelo. Incluye: sistema de cita previa con IA (asignación inteligente de cita según el tipo de trámite y la disponibilidad del funcionario especializado), diseño de la experiencia en la sala de espera (pantallas de información, tiempo de espera estimado, opción de completar partes del trámite desde un quiosco mientras se espera), sistema de atención presencial asistida por IA (el funcionario tiene en la pantalla la ficha del ciudadano, el historial de sus expedientes y los documentos que necesita para el trámite antes de que se acerque a la ventanilla) y diseño de la oficina de atención como espacio de acompañamiento digital para la ciudadanía con baja alfabetización digital.

5. Gestión de las reclamaciones y quejas ciudadanas: Las quejas son una fuente de información fundamental para mejorar los servicios. Diseña el sistema. Incluye: proceso de gestión de las quejas y sugerencias ciudadanas (recepción por cualquier canal, acuse de recibo automático, asignación al área responsable, seguimiento del plazo de respuesta, respuesta al ciudadano), análisis de las quejas con IA para identificar patrones (qué servicios generan más quejas, qué tipo de problemas son recurrentes, qué áreas del ayuntamiento tienen mayor tasa de insatisfacción), integración con el Defensor del Ciudadano municipal (proceso de derivación cuando la queja no se resuelve satisfactoriamente en primera instancia) y proceso de mejora continua a partir de las quejas (cómo las reclamaciones de los ciudadanos se traducen en mejoras concretas en los procesos o en los servicios).

6. Formación y desarrollo de los funcionarios de atención ciudadana: La calidad de la atención depende de las personas. Diseña el sistema. Incluye: programa de formación continua para los funcionarios de atención (conocimiento actualizado de los servicios y trámites del ayuntamiento, técnicas de comunicación con ciudadanos en situaciones difíciles, manejo de las herramientas digitales de atención), sistema de gestión del conocimiento para los agentes (base de conocimiento compartida donde se documentan las respuestas a las preguntas más frecuentes, actualizada en tiempo real cuando cambia algún procedimiento o servicio), proceso de coaching individual para los funcionarios con peores indicadores de calidad y gestión del bienestar emocional de los funcionarios de atención (que están expuestos a ciudadanos en situaciones de estrés, urgencia o incluso agresividad).

7. Medición de la experiencia ciudadana: La satisfacción del ciudadano es el indicador último del éxito. Diseña el sistema de medición. Incluye: encuesta de satisfacción automática tras cada contacto (NPS ciudadano: ¿recomendaría los servicios de su ayuntamiento? + preguntas específicas del canal: tiempo de espera, resolución, amabilidad del funcionario), análisis longitudinal de la satisfacción ciudadana (evolución del NPS por canal y por tipo de trámite, comparación entre meses y entre años), sistema de alerta cuando la satisfacción cae por debajo de un umbral (investigación inmediata de la causa y medidas correctoras), informe semestral de experiencia ciudadana para el equipo de gobierno municipal (con los datos de satisfacción, los problemas identificados y las mejoras implementadas) y comparativa con otros ayuntamientos de tamaño similar (benchmarking del NPS ciudadano en el sector público local español).

Incluye flujo conversacional del chatbot para los 5 casos de uso más frecuentes, plantilla de encuesta de satisfacción ciudadana y dashboard de KPIs de atención ciudadana. Todo adaptado a la normativa española de administración electrónica y atención al ciudadano.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 60,
                'use_case'         => 'Implementación de atención ciudadana digital con chatbot para resolver el 40% de las consultas sin intervención humana en un ayuntamiento de 350.000 habitantes',
                'vote_score'       => 41,
                'resource_type'    => 'prompt',
            ],
            [
                'profession_id'    => 10,
                'title'            => 'Consultor freelance de transformación digital para organismos públicos con IA',
                'description'      => 'Construye una práctica independiente de consultoría especializada en transformación digital del sector público usando IA para aumentar tu capacidad de entrega y diferenciarte en un mercado de nicho muy especializado.',
                'prompt_content'   => <<<'EOT'
Eres un consultor freelance especializado en transformación digital del sector público con experiencia trabajando con ayuntamientos, comunidades autónomas, ministerios y organismos públicos. Has salido de una consultora grande donde gestionabas proyectos de e-administración, y ahora trabajas de forma independiente ofreciendo servicios de asesoría estratégica, diseño de proyectos de digitalización y acompañamiento en la implementación de soluciones tecnológicas a las administraciones públicas.

Situación de tu práctica freelance:
- Consultor independiente de transformación digital pública con 3 años de práctica propia
- Servicios actuales: diagnóstico de madurez digital de organismos públicos, diseño de planes de transformación digital, acompañamiento en licitaciones tecnológicas, formación de directivos públicos en gestión de proyectos digitales
- Clientes actuales: 3 contratos activos (2 ayuntamientos medianos y 1 diputación provincial), facturación anual de 95.000 euros
- Objetivo: llegar a 160.000 euros en 18 meses sin contratar personal fijo
- Limitaciones: el ciclo de ventas en el sector público es muy largo (6-12 meses desde el primer contacto hasta el contrato), los contratos se adjudican por licitación lo que complica el pipeline y la gestión del tiempo entre contratos es difícil

Desarrolla el sistema completo para escalar tu práctica de consultoría de transformación digital pública:

1. Posicionamiento y especialización en el sector público: Para crecer en ingresos, necesitas ser el experto de referencia en un nicho específico. Diseña tu posicionamiento. Incluye: análisis de los segmentos del mercado de consultoría de transformación digital pública (ayuntamientos grandes, ayuntamientos medianos, diputaciones, comunidades autónomas, Administración General del Estado, organismos reguladores) y cuál es el nicho donde tienes más ventaja competitiva con la menor competencia, especialización temática dentro de la transformación digital pública (e-administración y tramitación electrónica, IA en el sector público, gobierno abierto y participación ciudadana, ciberseguridad pública, interoperabilidad de sistemas) y en qué área tienes credenciales únicas, propuesta de valor diferencial respecto a las grandes consultoras (velocidad de respuesta, coste menor, acceso directo al experto sin intermediarios, enfoque en organismos medianos que las grandes no quieren) y argumentario para que un organismo público te elija a ti frente a Everis, Indra o Capgemini.

2. Gestión del ciclo de ventas largo en el sector público: El ciclo de ventas público es un reto único para el freelance. Diseña el sistema. Incluye: mapa del ciclo de ventas en el sector público (fases: detección de la necesidad, construcción de la relación, diseño del proyecto, publicación de la licitación si aplica, presentación de la oferta, adjudicación, inicio del contrato) con los tiempos típicos de cada fase, estrategia de pipeline con múltiples oportunidades en diferentes fases para que no haya períodos sin ingresos (cuántas oportunidades necesitas tener en cada fase del funnel para cerrar el volumen de contratos que te has propuesto), gestión de los períodos sin contratos activos (cómo usarlos productivamente: creación de contenido, investigación del sector, desarrollo de herramientas propias), modelo de ingresos complementarios que no dependan del ciclo largo del sector público (formación de directivos públicos, talleres, informes de sector, licencias de herramientas que hayas desarrollado) y proceso de cualificación de oportunidades (cuándo merece la pena dedicar tiempo a desarrollar una propuesta y cuándo no).

3. Uso de la IA para multiplicar tu capacidad de entrega: La IA te permite hacer más sin contratar. Diseña tu stack de herramientas. Incluye: uso de Claude para el análisis y diagnóstico de organismos públicos (generación de informes de diagnóstico de madurez digital a partir de entrevistas y documentos del organismo, análisis de normativa aplicable, benchmarking con otras administraciones), automatización de la elaboración de planes de transformación digital (plantillas inteligentes que se adaptan al tamaño, tipo y madurez digital de cada organismo), uso de IA para la preparación de propuestas de consultoría para licitaciones (análisis del pliego, identificación de los criterios de valoración clave, generación del borrador de la propuesta técnica) y herramientas de IA para la gestión de proyectos y el reporting a clientes (seguimiento del avance del proyecto, generación de informes de progreso mensuales, detección de desviaciones del plan).

4. Desarrollo de productos de conocimiento para el sector público: Para reducir la dependencia de contratos de consultoría individuales, puedes vender conocimiento sistematizado. Diseña el portfolio. Incluye: diagnóstico express de madurez digital para ayuntamientos (servicio de 5 días con un informe de 30 páginas y un roadmap de digitalización: cómo estructurarlo, cómo entregarlo, precio objetivo de 4.000-6.000 euros), guía sectorial de transformación digital para un tipo específico de organismo (ayuntamientos de menos de 10.000 habitantes: las 10 medidas de digitalización que puedes implementar con presupuesto limitado), formación online en gestión de proyectos de transformación digital para directivos públicos (curso de 8 horas con certificado: plataforma, precio, estrategia de marketing hacia directivos públicos) y toolkit de licitación de soluciones tecnológicas para ayuntamientos (plantillas de pliegos técnicos para los sistemas más habituales: gestión de expedientes, sede electrónica, atención ciudadana).

5. Networking y posicionamiento como experto de referencia: En el sector público, la reputación y las relaciones son fundamentales. Diseña la estrategia. Incluye: participación en los espacios donde se reúnen los decisores de la transformación digital pública (Jornadas de Tecnologías de la Información en la Administración Pública, eventos de Red.es, FEMP -Federación Española de Municipios y Provincias-, consejos de CIOs de las comunidades autónomas), estrategia de LinkedIn para posicionarte como experto en transformación digital pública (qué tipo de contenido publica un consultor del sector público en LinkedIn que atrae a directivos públicos: análisis de normativa, casos de éxito de digitalización, opinión sobre proyectos del sector), proceso de generación de referencias entre clientes (los directores de sistemas o los alcaldes hablan entre sí: cómo asegurarte de que hablan bien de ti y te recomiendan) y colaboración con universidades y escuelas de administración pública como ponente o profesor asociado (INAP, escuelas de administración de comunidades autónomas, IUOG).

6. Gestión financiera de una práctica con ingresos irregulares: Los contratos del sector público se cobran a 30-60 días y tienen períodos de inactividad. Diseña el sistema. Incluye: modelo de cash flow para una práctica de consultoría pública con ingresos concentrados en pocos contratos grandes (cómo planificar los meses sin ingresos, qué reserva de liquidez mantener), modelo de facturación óptimo con el sector público (contratos por fases que generan pagos parciales, facturación mensual vs. por hitos del proyecto), decisión de cuándo crear una SL (cuándo el volumen de facturación justifica el coste de la SL y las obligaciones contables adicionales), gestión de los riesgos del contrato público (demora en el pago, modificación unilateral del contrato por parte de la administración, rescisión) y estrategia de diversificación de clientes para no depender de uno o dos organismos (cuántos contratos activos es el mínimo para la estabilidad de la práctica).

7. Escalado hacia un equipo o hacia la asociación con otros consultores: Para crecer más allá del límite personal, necesitas multiplicarte. Diseña el modelo. Incluye: cuándo incorporar el primer colaborador y con qué modelo (empleado, autónomo colaborador, socio), criterios para seleccionar el primer colaborador (qué competencia complementa a la tuya, cómo garantizas la calidad de su trabajo de cara al cliente público), modelo de trabajo en red con otros freelancers especializados en áreas complementarias (el experto en ciberseguridad pública, el diseñador de servicios públicos, el especialista en e-participación) para poder ofrecer proyectos más completos sin contratar en fijo, estrategia de posicionamiento de la práctica más allá del consultor individual (marca propia vs. seguir trabajando como persona física) y proceso de transferencia del conocimiento a colaboradores para que los clientes no dependan exclusivamente de tu presencia en los proyectos.

Incluye plantilla de propuesta de consultoría para licitaciones públicas, modelo de diagnóstico express de madurez digital para ayuntamientos y calendario de eventos y comunidades del sector público donde construir visibilidad. Todo adaptado a la realidad del consultor freelance en el mercado de transformación digital pública en España.
EOT,
                'tool_name'        => 'Claude',
                'difficulty'       => 'intermediate',
                'estimated_minutes'=> 65,
                'use_case'         => 'Escalar práctica freelance de consultoría de transformación digital pública de 95.000 a 160.000 euros anuales',
                'vote_score'       => 43,
                'resource_type'    => 'prompt',
            ],
        ];
        foreach ($skills as $data) {
            $slug = Str::slug($data['title']);
            if (Skill::where('slug', $slug)->exists()) {
                $this->command->info("Skipping: {$data['title']}");
                continue;
            }
            Skill::create(array_merge($data, [
                'user_id'     => $admin->id,
                'slug'        => $slug,
                'status'      => 'published',
                'version'     => 1,
                'views_count' => rand(80, 400),
                'saves_count' => rand(5, 30),
            ]));
            $this->command->info("Created: {$data['title']}");
        }
    }
}
